SELECT PAIS,
	   SUBG_VENT,
	   DES_REGI,
	   DES_ZONA,
	   PERIODO,
	   SUM(P100_O_MAS) P100_O_MAS,
	   SUM(P100_80) P100_80,
	   SUM(P80_60) P80_60,
	   SUM(P60_40) P60_40,
	   SUM(P40_20) P40_20,
	   SUM(P20_0) P20_0
FROM
(
	SELECT GEN_PAIS.VAL_I18N PAIS,
		   DES_SUBG_VENT SUBG_VENT,
		   DES_REGI,
		   DES_ZONA,
		   VAL_NOMB_PERI PERIODO,
		   CASE WHEN (PORCENTAJE > 100) THEN
		   		COUNT(*)
	       END P100_O_MAS,
		   CASE WHEN (PORCENTAJE <= 100 AND PORCENTAJE > 80) THEN
		   		COUNT(*)
	       END P100_80,
		   CASE WHEN (PORCENTAJE <= 80 AND PORCENTAJE > 60) THEN
		   		COUNT(*)
	       END P80_60,
		   CASE WHEN (PORCENTAJE <= 60 AND PORCENTAJE > 40) THEN
		   		COUNT(*)
	       END P60_40,
		   CASE WHEN (PORCENTAJE <= 40 AND PORCENTAJE > 20) THEN
		   		COUNT(*)
	       END P40_20,
		   CASE WHEN (PORCENTAJE <= 20 AND PORCENTAJE >= 0) THEN
		   		COUNT(*)
	       END P20_0	    
	FROM
	(
		SELECT CAB_REC.PAIS_OID_PAIS,
			   SUB.DES_SUBG_VENT,
			   REG.DES_REGI,
			   ZONA.DES_ZONA,
			   PERI.VAL_NOMB_PERI,
			   CAB_REC.CLIE_OID_CLIE,
			   TRUNC(DECODE(SUM(NVL(SOL_POS.NUM_UNID_ATEN,0)*NVL(SOL_POS.VAL_PREC_TOTA_UNIT_LOCA, 0)),0 ,0, SUM(NVL(REC_LIN.NUM_UNID_DEVU,0)*NVL(REC_LIN.VAL_PREC, 0))/ SUM(NVL(SOL_POS.NUM_UNID_ATEN,0)*NVL(SOL_POS.VAL_PREC_TOTA_UNIT_LOCA, 0)))*100, 2) PORCENTAJE
		FROM REC_CABEC_RECLA CAB_REC,
			 CRA_PERIO PERI,
			 ZON_TERRI_ADMIN TER_ADM,
			 ZON_ZONA ZONA,
			 ZON_SECCI SEC,
			 ZON_SUB_GEREN_VENTA SUB,
			 ZON_REGIO REG,
			 REC_OPERA_RECLA OP_REC,
			 REC_LINEA_OPERA_RECLA REC_LIN,
			 REC_TIPO_MOVIM TIP_MOV,
			 PED_SOLIC_CABEC SOL_CAB,
			 PED_SOLIC_POSIC SOL_POS,
		     (
			 SELECT FEC_INIC
			 FROM CRA_PERIO
			 WHERE OID_PERI = 1379 --PARAMETRO PERIODO INICIO--
			 )PER_INI,
			 (
			 SELECT FEC_FINA
			 FROM CRA_PERIO
			 WHERE OID_PERI = DECODE(57,-1, 71, 57) --PARAMETRO PERIODO FIN-- --PUEDE SER NULO --
			 )PER_FIN
		WHERE PERI.FEC_INIC >= PER_INI.FEC_INIC
			  AND PERI.FEC_FINA <= PER_FIN.FEC_FINA 
			  AND CAB_REC.PERD_OID_PERI_DOCU_REFE = PERI.OID_PERI
			  AND CAB_REC.ZTAD_OID_TERR_ADMI = TER_ADM.OID_TERR_ADMI
			  AND CAB_REC.OID_CABE_RECL = OP_REC.CARE_OID_CABE_RECL
			  AND TER_ADM.ZSCC_OID_SECC = SEC.OID_SECC
			  AND SEC.ZZON_OID_ZONA = ZONA.OID_ZONA 
		      AND OP_REC.OID_OPER_RECL = REC_LIN.OPRE_OID_OPER_RECL
			  AND TIP_MOV.OID_TIPO_MOVI = REC_LIN.TIMO_OID_TIPO_MOVI
			  AND REG.OID_REGI = ZONA.ZORG_OID_REGI
			  AND REG.ZSGV_OID_SUBG_VENT = SUB.OID_SUBG_VENT
			  AND CAB_REC.SOCA_OID_SOLI_CABE = SOL_CAB.OID_SOLI_CABE
			  AND SOL_CAB.OID_SOLI_CABE = SOL_POS.SOCA_OID_SOLI_CABE
			  AND TIP_MOV.COD_TIPO_MOVI <> 'E'
			  AND CAB_REC.PAIS_OID_PAIS = 1		  				 	-- PARAMETRO DE PAIS --
			  AND PERI.MARC_OID_MARC IN (1)							-- PARAMETRO DE MARCA --
			  AND PERI.CANA_OID_CANA IN (1) 						-- PARAMETRO DE CANAL --
--			  AND ZONA.OID_ZONA = 19 								-- PARAMETRO DE ZONA --
--			  AND ZONA.ZORG_OID_REGI = 7							-- PARAMETRO DE REGION --
		GROUP BY CAB_REC.PAIS_OID_PAIS, 
			  SUB.DES_SUBG_VENT,
			   REG.DES_REGI,
			   ZONA.DES_ZONA,
			   PERI.VAL_NOMB_PERI,
			   SOL_CAB.SBAC_OID_SBAC,
			   CAB_REC.CLIE_OID_CLIE
	) DATOS,
	(
	SELECT GEN.VAL_OID, GEN.VAL_I18N
	FROM V_GEN_I18N_SICC GEN
	WHERE GEN.ATTR_ENTI = 'SEG_PAIS'
		  AND GEN.IDIO_OID_IDIO = 1									-- PARAMETRO DE IDIOMA --	  
	) GEN_PAIS
	WHERE GEN_PAIS.VAL_OID(+) = DATOS.PAIS_OID_PAIS
	GROUP BY GEN_PAIS.VAL_I18N,
		   DES_SUBG_VENT,
		   DES_REGI,
		   DES_ZONA,
		   VAL_NOMB_PERI,
		   PORCENTAJE
)			 
GROUP BY PAIS,
	   SUBG_VENT,
	   DES_REGI,
	   DES_ZONA,
	   PERIODO
