
SELECT COD_ZONA,
	   RECLAMOS,
	   FACTURACION,
	   PORCENTAJE
FROM
(
	SELECT ZONA.COD_ZONA,
		   NVL(COUNT(OP.OID_OPER), 0) RECLAMOS,
		   NVL(COUNT(DISTINCT FAC.SOCA_OID_SOLI_CABE),0) FACTURACION,
		   TRUNC(DECODE(NVL(COUNT(DISTINCT FAC.SOCA_OID_SOLI_CABE),0), 0, 0,NVL(COUNT(OP.OID_OPER), 0)/NVL(COUNT(DISTINCT FAC.SOCA_OID_SOLI_CABE),0))*100, 2) PORCENTAJE 
	FROM REC_CABEC_RECLA CAB_REC,
		 CRA_PERIO PERI,
		 REC_OPERA OP,
		 REC_TIPOS_OPERA TIP_OP,
		 REC_OPERA_RECLA OP_REC,
		 FAC_DOCUM_CONTA_CABEC FAC,
		 ZON_ZONA ZONA,
	     (
			 SELECT FEC_INIC
			 FROM CRA_PERIO
			 WHERE OID_PERI = 1379 --PARAMETRO PERIODO INICIO--
		 )PER_INI,
		 (
			 SELECT FEC_FINA
			 FROM CRA_PERIO
			 WHERE OID_PERI = 71 --PARAMETRO PERIODO FIN--
		 )PER_FIN		 
	WHERE PERI.FEC_INIC >= PER_INI.FEC_INIC
		  AND PERI.FEC_FINA <= PER_FIN.FEC_FINA 
		  AND CAB_REC.SOCA_OID_SOLI_CABE = FAC.SOCA_OID_SOLI_CABE
		  AND CAB_REC.PERD_OID_PERI_RECL = PERI.OID_PERI
	      AND CAB_REC.OID_CABE_RECL = OP_REC.CARE_OID_CABE_RECL
	      AND TIP_OP.ROPE_OID_OPER = OP.OID_OPER
		  AND FAC.ZZON_OID_ZONA = ZONA.OID_ZONA
	      AND OP_REC.TIOP_OID_TIPO_OPER = TIP_OP.OID_TIPO_OPER
	--	  AND CAB_REC.PAIS_OID_PAIS = 1	 									-- PARAMETRO DE PAIS --
	--	  AND PERI.CANA_OID_CANA IN (1)										-- PARAMETRO DE CANAL --
	--	  AND PERI.MARC_OID_MARC IN (1)										-- PARAMETRO DE MARCA --
	--	  AND OP.OID_OPER = 1	 											-- PARAMETRO DE OPERACION --
	--	  AND TIP_OP.OID_TIPO_OPER = 1										-- PARAMETRO DE TIPO DE OPERACION --  
	GROUP BY ZONA.COD_ZONA	  
	ORDER BY RECLAMOS DESC
)	  
WHERE ROWNUM <= 10	  	  	  -- PARAMETRO DE CANTIDAD DE ZONAS --


	
	





	