SELECT MARCA, CANAL, PERIODO, DIA, NOMBREUSUARIO, DIGITADOR, DOCUMENTO, TIPO, SUM(CANTIDAD) CANTIDAD ,
	   SUM(COD_VENTA) COD_VENTA , MIN(HORA_INI) HORA_INI, MAX(HORA_FIN) HORA_FIN, 
	   (MAX(HORA_FIN) - MIN(HORA_INI))*24 HORA_TRAB,
	   DECODE((MAX(HORA_FIN) - MIN(HORA_INI)), 0 ,0, SUM(COD_VENTA) / ((MAX(HORA_FIN) - MIN(HORA_INI))*24)) PROMEDIO
	   FROM
(
		   SELECT MAR.DES_MARC MARCA, GEN_SEG_CAN.VAL_I18N CANAL, CRA.VAL_NOMB_PERI PERIODO,
		   TO_DATE(EST_DIG.FEC_INIC_SESI,'DD.MM.YYYY') AS DIA, USU.NOMBREUSUARIO,
		   USU.NOMBRE1 ||' '|| USU.NOMBRE2 ||' '|| USU.APELLIDOPATERNO AS DIGITADOR, 
		   GEN_TIP_SOL.VAL_I18N AS DOCUMENTO, PED_PRG.VAL_NOMB AS TIPO,
		   EST_DIG.NUM_OC AS CANTIDAD, EST_DIG.NUM_CV AS COD_VENTA, EST_DIG.FEC_INIC_SESI AS HORA_INI,
		   EST_DIG.FEC_FIN_SESI AS HORA_FIN 
		   FROM PED_PROCE PROCE,
		   		PED_PROGR PED_PRG,
				SEG_MARCA MAR,
		        PED_TIPO_SOLIC TIP_SOL,
				SEG_CANAL CAN,
				SEG_ACCES ACC,
				SEG_SUBAC SUBA,
				PED_ESTAD_DIGIT EST_DIG,
				OWN_MARE.V_USU_LARGO USU,
				PED_TIPO_SOLIC_PAIS TIP_SOL_PAI,
				CRA_PERIO CRA,
				(
				SELECT GEN.VAL_OID , GEN.VAL_I18N
				FROM V_GEN_I18N_SICC GEN
				WHERE GEN.ATTR_ENTI = 'SEG_CANAL'
				      AND GEN.IDIO_OID_IDIO = 1   -- PARAMETRO DE IDIOMA --
			    ) GEN_SEG_CAN,
				(
				SELECT GEN.VAL_OID, GEN.VAL_I18N
				FROM V_GEN_I18N_SICC GEN
				WHERE GEN.ATTR_ENTI = 'PED_TIPO_SOLIC'
				      AND GEN.IDIO_OID_IDIO = 1    -- PARAMETRO DE IDIOMA --
			    ) GEN_TIP_SOL	 
			WHERE MAR.OID_MARC = TIP_SOL.MARC_OID_MARC
				  AND PROCE.OID_PROC= EST_DIG.PROC_OID_PROC
				  AND PED_PRG.COD_PROG = PROCE.COD_PROC
				  AND GEN_TIP_SOL.VAL_OID = TIP_SOL.OID_TIPO_SOLI
				  AND GEN_SEG_CAN.VAL_OID = CAN.OID_CANA 
				  AND ACC.CANA_OID_CANA = CAN.OID_CANA
				  AND SUBA.ACCE_OID_ACCE = ACC.OID_ACCE
				  AND USU.NOMBREUSUARIO = EST_DIG.VAL_USUA
				  AND EST_DIG.TSPA_OID_TIPO_SOLI_PAIS = TIP_SOL_PAI.OID_TIPO_SOLI_PAIS
				  AND TIP_SOL_PAI.TSOL_OID_TIPO_SOLI = TIP_SOL.OID_TIPO_SOLI
				  AND SUBA.OID_SBAC = TIP_SOL.SBAC_OID_SBAC
				  AND CRA.OID_PERI = EST_DIG.PERD_OID_PERI
				  AND CRA.MARC_OID_MARC = MAR.OID_MARC
				  AND CRA.CANA_OID_CANA = CAN.OID_CANA
				  AND CRA.PAIS_OID_PAIS = 1                 --PARAMETRO PAIS --
				  AND EST_DIG.PERD_OID_PERI = 57   		    --PARAMETRO PERIODO --
				  AND MAR.OID_MARC = 1	  				   -- PARAMETRO OID DE MARCA --
				  AND CAN.OID_CANA = 1                     --PARAMETRO OID DE CANAL --
				  AND ACC.OID_ACCE IN (1)					   -- PARAMETRO OID DE ACCESO (SELECCION MULTIPLE)--
				  AND SUBA.OID_SBAC IN (1) 				   -- PARAMETRO OID DE SUBACCESO (SELECCION MULTIPLE) -- 
				  AND TO_DATE(EST_DIG.FEC_INIC_SESI) >= TO_DATE('01/01/2003', 'DD/MM/YYYY')	   -- PARAMETRO FECHA DE INICIO --
				  AND TO_DATE(EST_DIG.FEC_FIN_SESI) <= SYSDATE		   -- PARAMETRO FECHA DE FIN ---
)		
GROUP BY MARCA,
	  	 CANAL,
		 PERIODO,
		 DIA,
		 NOMBREUSUARIO,
		 DIGITADOR,
		 DOCUMENTO,
		 TIPO
	