
SELECT GEN_COMI.VAL_I18N COMISION,
	   SUBG.DES_SUBG_VENT SUBGEREN,
	   REG.DES_REGI REGION,
	   PERI.VAL_NOMB_PERI PERIODO,
	   ZONA.COD_ZONA,
	   ZONA.DES_ZONA,
	   CLI.VAL_NOM1||' '||CLI.VAL_APE1 NOMBRE,
	   COM_CAL.VAL_PORC_COMI,
	   COM_CAL.IMP_COMI IMPORTE_PAGAR,
	   (COM_CLI.IMP_MONT_PAGA * COM_CLI.VAL_PORC_COMI / 100) MONTO_ABONAR
FROM ZON_SUB_GEREN_VENTA SUBG,
	 ZON_REGIO REG,
	 ZON_ZONA ZONA,
	 COM_COMIS_CALCU COM_CAL,
	 COM_COMIS_COBRA_ACUMU_CLIEN COM_CLI,
	 COM_COMIS_COBRA_ACUMU COM_ACU,
	 CRA_PERIO PERI,
	 MAE_CLIEN CLI,
	 COM_COMIS COM,
	 (
	 SELECT P.FEC_INIC, P.FEC_FINA
	 FROM CRA_PERIO P
	 WHERE P.OID_PERI = 61 		   		 			  	-- PARAMETRO DE PERIODO --
	 ) PERI_PARA,
	 (
		 SELECT GEN.VAL_OID, GEN.VAL_I18N
		 FROM V_GEN_I18N_SICC GEN
		 WHERE GEN.ATTR_ENTI = 'COM_COMIS'
		 	   AND GEN.IDIO_OID_IDIO = 1  				-- PARAMETRO DE IDIOMA --
	 ) GEN_COMI
WHERE SUBG.OID_SUBG_VENT = REG.ZSGV_OID_SUBG_VENT
	  AND REG.OID_REGI = ZONA.ZORG_OID_REGI
	  AND ZONA.CLIE_OID_CLIE = COM_CAL.CLIE_OID_CLIE
	  AND COM_CAL.COMI_OID_COMI = GEN_COMI.VAL_OID(+)	 
      AND PERI.OID_PERI = COM_CAL.PERD_OID_PERI
	  AND COM.OID_COMI = COM_CAL.COMI_OID_COMI
	  AND ZONA.CLIE_OID_CLIE = CLI.OID_CLIE
	  AND COM_CLI.COC2_OID_COMI_COBR_ACUM = COM_ACU.OID_COMI_COBR_ACUM
	  AND COM_ACU.COMI_OID_COMI = COM_CAL.COMI_OID_COMI
	  AND (SELECT PE.FEC_INIC 
	  	   FROM CRA_PERIO PE
		   WHERE ZONA.PERD_OID_PERI_INIC = PE.OID_PERI
		  ) <= PERI_PARA.FEC_INIC  
	  AND (SELECT DECODE(PE.FEC_FINA, NULL, SYSDATE, PE.FEC_FINA) 
	  	   FROM CRA_PERIO PE
		   WHERE ZONA.PERD_OID_PERI_FINA = PE.OID_PERI
		  ) >= PERI_PARA.FEC_FINA	  
      AND SUBG.PAIS_OID_PAIS = 1		   		 	-- PARAMETRO DE PAIS --
	  AND SUBG.MARC_OID_MARC = 1					-- PARAMETRO DE MARCA --
	  AND SUBG.CANA_OID_CANA = 1					-- PARAMETRO DE CANAL --
	  AND COM_CAL.PERD_OID_PERI = 61					-- PARAMETRO DE PERIODO --
	  AND COM.IND_VENT_COBR = 'C' 					-- PARAMETRO DE TIPO DE COMISION --
	  AND COM_CAL.COMI_OID_COMI = 1319						-- PARAMETRO DE COMISION --
	  AND SUBG.OID_SUBG_VENT IN (1)					-- PARAMETRO DE SUBGERENCIA DE VENTAS --
	  AND REG.OID_REGI IN (1)						-- PARAMETRO DE REGION --
	  AND ZONA.OID_ZONA IN (10)						-- PARAMETRO DE ZONA -- 
