
SELECT GEN_COMIS.VAL_I18N AS COMISION,
	   PERI.VAL_NOMB_PERI,
	   SUBG.COD_SUBG_VENT,	  
	   REG.COD_REGI,
	   REG.DES_REGI,
	   --------------------------------------------------------------------------------------------------------
	   NVL((
	   SELECT SUM(VEN_PRE.VAL_VENT_NETA_ESTA)
	   FROM INT_FUENT_VENTA_PREVI_SAP VEN_PRE 
	   WHERE VEN_PRE.ZORG_OID_REGI = REG.OID_REGI
	   		 AND VEN_PRE.PERD_OID_PERI = COM_CAL.PERD_OID_PERI
	   GROUP BY VEN_PRE.ZORG_OID_REGI,
	   		    VEN_PRE.PERD_OID_PERI
	   ), 0) AS VENTA,
	   --------------------------------------------------------------------------------------------------------	   
	   NVL((
	   SELECT SUM(VEN_REA.IMP_VENT_NETA_ESTA)
	   FROM INT_FUENT_VENTA_REAL_VACUM VEN_REA
	   WHERE VEN_REA.PERD_OID_PERI = COM_CAL.PERD_OID_PERI
			 AND VEN_REA.ZORG_OID_REGI = REG.OID_REGI
	   GROUP BY VEN_REA.ZORG_OID_REGI,
	   		    VEN_REA.PERD_OID_PERI
	   ), 0) AS BASE_COMISION,
	   --------------------------------------------------------------------------------------------------------
   	   SUM(COM_CAL.IMP_COMI) IMPORTE_COMISION,
	   --------------------------------------------------------------------------------------------------------	   
	   TRUNC(DECODE(NVL((
	   SELECT SUM(VEN_PRE.VAL_VENT_NETA_ESTA)
	   FROM INT_FUENT_VENTA_PREVI_SAP VEN_PRE 
	   WHERE VEN_PRE.ZORG_OID_REGI = REG.OID_REGI
	   		 AND VEN_PRE.PERD_OID_PERI = COM_CAL.PERD_OID_PERI
	   GROUP BY VEN_PRE.ZORG_OID_REGI,
	   		    VEN_PRE.PERD_OID_PERI
	   ), 0), 0, 0,NVL((
	   SELECT SUM(VEN_REA.IMP_VENT_NETA_ESTA)
	   FROM INT_FUENT_VENTA_REAL_VACUM VEN_REA
	   WHERE VEN_REA.PERD_OID_PERI = COM_CAL.PERD_OID_PERI
			 AND VEN_REA.ZORG_OID_REGI = REG.OID_REGI
	   GROUP BY VEN_REA.ZORG_OID_REGI,
	   		    VEN_REA.PERD_OID_PERI
	   ), 0) / NVL((
	   SELECT SUM(VEN_PRE.VAL_VENT_NETA_ESTA)
	   FROM INT_FUENT_VENTA_PREVI_SAP VEN_PRE 
	   WHERE VEN_PRE.ZORG_OID_REGI = REG.OID_REGI
	   		 AND VEN_PRE.PERD_OID_PERI = COM_CAL.PERD_OID_PERI
	   GROUP BY VEN_PRE.ZORG_OID_REGI,
	   		    VEN_PRE.PERD_OID_PERI
	   ), 0)), 3) AS PARTICIPACION
	   --------------------------------------------------------------------------------------------------------	   	   
FROM ZON_SUB_GEREN_VENTA SUBG,
	 ZON_REGIO REG,
	 COM_COMIS_CALCU COM_CAL,
	 COM_COMIS COM,
	 CRA_PERIO PERI,
 	 (
		 SELECT P.FEC_INIC, P.FEC_FINA
		 FROM CRA_PERIO P
		 WHERE P.OID_PERI = 61 		   		 			  	-- PARAMETRO DE PERIODO --
	 ) PERI_PARA,
	 (
		 SELECT GEN.VAL_OID, GEN.VAL_I18N
		 FROM V_GEN_I18N_SICC GEN
		 WHERE GEN.ATTR_ENTI = 'COM_COMIS'
		 	   AND GEN.IDIO_OID_IDIO = 1   	 					  	-- PARAMETRO DE IDIOMA --
	 ) GEN_COMIS
WHERE SUBG.OID_SUBG_VENT = REG.ZSGV_OID_SUBG_VENT
	  AND PERI.OID_PERI = COM_CAL.PERD_OID_PERI
	  AND (SELECT PE.FEC_INIC 
	  	   FROM CRA_PERIO PE
		   WHERE REG.PERD_OID_PERI_INIC = PE.OID_PERI
		  ) <= PERI_PARA.FEC_INIC  
	  AND (SELECT DECODE(PE.FEC_FINA, NULL, SYSDATE, PE.FEC_FINA) 
	  	   FROM CRA_PERIO PE
		   WHERE REG.PERD_OID_PERI_FINA = PE.OID_PERI
		  ) >= PERI_PARA.FEC_FINA	  
	  AND COM_CAL.CLIE_OID_CLIE = REG.CLIE_OID_CLIE
	  AND COM_CAL.COMI_OID_COMI = COM.OID_COMI
	  AND COM.OID_COMI= GEN_COMIS.VAL_OID(+)
	  AND COM_CAL.PERD_OID_PERI IN (43)				-- PARAMETRO DE PERIODO --
	  AND SUBG.OID_SUBG_VENT IN (1)					-- PARAMETRO DE SUBGERENCIA DE VENTAS --
	  AND SUBG.MARC_OID_MARC = 1					-- PARAMETRO DE MARCA --
	  AND SUBG.CANA_OID_CANA = 1					-- PARAMETRO DE CANAL --
	  AND SUBG.PAIS_OID_PAIS = 1					-- PARAMETRO DE PAIS --
	  AND REG.OID_REGI IN (7)  						-- PARAMETRO DE REGION --
	  AND COM.OID_COMI = 1 							-- PARAMETRO DE COMISION --
	  AND COM.IND_VENT_COBR = 'C'					-- PARAMETRO DE TIPO DE COMISION --	  
GROUP BY  GEN_COMIS.VAL_I18N,
	  	  COM_CAL.PERD_OID_PERI,
          PERI.VAL_NOMB_PERI,
	      SUBG.COD_SUBG_VENT,	  
          REG.COD_REGI,
	      REG.DES_REGI,
	  	 REG.OID_REGI 