
SELECT PAIS,
	   COMIS,
	   VAL_NOMB_PERI,
	   COD_REGI,
	   DES_REGI,
	   SUM(MONTO_NETO) MONTO_NETO,
	   SUM(MONTO_RECUP) MONTO_RECUP,
	   DECODE(SUM(MONTO_RECUP), 0, 0, (SUM(MONTO_NETO)/SUM(MONTO_RECUP))*100) PORC_RECUP,
	   SUM(MONTO_PAGAR) MONTO_ABONAR,
	   COUNT(DISTINCT NUM_GANADO) NUM_LIDERES,
	   DECODE(COUNT(DISTINCT NUM_GANADO), 0, 0, COUNT(DISTINCT NUM_GAN_LID)/COUNT(DISTINCT NUM_GANADO)*100) PORC_LID_GANADORES	    
FROM
(
	SELECT GEN_PAIS.VAL_I18N PAIS,
		   GEN_COMIS.VAL_I18N COMIS,
		   PERI.VAL_NOMB_PERI,
		   SUBG.COD_SUBG_VENT,
		   REG.COD_REGI,
		   REG.DES_REGI,
		   NVL(COM_CLI.IMP_MONT_PAGA, 0) MONTO_PAGAR,
		   NVL(COM_CLI.IMP_MONT_RECU, 0) MONTO_RECUP,
		   DECODE(NVL(COM_CLI.VAL_PORC_RECU, 0), 0, 0, ((NVL(COM_CLI.IMP_MONT_RECU, 0)*100)/NVL(COM_CLI.VAL_PORC_RECU, 0))) MONTO_NETO,
		   CASE WHEN(NVL(COM_CLI.IMP_MONT_PAGA, 0) <> 0) THEN
		   	   COM_ACU.CLIE_OID_CLIE
		   END NUM_GAN_LID,
		   COM_ACU.CLIE_OID_CLIE NUM_GANADO
	FROM ZON_SUB_GEREN_VENTA SUBG,
		 ZON_REGIO REG,
		 ZON_ZONA ZONA,
		 ZON_SECCI SEC,
		 COM_COMIS_COBRA_ACUMU_CLIEN COM_CLI,
		 COM_COMIS_COBRA_ACUMU COM_ACU,
		 COM_COMIS COM,
		 CRA_PERIO PERI,
		 (
		 SELECT P.FEC_INIC, P.FEC_FINA
		 FROM CRA_PERIO P
		 WHERE P.OID_PERI = 61 		   		 			  	-- PARAMETRO DE PERIODO --
		 ) PERI_PARA,
    	 (
		 SELECT GEN.VAL_OID, GEN.VAL_I18N
		 FROM V_GEN_I18N_SICC GEN
		 WHERE GEN.ATTR_ENTI = 'SEG_PAIS'
		 	   AND GEN.IDIO_OID_IDIO = 1 	 		-- PARAMETRO DE IDIOMA --
		 ) GEN_PAIS,
	 	 (
		 SELECT GEN.VAL_OID, GEN.VAL_I18N
		 FROM V_GEN_I18N_SICC GEN
		 WHERE GEN.ATTR_ENTI = 'COM_COMIS'
		 	   AND GEN.IDIO_OID_IDIO = 1 	 		-- PARAMETRO DE IDIOMA --
		 ) GEN_COMIS	 
	WHERE SUBG.OID_SUBG_VENT = REG.ZSGV_OID_SUBG_VENT
		  AND REG.OID_REGI = ZONA.ZORG_OID_REGI
		  AND ZONA.OID_ZONA = SEC.ZZON_OID_ZONA
		  AND COM_ACU.CLIE_OID_CLIE = SEC.CLIE_OID_CLIE
		  AND COM_CLI.COC2_OID_COMI_COBR_ACUM = COM_ACU.OID_COMI_COBR_ACUM
		  AND SUBG.PAIS_OID_PAIS = GEN_PAIS.VAL_OID(+)
		  AND COM_ACU.COMI_OID_COMI = GEN_COMIS.VAL_OID(+)
		  AND PERI.OID_PERI = COM_ACU.PERD_OID_PERI
		  AND COM.OID_COMI = COM_ACU.COMI_OID_COMI
		  AND (SELECT PE.FEC_INIC 
		  	   FROM CRA_PERIO PE
			   WHERE SEC.PERD_OID_PERI_INIC = PE.OID_PERI
			  ) <= PERI_PARA.FEC_INIC  
		  AND (SELECT DECODE(PE.FEC_FINA, NULL, SYSDATE, PE.FEC_FINA) 
		  	   FROM CRA_PERIO PE
			   WHERE SEC.PERD_OID_PERI_FINA = PE.OID_PERI
			  ) >= PERI_PARA.FEC_FINA	  
		  AND COM.IND_VENT_COBR = 'C'
		  AND SUBG.PAIS_OID_PAIS = 1		   		 -- PARAMETRO DE PAIS --
		  AND SUBG.CANA_OID_CANA = 1				 -- PARAMETRO DE CANAL --
		  AND SUBG.MARC_OID_MARC = 1				 -- PARAMETRO DE MARCA --
		  AND SUBG.OID_SUBG_VENT IN (1,2,3,4,5,6,7,8,9)				 -- PARAMETRO DE SUBGERENCIA DE VENTAS --
		  AND REG.OID_REGI IN (1,2,3,4,5,6,7,8,9)					 -- PARAMETRO DE REGION --
		  AND ZONA.OID_ZONA IN (1,2,3,4,5,6,7,8,9)					 -- PARAMETRO DE ZONA --
		  AND SEC.OID_SECC IN (1,2,3,4,5,6,7,8,9)					 -- PARAMETRO DE SECCION --
		  AND COM_ACU.COMI_OID_COMI = 1319				 -- PARAMETRO DE COMISIONES --
		  AND COM_ACU.PERD_OID_PERI = 41				 -- PARAMETRO DE PERIODO --
		  AND COM_CLI.VAL_NIVE_TRAM = 1					 -- PARAMETRO DE FECHA DE VENCIMIENTO O NIVEL DE TRAMO --
)	  
GROUP BY PAIS,
	   COMIS,
	   VAL_NOMB_PERI,
	   COD_REGI,
	   DES_REGI

