(
SELECT PAIS,
	   SUBACCESO,
	   'DOCUMENTOS EMITIDOS' AS DOCU,
 	   NULL AS TIP_MED_PAGO,
	   DES_TIPO_DOCU TIPO_DOC,
 	   NULL AS RANGO ,
	   (SELECT GEN_MONEDA.VAL_I18N
	   FROM SEG_MONED MONE,
	   		(
			SELECT GEN.VAL_OID, GEN.VAL_I18N
			FROM V_GEN_I18N_SICC GEN
			WHERE GEN.ATTR_ENTI = 'SEG_MONED'
				  AND GEN.IDIO_OID_IDIO = 1	 							-- PARAMETRO DE IDIOMA --
			) GEN_MONEDA
 	   WHERE MONE.OID_MONE = MONE_OID_MONE
	   		 AND MONE.OID_MONE = GEN_MONEDA.VAL_OID(+)
	   ) AS MONE,
	   (SELECT  GEN_MONEDA.VAL_I18N
	   FROM SEG_MONED MONE,
	   		(
			SELECT GEN.VAL_OID, GEN.VAL_I18N
			FROM V_GEN_I18N_SICC GEN
			WHERE GEN.ATTR_ENTI = 'SEG_MONED'
				  AND GEN.IDIO_OID_IDIO = 1	 							-- PARAMETRO DE IDIOMA --
			) GEN_MONEDA
 	   WHERE MONE.OID_MONE = MONE_OID_MONE_ALT
   	   		 AND MONE.OID_MONE = GEN_MONEDA.VAL_OID(+)
	   ) MONE_ALT,
       NVL(SUM(VAL_MONE), 0) AS VAL_MONE,      
	   NVL(SUM(VAL_MONE_ALT), 0) AS VAL_MONE_ALT	   
FROM
	(
	SELECT GEN_PAIS.VAL_I18N PAIS, 
		   GEN_SUBA.VAL_I18N SUBACCESO,
		   PAIS.MONE_OID_MONE,
		   PAIS.MONE_OID_MONE_ALT,
		   TIP_DOC.DES_TIPO_DOCU,
	      ( 
		  SELECT DOC_CON_CAB.VAL_TOTA_PAGA_LOCA 
		  FROM SEG_MONED MONE
	 	  WHERE MONE.OID_MONE = PAIS.MONE_OID_MONE
		  		AND DOC_CON_CAB.MONE_OID_MONE = PAIS.MONE_OID_MONE			
		  )	AS VAL_MONE,
	      ( 
		  SELECT DOC_CON_CAB.VAL_TOTA_PAGA_DOCU 
		  FROM SEG_MONED MONE
	 	  WHERE MONE.OID_MONE = PAIS.MONE_OID_MONE_ALT
		  		AND DOC_CON_CAB.MONE_OID_MONE = PAIS.MONE_OID_MONE_ALT
		  )	AS VAL_MONE_ALT     
	FROM  SEG_PAIS PAIS,
		 FAC_DOCUM_CONTA_CABEC DOC_CON_CAB,
		 FAC_TIPO_DOCUM TIP_DOC,
		 SEG_CANAL CANAL,
		 SEG_ACCES ACCE,
		 SEG_SUBAC SUBA,
		 (	 
		 SELECT GEN.VAL_OID, GEN.VAL_I18N
		 FROM V_GEN_I18N_SICC GEN
		 WHERE GEN.ATTR_ENTI = 'SEG_PAIS'
		 	   AND GEN.IDIO_OID_IDIO = 1 								-- PARAMETRO DE IDIOMA --
		 ) GEN_PAIS,
		 (
		 SELECT GEN.VAL_OID, GEN.VAL_I18N
		 FROM V_GEN_I18N_SICC GEN
		 WHERE GEN.ATTR_ENTI = 'SEG_SUBAC'
		 	   AND GEN.IDIO_OID_IDIO = 1  								 -- PARAMETRO DE IDIOMA --
		 ) GEN_SUBA	
	WHERE PAIS.OID_PAIS = GEN_PAIS.VAL_OID(+)
		  AND CANAL.OID_CANA = ACCE.CANA_OID_CANA
		  AND ACCE.OID_ACCE = SUBA.ACCE_OID_ACCE
		  AND DOC_CON_CAB.SBAC_OID_SBAC = SUBA.OID_SBAC
		  AND DOC_CON_CAB.PAIS_OID_PAIS = PAIS.OID_PAIS
	      AND TIP_DOC.OID_TIPO_DOCU = DOC_CON_CAB.TIDO_OID_TIPO_DOCU
		  AND DOC_CON_CAB.MONE_OID_MONE IS NOT NULL
		  AND SUBA.OID_SBAC = GEN_SUBA.VAL_OID
		  AND TO_DATE(DOC_CON_CAB.FEC_EMIS) = TO_DATE('13/01/2005', 'DD/MM/YYYY')   -- PARAMETRO DE FECHA DE CIERRE --
--		  AND PAIS.OID_PAIS = 1  										-- PARAMETRO DE PAIS --
--		  AND OID_CANA = 1	  											-- PARAMETRO DE CANAL --
--		  AND ACCE.OID_ACCE = 1											-- PARAMETRO DE ACCESO --
--		  AND SUBA.OID_SBAC = 1											-- PARAMETRO DE SUBACCESO --
		)
	GROUP BY PAIS,
		  	 SUBACCESO,
		  	 'DOCUMENTOS EMITIDOS',
		     DES_TIPO_DOCU,	
	         MONE_OID_MONE,
	  		 MONE_OID_MONE_ALT
	)
	UNION ALL
	(
	SELECT GEN_PAIS.VAL_I18N PAIS,
		   GEN_SUBA.VAL_I18N SUBACCESO,
		   'COBROS POR MEDIOS DE PAGO' DOCU,
           GEN_TIP_MED_PAGO.VAL_I18N TIPO_MED_PAGO,
		   GEN_MED_PAGO.VAL_I18N MED_PAGO, NULL AS RANGO, 
  		   (SELECT GEN_MONEDA.VAL_I18N
		    FROM SEG_MONED MONE,
	   			 (
				 SELECT GEN.VAL_OID, GEN.VAL_I18N
				 FROM V_GEN_I18N_SICC GEN
				 WHERE GEN.ATTR_ENTI = 'SEG_MONED'
				 	   AND GEN.IDIO_OID_IDIO = 1	 							-- PARAMETRO DE IDIOMA --
			  	) GEN_MONEDA
			WHERE MONE.OID_MONE = MONE_OID_MONE
	   			  AND MONE.OID_MONE = GEN_MONEDA.VAL_OID(+)
			) AS MONE,
			(SELECT  GEN_MONEDA.VAL_I18N
			 FROM SEG_MONED MONE,
	   		 	  (
				  SELECT GEN.VAL_OID, GEN.VAL_I18N
				  FROM V_GEN_I18N_SICC GEN
				  WHERE GEN.ATTR_ENTI = 'SEG_MONED'
				  		AND GEN.IDIO_OID_IDIO = 1	 							-- PARAMETRO DE IDIOMA --
				  ) GEN_MONEDA
			WHERE MONE.OID_MONE = MONE_OID_MONE_ALT
   	   			  AND MONE.OID_MONE = GEN_MONEDA.VAL_OID(+)
			) MONE_ALT,
    	   NVL(SUM(MONE), 0) AS VAL_MONE,		         
		   NVL(SUM(MONE_ALT), 0) AS VAL_MONE_ALT
	FROM
		(
			( -- EFECTIVO --
			SELECT PAIS.OID_PAIS,
				   SUBA.OID_SBAC,
				   PAIS.MONE_OID_MONE,
				   PAIS.MONE_OID_MONE_ALT,
				   TIP_MED_PAG.OID_TIPO_MEDI_PAGO,
				   MED_PAG.OID_MEDI_PAGO,
				   (
				   SELECT MOV_CAJA_DET.IMP_MOVI
				   FROM	SEG_MONED MONE	   		 
				   WHERE MOV_CAJA_DET.MONE_OID_MONE = MONE.OID_MONE
						 AND MONE.OID_MONE = PAIS.MONE_OID_MONE
				   ) MONE,
			   	   (
				   SELECT MOV_CAJA_DET.IMP_DIVI
				   FROM	SEG_MONED MONE	   		 
				   WHERE MOV_CAJA_DET.MONE_OID_MONE = MONE.OID_MONE
						 AND MONE.OID_MONE = PAIS.MONE_OID_MONE_ALT
				   ) MONE_ALT
			FROM SEG_PAIS PAIS,
				 SEG_CANAL CANAL,
				 SEG_ACCES ACCE,
				 SEG_SUBAC SUBA,
				 PED_SOLIC_CABEC SOL_CAB,
				 BEL_MOVIM_CAJA_CABEC MOV_CAJA_CAB,
				 BEL_MOVIM_CAJA_DETAL MOV_CAJA_DET,
				 BEL_MEDIO_PAGO_BELCE MED_PAG_BEL,
				 BEL_MEDIO_PAGO MED_PAG,
				 BEL_TIPO_MEDIO_PAGO TIP_MED_PAG
			WHERE CANAL.OID_CANA = ACCE.CANA_OID_CANA
				  AND ACCE.OID_ACCE = SUBA.ACCE_OID_ACCE
				  AND SOL_CAB.PAIS_OID_PAIS = PAIS.OID_PAIS
				  AND SOL_CAB.SBAC_OID_SBAC = SUBA.OID_SBAC
				  AND MOV_CAJA_CAB.SOCA_OID_SOLI_CABE = SOL_CAB.OID_SOLI_CABE
				  AND SOL_CAB.VAL_NUME_SOLI IS NOT NULL
				  AND MOV_CAJA_DET.MCAC_OID_CABE = MOV_CAJA_CAB.OID_CABE
				  AND MOV_CAJA_DET.MPBC_OID_MEDI_PAGO_BELC = MED_PAG_BEL.OID_MEDI_PAGO_BELC
				  AND MED_PAG_BEL.MPAB_OID_MEDI_PAGO = MED_PAG.OID_MEDI_PAGO
				  AND TIP_MED_PAG.OID_TIPO_MEDI_PAGO = MED_PAG.TMEP_OID_TIPO_MEDI_PAGO
				  AND MED_PAG.PAIS_OID_PAIS = PAIS.OID_PAIS
			      AND TIP_MED_PAG.OID_TIPO_MEDI_PAGO = 1
			--	  AND PAIS.OID_PAIS = 1  										-- PARAMETRO DE PAIS --
			--	  AND OID_CANA = 1	  											-- PARAMETRO DE CANAL --
			--	  AND ACCE.OID_ACCE = 1											-- PARAMETRO DE ACCESO --
			--	  AND SUBA.OID_SBAC = 1											-- PARAMETRO DE SUBACCESO --
				  AND TO_DATE(MOV_CAJA_CAB.FEC_MOVI) = TO_DATE('01/03/2005', 'DD/MM/YYYY')     -- PARAMETRO FECHA DE CIERRE --	
			)
		UNION ALL
			( -- TARJETA --
			SELECT PAIS.OID_PAIS,
				   SUBA.OID_SBAC,
				   PAIS.MONE_OID_MONE,
				   PAIS.MONE_OID_MONE_ALT,
				   TIP_MED_PAG.OID_TIPO_MEDI_PAGO,
				   MED_PAG.OID_MEDI_PAGO,
				   (
				   SELECT MOV_CAJA_DET.IMP_MOVI
				   FROM	SEG_MONED MONE	   		 
				   WHERE MOV_CAJA_DET.MONE_OID_MONE = MONE.OID_MONE
						 AND MONE.OID_MONE = PAIS.MONE_OID_MONE
				   ) MONE,
			   	   (
				   SELECT MOV_CAJA_DET.IMP_DIVI
				   FROM	SEG_MONED MONE	   		 
				   WHERE MOV_CAJA_DET.MONE_OID_MONE = MONE.OID_MONE
						 AND MONE.OID_MONE = PAIS.MONE_OID_MONE_ALT
				   ) MONE_ALT
			FROM SEG_PAIS PAIS,
				 SEG_CANAL CANAL,
				 SEG_ACCES ACCE,
				 SEG_SUBAC SUBA,
				 PED_SOLIC_CABEC SOL_CAB,
				 BEL_MOVIM_CAJA_CABEC MOV_CAJA_CAB,
				 BEL_MOVIM_CAJA_DETAL MOV_CAJA_DET,
				 BEL_MEDIO_PAGO_BELCE MED_PAG_BEL,
				 BEL_MEDIO_PAGO MED_PAG,
				 BEL_TIPO_MEDIO_PAGO TIP_MED_PAG
			 WHERE CANAL.OID_CANA = ACCE.CANA_OID_CANA
				  AND ACCE.OID_ACCE = SUBA.ACCE_OID_ACCE
				  AND SOL_CAB.PAIS_OID_PAIS = PAIS.OID_PAIS
				  AND SOL_CAB.SBAC_OID_SBAC = SUBA.OID_SBAC
				  AND MOV_CAJA_CAB.SOCA_OID_SOLI_CABE = SOL_CAB.OID_SOLI_CABE
				  AND SOL_CAB.VAL_NUME_SOLI IS NOT NULL
				  AND MOV_CAJA_DET.MCAC_OID_CABE = MOV_CAJA_CAB.OID_CABE
				  AND MOV_CAJA_DET.MPBC_OID_MEDI_PAGO_BELC = MED_PAG_BEL.OID_MEDI_PAGO_BELC
				  AND MED_PAG_BEL.MPAB_OID_MEDI_PAGO = MED_PAG.OID_MEDI_PAGO
				  AND TIP_MED_PAG.OID_TIPO_MEDI_PAGO = MED_PAG.TMEP_OID_TIPO_MEDI_PAGO
				  AND MED_PAG.PAIS_OID_PAIS = PAIS.OID_PAIS
				  AND TIP_MED_PAG.OID_TIPO_MEDI_PAGO = 2
			--	  AND PAIS.OID_PAIS = 1  										-- PARAMETRO DE PAIS --
			--	  AND OID_CANA = 1	  											-- PARAMETRO DE CANAL --
			--	  AND ACCE.OID_ACCE = 1											-- PARAMETRO DE ACCESO --
			--	  AND SUBA.OID_SBAC = 1											-- PARAMETRO DE SUBACCESO --
			--	  AND TO_DATE(MOV_CAJA_CAB.FEC_MOVI) = TO_DATE('01/03/2005', 'DD/MM/YYYY')     -- PARAMETRO FECHA DE CIERRE --	
			)
		UNION ALL
			( --CHEQUES--
			SELECT PAIS.OID_PAIS,
				   SUBA.OID_SBAC,
				   PAIS.MONE_OID_MONE,
				   PAIS.MONE_OID_MONE_ALT,
				   TIP_MED_PAG.OID_TIPO_MEDI_PAGO,
				   MED_PAG.OID_MEDI_PAGO,
				   (
				   SELECT MOV_CAJA_DET.IMP_MOVI
				   FROM	SEG_MONED MONE	   		 
				   WHERE MOV_CAJA_DET.MONE_OID_MONE = MONE.OID_MONE
						 AND MONE.OID_MONE = PAIS.MONE_OID_MONE
				   ) MONE,
			   	   (
				   SELECT MOV_CAJA_DET.IMP_DIVI
				   FROM	SEG_MONED MONE	   		 
				   WHERE MOV_CAJA_DET.MONE_OID_MONE = MONE.OID_MONE
						 AND MONE.OID_MONE = PAIS.MONE_OID_MONE_ALT
				   ) MONE_ALT	     	   
			FROM SEG_PAIS PAIS,
				 SEG_CANAL CANAL,
				 SEG_ACCES ACCE,
				 SEG_SUBAC SUBA,
				 PED_SOLIC_CABEC SOL_CAB,
				 BEL_MOVIM_CAJA_CABEC MOV_CAJA_CAB,
				 BEL_MOVIM_CAJA_DETAL MOV_CAJA_DET,
				 BEL_MEDIO_PAGO_BELCE MED_PAG_BEL,
				 BEL_MEDIO_PAGO MED_PAG,
				 BEL_TIPO_MEDIO_PAGO TIP_MED_PAG
			WHERE CANAL.OID_CANA = ACCE.CANA_OID_CANA
				  AND ACCE.OID_ACCE = SUBA.ACCE_OID_ACCE
				  AND SOL_CAB.PAIS_OID_PAIS = PAIS.OID_PAIS
				  AND SOL_CAB.SBAC_OID_SBAC = SUBA.OID_SBAC
				  AND MOV_CAJA_CAB.SOCA_OID_SOLI_CABE = SOL_CAB.OID_SOLI_CABE
				  AND SOL_CAB.VAL_NUME_SOLI IS NOT NULL
				  AND MOV_CAJA_DET.MCAC_OID_CABE = MOV_CAJA_CAB.OID_CABE
				  AND MOV_CAJA_DET.MPBC_OID_MEDI_PAGO_BELC = MED_PAG_BEL.OID_MEDI_PAGO_BELC
				  AND MED_PAG_BEL.MPAB_OID_MEDI_PAGO = MED_PAG.OID_MEDI_PAGO
				  AND TIP_MED_PAG.OID_TIPO_MEDI_PAGO = MED_PAG.TMEP_OID_TIPO_MEDI_PAGO
				  AND MED_PAG.PAIS_OID_PAIS = PAIS.OID_PAIS
			      AND TIP_MED_PAG.OID_TIPO_MEDI_PAGO = 3
			--	  AND PAIS.OID_PAIS = 1  										-- PARAMETRO DE PAIS --
			--	  AND OID_CANA = 1	  											-- PARAMETRO DE CANAL --
			--	  AND ACCE.OID_ACCE = 1											-- PARAMETRO DE ACCESO --
			--	  AND SUBA.OID_SBAC = 1											-- PARAMETRO DE SUBACCESO --
			--	  AND TO_DATE(MOV_CAJA_CAB.FEC_MOVI) = TO_DATE('01/03/2005', 'DD/MM/YYYY')     -- PARAMETRO FECHA DE CIERRE --	
			)
		UNION ALL
			( -- VALES DE COMPRA --
			SELECT PAIS.OID_PAIS,
				   SUBA.OID_SBAC,
				   PAIS.MONE_OID_MONE,
				   PAIS.MONE_OID_MONE_ALT,
				   TIP_MED_PAG.OID_TIPO_MEDI_PAGO,
				   MED_PAG.OID_MEDI_PAGO,
			  	   (
				   SELECT MOV_CAJA_DET.IMP_MOVI
				   FROM SEG_MONED MONE	   		 
				   WHERE MOV_CAJA_DET.MONE_OID_MONE = MONE.OID_MONE
						 AND MONE.OID_MONE = PAIS.MONE_OID_MONE
				   ) MONE,
			   	   (
				   SELECT MOV_CAJA_DET.IMP_DIVI
				   FROM	 SEG_MONED MONE	   		 
				   WHERE MOV_CAJA_DET.MONE_OID_MONE = MONE.OID_MONE
						 AND MONE.OID_MONE = PAIS.MONE_OID_MONE_ALT
				   ) MONE_ALT
			FROM SEG_PAIS PAIS,
				 SEG_CANAL CANAL,
				 SEG_ACCES ACCE,
				 SEG_SUBAC SUBA,
				 PED_SOLIC_CABEC SOL_CAB,
				 BEL_MOVIM_CAJA_CABEC MOV_CAJA_CAB,
				 BEL_MOVIM_CAJA_DETAL MOV_CAJA_DET,
				 BEL_MEDIO_PAGO_BELCE MED_PAG_BEL,
				 BEL_MEDIO_PAGO MED_PAG,
				 BEL_TIPO_MEDIO_PAGO TIP_MED_PAG
			WHERE CANAL.OID_CANA = ACCE.CANA_OID_CANA
				  AND ACCE.OID_ACCE = SUBA.ACCE_OID_ACCE
				  AND SOL_CAB.PAIS_OID_PAIS = PAIS.OID_PAIS
				  AND SOL_CAB.SBAC_OID_SBAC = SUBA.OID_SBAC
				  AND MOV_CAJA_CAB.SOCA_OID_SOLI_CABE = SOL_CAB.OID_SOLI_CABE
				  AND SOL_CAB.VAL_NUME_SOLI IS NOT NULL
				  AND MOV_CAJA_DET.MCAC_OID_CABE = MOV_CAJA_CAB.OID_CABE
				  AND MOV_CAJA_DET.MPBC_OID_MEDI_PAGO_BELC = MED_PAG_BEL.OID_MEDI_PAGO_BELC
				  AND MED_PAG_BEL.MPAB_OID_MEDI_PAGO = MED_PAG.OID_MEDI_PAGO
				  AND TIP_MED_PAG.OID_TIPO_MEDI_PAGO = MED_PAG.TMEP_OID_TIPO_MEDI_PAGO
				  AND MED_PAG.PAIS_OID_PAIS = PAIS.OID_PAIS
			      AND TIP_MED_PAG.OID_TIPO_MEDI_PAGO = 4
			--	  AND PAIS.OID_PAIS = 1  										-- PARAMETRO DE PAIS --
			--	  AND OID_CANA = 1	  											-- PARAMETRO DE CANAL --
			--	  AND ACCE.OID_ACCE = 1											-- PARAMETRO DE ACCESO --
			--	  AND SUBA.OID_SBAC = 1											-- PARAMETRO DE SUBACCESO --
			--	  AND TO_DATE(MOV_CAJA_CAB.FEC_MOVI) = TO_DATE('01/03/2005', 'DD/MM/YYYY')     -- PARAMETRO FECHA DE CIERRE --	
			)
		UNION ALL
			( -- OTROS --
			SELECT PAIS.OID_PAIS,
				   SUBA.OID_SBAC,
				   PAIS.MONE_OID_MONE,
				   PAIS.MONE_OID_MONE_ALT,
				   TIP_MED_PAG.OID_TIPO_MEDI_PAGO,
				   MED_PAG.OID_MEDI_PAGO,
			   	   (
				   SELECT MOV_CAJA_DET.IMP_MOVI
				   FROM	SEG_MONED MONE	   		 
				   WHERE MOV_CAJA_DET.MONE_OID_MONE = MONE.OID_MONE
						 AND MONE.OID_MONE = PAIS.MONE_OID_MONE
				   ) MONE,
			   	   (
				   SELECT MOV_CAJA_DET.IMP_DIVI
				   FROM	SEG_MONED MONE	   		 
				   WHERE MOV_CAJA_DET.MONE_OID_MONE = MONE.OID_MONE
						 AND MONE.OID_MONE = PAIS.MONE_OID_MONE_ALT
				   ) MONE_ALT	 
			FROM SEG_PAIS PAIS,
				 SEG_CANAL CANAL,
				 SEG_ACCES ACCE,
				 SEG_SUBAC SUBA,
				 PED_SOLIC_CABEC SOL_CAB,
				 BEL_MOVIM_CAJA_CABEC MOV_CAJA_CAB,
				 BEL_MOVIM_CAJA_DETAL MOV_CAJA_DET,
				 BEL_MEDIO_PAGO_BELCE MED_PAG_BEL,
				 BEL_MEDIO_PAGO MED_PAG,
				 BEL_TIPO_MEDIO_PAGO TIP_MED_PAG		 	
			WHERE CANAL.OID_CANA = ACCE.CANA_OID_CANA
				  AND ACCE.OID_ACCE = SUBA.ACCE_OID_ACCE
				  AND SOL_CAB.PAIS_OID_PAIS = PAIS.OID_PAIS
				  AND SOL_CAB.SBAC_OID_SBAC = SUBA.OID_SBAC
				  AND MOV_CAJA_CAB.SOCA_OID_SOLI_CABE = SOL_CAB.OID_SOLI_CABE
				  AND SOL_CAB.VAL_NUME_SOLI IS NOT NULL
				  AND MOV_CAJA_DET.MCAC_OID_CABE = MOV_CAJA_CAB.OID_CABE
				  AND MOV_CAJA_DET.MPBC_OID_MEDI_PAGO_BELC = MED_PAG_BEL.OID_MEDI_PAGO_BELC
				  AND MED_PAG_BEL.MPAB_OID_MEDI_PAGO = MED_PAG.OID_MEDI_PAGO
				  AND TIP_MED_PAG.OID_TIPO_MEDI_PAGO = MED_PAG.TMEP_OID_TIPO_MEDI_PAGO
				  AND MED_PAG.PAIS_OID_PAIS = PAIS.OID_PAIS
  	      		  AND TIP_MED_PAG.OID_TIPO_MEDI_PAGO NOT IN (1,2,3,4)
			--	  AND PAIS.OID_PAIS = 1  										-- PARAMETRO DE PAIS --
			--	  AND OID_CANA = 1	  											-- PARAMETRO DE CANAL --
			--	  AND ACCE.OID_ACCE = 1											-- PARAMETRO DE ACCESO --
			--	  AND SUBA.OID_SBAC = 1											-- PARAMETRO DE SUBACCESO --
			--	  AND TO_DATE(MOV_CAJA_CAB.FEC_MOVI) = TO_DATE('01/03/2005', 'DD/MM/YYYY')     -- PARAMETRO FECHA DE CIERRE --	
			)
		) DOC,
		(
	    SELECT GEN.VAL_OID, GEN.VAL_I18N
		FROM V_GEN_I18N_SICC GEN
		WHERE GEN.ATTR_ENTI = 'SEG_PAIS'
		     AND GEN.IDIO_OID_IDIO = 1 								-- PARAMETRO DE IDIOMA --
	    ) GEN_PAIS,
        (
	    SELECT GEN.VAL_OID, GEN.VAL_I18N
		FROM V_GEN_I18N_SICC GEN
		WHERE GEN.ATTR_ENTI = 'SEG_SUBAC'
		      AND GEN.IDIO_OID_IDIO = 1  								 -- PARAMETRO DE IDIOMA --
	    ) GEN_SUBA,		 	
		(
		SELECT GEN.VAL_OID, GEN.VAL_I18N
		FROM V_GEN_I18N_SICC GEN
		WHERE GEN.ATTR_ENTI = 'BEL_TIPO_MEDIO_PAGO'
		      AND GEN.IDIO_OID_IDIO = 1								 -- PARAMETRO DE IDIOMA --
	    ) GEN_TIP_MED_PAGO,
		(
		SELECT GEN.VAL_OID, GEN.VAL_I18N
		FROM V_GEN_I18N_SICC GEN
		WHERE GEN.ATTR_ENTI = 'BEL_MEDIO_PAGO'
			   AND GEN.IDIO_OID_IDIO = 1	   							 -- PARAMETRO DE IDIOMA --
        ) GEN_MED_PAGO
		WHERE DOC.OID_PAIS = GEN_PAIS.VAL_OID(+)
			  AND DOC.OID_SBAC = GEN_SUBA.VAL_OID(+)
			  AND DOC.OID_TIPO_MEDI_PAGO = GEN_TIP_MED_PAGO.VAL_OID(+)
			  AND DOC.OID_MEDI_PAGO = GEN_MED_PAGO.VAL_OID(+)
		GROUP BY GEN_PAIS.VAL_I18N,
		         GEN_SUBA.VAL_I18N,
		         'COBROS POR MEDIOS DE PAGO',
	             GEN_TIP_MED_PAGO.VAL_I18N,
				 GEN_MED_PAGO.VAL_I18N,
				 MONE_OID_MONE,
				 MONE_OID_MONE_ALT
)
order by pais, subacceso, docu desc