SELECT PAIS,
	   COD_SBAC,
	   DESC_SUBA,
	   DES_MARC_PROD,
	   DESC_UNI_NEG,
	   NEGOC,
	   DESC_PROD,
	   COD_SAP,
	   COD_OPER,
	   FECHA,
	   UNID_ATEN,
	   MONTO_FAC,
	   N_OPERAC
FROM
(
	(
	SELECT GEN_PAIS.VAL_I18N PAIS,
		   SUBA.COD_SBAC,
		   GEN_SUBA.VAL_I18N DESC_SUBA,
		   MAR_PRO.DES_MARC_PROD, 
		   GEN_UNI_NEG.VAL_I18N DESC_UNI_NEG,
		   GEN_NEG.VAL_I18N NEGOC,  
		   GEN_PROD.VAL_I18N DESC_PROD,
		   PROD.COD_SAP,
		   'VT' COD_OPER,
		   SOL_CAB.FEC_CRON FECHA,
		   SUM(SOL_POS.NUM_UNID_VENT) UNID_ATEN,
		   SUM(NVL(SOL_POS.VAL_PREC_CATA_UNIT_LOCA, 0) * NVL(SOL_POS.NUM_UNID_VENT, 0)) MONTO_FAC,
		   COUNT(*) N_OPERAC,
		   1 AS CONTROL_OPER
	FROM PED_SOLIC_CABEC SOL_CAB,
		 PED_TIPO_SOLIC TIP_SOL,
		 PED_TIPO_SOLIC_PAIS TIP_SOL_PAIS,
		 SEG_ACCES ACCE,
		 SEG_SUBAC SUBA,
		 PED_SOLIC_POSIC SOL_POS,
		 SEG_PAIS PAIS,
		 MAE_PRODU PROD,
		 SEG_MARCA_PRODU MAR_PRO,
		 MAE_UNIDA_NEGOC UNI_NEG,
		 MAE_NEGOC NEG,
		 (
		 SELECT GEN.VAL_OID, GEN.VAL_I18N
		 FROM V_GEN_I18N_SICC GEN
		 WHERE GEN.ATTR_ENTI = 'MAE_PRODU'
		 	 AND GEN.IDIO_OID_IDIO = 1		  							-- PRAMETRO DE IDIOMA --	 
		 ) GEN_PROD,
		 (
		 SELECT GEN.VAL_OID, GEN.VAL_I18N
		 FROM V_GEN_I18N_SICC GEN
		 WHERE GEN.ATTR_ENTI = 'MAE_NEGOC'
		 	 AND GEN.IDIO_OID_IDIO = 1		  							-- PRAMETRO DE IDIOMA --	 
		 ) GEN_NEG,
		 (
		 SELECT GEN.VAL_OID, GEN.VAL_I18N
		 FROM V_GEN_I18N_SICC GEN
		 WHERE GEN.ATTR_ENTI = 'MAE_UNIDA_NEGOC'
		 	 AND GEN.IDIO_OID_IDIO = 1		  							-- PRAMETRO DE IDIOMA --	 
		 ) GEN_UNI_NEG,
		 (
		 SELECT GEN.VAL_OID, GEN.VAL_I18N
		 FROM V_GEN_I18N_SICC GEN
		 WHERE GEN.ATTR_ENTI = 'SEG_PAIS'
		 	 AND GEN.IDIO_OID_IDIO = 1		  							-- PRAMETRO DE IDIOMA --
		 ) GEN_PAIS,
		 (
		 SELECT GEN.VAL_OID, GEN.VAL_I18N
		 FROM V_GEN_I18N_SICC GEN
		 WHERE GEN.ATTR_ENTI = 'SEG_SUBAC'
		 	   AND GEN.IDIO_OID_IDIO = 1  							-- PARAMETRO DE IDIOMA --
		 ) GEN_SUBA
	WHERE ACCE.OID_ACCE = TIP_SOL.ACCE_OID_ACCE
		  AND TIP_SOL.OID_TIPO_SOLI = TIP_SOL_PAIS.TSOL_OID_TIPO_SOLI
		  AND TIP_SOL_PAIS.OID_TIPO_SOLI_PAIS = SOL_CAB.TSPA_OID_TIPO_SOLI_PAIS
		  AND SOL_POS.SOCA_OID_SOLI_CABE = SOL_CAB.OID_SOLI_CABE
		  AND SUBA.ACCE_OID_ACCE = ACCE.OID_ACCE
		  AND SOL_CAB.SBAC_OID_SBAC = SUBA.OID_SBAC
	  	  AND SOL_CAB.IND_TS_NO_CONSO = 0
		  AND SOL_CAB.IND_PEDI_PRUE = 0
		  AND SUBA.OID_SBAC = GEN_SUBA.VAL_OID(+)
		  AND SOL_CAB.PAIS_OID_PAIS = PAIS.OID_PAIS
		  AND PAIS.OID_PAIS = GEN_PAIS.VAL_OID(+)
	      AND SOL_POS.NUM_UNID_VENT <> 0
		  AND SOL_POS.NUM_UNID_VENT IS NOT NULL
		  AND PROD.OID_PROD = SOL_POS.PROD_OID_PROD
		  AND PROD.PAIS_OID_PAIS = SOL_CAB.PAIS_OID_PAIS
		  AND MAR_PRO.OID_MARC_PROD = PROD.MAPR_OID_MARC_PROD
		  AND UNI_NEG.OID_UNID_NEGO = PROD.UNEG_OID_UNID_NEGO
		  AND UNI_NEG.OID_UNID_NEGO = GEN_UNI_NEG.VAL_OID(+)
		  AND NEG.OID_NEGO = PROD.NEGO_OID_NEGO
		  AND NEG.OID_NEGO = GEN_NEG.VAL_OID(+)
		  AND PROD.OID_PROD = GEN_PROD.VAL_OID(+)
	--	  AND PROD.MAPR_OID_MARC_PROD = 1							  -- PARAMETRO DE MARCA DE PRODUCTO --
	--	  AND PROD.UNEG_OID_UNID_NEGO = 1							  -- PARAMETRO DE UNIDAD DE NEGOCIO --
	--	  AND PROD.NEGO_OID_NEGO = 1	  								 -- PARAMETRO DE NEGOCIO --
		  AND PROD.COD_SAP = '200007727-N003'						  -- PARAMETRO DE PRODUCTO (CODIGO SAP) -- 
		  AND TO_DATE(SOL_CAB.FEC_CRON) >= TO_DATE('01/01/2000', 'DD/MM/YYYY') --PARAMETRO DE FECHA DE INICIO --
		  AND TO_DATE(SOL_CAB.FEC_CRON) <= TO_DATE('01/01/2050', 'DD/MM/YYYY') --PARAMETRO DE FECHA DE FIN --
		  AND SOL_CAB.SBAC_OID_SBAC IN (1)			  				-- PARAMETRO DE SUBACCESO --
		  AND SOL_CAB.PAIS_OID_PAIS = 1	  				  			-- PARAMETRO DE PAIS --
		  AND TIP_SOL.ACCE_OID_ACCE = 1								-- PARAMETRO DE ACCESO --
		  AND ACCE.CANA_OID_CANA = 1  								-- PARAMETRO DE CANAL --
	GROUP BY GEN_PAIS.VAL_I18N,
		   SUBA.COD_SBAC,
		   GEN_SUBA.VAL_I18N,
		   MAR_PRO.DES_MARC_PROD, 
		   GEN_UNI_NEG.VAL_I18N,
	  	   GEN_NEG.VAL_I18N,
		   PROD.COD_SAP,
	   	   GEN_PROD.VAL_I18N,
		   'VT',
		   SOL_CAB.FEC_CRON
	)
	UNION ALL
	(
	SELECT GEN_PAIS.VAL_I18N PAIS,
		   SUBA.COD_SBAC,
		   GEN_SUBA.VAL_I18N DESC_SUBA,
		   MAR_PRO.DES_MARC_PROD, 
		   GEN_UNI_NEG.VAL_I18N DESC_UNI_NEG,
		   GEN_NEG.VAL_I18N NEGOC,  
		   GEN_PROD.VAL_I18N DESC_PROD,
		   PROD.COD_SAP,
		   'CM' COD_OPER,
		   SOL_CAB.FEC_CRON FECHA,
		   SUM(SOL_POS.NUM_UNID_CAMB) UNID_ATEN,
		   SUM(NVL(SOL_POS.VAL_PREC_CATA_UNIT_LOCA, 0) * NVL(SOL_POS.NUM_UNID_CAMB, 0)) MONTO_FAC,
		   COUNT(*) N_OPERAC,
		   2 AS CONTROL_OPER
	FROM PED_SOLIC_CABEC SOL_CAB,
		 PED_TIPO_SOLIC TIP_SOL,
		 PED_TIPO_SOLIC_PAIS TIP_SOL_PAIS,
		 SEG_ACCES ACCE,
		 SEG_SUBAC SUBA,
		 PED_SOLIC_POSIC SOL_POS,
		 SEG_PAIS PAIS,
		 MAE_PRODU PROD,
		 SEG_MARCA_PRODU MAR_PRO,
		 MAE_UNIDA_NEGOC UNI_NEG,
		 MAE_NEGOC NEG,
		 (
		 SELECT GEN.VAL_OID, GEN.VAL_I18N
		 FROM V_GEN_I18N_SICC GEN
		 WHERE GEN.ATTR_ENTI = 'MAE_PRODU'
		 	 AND GEN.IDIO_OID_IDIO = 1		  							-- PRAMETRO DE IDIOMA --	 
		 ) GEN_PROD,
		 (
		 SELECT GEN.VAL_OID, GEN.VAL_I18N
		 FROM V_GEN_I18N_SICC GEN
		 WHERE GEN.ATTR_ENTI = 'MAE_NEGOC'
		 	 AND GEN.IDIO_OID_IDIO = 1		  							-- PRAMETRO DE IDIOMA --	 
		 ) GEN_NEG,
		 (
		 SELECT GEN.VAL_OID, GEN.VAL_I18N
		 FROM V_GEN_I18N_SICC GEN
		 WHERE GEN.ATTR_ENTI = 'MAE_UNIDA_NEGOC'
		 	 AND GEN.IDIO_OID_IDIO = 1		  							-- PRAMETRO DE IDIOMA --	 
		 ) GEN_UNI_NEG,
		 (
		 SELECT GEN.VAL_OID, GEN.VAL_I18N
		 FROM V_GEN_I18N_SICC GEN
		 WHERE GEN.ATTR_ENTI = 'SEG_PAIS'
		 	 AND GEN.IDIO_OID_IDIO = 1		  							-- PRAMETRO DE IDIOMA --
		 ) GEN_PAIS,
		 (
		 SELECT GEN.VAL_OID, GEN.VAL_I18N
		 FROM V_GEN_I18N_SICC GEN
		 WHERE GEN.ATTR_ENTI = 'SEG_SUBAC'
		 	   AND GEN.IDIO_OID_IDIO = 1  							-- PARAMETRO DE IDIOMA --
		 ) GEN_SUBA
	WHERE ACCE.OID_ACCE = TIP_SOL.ACCE_OID_ACCE
		  AND TIP_SOL.OID_TIPO_SOLI = TIP_SOL_PAIS.TSOL_OID_TIPO_SOLI
		  AND TIP_SOL_PAIS.OID_TIPO_SOLI_PAIS = SOL_CAB.TSPA_OID_TIPO_SOLI_PAIS
		  AND SOL_POS.SOCA_OID_SOLI_CABE = SOL_CAB.OID_SOLI_CABE
		  AND SUBA.ACCE_OID_ACCE = ACCE.OID_ACCE
		  AND SOL_CAB.SBAC_OID_SBAC = SUBA.OID_SBAC
	  	  AND SOL_CAB.IND_TS_NO_CONSO = 0
		  AND SOL_CAB.IND_PEDI_PRUE = 0
		  AND SUBA.OID_SBAC = GEN_SUBA.VAL_OID(+)
		  AND SOL_CAB.PAIS_OID_PAIS = PAIS.OID_PAIS
		  AND PAIS.OID_PAIS = GEN_PAIS.VAL_OID(+)
	      AND SOL_POS.NUM_UNID_CAMB <> 0
		  AND SOL_POS.NUM_UNID_CAMB IS NOT NULL
		  AND PROD.OID_PROD = SOL_POS.PROD_OID_PROD
		  AND PROD.PAIS_OID_PAIS = SOL_CAB.PAIS_OID_PAIS
		  AND MAR_PRO.OID_MARC_PROD = PROD.MAPR_OID_MARC_PROD
		  AND UNI_NEG.OID_UNID_NEGO = PROD.UNEG_OID_UNID_NEGO
		  AND UNI_NEG.OID_UNID_NEGO = GEN_UNI_NEG.VAL_OID(+)
		  AND NEG.OID_NEGO = PROD.NEGO_OID_NEGO
		  AND NEG.OID_NEGO = GEN_NEG.VAL_OID(+)
		  AND PROD.OID_PROD = GEN_PROD.VAL_OID(+)
		  AND PROD.MAPR_OID_MARC_PROD = 1							  -- PARAMETRO DE MARCA DE PRODUCTO --
	      AND PROD.UNEG_OID_UNID_NEGO = 1							  -- PARAMETRO DE UNIDAD DE NEGOCIO --
	      AND PROD.NEGO_OID_NEGO = 1	  								 -- PARAMETRO DE NEGOCIO --
		  AND PROD.COD_SAP = '200007727-N003'						  -- PARAMETRO DE PRODUCTO (CODIGO SAP) -- 
		  AND TO_dATE(SOL_CAB.FEC_CRON) >= TO_DATE('01/01/2000', 'DD/MM/YYYY') --PARAMETRO DE FECHA DE INICIO --
		  AND TO_DATE(SOL_CAB.FEC_CRON) <= TO_DATE('01/01/2050', 'DD/MM/YYYY') --PARAMETRO DE FECHA DE FIN --
		  AND SOL_CAB.SBAC_OID_SBAC IN (1)			  				-- PARAMETRO DE SUBACCESO --
		  AND SOL_CAB.PAIS_OID_PAIS = 1	  				  			-- PARAMETRO DE PAIS --
		  AND TIP_SOL.ACCE_OID_ACCE = 1								-- PARAMETRO DE ACCESO --
		  AND ACCE.CANA_OID_CANA = 1  								-- PARAMETRO DE CANAL --
	GROUP BY GEN_PAIS.VAL_I18N,
		   SUBA.COD_SBAC,
		   GEN_SUBA.VAL_I18N,
		   MAR_PRO.DES_MARC_PROD, 
		   GEN_UNI_NEG.VAL_I18N,
	  	   GEN_NEG.VAL_I18N,
		   PROD.COD_SAP,
	   	   GEN_PROD.VAL_I18N,
		   'CM',
		   SOL_CAB.FEC_CRON
	)
)	   
WHERE CONTROL_OPER IN (1, 2)	   
ORDER BY COD_SAP,
		 COD_OPER,
		 FECHA
