SELECT GEN_PAIS.VAL_I18N PAIS,
	   DTO_DES.NUM_DESC COD_DESC,
	   SUBA.COD_SBAC COD_LOCAL,
	   GEN_SUBA.VAL_I18N NOMB_LOCAL,
	   PROD.COD_SAP COD_PRODU,
	   GEN_PRODU.VAL_I18N DESC_PRODU,
	   NVL(SUM(PED_SOL_POS.NUM_UNID_ATEN),0) TOTAL_UNID_ATEN,
	   NVL(SUM(PED_SOL_POS.VAL_PREC_CATA_UNIT_DOCU),0) TOTAL_P_CAT,
	   NVL(SUM(PED_SOL_POS.VAL_PREC_FACT_UNIT_DOCU),0) TOTAL_P_FAC
FROM PED_SOLIC_POSIC PED_SOL_POS,
	 MAE_PRODU PROD,
	 SEG_CANAL CANAL,
	 SEG_ACCES ACCE,
	 SEG_SUBAC SUBA,
	 MAE_CLIEN CLI,
	 PED_SOLIC_CABEC PED_SOL_CAB,
	 DTO_HISTO_DTO DTO_HIS,
	 DTO_DESCU DTO_DES,
	 CRA_PERIO PERIO,
	 SEG_PAIS,
	 PED_SEGUI_PEDID SEG_PED,
	 (
	 SELECT GEN.VAL_OID, GEN.VAL_I18N
	 FROM V_GEN_I18N_SICC GEN
	 WHERE GEN.ATTR_ENTI = 'SEG_SUBAC'
	 	   AND GEN.IDIO_OID_IDIO = 1  	   								  -- PARAMETRO DE IDIOMA --
	 ) GEN_SUBA,
	 (
	 SELECT GEN.VAL_OID, GEN.VAL_I18N
	 FROM V_GEN_I18N_SICC GEN
	 WHERE GEN.ATTR_ENTI = 'MAE_PRODU'
	 	   AND GEN.IDIO_OID_IDIO = 1  									  -- PARAMETRO DE IDIOMA --	 
	 ) GEN_PRODU,
	 (
	 SELECT GEN.VAL_OID, GEN.VAL_I18N
	 FROM V_GEN_I18N_SICC GEN
	 WHERE GEN.ATTR_ENTI = 'SEG_PAIS'
	 	   AND GEN.IDIO_OID_IDIO = 1 									  -- PARAMETRO DE IDIOMA --
	 ) GEN_PAIS
WHERE PED_SOL_POS.PROD_OID_PROD = PROD.OID_PROD
	  AND PED_SOL_CAB.SBAC_OID_SBAC = SUBA.OID_SBAC
	  AND PED_SOL_CAB.CLIE_OID_CLIE = CLI.OID_CLIE
	  AND PED_SOL_CAB.PERD_OID_PERI = PERIO.OID_PERI
	  AND ACCE.OID_ACCE = SUBA.ACCE_OID_ACCE
	  AND CANAL.OID_CANA = ACCE.CANA_OID_CANA
	  AND PERIO.CANA_OID_CANA = CANAL.OID_CANA
	  AND DTO_HIS.CLIE_OID_CLIE = CLI.OID_CLIE
	  AND DTO_HIS.PAIS_OID_PAIS = PED_SOL_CAB.PAIS_OID_PAIS
	  AND DTO_HIS.SOCA_OID_SOLI_CABE = PED_SOL_CAB.OID_SOLI_CABE
	  AND DTO_DES.CANA_OID_CANA = CANAL.OID_CANA
	  AND DTO_DES.OID_DESC = DTO_HIS.DCTO_OID_DESC
	  AND PED_SOL_POS.SOCA_OID_SOLI_CABE = PED_SOL_CAB.OID_SOLI_CABE
	  AND PED_SOL_CAB.PAIS_OID_PAIS = SEG_PAIS.OID_PAIS
	  AND PED_SOL_CAB.OID_SOLI_CABE = SEG_PED.SOCA_OID_SOLI_CABE
	  AND SEG_PED.HISE_OID_HITO = 1
	  AND SEG_PAIS.OID_PAIS = GEN_PAIS.VAL_OID(+)
	  AND SUBA.OID_SBAC = GEN_SUBA.VAL_OID(+)
	  AND PROD.OID_PROD = GEN_PRODU.VAL_OID(+)
--	  AND PED_SOL_CAB.PAIS_OID_PAIS = 1			   			-- PARAMETRO DE PAIS --
--	  AND SUBA.OID_SBAC IN (1)			  						-- PARAMETRO DE SUBACCESO --
--	  AND ACCE.OID_ACCE = 1									-- PARAMETRO DE ACCESO --
--	  AND CANAL.OID_CANA = 1								-- PARAMETRO DE CANAL --
--	  AND DTO_DES.NUM_DESC = 3 									 -- PARAMETRO DE NUMERO DE DESCUENTO --
--	  AND TO_DATE(SEG_PED.FEC) >= TO_DATE('01/01/2000'||':'||'10:10:10','DD/MM/YYYY:HH24:MI:SS') -- PARAMETRO DE FECHA DESDE Y HORA DESDE--
--	  AND TO_DATE(SEG_PED.FEC) <= TO_DATE('01/01/2050'||':'||'10:10:10','DD/MM/YYYY:HH24:MI:SS') -- PARAMETRO DE FECHA HASTA Y HORA HASTA--
GROUP BY GEN_PAIS.VAL_I18N, 
	  	 DTO_DES.NUM_DESC,
	     SUBA.COD_SBAC,
         GEN_SUBA.VAL_I18N,
	     PROD.COD_SAP,
	     GEN_PRODU.VAL_I18N
ORDER BY GEN_PAIS.VAL_I18N,
	  	 DTO_DES.NUM_DESC,
	     SUBA.COD_SBAC,
         GEN_SUBA.VAL_I18N,
		 PROD.COD_SAP,
	     GEN_PRODU.VAL_I18N
