SELECT * 
FROM
(
	(
	SELECT GEN_PAIS.VAL_I18N PAIS,
		   DTO_DES.NUM_DESC COD_DESC,
		   SUBA.COD_SBAC COD_LOCAL,
		   GEN_SUBA.VAL_I18N NOMB_LOCAL,
		   NULL AS COD_ESP, NULL AS COD_CLIE, NULL AS NOMB_CLI,
		   PROD.COD_SAP COD_PRODU,
		   GEN_PRODU.VAL_I18N DESC_PRODU,
		   NVL(SUM(PED_SOL_POS.NUM_UNID_ATEN),0) TOTAL_UNID_ATEN,
		   NVL(SUM(PED_SOL_POS.VAL_PREC_CATA_UNIT_DOCU),0) TOTAL_P_CAT,
		   NVL(SUM(PED_SOL_POS.VAL_PREC_FACT_UNIT_DOCU),0) TOTAL_P_FAC,
		   1 AS DETALLE
	FROM PED_SOLIC_POSIC PED_SOL_POS,
		 MAE_PRODU PROD,
		 SEG_CANAL CANAL,
		 SEG_ACCES ACCE,
		 SEG_SUBAC SUBA,
		 MAE_CLIEN CLI,
		 PED_SOLIC_CABEC PED_SOL_CAB,
		 DTO_HISTO_DTO DTO_HIS,
		 DTO_DESCU DTO_DES,
		 CRA_PERIO PERIO,
		 SEG_PAIS,
		 PED_SEGUI_PEDID SEG_PED,
		 (
		 SELECT GEN.VAL_OID, GEN.VAL_I18N
		 FROM V_GEN_I18N_SICC GEN
		 WHERE GEN.ATTR_ENTI = 'SEG_SUBAC'
		 	   AND GEN.IDIO_OID_IDIO = 1  	   								  -- PARAMETRO DE IDIOMA --
		 ) GEN_SUBA,
		 (
		 SELECT GEN.VAL_OID, GEN.VAL_I18N
		 FROM V_GEN_I18N_SICC GEN
		 WHERE GEN.ATTR_ENTI = 'MAE_PRODU'
		 	   AND GEN.IDIO_OID_IDIO = 1  									  -- PARAMETRO DE IDIOMA --	 
		 ) GEN_PRODU,
		 (
		 SELECT GEN.VAL_OID, GEN.VAL_I18N
		 FROM V_GEN_I18N_SICC GEN
		 WHERE GEN.ATTR_ENTI = 'SEG_PAIS'
		 	   AND GEN.IDIO_OID_IDIO = 1 									  -- PARAMETRO DE IDIOMA --
		 ) GEN_PAIS
	WHERE PED_SOL_POS.PROD_OID_PROD = PROD.OID_PROD
		  AND PED_SOL_CAB.SBAC_OID_SBAC = SUBA.OID_SBAC
		  AND PED_SOL_CAB.CLIE_OID_CLIE = CLI.OID_CLIE
		  AND PED_SOL_CAB.PERD_OID_PERI = PERIO.OID_PERI
		  AND ACCE.OID_ACCE = SUBA.ACCE_OID_ACCE
		  AND CANAL.OID_CANA = ACCE.CANA_OID_CANA
		  AND PERIO.CANA_OID_CANA = CANAL.OID_CANA
		  AND DTO_HIS.CLIE_OID_CLIE = CLI.OID_CLIE
		  AND DTO_HIS.PAIS_OID_PAIS = PED_SOL_CAB.PAIS_OID_PAIS
		  AND DTO_HIS.SOCA_OID_SOLI_CABE = PED_SOL_CAB.OID_SOLI_CABE
		  AND DTO_DES.CANA_OID_CANA = CANAL.OID_CANA
		  AND DTO_DES.OID_DESC = DTO_HIS.DCTO_OID_DESC
		  AND PED_SOL_POS.SOCA_OID_SOLI_CABE = PED_SOL_CAB.OID_SOLI_CABE
		  AND PED_SOL_CAB.PAIS_OID_PAIS = SEG_PAIS.OID_PAIS
		  AND PED_SOL_CAB.OID_SOLI_CABE = SEG_PED.SOCA_OID_SOLI_CABE
		  AND SEG_PED.HISE_OID_HITO = 1
		  AND SEG_PAIS.OID_PAIS = GEN_PAIS.VAL_OID(+)
		  AND SUBA.OID_SBAC = GEN_SUBA.VAL_OID(+)
		  AND PROD.OID_PROD = GEN_PRODU.VAL_OID(+)
	--	  AND PED_SOL_CAB.PAIS_OID_PAIS = 1			   			-- PARAMETRO DE PAIS --
	--	  AND SUBA.OID_SBAC IN (1)			  						-- PARAMETRO DE SUBACCESO --
	--	  AND ACCE.OID_ACCE = 1									-- PARAMETRO DE ACCESO --
	--	  AND CANAL.OID_CANA = 1								-- PARAMETRO DE CANAL --
	--	  AND DTO_DES.NUM_DESC = 3 									 -- PARAMETRO DE NUMERO DE DESCUENTO --
	--	  AND TO_DATE(SEG_PED.FEC) >= TO_DATE('01/01/2000'||':'||'10:10:10','DD/MM/YYYY:HH24:MI:SS') -- PARAMETRO DE FECHA DESDE Y HORA DESDE--
	--	  AND TO_DATE(SEG_PED.FEC) <= TO_DATE('01/01/2050'||':'||'10:10:10','DD/MM/YYYY:HH24:MI:SS') -- PARAMETRO DE FECHA HASTA Y HORA HASTA--
	GROUP BY GEN_PAIS.VAL_I18N, 
		  	 DTO_DES.NUM_DESC,
		     SUBA.COD_SBAC,
	         GEN_SUBA.VAL_I18N,
		     PROD.COD_SAP,
		     GEN_PRODU.VAL_I18N
	)
UNION ALL
	(
	SELECT  
		   GEN_PAIS.VAL_I18N PAIS,
		   DTO_DES.NUM_DESC COD_DESC,
		   SUBA.COD_SBAC COD_LOCAL,
		   GEN_SUBA.VAL_I18N NOMB_LOCAL,
		   PED_SOL_CAB.VAL_USUA COD_ESP,
		   CLI.COD_CLIE,
		   CLI.VAL_NOM1||' '||CLI.VAL_NOM2||' '||CLI.VAL_APE1||' '||CLI.VAL_APE2 NOMB_CLI,
		   PROD.COD_SAP COD_PRODU,
		   GEN_PRODU.VAL_I18N DESC_PRODU,
		   NVL(SUM(PED_SOL_POS.NUM_UNID_ATEN),0) TOTAL_UNID_ATEN,
		   NVL(SUM(PED_SOL_POS.VAL_PREC_CATA_UNIT_DOCU),0) TOTAL_P_CAT,
		   NVL(SUM(PED_SOL_POS.VAL_PREC_FACT_UNIT_DOCU),0) TOTAL_P_FAC,
		   2 AS DETALLE
	FROM PED_SOLIC_POSIC PED_SOL_POS,
		 MAE_PRODU PROD,
		 SEG_CANAL CANAL,
		 SEG_ACCES ACCE,
		 SEG_SUBAC SUBA,
		 PED_SOLIC_CABEC PED_SOL_CAB,
		 MAE_CLIEN CLI,
		 DTO_HISTO_DTO DTO_HIS,
		 DTO_DESCU DTO_DES,
		 DTO_DESCU_ACCES DTO_DES_ACC,
		 DTO_DESCU_SUBAC DTO_DES_SUB,
		 CRA_PERIO PERIO,
		 SEG_PAIS,
		 PED_SEGUI_PEDID SEG_PED,
		 (
		 SELECT GEN.VAL_OID, GEN.VAL_I18N
		 FROM V_GEN_I18N_SICC GEN
		 WHERE GEN.ATTR_ENTI = 'SEG_SUBAC'
		 	   AND GEN.IDIO_OID_IDIO = 1  	   								  -- PARAMETRO DE IDIOMA --
		 ) GEN_SUBA,
		 (
		 SELECT GEN.VAL_OID, GEN.VAL_I18N
		 FROM V_GEN_I18N_SICC GEN
		 WHERE GEN.ATTR_ENTI = 'MAE_PRODU'
		 	   AND GEN.IDIO_OID_IDIO = 1  									  -- PARAMETRO DE IDIOMA --	 
		 ) GEN_PRODU,
		 (
		 SELECT GEN.VAL_OID, GEN.VAL_I18N
		 FROM V_GEN_I18N_SICC GEN
		 WHERE GEN.ATTR_ENTI = 'SEG_PAIS'
		 	   AND GEN.IDIO_OID_IDIO = 1 									  -- PARAMETRO DE IDIOMA --
		 ) GEN_PAIS
	WHERE PED_SOL_POS.PROD_OID_PROD = PROD.OID_PROD
		  AND PED_SOL_CAB.SBAC_OID_SBAC = SUBA.OID_SBAC
		  AND PED_SOL_CAB.CLIE_OID_CLIE = CLI.OID_CLIE
		  AND PED_SOL_CAB.PERD_OID_PERI = PERIO.OID_PERI
		  AND ACCE.OID_ACCE = SUBA.ACCE_OID_ACCE
		  AND CANAL.OID_CANA = ACCE.CANA_OID_CANA
		  AND PERIO.CANA_OID_CANA = CANAL.OID_CANA
		  AND DTO_DES_ACC.ACCE_OID_ACCE = ACCE.OID_ACCE
		  AND DTO_DES_ACC.DCTO_OID_DESC = DTO_DES.OID_DESC
		  AND DTO_DES_SUB.SBAC_OID_SBAC = SUBA.OID_SBAC
		  AND DTO_DES_SUB.DCTO_OID_DESC = DTO_DES.OID_DESC
		  AND DTO_HIS.CLIE_OID_CLIE = CLI.OID_CLIE
		  AND DTO_HIS.PAIS_OID_PAIS = PED_SOL_CAB.PAIS_OID_PAIS
		  AND DTO_HIS.SOCA_OID_SOLI_CABE = PED_SOL_CAB.OID_SOLI_CABE
		  AND DTO_DES.CANA_OID_CANA = CANAL.OID_CANA
		  AND DTO_DES.OID_DESC = DTO_HIS.DCTO_OID_DESC
		  AND PED_SOL_POS.SOCA_OID_SOLI_CABE = PED_SOL_CAB.OID_SOLI_CABE
		  AND PED_SOL_CAB.PAIS_OID_PAIS = SEG_PAIS.OID_PAIS
		  AND PED_SOL_CAB.OID_SOLI_CABE = SEG_PED.SOCA_OID_SOLI_CABE
		  AND SEG_PED.HISE_OID_HITO = 1
		  AND SEG_PAIS.OID_PAIS = GEN_PAIS.VAL_OID(+)
		  AND SUBA.OID_SBAC = GEN_SUBA.VAL_OID(+)
		  AND PROD.OID_PROD = GEN_PRODU.VAL_OID(+)
	--	  AND PED_SOL_CAB.PAIS_OID_PAIS = 1			   			-- PARAMETRO DE PAIS --
	--	  AND SUBA.OID_SBAC IN (1)			  						-- PARAMETRO DE SUBACCESO --
	--	  AND ACCE.OID_ACCE = 1									-- PARAMETRO DE ACCESO --
	--	  AND CANAL.OID_CANA = 1								-- PARAMETRO DE CANAL --
	--	  AND DTO_DES.NUM_DESC = 3 									 -- PARAMETRO DE NUMERO DE DESCUENTO --
	--	  AND TO_DATE(SEG_PED.FEC) >= TO_DATE('01/01/2000'||':'||'10:10:10','DD/MM/YYYY:HH24:MI:SS') -- PARAMETRO DE FECHA DESDE Y HORA DESDE--
	--	  AND TO_DATE(SEG_PED.FEC) <= TO_DATE('01/01/2050'||':'||'10:10:10','DD/MM/YYYY:HH24:MI:SS') -- PARAMETRO DE FECHA HASTA Y HORA HASTA--
	GROUP BY GEN_PAIS.VAL_I18N, 
		  	 DTO_DES.NUM_DESC,
		     SUBA.COD_SBAC,
	         GEN_SUBA.VAL_I18N,
		     PED_SOL_CAB.VAL_USUA,
	         CLI.COD_CLIE,
	         CLI.VAL_NOM1||' '||CLI.VAL_NOM2||' '||CLI.VAL_APE1||' '||CLI.VAL_APE2,
		     PROD.COD_SAP,
		     GEN_PRODU.VAL_I18N
	)
)
ORDER BY DETALLE,
	  	 PAIS,
		 COD_DESC,
		 COD_LOCAL,
	     NOMB_LOCAL,
		 COD_ESP,
		 COD_CLIE,
	     NOMB_CLI,
		 COD_PRODU,
		 DESC_PRODU

