( 
SELECT 
	  PERI.VAL_NOMB_PERI, 
	  I18PAIS.VAL_I18N PAIS, 
	  MARCA.DES_MARC, 
	  I18CANAL.VAL_I18N CANAL,
	  OFEDET.NUM_LINE_OFER AS NUM_LINEA_OFER, 
	  OFEDET.VAL_CODI_VENT, 
	  OFEDET.VAL_TEXT_BREV, 
	  OFEDET.IMP_PREC_CATA,  
	  CAT.DES_CATA, 
	  I18GEN.VAL_I18N GENERICO, 
	  I18SGEN.VAL_I18N SUPERGENERICO,
	  (MFC.OID_CABE || 0) AS ORDEN
FROM
	  CRA_PERIO PERI,
	  PRE_OFERT OFE,
	  PRE_OFERT_DETAL OFEDET,
	  PRE_MATRI_FACTU_CABEC MFC,
	  MAE_PRODU PROD,
	  PRE_CATAL CAT,
	  SEG_MARCA MARCA,
	  (
	  SELECT V.VAL_OID, V.VAL_I18N 
	  FROM V_GEN_I18N_SICC V 
	  WHERE V.ATTR_ENTI = 'MAE_GENER' 
	  AND V.IDIO_OID_IDIO = 1		 	 		 -- PARAMETRO --
	  ) I18GEN,
	  (
	  SELECT V.VAL_OID, V.VAL_I18N 
	  FROM V_GEN_I18N_SICC V 
	  WHERE V.ATTR_ENTI = 'MAE_SUPER_GENER' 
	  AND V.IDIO_OID_IDIO = 1		 	 		 -- PARAMETRO --
	  ) I18SGEN,
	  (
	  SELECT V.VAL_OID, V.VAL_I18N 
	  FROM V_GEN_I18N_SICC V 
	  WHERE V.ATTR_ENTI = 'SEG_PAIS' 
	  AND V.IDIO_OID_IDIO = 1		 	 		 -- PARAMETRO --
	  ) I18PAIS,
	  (
	  SELECT V.VAL_OID, V.VAL_I18N 
	  FROM V_GEN_I18N_SICC V 
	  WHERE V.ATTR_ENTI = 'SEG_CANAL' 
	  AND V.IDIO_OID_IDIO = 1		 	 		 -- PARAMETRO --
	  ) I18CANAL
WHERE
	  	  PERI.OID_PERI = MFC.PERD_OID_PERI
	  AND OFE.MFCA_OID_CABE = MFC.OID_CABE
	  AND OFE.OID_OFER = OFEDET.OFER_OID_OFER  	
	  AND OFEDET.PROD_OID_PROD = PROD.OID_PROD
	  AND OFEDET.OCAT_OID_CATAL = CAT.OID_CATA(+)
      AND I18PAIS.VAL_OID(+) = PERI.PAIS_OID_PAIS 
      AND I18CANAL.VAL_OID(+) = PERI.CANA_OID_CANA 
      AND I18GEN.VAL_OID(+) = PROD.GENE_OID_GENE 
      AND I18SGEN.VAL_OID(+) = PROD.SGEN_OID_SUPE_GENE
	  AND PERI.MARC_OID_MARC = MARCA.OID_MARC(+) 
	  AND PERI.PAIS_OID_PAIS = 1		 		   -- PARAMETRO --
	  AND PERI.MARC_OID_MARC = 1		 		   -- PARAMETRO --
	  AND PERI.CANA_OID_CANA = 1		 		   -- PARAMETRO --
	  AND PERI.OID_PERI = 57		 		   -- PARAMETRO --
	  AND OFEDET.NUM_LINE_OFER >= 1				   -- PARAMETRO --
	  AND OFEDET.NUM_LINE_OFER <= 96024			   -- PARAMETRO --
) 
UNION ALL
(
SELECT 
	  NULL, NULL, NULL, NULL, 
	  TXTOFE.NUM_ORDE AS NUM_ORDE, NULL, TXTOFE.VAL_TEXT, NULL,  
	  NULL,  
	  NULL, NULL,
	  (MFC.OID_CABE || 1) AS ORDEN
FROM
	  PRE_MATRI_FACTU_CABEC MFC,
	  PRE_TEXTO_OFERT TXTOFE
WHERE
  	  TXTOFE.MFCA_OID_CABE = MFC.OID_CABE
	  AND TXTOFE.MFCA_OID_CABE IN (
									SELECT 
										  DISTINCT MFC.OID_CABE
									FROM
										  CRA_PERIO PERI,
										  PRE_OFERT OFE,
										  PRE_OFERT_DETAL OFEDET,
										  PRE_MATRI_FACTU_CABEC MFC
									WHERE
										  	  PERI.OID_PERI = MFC.PERD_OID_PERI
										  AND OFE.MFCA_OID_CABE = MFC.OID_CABE
										  AND OFE.OID_OFER = OFEDET.OFER_OID_OFER  	
										  AND PERI.PAIS_OID_PAIS = 1		 		   -- PARAMETRO --
										  AND PERI.MARC_OID_MARC = 1		 		   -- PARAMETRO --
										  AND PERI.CANA_OID_CANA = 1		 		   -- PARAMETRO --
										  AND PERI.OID_PERI = 57		 		   -- PARAMETRO --
		  							)
)
ORDER BY
	NUM_LINEA_OFER,
	ORDEN,
	VAL_CODI_VENT
