SELECT 
	  RESULT.EXISTENCIA,
	  PERI.VAL_NOMB_PERI, 
	  I18PAIS.VAL_I18N AS PAIS, 
	  MARCA.DES_MARC, 
	  I18CANAL.VAL_I18N AS CANAL,
	  RESULT.VAL_CODI_VENT,
	  RESULT.COD_SAP, 
	  CVIDA.COD_CICL_VIDA, 
	  TOFER.COD_TIPO_OFER, 
	  I18PROD.VAL_I18N AS DESC_PROD,
	  RESULT.UNID_ESTI_MP, 
	  RESULT.UNID_ESTI_BPS,
	  RESULT.DIF_ESTIM,
	  RESULT.PREC_CATA_MP,
	  RESULT.PREC_CATA_BPS,
	  RESULT.DIF_PREC,  
	  CAT.DES_CATA, 
	  RESULT.NUM_PAGI_CATA, 
	  AC.COD_ACCE
FROM
	  CRA_PERIO PERI,
	  PRE_CATAL CAT,
	  SEG_MARCA MARCA,
	  PRE_CICLO_VIDA CVIDA,
	  PRE_TIPO_OFERT TOFER,
	  SEG_ACCES AC,
	  (
	  SELECT V.VAL_OID, V.VAL_I18N 
	  FROM V_GEN_I18N_SICC V 
	  WHERE V.ATTR_ENTI = 'MAE_PRODU'
	  AND V.IDIO_OID_IDIO = 1		 	 		 -- PARAMETRO --
	  ) I18PROD,
	  (
	  SELECT V.VAL_OID, V.VAL_I18N 
	  FROM V_GEN_I18N_SICC V 
	  WHERE V.ATTR_ENTI = 'SEG_PAIS' 
	  AND V.IDIO_OID_IDIO = 1		 	 		 -- PARAMETRO --
	  ) I18PAIS,
	  (
	  SELECT V.VAL_OID, V.VAL_I18N 
	  FROM V_GEN_I18N_SICC V 
	  WHERE V.ATTR_ENTI = 'SEG_CANAL' 
	  AND V.IDIO_OID_IDIO = 1		 	 		 -- PARAMETRO --
	  ) I18CANAL,
	  (
	  (
/******* SOLO EN MATRIZ ************************************************************************************************/
	   SELECT 
	   		  '001' AS EXISTENCIA,
			  OFEDET.VAL_CODI_VENT,
			  OFEDET.NUM_UNID_ESTI AS UNID_ESTI_MP,
			  NULL AS UNID_ESTI_BPS,
			  OFEDET.PROD_OID_PROD, 
			  PRO.COD_SAP, 
			  1 AS DIF_ESTIM, 
			  1 AS DIF_PREC,  
			  OFEDET.IMP_PREC_CATA AS PREC_CATA_MP,
			  NULL AS PREC_CATA_BPS, 
			  OFEDET.OCAT_OID_CATAL, 
			  OFEDET.NUM_PAGI_CATA, 
			  MFC.PERD_OID_PERI, 
			  OFEDET.CIVI_OID_CICLO_VIDA, 
			  OFEDET.TOFE_OID_TIPO_OFER, 
			  OFEDET.OID_DETA_OFER,
			  OFE.ACCE_OID_ACCE
	   FROM 
		   	  MAE_PRODU PRO, 
		   	  PRE_OFERT_DETAL OFEDET, 
			  PRE_OFERT OFE, 
			  PRE_MATRI_FACTU_CABEC MFC 
	   WHERE
			  OFEDET.PROD_OID_PROD = PRO.OID_PROD
			  AND OFE.MFCA_OID_CABE = MFC.OID_CABE
			  AND OFEDET.OFER_OID_OFER = OFE.OID_OFER 
			  AND OFEDET.PROD_OID_PROD NOT IN (SELECT DISTINCT EV.PROD_OID_PROD FROM PRE_ESTIM_VENTA EV)
			  AND MFC.PERD_OID_PERI = 61		 		   	   -- PARAMETRO -- 
	  )
UNION
	  (
/******* SOLO EN ESTIMADOS ************************************************************************************************/
	   SELECT 
	   		  '010' AS EXISTENCIA,
			  NULL AS VAL_CODI_VENT,
			  NULL AS UNID_ESTI_MP,
			  ESTVTA.NUM_UNID_ESTI AS UNID_ESTI_BPS,
			  ESTVTA.PROD_OID_PROD, 
			  PRO.COD_SAP, 
			  1 AS DIF_ESTIM, 
			  1 AS DIF_PREC,  
			  NULL AS PREC_CATA_MP,
			  ESTVTA.IMP_PREC_CATA AS PREC_CATA_BPS, 
			  ESTVTA.OCAT_OID_CATA, 
			  ESTVTA.NUM_PAGI_CATA, 
			  ESTVTA.PERD_OID_PERI, 
			  ESTVTA.CIVI_OID_CICL_VIDA,  
			  ESTVTA.TOFE_OID_TIPO_OFER,  
			  NULL AS OID_DETA_OFER,
			  NULL AS ACCE_OID_ACCE
	   FROM 
		   	  MAE_PRODU PRO, 
		   	  PRE_ESTIM_VENTA ESTVTA
	   WHERE
			  ESTVTA.PROD_OID_PROD = PRO.OID_PROD
			  AND ESTVTA.PROD_OID_PROD NOT IN (SELECT DISTINCT OD.PROD_OID_PROD FROM PRE_OFERT_DETAL OD)
			  AND ESTVTA.PERD_OID_PERI = 61		 		   	   -- PARAMETRO --

	  )
UNION
	  (
/******* EN ESTIMADOS Y EN MATRIZ ************************************************************************************************/
	   SELECT 
	   		  '111' AS EXISTENCIA,
			  OFEDET.VAL_CODI_VENT,
			  OFEDET.NUM_UNID_ESTI AS UNID_ESTI_MP,
			  ESTVTA.NUM_UNID_ESTI AS UNID_ESTI_BPS,
			  OFEDET.PROD_OID_PROD, 
			  PRO.COD_SAP, 
			  DECODE((NVL(OFEDET.NUM_UNID_ESTI,0) - NVL(ESTVTA.NUM_UNID_ESTI,0)),0,0,1) AS DIF_ESTIM, 
			  DECODE((NVL(OFEDET.IMP_PREC_CATA,0) - NVL(ESTVTA.IMP_PREC_CATA ,0)),0,0,1) AS DIF_PREC,  
			  OFEDET.IMP_PREC_CATA AS PREC_CATA_MP,
			  ESTVTA.IMP_PREC_CATA AS PREC_CATA_BPS, 
			  OFEDET.OCAT_OID_CATAL, 
			  OFEDET.NUM_PAGI_CATA, 
			  MFC.PERD_OID_PERI, 
			  OFEDET.CIVI_OID_CICLO_VIDA, 
			  OFEDET.TOFE_OID_TIPO_OFER, 
			  OFEDET.OID_DETA_OFER,
			  OFE.ACCE_OID_ACCE
	   FROM 
		   	  MAE_PRODU PRO,
		   	  PRE_ESTIM_VENTA ESTVTA,
		   	  PRE_OFERT_DETAL OFEDET, 
			  PRE_OFERT OFE, 
			  PRE_MATRI_FACTU_CABEC MFC 
	   WHERE
			  OFEDET.PROD_OID_PROD = PRO.OID_PROD
			  AND OFE.MFCA_OID_CABE = MFC.OID_CABE
			  AND OFEDET.OFER_OID_OFER = OFE.OID_OFER 
			  AND OFEDET.PROD_OID_PROD = ESTVTA.PROD_OID_PROD
			  AND MFC.PERD_OID_PERI = ESTVTA.PERD_OID_PERI 
			  AND OFEDET.CIVI_OID_CICLO_VIDA = ESTVTA.CIVI_OID_CICL_VIDA 
			  AND OFEDET.TOFE_OID_TIPO_OFER = ESTVTA.TOFE_OID_TIPO_OFER 
			  AND OFEDET.OCAT_OID_CATAL = ESTVTA.OCAT_OID_CATA 
			  AND OFEDET.NUM_PAGI_CATA = ESTVTA.NUM_PAGI_CATA 
	  )
	  ) RESULT
WHERE
	      PERI.OID_PERI = RESULT.PERD_OID_PERI
	  AND RESULT.OCAT_OID_CATAL = CAT.OID_CATA
	  AND RESULT.CIVI_OID_CICLO_VIDA = CVIDA.OID_CICL_VIDA
	  AND RESULT.TOFE_OID_TIPO_OFER = TOFER.OID_TIPO_OFER
	  AND RESULT.ACCE_OID_ACCE = AC.OID_ACCE(+) 
	  AND PERI.MARC_OID_MARC = MARCA.OID_MARC
	  --
      AND I18PAIS.VAL_OID(+) = PERI.PAIS_OID_PAIS 
      AND I18CANAL.VAL_OID(+) = PERI.CANA_OID_CANA 
      AND I18PROD.VAL_OID(+) = RESULT.PROD_OID_PROD
------------------------------------------------------------------------------------------------
	  AND PERI.PAIS_OID_PAIS = 1		 		   -- PARAMETRO --
	  AND PERI.MARC_OID_MARC = 1		 		   -- PARAMETRO --
	  AND PERI.CANA_OID_CANA = 1		 		   -- PARAMETRO --
	  AND PERI.OID_PERI = 61		 		   	   -- PARAMETRO --
--	  AND DIF_ESTIM = 1	  						   -- PARAMETRO (CHECK) --
--	  AND DIF_PREC = 1	  						   -- PARAMETRO (CHECK) --
ORDER BY
	  RESULT.EXISTENCIA DESC,
	  RESULT.VAL_CODI_VENT,
	  RESULT.COD_SAP

	  
--  IMPORTANTE --
-- Campo EXISTENCIA (Para agrupar y ordenar los registros en el reporte) 
-- - 111 Existen datos en las dos tablas.
-- - 010 Existen datos solo en estimados.
-- - 001 Existen datos solo en la matriz.