SELECT 
	ALTERN.PAIS, ALTERN.DES_MARC, ALTERN.CANAL,
	'000000000000' as "CODIGO [INCIDENCIA]", 
	ALTERN.VAL_CODI_VENT,
	ALTERN.COD_SAP,
	ALTERN.DESC_PROD,
	ALTERN.IMP_PREC_CATA,
	ALTERN.ESTRAT,
	ALTERN.VAL_FACT_REPE,
	ALTERN.VAL_NOMB_PERI,
	ORIG.VAL_CODI_VENT AS VAL_CODI_VENT_O,
	ORIG.COD_SAP AS COD_SAP_O,
	ORIG.DESC_PROD AS DESC_PROD_O,
	ORIG.IMP_PREC_CATA AS IMP_PREC_CATA_O,
	ORIG.ESTRAT AS ESTRAT_O,
	ORIG.VAL_FACT_REPE AS VAL_FACT_REPE_O,
	ORIG.VAL_NOMB_PERI AS VAL_NOMB_PERI_O
FROM
	(
	SELECT 
		  I18PAIS.VAL_I18N PAIS, MARCA.DES_MARC, I18CANAL.VAL_I18N CANAL,
		  OFEDET.VAL_CODI_VENT, PROD.COD_SAP, I18PROD.VAL_I18N AS DESC_PROD, 
		  OFEDET.IMP_PREC_CATA, ES.COD_ESTR ESTRAT, OFEDET.VAL_FACT_REPE, PERI.VAL_NOMB_PERI, 
		  MF.OID_MATR_FACT, PERI.OID_PERI, PROD.OID_PROD  
	FROM
		  CRA_PERIO PERI,
		  PRE_OFERT OFE,
		  PRE_OFERT_DETAL OFEDET,
		  PRE_MATRI_FACTU MF,
		  PRE_MATRI_FACTU_CABEC MFC,
		  MAE_PRODU PROD,
		  PRE_ESTRA ES,
		  SEG_MARCA MARCA,
		  (
		  SELECT V.VAL_OID, V.VAL_I18N 
		  FROM V_GEN_I18N_SICC V 
		  WHERE V.ATTR_ENTI = 'MAE_PRODU'
		  AND V.IDIO_OID_IDIO = 1		 	 		 -- PARAMETRO --
		  ) I18PROD,
		  (
		  SELECT V.VAL_OID, V.VAL_I18N 
		  FROM V_GEN_I18N_SICC V 
		  WHERE V.ATTR_ENTI = 'SEG_PAIS' 
		  AND V.IDIO_OID_IDIO = 1		 	 		 -- PARAMETRO --
		  ) I18PAIS,
		  (
		  SELECT V.VAL_OID, V.VAL_I18N 
		  FROM V_GEN_I18N_SICC V 
		  WHERE V.ATTR_ENTI = 'SEG_CANAL' 
		  AND V.IDIO_OID_IDIO = 1		 	 		 -- PARAMETRO --
		  ) I18CANAL
	WHERE
		      PERI.OID_PERI = MFC.PERD_OID_PERI
		  AND OFE.MFCA_OID_CABE = MFC.OID_CABE
		  AND MF.MFCA_OID_CABE = MFC.OID_CABE
		  AND OFE.OID_OFER = OFEDET.OFER_OID_OFER  	
		  AND OFEDET.OID_DETA_OFER = MF.OFDE_OID_DETA_OFER
		  AND OFEDET.PROD_OID_PROD = PROD.OID_PROD
		  AND OFE.COES_OID_ESTR = ES.OID_ESTR
	      AND I18PAIS.VAL_OID(+) = PERI.PAIS_OID_PAIS 
	      AND I18CANAL.VAL_OID(+) = PERI.CANA_OID_CANA 
	      AND I18PROD.VAL_OID(+) = OFEDET.PROD_OID_PROD 
		  AND PERI.MARC_OID_MARC = MARCA.OID_MARC(+)
		  AND PERI.OID_PERI = 57		 		   -- PARAMETRO --
	) ALTERN,
	(
	SELECT 
		  I18PAIS.VAL_I18N PAIS, MARCA.DES_MARC, I18CANAL.VAL_I18N CANAL,
		  OFEDET.VAL_CODI_VENT, PROD.COD_SAP, I18PROD.VAL_I18N AS DESC_PROD, 
		  OFEDET.IMP_PREC_CATA, ES.COD_ESTR ESTRAT, OFEDET.VAL_FACT_REPE, PERI.VAL_NOMB_PERI,
		  MF.OID_MATR_FACT, PERI.OID_PERI, PROD.OID_PROD  
	FROM
		  CRA_PERIO PERI,
		  PRE_OFERT OFE,
		  PRE_OFERT_DETAL OFEDET,
		  PRE_MATRI_FACTU MF,
		  PRE_MATRI_FACTU_CABEC MFC,
		  MAE_PRODU PROD,
		  PRE_ESTRA ES,
		  SEG_MARCA MARCA,
		  (
		  SELECT V.VAL_OID, V.VAL_I18N 
		  FROM V_GEN_I18N_SICC V 
		  WHERE V.ATTR_ENTI = 'MAE_PRODU'
		  AND V.IDIO_OID_IDIO = 1		 	 		 -- PARAMETRO --
		  ) I18PROD,
		  (
		  SELECT V.VAL_OID, V.VAL_I18N 
		  FROM V_GEN_I18N_SICC V 
		  WHERE V.ATTR_ENTI = 'SEG_PAIS' 
		  AND V.IDIO_OID_IDIO = 1		 	 		 -- PARAMETRO --
		  ) I18PAIS,
		  (
		  SELECT V.VAL_OID, V.VAL_I18N 
		  FROM V_GEN_I18N_SICC V 
		  WHERE V.ATTR_ENTI = 'SEG_CANAL' 
		  AND V.IDIO_OID_IDIO = 1		 	 		 -- PARAMETRO --
		  ) I18CANAL
	WHERE
		      PERI.OID_PERI = MFC.PERD_OID_PERI
		  AND OFE.MFCA_OID_CABE = MFC.OID_CABE
		  AND MF.MFCA_OID_CABE = MFC.OID_CABE
		  AND OFE.OID_OFER = OFEDET.OFER_OID_OFER  	
		  AND OFEDET.OID_DETA_OFER = MF.OFDE_OID_DETA_OFER
		  AND OFEDET.PROD_OID_PROD = PROD.OID_PROD
		  AND OFE.COES_OID_ESTR = ES.OID_ESTR
	      AND I18PAIS.VAL_OID(+) = PERI.PAIS_OID_PAIS 
	      AND I18CANAL.VAL_OID(+) = PERI.CANA_OID_CANA 
	      AND I18PROD.VAL_OID(+) = OFEDET.PROD_OID_PROD 
		  AND PERI.MARC_OID_MARC = MARCA.OID_MARC(+)
		  AND PERI.PAIS_OID_PAIS = 1		 		   -- PARAMETRO --
		  AND PERI.MARC_OID_MARC = 1		 		   -- PARAMETRO --
		  AND PERI.CANA_OID_CANA = 1		 		   -- PARAMETRO --
	) ORIG,
	PRE_MATRI_REEMP MREEMP
WHERE
	 	ORIG.PAIS = ALTERN.PAIS
	AND ORIG.DES_MARC = ALTERN.DES_MARC
	AND ORIG.CANAL = ALTERN.CANAL
	AND MREEMP.MAFA_OID_COD_PPAL = ORIG.OID_MATR_FACT  
	AND MREEMP.MAFA_OID_COD_REEM = ALTERN.OID_MATR_FACT  
	AND ALTERN.VAL_CODI_VENT >= 1	   			--//  Estos son, en teoria los codigos por los que hay que filtrar pero 
	AND ALTERN.VAL_CODI_VENT <= 9999999		--// Matias no los tiene y levanto una incidencia 
ORDER BY
	ALTERN.PAIS, ALTERN.DES_MARC, ALTERN.CANAL,
	VAL_CODI_VENT	