/*
 * RegistroOnline1.java
 *
 * Created on 9 de diciembre de 2004, 12:49 PM
 */

package es.indra.sicc.ped.applet;
import es.indra.mare.common.dto.MareDTO;
import es.indra.sicc.comunapplet.UtilApplet;
import es.indra.sicc.comunapplet.exceptions.AppletException;
//import es.indra.sicc.dtos.ped.applet.DTOCabeceraSolicitud;
//import es.indra.sicc.dtos.ped.applet.DTOInfoProducto;
//import es.indra.sicc.ped.applet.util.ConstantesApplet;
import es.indra.sicc.comunapplet.ComboBoxApplet;
import es.indra.sicc.ped.applet.componentes.TablaDetalle;
//import es.indra.sicc.util.ped.applet.Base64;


import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;

//import javax.swing.AbstractAction;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JApplet;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;
import javax.swing.border.EtchedBorder;
import javax.swing.border.TitledBorder;

/**
 *
 * @author  jpbosnja
 */
abstract class RegistroOnline extends JApplet { //javax.swing.JDialog
    protected Long oidPais;
    protected String fechaSistema;
    protected String ormi;
    protected String user;
    protected String clave;
    protected RegistroCache cache;
    protected Long oidCliente;
    protected Long oidTipoCliente;
    protected Long oidTipoSolicitud;
    protected Long oidAcceso;
    protected Long oidSubacceso;
    protected Long oidCanal;
    
    protected Long oidIdioma = null;
    protected String ip = null;
    protected String valueIndCodigVenta = null;
    protected String url = null;
    protected String urlLogin = null;
        
    protected int bg_red = 245;      // initialize background colors
    protected int bg_green = 12;
    protected int bg_blue = 123;
    
    protected Cabecera pestaniaCabeceraImplementacion = null;
    protected Cliente marcoCliente = null;
    protected DatosDetalle marcoDatosDetalle = null;
    protected int longCodClie = 0;
    protected String valCodVentaAnterior = "";
    protected String valCodProductoAnterior = "";
    protected String valUnidDemandadasAnterior = "";
    
    
    /** Initializes the applet RegistroOnline1 */
    public void init() {
        /*try {
          this.initComponents();
          this.registroOnline_onload(); 
        } catch (AppletException e) {
          e.printStackTrace();
        }*/
    }
    
    protected abstract void cargarCombos() throws AppletException;
    protected abstract void cargarDatosIniciales() throws AppletException;
    protected abstract Boolean comprobarDatosObligatorios() throws AppletException;
    protected abstract void ejecutarJava() throws AppletException;
    public abstract MareDTO ejecutarNegocio(String idBusiness, String nombreDTO, MareDTO dto ) throws AppletException;
    public abstract Object ejecutarWeb(String nombreFuncionJS, String url) throws AppletException;
    protected abstract void mostrarDatosAsociadosTipoSolicitud() throws AppletException;
    protected abstract void mostrarDetalle() throws AppletException;
    protected abstract void mostrarFechaFacturacion() throws AppletException;
    protected abstract void mostrarPeriodos(Long oidTipoSolicitud) throws AppletException;
    protected abstract void obtenerValoresDefecto() throws AppletException;
    protected abstract void registroOnline_onload() throws AppletException;
    protected abstract void seleccionarPeriodo() throws AppletException;
    protected abstract void seleccionarTipoSolicitud() throws AppletException;
    protected abstract void cbtipoSolicitud_onchange() throws AppletException;
    public abstract void reiniciar();
    

    public void start(){
        //System.out.println("Entre al start");
        try  {
           cache = RegistroCache.getInstance();
           //System.out.println("Instancie Cache");
           //cargarDatosIniciales();
           //System.out.println("Fin carga de datos");
           this.initComponents();
           this.registroOnline_onload();
        } catch (Exception ex)  {
          ex.printStackTrace();
        } 
    }
    


    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() throws AppletException
    {//GEN-BEGIN:initComponents

        lbTipoSolicitudObligatorio = new javax.swing.JLabel();
        lbPeriodoObligatorio = new javax.swing.JLabel();
        lbCodClienteObligatorio = new javax.swing.JLabel();
        lbTipoDespachoObligatorio = new javax.swing.JLabel();
        lbTipoDocumentoObligatorio = new javax.swing.JLabel();
        lbReceptorFacturaObligatorio = new javax.swing.JLabel();
        lbPagadorFacturaObligatorio = new javax.swing.JLabel();
        lbDestinoObligatorio = new javax.swing.JLabel();
        lbCodVentaObligatorio = new javax.swing.JLabel();
        lbCodProductoObligatorio = new javax.swing.JLabel();
        lbUnidadesDemandadasObligatorio = new javax.swing.JLabel();

        //pnGeneral = new javax.swing.JPanel();
        jTabbedPane = new javax.swing.JTabbedPane();
        pestaniaCabecera = new javax.swing.JPanel();
        pnBtnAltaCliente = new javax.swing.JPanel();
        pnAceptarCancelar = new javax.swing.JPanel();
        btnAltaCliente = new javax.swing.JButton();
        initTipoSolicitud();
        initDatosSolicitud();
        initCliente();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pestaniaDetalle = new javax.swing.JPanel();
        initDatosCabecera();
        initDatosDetalle();
        initTablaDetalle();
        //jMenuBar1 = new javax.swing.JMenuBar();
        //jMenu = new javax.swing.JMenu();
        //jMenuItem1 = new javax.swing.JMenuItem();
      
      //Backgrounds
        Color Background = new Color(242,242,241);
        Color ButtonBack = new Color(5, 123, 162);
        Color Blanco = new Color (255, 255, 255);
        //pnGeneral.setBackground(Background);
        getContentPane().setBackground(Background);
        pestaniaCabecera.setBackground(Background);
        pestaniaDetalle.setBackground(Background);
        TipoSolicitud.setBackground(Background);
        pnDatosSolicitud.setBackground(Background);
        Cliente.setBackground(Background);
        DatosCabecera.setBackground(Background);
        pnDatosDetalle.setBackground(Background);
        panelTablaDetalle.setBackground(Background);
        pnBtnAltaCliente.setBackground(Background);
        //groupIndCodigVenta.setBackground(Background);
        rbIndCodigVentaCV.setBackground(Background);
        rbIndCodigVentaProducto.setBackground(Background);
        chkDemandaNoAtendida.setBackground(Blanco);
        /*
        cbAccesoFisico.setBackground(Blanco);
        cbDestino.setBackground(Blanco);
        cbFormaPago.setBackground(Blanco);
        cbPeriodo.setBackground(Blanco);
        cbTipoDespacho.setBackground(Blanco);
        cbTipoDocumento.setBackground(Blanco);
        cbTipoSolicitud.setBackground(Blanco);
        */
        
        //btnAltaCliente.setBackground(Background);
        btnBuscarCliente.setBackground(ButtonBack);
        btnBuscarConRefencia.setBackground(ButtonBack);
        btnBuscarReceptorFac.setBackground(ButtonBack);
        btnBuscarPagador.setBackground(ButtonBack);
        btnAniadir.setBackground(ButtonBack);
        btnEliminar.setBackground(ButtonBack);
        btnGuardar.setBackground(ButtonBack);
        btnBuscarProd.setBackground(ButtonBack);
        btnBuscarSolAnter.setBackground(ButtonBack);
        btnPresentarFlete.setBackground(ButtonBack);
        this.btnSimularCuadre.setBackground(ButtonBack);
        btnAceptar.setBackground(ButtonBack);
        btnCancelar.setBackground(ButtonBack);
        
      //Layouts
        pestaniaCabecera.setLayout(null);
        pnDatosSolicitud.setLayout(null);
        TipoSolicitud.setLayout(null);
        Cliente.setLayout(null);
        pestaniaDetalle.setLayout(null);
        DatosCabecera.setLayout(null);
        pnDatosDetalle.setLayout(null);
        panelTablaDetalle.setLayout(null);
        pnBtnDatosDetalle.setLayout(null);
        pnBtnTablaDetalle.setLayout(null);
        pnBtnAltaCliente.setLayout(null);
        pnAceptarCancelar.setLayout(null);
        //pnGeneral.setLayout(null);
        
      //Borders
        //jMenu.setBorder( new EtchedBorder());
        pnAceptarCancelar.setBorder(new EtchedBorder());
        pnBtnAltaCliente.setBorder(new EtchedBorder());
        btnAltaCliente.setBorder(BorderFactory.createLineBorder(ButtonBack,2));
        //Tipo Solicitud
          TipoSolicitud.setBorder(new javax.swing.border.TitledBorder(new EtchedBorder(),"Tipo Solicitud"));
        //cbTipoSolicitud.setBorder(new EtchedBorder());
        //Datos Solicitud
          pnDatosSolicitud.setBorder(new TitledBorder(new EtchedBorder(),"DatosSolicitud"));
        //Clinete
          Cliente.setBorder(new javax.swing.border.TitledBorder(new EtchedBorder(),"Cliente"));
        //Datos Cabecera
          DatosCabecera.setBorder(new javax.swing.border.TitledBorder(new EtchedBorder(),"Datos Cabecera"));
        //Datos Detalle
          pnDatosDetalle.setBorder(new javax.swing.border.TitledBorder(new EtchedBorder(),"Datos Detalle"));
          pnBtnDatosDetalle.setBorder(new EtchedBorder());
        //Tabla Detalle
          panelTablaDetalle.setBorder(new javax.swing.border.TitledBorder( new EtchedBorder(),"Tabla Detalle"));
          pnBtnTablaDetalle.setBorder(new EtchedBorder());

      //atributos
        btnAltaCliente.setText("Nuevo cliente");
        //Tipo Solicitud
        lbTipoSolicitudObligatorio.setText("(*)");
        lbTipoSolicitudObligatorio.setFont(new Font ( "Arial", Font.BOLD, 11 ) );
        lbTipoSolicitudObligatorio.setForeground(Color.RED);
        lbPeriodoObligatorio.setText("(*)");
        lbPeriodoObligatorio.setFont(new Font ( "Arial", Font.BOLD, 11 ) );
        lbPeriodoObligatorio.setForeground(Color.RED);
        lbCodClienteObligatorio.setText("(*)");
        lbCodClienteObligatorio.setFont(new Font ( "Arial", Font.BOLD, 11 ) );
        lbCodClienteObligatorio.setForeground(Color.RED);
        lbTipoDespachoObligatorio.setText("(*)");
        lbTipoDespachoObligatorio.setFont(new Font ( "Arial", Font.BOLD, 11 ) );
        lbTipoDespachoObligatorio.setForeground(Color.RED);
        lbTipoDocumentoObligatorio.setText("(*)");
        lbTipoDocumentoObligatorio.setFont(new Font ( "Arial", Font.BOLD, 11 ) );
        lbTipoDocumentoObligatorio.setForeground(Color.RED);
        lbReceptorFacturaObligatorio.setText("(*)");
        lbReceptorFacturaObligatorio.setFont(new Font ( "Arial", Font.BOLD, 11 ) );
        lbReceptorFacturaObligatorio.setForeground(Color.RED);
        lbPagadorFacturaObligatorio.setText("(*)");
        lbPagadorFacturaObligatorio.setFont(new Font ( "Arial", Font.BOLD, 11 ) );
        lbPagadorFacturaObligatorio.setForeground(Color.RED);
        lbDestinoObligatorio.setText("(*)");
        lbDestinoObligatorio.setFont(new Font ( "Arial", Font.BOLD, 11 ) );
        lbDestinoObligatorio.setForeground(Color.RED);
        lbCodVentaObligatorio.setText("(*)");
        lbCodVentaObligatorio.setFont(new Font ( "Arial", Font.BOLD, 11 ) );
        lbCodVentaObligatorio.setForeground(Color.RED);
        lbCodProductoObligatorio.setText("(*)");
        lbCodProductoObligatorio.setFont(new Font ( "Arial", Font.BOLD, 11 ) );
        lbCodProductoObligatorio.setForeground(Color.RED);
        lbUnidadesDemandadasObligatorio.setText("(*)");
        lbUnidadesDemandadasObligatorio.setFont(new Font ( "Arial", Font.BOLD, 11 ) );
        lbUnidadesDemandadasObligatorio.setForeground(Color.RED);
        
        
        lblTipoSolicitud.setText("Tipo Solicitud:");
        lblTipoSolicitud.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        cbTipoSolicitud.setEditable( true );
        lbMarca.setText("Marca:");
        lbMarca.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        lbMarcaTipoSolicitud.setText("");
        lbMarcaTipoSolicitud.setFont( new Font ( "Arial", Font.PLAIN, 11 ) );
        lbCanal.setText("Canal:");
        lbCanal.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        lbCanalTipoSolicitud.setText("");
        lbCanalTipoSolicitud.setFont( new Font ( "Arial", Font.PLAIN, 11 ) );
        lbAcceso.setText("Acceso:");
        lbAcceso.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        lbAccesoTipoSolicitud.setText("");
        lbAccesoTipoSolicitud.setFont( new Font ( "Arial", Font.PLAIN, 11 ) );
        lbSubacceso.setText("Subacceso:");
        lbSubacceso.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        lbSubaccesoTipoSolicitud.setText("");
        lbSubaccesoTipoSolicitud.setFont( new Font ( "Arial", Font.PLAIN, 11 ) );
        lbMonedaDoc.setText("Moneda:");
        lbMonedaDoc.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        lbMonedaDocTipoSolicitud.setText("");
        lbMonedaDocTipoSolicitud.setFont( new Font ( "Arial", Font.PLAIN, 11 ) );
        //Datos Solicitud
        lbPeriodo.setText("Periodo");
        lbPeriodo.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        cbPeriodo.setEditable( true );
        lbAccesoFisico.setText("Acceso f\u00edsico");
        lbAccesoFisico.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        cbAccesoFisico.setEditable( true );
        lbTipoDespacho.setText("Tipo despacho");
        lbTipoDespacho.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        cbTipoDespacho.setEditable( true );
        lbFechaProgramadaFac.setText("Fecha prog. fac.");
        lbFechaProgramadaFac.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        lbNumeroClientes.setText("Número Clientes");
        lbNumeroClientes.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        lbIndCodigoVentaProducto.setText("Ind. Cod. Venta");
        lbIndCodigoVentaProducto.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        rbIndCodigVentaCV.setText("CV");
        rbIndCodigVentaCV.setVisible(true);
        rbIndCodigVentaProducto.setText("Producto");
        rbIndCodigVentaProducto.setVisible(true);
        lbFormaPago.setText("Forma pago");
        lbFormaPago.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        cbFormaPago.setEditable( true );
        lbObservaciones.setText("Observaciones");
        lbObservaciones.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        jScrollPaneObservaciones.setViewportView(atxObservaciones);
        //Clinete
        lbTituloNombre.setHorizontalAlignment(SwingConstants.LEFT);
        lbTituloNombre.setText("Nombre:");
        lbTituloNombre.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        lbTituloCodCliente.setHorizontalAlignment(SwingConstants.LEFT);
        lbTituloCodCliente.setText("Cod. cliente:");
        lbTituloCodCliente.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.setForeground( Blanco);
        lbNombre.setText("");
        lbNombre.setFont( new Font ( "Arial", Font.PLAIN, 11 ) );
        lbTituloApellidos.setText("Apellidos:");
        lbTituloApellidos.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        lbApellidos.setText("");
        lbApellidos.setFont( new Font ( "Arial", Font.PLAIN, 11 ) );
        lbTituloLineaCredito.setText("L\u00ednea credito:");
        lbTituloLineaCredito.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        lbLineaCredito.setText("");
        lbLineaCredito.setFont( new Font ( "Arial", Font.PLAIN, 11 ) );
        lbTituloLineaDisp.setText("L\u00ednea disp.:");
        lbTituloLineaDisp.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        lbLineaDisp.setText("");
        lbLineaDisp.setFont( new Font ( "Arial", Font.PLAIN, 11 ) );
        lbTituloDeudaVencida.setText("Deuda vencida:");
        lbTituloDeudaVencida.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        lbDeudaVencida.setText("");
        lbDeudaVencida.setFont( new Font ( "Arial", Font.PLAIN, 11 ) );
        lbTituloTipoDocumento.setText("Tipo doc.:");
        lbTituloTipoDocumento.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        cbTipoDocumento.setEditable( true );
        lbTituloDocumentoLegal.setText("Doc. legal:");
        lbTituloDocumentoLegal.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        lbDocumentoLegal.setText("");
        lbDocumentoLegal.setFont( new Font ( "Arial", Font.PLAIN, 11 ) );
        lbTituloDestino.setText("Destino:");
        lbTituloDestino.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        cbDestino.setEditable( true );
        lbTituloConsultoraRefencia.setText("Consultora ref.:");
        lbTituloConsultoraRefencia.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        btnBuscarConRefencia.setText("Buscar");
        btnBuscarConRefencia.setForeground( Blanco);
        lbTituloPagadorFactura.setText("Pagador factura:");
        lbTituloPagadorFactura.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        lbTituloReceptorFactura.setText("Receptor factura:");
        lbTituloReceptorFactura.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        btnBuscarReceptorFac.setText("Buscar");
        btnBuscarReceptorFac.setForeground( Blanco);
        btnBuscarPagador.setText("Buscar");
        btnBuscarPagador.setForeground( Blanco);
        //Datos Cabecera
        lbTituloLineaDispDetalle.setText("L\u00ednea disp.");
        lbTituloLineaDispDetalle.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        lbLineaDispDetalle.setText("");
        lbLineaDispDetalle.setFont( new Font ( "Arial", Font.PLAIN, 11 ) );
        lbTituloCodClienteDetalle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbTituloCodClienteDetalle.setText("Cod. cliente");
        lbTituloCodClienteDetalle.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        lbTituloCodClienteDetalle.setAlignmentY(0.0F);
        lbTituloNombreDetalle.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbTituloNombreDetalle.setText("Nombre");
        lbTituloNombreDetalle.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        lbNombreDetalle.setText("");
        lbNombreDetalle.setFont( new Font ( "Arial", Font.PLAIN, 11 ) );
        lbTituloApellidosDetalle.setText("Apellidos");
        lbTituloApellidosDetalle.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        lbApellidosDetalle.setText("");
        lbApellidosDetalle.setFont( new Font ( "Arial", Font.PLAIN, 11 ) );
        lbCodClienteDetalle.setText("");
        lbCodClienteDetalle.setFont( new Font ( "Arial", Font.PLAIN, 11 ) );
        lbTituloFormaPagoDetalle.setText("Forma pago");
        lbTituloFormaPagoDetalle.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        lbFormaPagoDetalle.setText("");
        lbFormaPagoDetalle.setFont( new Font ( "Arial", Font.PLAIN, 11 ) );
        //Datos Detalle
        lbCodVenta.setText("Cod. Venta");
        lbCodVenta.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        lbStockDisponibleCantidad.setText("");
        lbStockDisponibleCantidad.setFont( new Font ( "Arial", Font.PLAIN, 11 ) );
        lbCodProducto.setText("Cod. Producto");
        lbCodProducto.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        jLabel4.setText("Limite Venta");
        jLabel4.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        lbDesc.setText("Descripcion");
        lbDesc.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        lbDescripcion.setText("");
        lbDescripcion.setFont( new Font ( "Arial", Font.PLAIN, 11 ) );
        lbUnidDemandadas.setText("Unid. Demandadas");
        lbUnidDemandadas.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        lbLimiteVentaCantidad.setText("");
        lbLimiteVentaCantidad.setFont( new Font ( "Arial", Font.PLAIN, 11 ) );
        lbStockDisponible.setText("Stock Disponible");       
        lbStockDisponible.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        lbControlLiq.setText("Control Liquidacion");
        lbControlLiq.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        jLabel11.setText("Reserva");
        jLabel11.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        lbDemandaNoAtendida.setText("Demanda No Atendida");
        lbDemandaNoAtendida.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        lbObservaciones1.setText("Observaciones");
        lbObservaciones1.setFont( new Font ( "Arial", Font.BOLD, 11 ) );
        lbControlLiqCantidad.setText("");
        lbControlLiqCantidad.setFont( new Font ( "Arial", Font.PLAIN, 11 ) );
        lbReservaCantidad.setText("");
        lbReservaCantidad.setFont( new Font ( "Arial", Font.PLAIN, 11 ) );
        btnAniadir.setText("A\u00f1adir");
        btnEliminar.setText("Eliminar");
        btnGuardar.setText("Guardar");
        btnBuscarProd.setText("Buscar prod.");
        btnBuscarSolAnter.setText("Buscar sol. anter.");
        btnPresentarFlete.setText("Presentar flete");
        btnSimularCuadre.setText("Simular cuadre");
        jScrollPaneObservaciones1.setViewportView(atxObservacionesDatosDetalle);

        //Tabla Detalle      
        //tablaDetalle.getColumn(1).setTitle("y...");
        //panelTablaDetalle.setLayout(null);
        //spTablaDetalle.setLayout(null);
        //tablaDetalle.setLayout(null);
        spTablaDetalle.setHorizontalScrollBarPolicy( JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS );
        spTablaDetalle.setVerticalScrollBarPolicy( JScrollPane.VERTICAL_SCROLLBAR_ALWAYS );

        //Generales
        btnAceptar.setText("Aceptar");
        btnAceptar.setForeground( Blanco);
        btnCancelar.setText("Cancelar");
        btnCancelar.setForeground( Blanco);
        btnAniadir.setForeground( Blanco);
        btnEliminar.setForeground( Blanco);
        btnGuardar.setForeground( Blanco);
        btnBuscarProd.setForeground( Blanco);
        btnBuscarSolAnter.setForeground( Blanco);
        btnPresentarFlete.setForeground( Blanco);
        btnSimularCuadre.setForeground( Blanco);

      //Adds
        pnBtnAltaCliente.add(btnAltaCliente);
        //Tipo Solicitud
        TipoSolicitud.add(lblTipoSolicitud);
        TipoSolicitud.add(cbTipoSolicitud);
        TipoSolicitud.add(lbMarca);
        TipoSolicitud.add(lbMarcaTipoSolicitud);
        TipoSolicitud.add(lbCanal);
        TipoSolicitud.add(lbCanalTipoSolicitud);
        TipoSolicitud.add(lbAcceso);
        TipoSolicitud.add(lbAccesoTipoSolicitud);
        TipoSolicitud.add(lbSubacceso);
        TipoSolicitud.add(lbSubaccesoTipoSolicitud);
        TipoSolicitud.add(lbMonedaDoc);
        TipoSolicitud.add(lbMonedaDocTipoSolicitud);
        TipoSolicitud.add(lbTipoSolicitudObligatorio);
        //Datos Solicitud
        pnDatosSolicitud.add(lbPeriodo);
        pnDatosSolicitud.add(cbPeriodo);
        pnDatosSolicitud.add(lbAccesoFisico);
        pnDatosSolicitud.add(cbAccesoFisico);
        pnDatosSolicitud.add(lbTipoDespacho);
        pnDatosSolicitud.add(cbTipoDespacho);
        pnDatosSolicitud.add(lbFechaProgramadaFac);
        pnDatosSolicitud.add(txtFechaProgramadaFac);
        pnDatosSolicitud.add(lbNumeroClientes);
        pnDatosSolicitud.add(txtNumeroClientes);
        pnDatosSolicitud.add(lbIndCodigoVentaProducto);
        //DatosSolicitud.add(chkIndCodigoVentaProducto);
        groupIndCodigVenta.add(rbIndCodigVentaCV);
        groupIndCodigVenta.add(rbIndCodigVentaProducto);
        pnDatosSolicitud.add(rbIndCodigVentaCV);
        pnDatosSolicitud.add(rbIndCodigVentaProducto);
        pnDatosSolicitud.add(lbFormaPago);
        pnDatosSolicitud.add(lbObservaciones);
        pnDatosSolicitud.add(jScrollPaneObservaciones);
        pnDatosSolicitud.add(lbPeriodoObligatorio);
        pnDatosSolicitud.add(lbTipoDespachoObligatorio);
        //Clinete
        Cliente.add(lbTituloNombre);
        Cliente.add(lbTituloCodCliente);
        Cliente.add(txtCodCliente);
        Cliente.add(btnBuscarCliente);
        Cliente.add(lbNombre);
        Cliente.add(lbTituloApellidos);
        Cliente.add(lbApellidos);
        Cliente.add(lbTituloLineaCredito);
        Cliente.add(lbLineaCredito);
        Cliente.add(lbTituloLineaDisp);
        Cliente.add(lbLineaDisp);
        Cliente.add(lbTituloDeudaVencida);
        Cliente.add(lbDeudaVencida);
        Cliente.add(lbTituloTipoDocumento);
        Cliente.add(cbTipoDocumento);
        Cliente.add(lbTituloDocumentoLegal);
        Cliente.add(lbDocumentoLegal);
        Cliente.add(lbTituloDestino);
        Cliente.add(cbDestino);
        Cliente.add(lbTituloConsultoraRefencia);
        Cliente.add(txtConsultoraRefencia);
        Cliente.add(btnBuscarConRefencia);
        Cliente.add(lbTituloReceptorFactura);
        Cliente.add(txtReceptorFactura);
        Cliente.add(btnBuscarReceptorFac);
        Cliente.add(lbTituloPagadorFactura);
        Cliente.add(txtPagadorFactura);
        Cliente.add(btnBuscarPagador);
        Cliente.add(lbCodClienteObligatorio);
        Cliente.add(lbTipoDocumentoObligatorio);
        Cliente.add(lbReceptorFacturaObligatorio);
        Cliente.add(lbPagadorFacturaObligatorio);
        Cliente.add(lbDestinoObligatorio);
        //Datos Cabecera
        DatosCabecera.add(lbTituloLineaDispDetalle);
        DatosCabecera.add(lbLineaDispDetalle);
        DatosCabecera.add(lbTituloCodClienteDetalle);
        DatosCabecera.add(lbTituloNombreDetalle);
        DatosCabecera.add(lbNombreDetalle);
        DatosCabecera.add(lbTituloApellidosDetalle);
        DatosCabecera.add(lbApellidosDetalle);
        DatosCabecera.add(lbCodClienteDetalle);
        DatosCabecera.add(lbTituloFormaPagoDetalle);
        DatosCabecera.add(lbFormaPagoDetalle);        
        //Datos Detalle
        pnDatosDetalle.add(lbCodVenta);
        pnDatosDetalle.add(lbStockDisponible);
        pnDatosDetalle.add(lbCodProducto);
        pnDatosDetalle.add(jLabel4);
        pnDatosDetalle.add(lbDesc);
        pnDatosDetalle.add(lbDescripcion);
        pnDatosDetalle.add(lbUnidDemandadas);
        pnDatosDetalle.add(lbLimiteVentaCantidad);
        pnDatosDetalle.add(lbStockDisponibleCantidad);        
        pnDatosDetalle.add(txtCodVenta);
        pnDatosDetalle.add(txtCodProducto);
        pnDatosDetalle.add(txtUnidDemandadas);
        pnDatosDetalle.add(lbControlLiq);
        pnDatosDetalle.add(jLabel11);
        pnDatosDetalle.add(lbDemandaNoAtendida);
        pnDatosDetalle.add(lbObservaciones1);
        pnDatosDetalle.add(lbControlLiqCantidad);
        pnDatosDetalle.add(lbReservaCantidad);
        pnDatosDetalle.add(chkDemandaNoAtendida);
        pnDatosDetalle.add(lbCodProductoObligatorio);
        pnDatosDetalle.add(lbCodVentaObligatorio);
        pnDatosDetalle.add(lbUnidadesDemandadasObligatorio);
        pnBtnDatosDetalle.add(btnAniadir);
        pnBtnDatosDetalle.add(btnGuardar);
        pnBtnDatosDetalle.add(btnBuscarProd);
        pnBtnDatosDetalle.add(btnBuscarSolAnter);
        pnBtnDatosDetalle.add(btnPresentarFlete);
        pnBtnDatosDetalle.add(btnSimularCuadre);        
        
        
        pnDatosDetalle.add(jScrollPaneObservaciones1);
        //Tabla Detalle      
        spTablaDetalle.getViewport().add( tablaDetalle );
        panelTablaDetalle.add( spTablaDetalle );
        pnBtnTablaDetalle.add(btnEliminar);        
        //panelTablaDetalle.add(tablaDetalle);

        //Generales
        pestaniaCabecera.add(pnDatosSolicitud);
        pestaniaCabecera.add(TipoSolicitud);
        pestaniaCabecera.add(Cliente);
        pnAceptarCancelar.add(btnAceptar);
        pnAceptarCancelar.add(btnCancelar);
        pestaniaCabecera.add(pnAceptarCancelar);
        jTabbedPane.addTab("Cabecera", pestaniaCabecera);
        jTabbedPane.addTab("Detalle", pestaniaDetalle);
        pestaniaDetalle.add(DatosCabecera);      
        pestaniaDetalle.add(pnDatosDetalle);
        pestaniaDetalle.add(pnBtnDatosDetalle);
        pestaniaDetalle.add(pnBtnTablaDetalle);
        pestaniaDetalle.add(panelTablaDetalle);
        jTabbedPane.setBackgroundAt(0,Background);
        jTabbedPane.setBackgroundAt(1,Background);
        pestaniaCabecera.add(pnBtnAltaCliente);
        //pnGeneral.add(pnBtnAltaCliente);
        //pnGeneral.add(jTabbedPane);
        getContentPane().add(jTabbedPane);//, java.awt.BorderLayout.CENTER

      //Bounds
        //pestaniaCabecera.setBounds(0,20,800,200);
        //pestaniaDetalle.setBounds(0,20,800,200);
        pnBtnAltaCliente.setBounds(0,0,796,20);
        btnAltaCliente.setBounds(710,0,85,20);
        pnDatosSolicitud.setBounds(0, 150, 800, 220);
        //Tipo Solicitud
        lblTipoSolicitud.setBounds(30, 20, 100, 20);
        cbTipoSolicitud.setBounds(30, 40, 400, 20);
        lbMarca.setBounds(30, 70, 100, 20);
        lbMarcaTipoSolicitud.setBounds(30, 85, 140, 20);
        lbCanal.setBounds(180, 70, 140, 20);
        lbCanalTipoSolicitud.setBounds(180, 85, 140, 20);
        lbAcceso.setBounds(330, 70, 140, 20);
        lbAccesoTipoSolicitud.setBounds(330, 85, 140, 20);
        lbSubacceso.setBounds(470, 70, 140, 20);
        lbSubaccesoTipoSolicitud.setBounds(470, 85, 140, 20);
        lbMonedaDoc.setBounds(650, 70, 140, 20);
        lbMonedaDocTipoSolicitud.setBounds(650, 85, 140, 20);
        TipoSolicitud.setBounds(0, 20, 800, 130);

        //Datos Solicitud
        lbPeriodo.setBounds(30, 20, 100, 20);
        cbPeriodo.setBounds(30, 40, 140, 20);
        lbAccesoFisico.setBounds(200, 20, 140, 20);
        cbAccesoFisico.setBounds(200, 40, 140, 20);
        lbTipoDespacho.setBounds(30, 70, 140, 20);
        cbTipoDespacho.setBounds(30, 90, 140, 20);
        lbFechaProgramadaFac.setBounds(200, 70, 140, 20);
        txtFechaProgramadaFac.setBounds(200, 90, 140, 20);
        lbNumeroClientes.setBounds(490, 70, 140, 20);
        txtNumeroClientes.setBounds(490, 90, 140, 20);
        lbIndCodigoVentaProducto.setBounds(350, 70, 140, 20);
        //chkIndCodigoVentaProducto.setBounds(420, 60, 21, 21);
        rbIndCodigVentaCV.setBounds(350, 90, 50, 20);
        rbIndCodigVentaProducto.setBounds(400, 90, 90, 20);
        
        lbFormaPago.setBounds(350, 20, 140, 20);
        pnDatosSolicitud.add(cbFormaPago);
        cbFormaPago.setBounds(350, 40, 280, 20);
        lbObservaciones.setBounds(30, 120, 100, 20);
        jScrollPaneObservaciones.setBounds(30, 140, 750, 60);
        //Clinete
        lbTituloNombre.setBounds(200, 20, 140, 20);
        lbTituloCodCliente.setBounds(30, 20, 140, 20);
        txtCodCliente.setBounds(30, 40, 140, 20);
        btnBuscarCliente.setBounds(30, 70, 110, 20);
        lbNombre.setBounds(200, 35, 140, 20);
        lbTituloApellidos.setBounds(350, 20, 140, 20);
        lbApellidos.setBounds(350, 35, 250, 20);
        lbTituloLineaCredito.setBounds(650, 20, 140, 20);
        lbLineaCredito.setBounds(650, 35, 140, 20);
        lbTituloLineaDisp.setBounds(200, 70, 140, 20);
        lbLineaDisp.setBounds(200, 85, 140, 20);
        lbTituloDeudaVencida.setBounds(650, 70, 140, 20);
        lbDeudaVencida.setBounds(650, 85, 140, 20);
        lbTituloTipoDocumento.setBounds(30, 110, 140, 20);
        cbTipoDocumento.setBounds(30, 130, 230, 20);
        lbTituloDocumentoLegal.setBounds(350, 70, 100, 20);
        lbDocumentoLegal.setBounds(350, 85, 140, 20);
        lbTituloDestino.setBounds(350, 110, 110, 20);
        cbDestino.setBounds(350, 130, 140, 20);
        lbTituloConsultoraRefencia.setBounds(30, 170, 140, 20);
        txtConsultoraRefencia.setBounds(30, 190, 140, 20);
        btnBuscarConRefencia.setBounds(30, 220, 110, 20);
        lbTituloReceptorFactura.setBounds(180, 170, 110, 20);
        txtReceptorFactura.setBounds(180, 190, 140, 20);
        btnBuscarReceptorFac.setBounds(180, 220, 110, 20);
        lbTituloPagadorFactura.setBounds(350, 170, 110, 20);
        txtPagadorFactura.setBounds(350, 190, 140, 20);
        Cliente.setBounds(0, 370, 800, 260);
        btnBuscarPagador.setBounds(350, 220, 110, 20);        
        //Datos Cabecera
        lbTituloCodClienteDetalle.setBounds(20, 30, 100, 20);
        lbCodClienteDetalle.setBounds(20, 45, 110, 20);
        lbTituloLineaDispDetalle.setBounds(20, 70, 100, 20);
        lbLineaDispDetalle.setBounds(20, 85, 70, 20);
        lbTituloNombreDetalle.setBounds(100, 30, 90, 20);
        lbNombreDetalle.setBounds(145, 45, 200, 20);
        lbTituloApellidosDetalle.setBounds(400, 30, 70, 20);
        lbApellidosDetalle.setBounds(400, 45, 250, 20);
        lbTituloFormaPagoDetalle.setBounds(145, 70, 100, 20);
        lbFormaPagoDetalle.setBounds(145, 85, 200, 20);
        DatosCabecera.setBounds(0, 20, 800, 120);
        //Datos Detalle
        lbCodVenta.setBounds(20, 30, 74, 20);
        txtCodVenta.setBounds(20, 50, 90, 21);
        lbCodVentaObligatorio.setBounds(115, 40, 40,40);
        lbUnidDemandadas.setBounds(20, 80, 120, 20);
        txtUnidDemandadas.setBounds(20, 100, 90, 21);
        lbUnidadesDemandadasObligatorio.setBounds(115, 90, 40,40);
        lbControlLiq.setBounds(20, 130, 120, 20);
        lbControlLiqCantidad.setBounds(20, 150, 90, 20);
        lbObservaciones1.setBounds(20, 180, 110, 20);
        jScrollPaneObservaciones1.setBounds(20, 200, 760, 50);

        lbCodProducto.setBounds(300, 30, 100, 20);
        txtCodProducto.setBounds(300, 50, 120, 21);
        lbCodProductoObligatorio.setBounds(425, 40, 40,40);
        lbStockDisponible.setBounds(300, 80, 100, 20);
        lbStockDisponibleCantidad.setBounds(300, 100, 120, 20);
        jLabel11.setBounds(300, 130, 100, 20);
        lbReservaCantidad.setBounds(300, 150, 70, 20);

        lbDesc.setBounds(540, 30, 250, 20);
        lbDescripcion.setBounds(540, 50, 250, 20);
        jLabel4.setBounds(540, 80, 90, 20);
        lbLimiteVentaCantidad.setBounds(540, 100, 140, 20);
        lbDemandaNoAtendida.setBounds(540, 130, 140, 20);
        chkDemandaNoAtendida.setBounds(540, 150, 20, 21);

        pnDatosDetalle.setBounds(0, 150, 800, 270);
        pnBtnDatosDetalle.setBounds(2,420,796,20);
        btnAniadir.setBounds(0,0,73,20);//(410, 160, 73, 20);
        btnGuardar.setBounds(75,0,85,20);//(565, 160, 73, 20);
        jTabbedPane.setBounds(0, 20, 820, 710);
        btnBuscarProd.setBounds(161,0,115,20);//(638, 160, 73, 20);
        btnBuscarSolAnter.setBounds(277,0,135,20);//(720, 160, 73, 20);
        btnPresentarFlete.setBounds(413,0,135,20);//(410, 190, 73, 20);
        btnSimularCuadre.setBounds(549,0,135,20);

        //Tabla Detalle      

        pnBtnTablaDetalle.setBounds(2, 640, 796, 20);
        btnEliminar.setBounds(0,0,85,20);//(488, 160, 73, 20);
        
        //tablaDetalle.setBounds(0, 0, 700, 140);
        spTablaDetalle.setBounds(30, 30, 740, 140);
        panelTablaDetalle.setBounds(0, 450, 800, 190);
        //Generales
        pnAceptarCancelar.setBounds(2,630,796,20);
        btnCancelar.setBounds(81,0,85,20);
        btnAceptar.setBounds(0,0,80,20);        

        lbTipoSolicitudObligatorio.setBounds(435, 30,40,40);        
        lbPeriodoObligatorio.setBounds(175, 30,40,40);
        lbCodClienteObligatorio.setBounds(175, 30, 40,40);
        lbTipoDespachoObligatorio.setBounds(175,80, 40,40);
        lbTipoDocumentoObligatorio.setBounds(265, 120, 40, 40);
        lbReceptorFacturaObligatorio.setBounds(325, 180, 40,40);
        lbPagadorFacturaObligatorio.setBounds(495, 180,40,40);
        lbDestinoObligatorio.setBounds(495, 120, 40,40);


      
      //ActionListeners
        //Tipo Solicitud
        cbTipoSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoSolicitudActionPerformed(evt);
            }
        });
        
        //Cliente
        txtCodCliente.addFocusListener(new FocusAdapter () {
          public void focusLost ( FocusEvent evt ) {
            txtcodCliente_lostFocus( evt );
          }
        });
        
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });
            
        //Agregado por Guido Pons 
         atxObservacionesDatosDetalle.addKeyListener(new java.awt.event.KeyListener() {
            public void keyTyped( KeyEvent evt) {}
            public void keyReleased( KeyEvent evt) {}
            public void keyPressed( KeyEvent evt) {
                if (evt.getKeyCode() == KeyEvent.VK_TAB) {
                    atxObservacionesDatosDetalle.transferFocus();
                }
            }
        });
        //Fin Agregado por Guido Pons        

        
        cbTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoDocumentoActionPerformed(evt);
            }
        });
        btnBuscarConRefencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarConRefenciaActionPerformed(evt);
            }
        });
 
        //Agregado por Guido Pons
        btnBuscarConRefencia.addKeyListener(new java.awt.event.KeyListener() {
            public void keyTyped( java.awt.event.KeyEvent evt) {}
            public void keyReleased( java.awt.event.KeyEvent evt) {}
            public void keyPressed( java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    btnBuscarConRefenciaKeyPressed(evt);
                }
            }
        });
        //Fin Agregado por Guido Pons
 
        txtReceptorFactura.addFocusListener(new FocusAdapter () {
          public void focusLost ( FocusEvent evt ) {
            txtReceptorFactura_lostFocus( evt );
          }
        });
        btnBuscarReceptorFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarReceptorFacActionPerformed(evt);
            }
        });
        txtPagadorFactura.addFocusListener(new FocusAdapter () {
          public void focusLost ( FocusEvent evt ) {
            txtPagadorFactura_lostFocus( evt );
          }
        });
        btnBuscarPagador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPagadorActionPerformed(evt);
            }
        });
        //Datos Cabecera
        //Datos Detalle
        //Tabla Detalle      
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pestaniaCabeceraImplementacion.validarCabeceraSolicitud();
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcoDatosDetalle.revertirAlmacen(Boolean.TRUE);
                reiniciar();
            }
        });

       /* Modificacion por Performance alorenzo 26/07/2006 */
       
       /* txtCodVenta.addFocusListener(new FocusAdapter () {          
          public void focusLost ( FocusEvent evt ) {          
            marcoDatosDetalle.txtCodVentaOnChange();            
          }
        });

        txtCodProducto.addFocusListener(new FocusAdapter () {          
        public void focusLost ( FocusEvent evt ) {          
            marcoDatosDetalle.txtCodProductoOnChange();            
          }
        });       
        
        txtUnidDemandadas.addFocusListener(new FocusAdapter () {
          public void focusLost ( FocusEvent evt ) {
            marcoDatosDetalle.txtUniDemandadasOnChange();            
          }
        });

        
        */

       txtCodVenta.addFocusListener(new FocusAdapter () {                    
       public void focusLost ( FocusEvent evt ) {
          if (!txtCodVenta.getText().toString().equalsIgnoreCase(valCodVentaAnterior.toString())){
                  valCodVentaAnterior = txtCodVenta.getText().toString();
                  marcoDatosDetalle.txtCodVentaOnChange();                
                  valUnidDemandadasAnterior = "";
              }
          }
        }
        );  
        
        txtCodProducto.addFocusListener(new FocusAdapter () {          
        public void focusLost ( FocusEvent evt ) {          
            if (!txtCodProducto.getText().toString().equalsIgnoreCase(valCodProductoAnterior.toString())){
                 valCodProductoAnterior = txtCodProducto.getText().toString();
                 marcoDatosDetalle.txtCodProductoOnChange();            
                 valUnidDemandadasAnterior = "";
            }
          }
        });       
        
        txtUnidDemandadas.addFocusListener(new FocusAdapter () {
          public void focusLost ( FocusEvent evt ) {
            if (!txtUnidDemandadas.getText().toString().equalsIgnoreCase(valUnidDemandadasAnterior.toString())){
                 valUnidDemandadasAnterior = txtUnidDemandadas.getText().toString();
                 marcoDatosDetalle.txtUniDemandadasOnChange();            
            }
          }
        });
        /* Fin Modificacion por Performance alorenzo 26/07/2006 */
        
        txtConsultoraRefencia.addFocusListener(new FocusAdapter () {
          public void focusLost ( FocusEvent evt ) {
            if(longCodClie > 0 && txtConsultoraRefencia.getText().trim().length() > 0) {
              String aux = txtConsultoraRefencia.getText();
              while(aux.length() < longCodClie) {
                aux = "0" + aux;            
              }
              txtConsultoraRefencia.setText(aux);
            }            
          }
        });
        

        btnAniadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAniadirActionPerformed(evt); 
                valCodVentaAnterior = "";
                valCodProductoAnterior = "";
                valUnidDemandadasAnterior = "";
            }
        });

        //Agregado por Guido Pons
        btnAniadir.addKeyListener(new java.awt.event.KeyListener() {
            public void keyTyped( java.awt.event.KeyEvent evt) {}
            public void keyReleased( java.awt.event.KeyEvent evt) {}
            public void keyPressed( java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    btnAniadirKeyPressed(evt);
                    valCodVentaAnterior = "";
                    valCodProductoAnterior = "";  
                    valUnidDemandadasAnterior = "";
                }
            }
        });
        // fin Agregado por Guido Pons
        
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //btnAniadirActionPerformed(evt);
                marcoDatosDetalle.btnEliminarClick();
            }
        });

        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcoDatosDetalle.btnGuardarClick();
            }
        });

        btnBuscarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcoDatosDetalle.btnBuscarProductoClick();
            }
        });

        btnBuscarSolAnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcoDatosDetalle.btnBuscarSolicitudesAnterioresClick();
            }
        });

        
        btnPresentarFlete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcoDatosDetalle.btnPresentarFlete();
            }
        });
        
        btnSimularCuadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcoDatosDetalle.btnSimularCuadre_click();
            }
        });

        /*
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pestaniaCabeceraImplementacion.validarCabeceraSolicitud();
            }
        });
        pnBotonera.add(btnAceptar);
        btnAceptar.setBounds(30,500,80,20);
        getContentPane().add(pnBotonera, BorderLayout.SOUTH);
        pnBotonera.setBounds(0,500,820,40);*/
        

        //jMenu.setText("Cliente");
        //jMenuItem1.setText("Alta Cliente");
        btnAltaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaClienteActionPerformed(evt);
            }
        });
        //jMenu.add(jMenuItem1);

        //jMenuBar1.add(jMenu);

        //setJMenuBar(jMenuBar1);
        
    }//GEN-END:initComponents
    private void initTipoSolicitud()
    {
        TipoSolicitud = new javax.swing.JPanel();
        lblTipoSolicitud = new javax.swing.JLabel();
        cbTipoSolicitud = new ComboBoxApplet();//javax.swing.JComboBox();
        lbMarca = new javax.swing.JLabel();
        lbMarcaTipoSolicitud = new javax.swing.JLabel();
        lbCanal = new javax.swing.JLabel();
        lbCanalTipoSolicitud = new javax.swing.JLabel();
        lbAcceso = new javax.swing.JLabel();
        lbAccesoTipoSolicitud = new javax.swing.JLabel();
        lbSubacceso = new javax.swing.JLabel();
        lbSubaccesoTipoSolicitud = new javax.swing.JLabel();
        lbMonedaDoc = new javax.swing.JLabel();
        lbMonedaDocTipoSolicitud = new javax.swing.JLabel();
    }
    private void initDatosSolicitud()
    {
        pnDatosSolicitud = new javax.swing.JPanel();
        //pnBotonera = new javax.swing.JPanel();
        lbPeriodo = new javax.swing.JLabel();
        cbPeriodo = new ComboBoxApplet();//javax.swing.JComboBox();
        lbAccesoFisico = new javax.swing.JLabel();
        cbAccesoFisico = new ComboBoxApplet();//javax.swing.JComboBox();
        lbTipoDespacho = new javax.swing.JLabel();
        cbTipoDespacho = new ComboBoxApplet();//javax.swing.JComboBox();
        lbFechaProgramadaFac = new javax.swing.JLabel();
        txtFechaProgramadaFac = new javax.swing.JTextField();
        lbNumeroClientes = new javax.swing.JLabel();
        txtNumeroClientes = new javax.swing.JTextField();
        lbIndCodigoVentaProducto = new javax.swing.JLabel();
        //chkIndCodigoVentaProducto = new javax.swing.JCheckBox();
        rbIndCodigVentaProducto = new JRadioButton("Producto", false);
        /*rbIndCodigVentaProducto.addActionListener(new AbstractAction("Producto") {
          public void actionPerformed(ActionEvent evt) {
            valueIndCodigVenta = ConstantesApplet.PRODUCTO;
          }
        } );*/
        rbIndCodigVentaCV = new JRadioButton("CV", false);
        /*new AbstractAction("cv") {
          public void actionPerformed(ActionEvent evt) {
            valueIndCodigVenta = ConstantesApplet.PRODUCTO;
          }
        } );*/
        lbFormaPago = new javax.swing.JLabel();
        cbFormaPago = new ComboBoxApplet();//javax.swing.JComboBox();
        lbObservaciones = new javax.swing.JLabel();
        jScrollPaneObservaciones = new javax.swing.JScrollPane();
        atxObservaciones = new javax.swing.JTextArea();
    }
    private void initCliente()
    {
        Cliente = new javax.swing.JPanel();
        lbTituloNombre = new javax.swing.JLabel();
        lbTituloCodCliente = new javax.swing.JLabel();
        txtCodCliente = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        lbNombre = new javax.swing.JLabel();
        lbTituloApellidos = new javax.swing.JLabel();
        lbApellidos = new javax.swing.JLabel();
        lbTituloLineaCredito = new javax.swing.JLabel();
        lbLineaCredito = new javax.swing.JLabel();
        lbTituloLineaDisp = new javax.swing.JLabel();
        lbLineaDisp = new javax.swing.JLabel();
        lbTituloDeudaVencida = new javax.swing.JLabel();
        lbDeudaVencida = new javax.swing.JLabel();
        lbTituloTipoDocumento = new javax.swing.JLabel();
        cbTipoDocumento = new ComboBoxApplet();//javax.swing.JComboBox();
        lbTituloDocumentoLegal = new javax.swing.JLabel();
        lbDocumentoLegal = new javax.swing.JLabel();
        lbTituloDestino = new javax.swing.JLabel();
        cbDestino = new ComboBoxApplet();//javax.swing.JComboBox();
        lbTituloConsultoraRefencia = new javax.swing.JLabel();
        txtConsultoraRefencia = new javax.swing.JTextField();
        btnBuscarConRefencia = new javax.swing.JButton();
        lbTituloReceptorFactura = new javax.swing.JLabel();
        txtReceptorFactura = new javax.swing.JTextField();
        btnBuscarReceptorFac = new javax.swing.JButton();
        lbTituloPagadorFactura = new javax.swing.JLabel();
        txtPagadorFactura = new javax.swing.JTextField();
        btnBuscarPagador = new javax.swing.JButton();
    
    }
    private void initDatosCabecera()
    {
        DatosCabecera = new javax.swing.JPanel();
        lbTituloLineaDispDetalle = new javax.swing.JLabel();
        lbLineaDispDetalle = new javax.swing.JLabel();
        lbTituloCodClienteDetalle = new javax.swing.JLabel();
        lbTituloNombreDetalle = new javax.swing.JLabel();
        lbNombreDetalle = new javax.swing.JLabel();
        lbTituloApellidosDetalle = new javax.swing.JLabel();
        lbApellidosDetalle = new javax.swing.JLabel();
        lbCodClienteDetalle = new javax.swing.JLabel();
        lbTituloFormaPagoDetalle = new javax.swing.JLabel();
        lbFormaPagoDetalle = new javax.swing.JLabel();
    
    }
    private void initDatosDetalle()
    {
        pnDatosDetalle = new javax.swing.JPanel();
        pnBtnDatosDetalle = new javax.swing.JPanel();
        lbCodVenta = new javax.swing.JLabel();
        lbStockDisponibleCantidad = new javax.swing.JLabel();
        lbCodProducto = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbDesc = new javax.swing.JLabel();
        lbDescripcion = new javax.swing.JLabel();
        lbUnidDemandadas = new javax.swing.JLabel();
        lbLimiteVentaCantidad = new javax.swing.JLabel();
        lbStockDisponible = new javax.swing.JLabel();
        txtCodVenta = new javax.swing.JTextField();
        txtCodProducto = new javax.swing.JTextField();
        txtUnidDemandadas = new javax.swing.JTextField();
        lbControlLiq = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbDemandaNoAtendida = new javax.swing.JLabel();
        lbObservaciones1 = new javax.swing.JLabel();
        lbControlLiqCantidad = new javax.swing.JLabel();
        lbReservaCantidad = new javax.swing.JLabel();
        chkDemandaNoAtendida = new javax.swing.JCheckBox();
        btnAniadir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBuscarProd = new javax.swing.JButton();
        btnBuscarSolAnter = new javax.swing.JButton();
        btnPresentarFlete = new javax.swing.JButton();
        btnSimularCuadre = new javax.swing.JButton();
        jScrollPaneObservaciones1 = new javax.swing.JScrollPane();
        atxObservacionesDatosDetalle = new javax.swing.JTextArea();
    
    }
    private void initTablaDetalle()
    {
        panelTablaDetalle = new javax.swing.JPanel();
        pnBtnTablaDetalle = new javax.swing.JPanel();
        //jTable1 = new javax.swing.JTable();
        tablaDetalle = new TablaDetalle();
        spTablaDetalle = new JScrollPane();
    
    }
    private void cbTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {
      try {
        this.marcoCliente.cbTipoDocumento_onChange();
      } catch (AppletException e) {
        e.printStackTrace();
        UtilApplet.procesarError(e, this);
      }
    }
  
    private void btnBuscarConRefenciaActionPerformed(java.awt.event.ActionEvent evt) {
      try {
        this.marcoCliente.btnBuscarConsultoraReferencia_onClick();
      } catch (AppletException e) {
        e.printStackTrace();
        UtilApplet.procesarError(e, this);
      }
    }

     //Agregado por Guido Pons
     private void btnBuscarConRefenciaKeyPressed(java.awt.event.KeyEvent evt) {
      try {
            this.marcoCliente.btnBuscarConsultoraReferencia_onClick();
      } catch (AppletException e) {
        e.printStackTrace();
        UtilApplet.procesarError(e, this);
      }
    }
    //Fin Agregado por Guido Pons
    
    private void btnBuscarReceptorFacActionPerformed(java.awt.event.ActionEvent evt) {
      try {
        this.marcoCliente.btnBuscarReceptor_onClick();
      } catch (AppletException e) {
        e.printStackTrace();
        UtilApplet.procesarError(e, this);
      }
    }
    
    private void btnBuscarPagadorActionPerformed(java.awt.event.ActionEvent evt) {
      try {
        this.marcoCliente.btnBuscarPagador_onClick();
      } catch (AppletException e) {
        e.printStackTrace();
        UtilApplet.procesarError(e, this);
      }
    }
    

    private void btnAniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAniadirActionPerformed
      this.marcoDatosDetalle.btnAnyadirClick();
    }
    
    //Agregado por Guido Pons
    private void btnAniadirKeyPressed(KeyEvent evt) {
      this.marcoDatosDetalle.btnAnyadirClick();
    }
    //Fin Agregado por Guido Pons
    
    
    private void altaClienteActionPerformed(java.awt.event.ActionEvent evt) {
      try {
        this.ejecutarWeb("mostrarInsertarClienteBasico", "'LPInsertarClienteBasico'");
        this.marcoCliente.txtcodCliente_lostFocus();
      } catch (AppletException e) {
        e.printStackTrace();
        UtilApplet.procesarError(e, this);
      }
    }
    
    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {     
     try {
        this.marcoCliente.btnBuscarCliente_onClick();
      } catch (AppletException e) {
        e.printStackTrace();
        UtilApplet.procesarError(e, this);
      }
    }
    
   

    
    private void cbTipoSolicitudActionPerformed(java.awt.event.ActionEvent evt) {
      try {
        this.cbtipoSolicitud_onchange();
      } catch (AppletException e) {
        e.printStackTrace();
        UtilApplet.procesarError(e, this);
      }
    }
    
    private void txtcodCliente_lostFocus(FocusEvent fe) {
      try {
        if(this.longCodClie > 0 && this.txtCodCliente.getText().trim().length() > 0) {
          String aux = this.txtCodCliente.getText();
          while(aux.length() < this.longCodClie) {
            aux = "0" + aux;            
          }
          this.txtCodCliente.setText(aux);
        }
        this.marcoCliente.txtcodCliente_lostFocus();
      } catch (AppletException e) {
        e.printStackTrace();
        UtilApplet.procesarError(e, this);
      }
    }
        
    private void txtReceptorFactura_lostFocus(FocusEvent fe) {
      try {
        if(this.longCodClie > 0 && this.txtReceptorFactura.getText().trim().length() > 0) {
          String aux = this.txtReceptorFactura.getText();
          while(aux.length() < this.longCodClie) {
            aux = "0" + aux;            
          }
          this.txtReceptorFactura.setText(aux);
        }
        this.marcoCliente.txtReceptorFactura_lostFocus();
      } catch (AppletException e) {
        e.printStackTrace();
        UtilApplet.procesarError(e, this);
      }
    }
    
    private void txtPagadorFactura_lostFocus(FocusEvent fe) {
      try {
        if(this.longCodClie > 0 && this.txtPagadorFactura.getText().trim().length() > 0) {
          String aux = this.txtPagadorFactura.getText();
          while(aux.length() < this.longCodClie) {
            aux = "0" + aux;            
          }
          this.txtPagadorFactura.setText(aux);
        }
        this.marcoCliente.txtPagadorFactura_lostFocus();
      } catch (AppletException e) {
        e.printStackTrace();
        UtilApplet.procesarError(e, this);
      }
    }
        
    
    protected javax.swing.JLabel lbTipoSolicitudObligatorio;
    protected javax.swing.JLabel lbPeriodoObligatorio;
    protected javax.swing.JLabel lbCodClienteObligatorio;    
    protected javax.swing.JLabel lbTipoDespachoObligatorio;
    protected javax.swing.JLabel lbTipoDocumentoObligatorio;
    protected javax.swing.JLabel lbReceptorFacturaObligatorio;
    protected javax.swing.JLabel lbPagadorFacturaObligatorio;
    protected javax.swing.JLabel lbDestinoObligatorio;
    protected javax.swing.JLabel lbCodVentaObligatorio;
    protected javax.swing.JLabel lbCodProductoObligatorio;
    protected javax.swing.JLabel lbUnidadesDemandadasObligatorio;
    
    //protected javax.swing.JPanel pnGeneral;
    protected javax.swing.JPanel pnBtnAltaCliente;
    protected javax.swing.JPanel pnAceptarCancelar;
    protected javax.swing.JPanel Cliente;
    protected javax.swing.JPanel DatosCabecera;
    protected javax.swing.JPanel pnDatosDetalle;
    protected javax.swing.JPanel pnDatosSolicitud;
    protected javax.swing.JPanel pestaniaCabecera;
    protected javax.swing.JPanel pestaniaDetalle;
    protected javax.swing.JPanel panelTablaDetalle;
    protected javax.swing.JPanel pnBtnDatosDetalle;
    protected javax.swing.JPanel pnBtnTablaDetalle;
    protected javax.swing.JPanel TipoSolicitud;
    //protected javax.swing.JPanel pnBotonera;
    protected javax.swing.JTextArea atxObservaciones;
    protected javax.swing.JTextArea atxObservacionesDatosDetalle;
    protected javax.swing.JButton btnAltaCliente;
    protected javax.swing.JButton btnAniadir;
    protected javax.swing.JButton btnEliminar;
    protected javax.swing.JButton btnGuardar;
    protected javax.swing.JButton btnBuscarProd;
    protected javax.swing.JButton btnBuscarSolAnter;
    protected javax.swing.JButton btnPresentarFlete;
    protected javax.swing.JButton btnSimularCuadre;
    protected javax.swing.JButton btnBuscarCliente;
    protected javax.swing.JButton btnBuscarConRefencia;
    protected javax.swing.JButton btnBuscarPagador;
    protected javax.swing.JButton btnBuscarReceptorFac;
    protected javax.swing.JButton btnAceptar;
    protected javax.swing.JButton btnCancelar;
    protected ComboBoxApplet cbAccesoFisico;
    protected ComboBoxApplet cbDestino;
    protected ComboBoxApplet cbFormaPago;
    protected ComboBoxApplet cbPeriodo;
    protected ComboBoxApplet cbTipoDespacho;
    protected ComboBoxApplet cbTipoDocumento;
    protected ComboBoxApplet cbTipoSolicitud;
    protected javax.swing.JCheckBox chkDemandaNoAtendida;
    protected JRadioButton rbIndCodigVentaProducto;
    protected JRadioButton rbIndCodigVentaCV;
    final protected ButtonGroup groupIndCodigVenta = new ButtonGroup();
    protected javax.swing.JLabel jLabel11;
    protected javax.swing.JLabel jLabel4;
    protected javax.swing.JScrollPane jScrollPaneObservaciones;
    protected javax.swing.JScrollPane jScrollPaneObservaciones1;
    protected javax.swing.JTabbedPane jTabbedPane;
    protected TablaDetalle tablaDetalle;
    protected JScrollPane spTablaDetalle;
    //protected javax.swing.JTable jTable1;
    protected javax.swing.JLabel lbAcceso;
    protected javax.swing.JLabel lbAccesoTipoSolicitud;
    protected javax.swing.JLabel lbAccesoFisico;
    protected javax.swing.JLabel lbApellidos;
    protected javax.swing.JLabel lbApellidosDetalle;
    protected javax.swing.JLabel lbCanal;
    protected javax.swing.JLabel lbCanalTipoSolicitud;
    protected javax.swing.JLabel lbCodClienteDetalle;
    protected javax.swing.JLabel lbCodProducto;
    protected javax.swing.JLabel lbCodVenta;
    protected javax.swing.JLabel lbControlLiq;
    protected javax.swing.JLabel lbControlLiqCantidad;
    protected javax.swing.JLabel lbDemandaNoAtendida;
    protected javax.swing.JLabel lbDesc;
    protected javax.swing.JLabel lbDescripcion;
    protected javax.swing.JLabel lbDeudaVencida;
    protected javax.swing.JLabel lbDocumentoLegal;
    protected javax.swing.JLabel lbFechaProgramadaFac;
    protected javax.swing.JLabel lbNumeroClientes;
    protected javax.swing.JLabel lbFormaPago;
    protected javax.swing.JLabel lbFormaPagoDetalle;
    protected javax.swing.JLabel lbIndCodigoVentaProducto;
    protected javax.swing.JLabel lbLimiteVentaCantidad;
    protected javax.swing.JLabel lbLineaCredito;
    protected javax.swing.JLabel lbLineaDisp;
    protected javax.swing.JLabel lbLineaDispDetalle;
    protected javax.swing.JLabel lbMarca;
    protected javax.swing.JLabel lbMarcaTipoSolicitud;
    protected javax.swing.JLabel lbMonedaDoc;
    protected javax.swing.JLabel lbMonedaDocTipoSolicitud;
    protected javax.swing.JLabel lbNombre;
    protected javax.swing.JLabel lbNombreDetalle;
    protected javax.swing.JLabel lbObservaciones;
    protected javax.swing.JLabel lbObservaciones1;
    protected javax.swing.JLabel lbPeriodo;
    protected javax.swing.JLabel lbReservaCantidad;
    protected javax.swing.JLabel lbStockDisponible;
    protected javax.swing.JLabel lbStockDisponibleCantidad;
    protected javax.swing.JLabel lbSubacceso;
    protected javax.swing.JLabel lbSubaccesoTipoSolicitud;
    protected javax.swing.JLabel lbTipoDespacho;
    protected javax.swing.JLabel lbTituloApellidos;
    protected javax.swing.JLabel lbTituloApellidosDetalle;
    protected javax.swing.JLabel lbTituloCodCliente;
    protected javax.swing.JLabel lbTituloCodClienteDetalle;
    protected javax.swing.JLabel lbTituloConsultoraRefencia;
    protected javax.swing.JLabel lbTituloDestino;
    protected javax.swing.JLabel lbTituloDeudaVencida;
    protected javax.swing.JLabel lbTituloDocumentoLegal;
    protected javax.swing.JLabel lbTituloFormaPagoDetalle;
    protected javax.swing.JLabel lbTituloLineaCredito;
    protected javax.swing.JLabel lbTituloLineaDisp;
    protected javax.swing.JLabel lbTituloLineaDispDetalle;
    protected javax.swing.JLabel lbTituloNombre;
    protected javax.swing.JLabel lbTituloNombreDetalle;
    protected javax.swing.JLabel lbTituloPagadorFactura;
    protected javax.swing.JLabel lbTituloReceptorFactura;
    protected javax.swing.JLabel lbTituloTipoDocumento;
    protected javax.swing.JLabel lbUnidDemandadas;
    protected javax.swing.JLabel lblTipoSolicitud;
    protected javax.swing.JTextField txtCodCliente;
    protected javax.swing.JTextField txtCodProducto;
    protected javax.swing.JTextField txtCodVenta;
    protected javax.swing.JTextField txtConsultoraRefencia;
    protected javax.swing.JTextField txtFechaProgramadaFac;
    protected javax.swing.JTextField txtPagadorFactura;
    protected javax.swing.JTextField txtReceptorFactura;
    protected javax.swing.JTextField txtUnidDemandadas;
    protected javax.swing.JTextField txtNumeroClientes;
    // End of variables declaration
    
    
    /*
    public void mostrarError(int codigoError) {
    //TODO
    
      JOptionPane.showMessageDialog( 
          getParent(), "Error " + codigoError, 
          "Titulño error", 
          JOptionPane.ERROR_MESSAGE );
          
    }

    public void mostrarError(String msg) {
      JOptionPane.showMessageDialog( 
          getParent(), msg, 
          "Error ocurrido", 
          JOptionPane.ERROR_MESSAGE );
    }
    
    public void mostrarMensaje(int codigoMensaje) {
    //TODO
      JOptionPane.showMessageDialog( 
          this.getParent(), "Msg " + codigoMensaje, 
          "Titulño error", 
          JOptionPane.INFORMATION_MESSAGE );
    }
    */
    public Long getOidPais() 
    {
      return this.oidPais;
    }
    
    public Long getOidIdioma() 
    {
      return this.oidIdioma;
    }
    
    public String getUser() 
    {
      return this.user;
    }

    
    public String getPrueba() 
    {
      //System.out.println("es getPrueba()");
      return "anda";
    }

    protected void deshabilitarTodo() {
      this.setEnabled(false); 
    }
    
   public static void main(String []args) 
   {
     //RegistroOnlineApplet frame = new RegistroOnlineApplet();
     //frame.init();
     //frame.show();
   }

}
