SELECT *
FROM
(
 	SELECT PRO.STRINGVALUE SOCIEDAD_DEFECTO
	FROM PRINCIPALS PRI,
		PROPERTYVALUES PRO			
	WHERE PRI.NAME = 'USUARIO1'			   	  	 -- PARAMETRO DE USUARIO POR DEFECTO --
		 AND PRO.IDPROPERTY = 48
		 AND PRO.IDPRINCIPAL = PRI.IDPRINCIPAL
),	
(		
SELECT PAIS,
	   DES_REGI,
	   DES_ZONA,	
	   SUM(VTA_NETA_ESTAD) VENTA_NETA_ESTAD,
	   SUM(N_PEDIDOS) N_PEDIDO,
	   DECODE(SUM(N_PEDIDOS), 0 , 0, (SUM(N_PEDIDOS)/SUM(ACTI_FINALES))*100) ACTIVIDAD,   
   	   SUM(ACTI_FINALES) ACTI_FINALES,
   	   SUM(INGRESOS) INGRESOS,
	   SUM(REINGRESOS) REINGRESOS,
	   SUM(EGRESOS) EGRESOS,	   
	   SUM(INGRESOS) + SUM(REINGRESOS) - SUM(EGRESOS) CAPITALIZACION,
	   SUM(REZO_RECIBIDAS) REZO_RECIBIDAS,
	   SUM(REZO_ENTREGADAS) REZO_ENTREGADAS,		   	   
	   DECODE(SUM(N_PEDIDOS), 0, 0, SUM(VTA_NETA_ESTAD)/SUM(N_PEDIDOS)) PMNP,
	   DECODE(SUM(UNIDADES_VENDIDAS), 0, 0, SUM(VTA_NETA_ESTAD)/SUM(UNIDADES_VENDIDAS)) PPU,	    	   
   	   DECODE(SUM(N_PEDIDOS), 0, 0, SUM(UNIDADES_VENDIDAS)/SUM(N_PEDIDOS)) PUP,
   	   DECODE(SUM(N_PEDIDOS), 0, 0, SUM(N_CLIENTES)/SUM(N_PEDIDOS)) CPP
FROM 		
	(		
	SELECT GEN_PAIS.VAL_I18N PAIS,
		   REG.OID_REGI,
		   REG.DES_REGI,
		   ZONA.OID_ZONA,
		   ZONA.DES_ZONA,
		   (
		   SELECT SUM(NVL(VR.NUM_ACTI_FINA, 0))
		   FROM INT_FUENT_VENTAS_REAL VR
		   WHERE VR.PERD_OID_PERI = PERI.OID_PERI
		   		 AND VR.ZZON_OID_ZONA = ZONA.OID_ZONA
				 AND VR.ZORG_OID_REGI = REG.OID_REGI
		   GROUP BY REG.OID_REGI,
				 ZONA.OID_ZONA
		   ) ACTI_FINALES,
		   (
		   SELECT SUM(NVL(VR.NUM_INGR, 0))
		   FROM INT_FUENT_VENTAS_REAL VR
		   WHERE VR.PERD_OID_PERI = PERI.OID_PERI
		   		 AND VR.ZZON_OID_ZONA = ZONA.OID_ZONA
				 AND VR.ZORG_OID_REGI = REG.OID_REGI
		   GROUP BY REG.OID_REGI,
				 ZONA.OID_ZONA
		   ) INGRESOS,
   		   (
		   SELECT SUM(NVL(VR.NUM_EGRE, 0))
		   FROM INT_FUENT_VENTAS_REAL VR
		   WHERE VR.PERD_OID_PERI = PERI.OID_PERI
		   		 AND VR.ZZON_OID_ZONA = ZONA.OID_ZONA
				 AND VR.ZORG_OID_REGI = REG.OID_REGI
		   GROUP BY REG.OID_REGI,
				 ZONA.OID_ZONA
		   ) EGRESOS,
		   (
		   SELECT SUM(NVL(VR.NUM_REIN, 0))
		   FROM INT_FUENT_VENTAS_REAL VR
		   WHERE VR.PERD_OID_PERI = PERI.OID_PERI
		   		 AND VR.ZZON_OID_ZONA = ZONA.OID_ZONA
				 AND VR.ZORG_OID_REGI = REG.OID_REGI
		   GROUP BY REG.OID_REGI,
				 ZONA.OID_ZONA
		   ) REINGRESOS,
		   (
		   SELECT SUM(NVL(VR.NUM_REZO_RECI, 0))
		   FROM INT_FUENT_VENTAS_REAL VR
		   WHERE VR.PERD_OID_PERI = PERI.OID_PERI
		   		 AND VR.ZZON_OID_ZONA = ZONA.OID_ZONA
				 AND VR.ZORG_OID_REGI = REG.OID_REGI
		   GROUP BY REG.OID_REGI,
				 ZONA.OID_ZONA
		   ) REZO_RECIBIDAS,
		   (
		   SELECT SUM(NVL(VR.NUM_REZO_ENTR, 0))
		   FROM INT_FUENT_VENTAS_REAL VR
		   WHERE VR.PERD_OID_PERI = PERI.OID_PERI
		   		 AND VR.ZZON_OID_ZONA = ZONA.OID_ZONA
				 AND VR.ZORG_OID_REGI = REG.OID_REGI
		   GROUP BY REG.OID_REGI,
				 ZONA.OID_ZONA
		   ) REZO_ENTREGADAS,
		   (
		   SELECT SUM(NVL(VRA.IMP_VENT_NETA_ESTA, 0))
		   FROM INT_FUENT_VENTA_REAL_VACUM VRA
		   WHERE VRA.PERD_OID_PERI = PERI.OID_PERI
		   		 AND VRA.ZZON_OID_ZONA = ZONA.OID_ZONA
				 AND VRA.ZORG_OID_REGI = REG.OID_REGI
		   GROUP BY REG.OID_REGI,
				 ZONA.OID_ZONA
		   ) VTA_NETA_ESTAD,
		   (
		   SELECT SUM(NVL(VRA.NUM_PEDI, 0))
		   FROM INT_FUENT_VENTA_REAL_VACUM VRA
		   WHERE VRA.PERD_OID_PERI = PERI.OID_PERI
		   		 AND VRA.ZZON_OID_ZONA = ZONA.OID_ZONA
				 AND VRA.ZORG_OID_REGI = REG.OID_REGI
		   GROUP BY REG.OID_REGI,
				 ZONA.OID_ZONA
		   ) N_PEDIDOS,
		   (
		   SELECT SUM(NVL(VRA.NUM_UNID_VEND, 0))
		   FROM INT_FUENT_VENTA_REAL_VACUM VRA
		   WHERE VRA.PERD_OID_PERI = PERI.OID_PERI
		   		 AND VRA.ZZON_OID_ZONA = ZONA.OID_ZONA
				 AND VRA.ZORG_OID_REGI = REG.OID_REGI
		   GROUP BY REG.OID_REGI,
				 ZONA.OID_ZONA
		   ) UNIDADES_VENDIDAS,
		   (
		   SELECT SUM(NVL(VRA.NUM_CLIE, 0))
		   FROM INT_FUENT_VENTA_REAL_VACUM VRA
		   WHERE VRA.PERD_OID_PERI = PERI.OID_PERI
		   		 AND VRA.ZZON_OID_ZONA = ZONA.OID_ZONA
				 AND VRA.ZORG_OID_REGI = REG.OID_REGI
		   GROUP BY REG.OID_REGI,
				 ZONA.OID_ZONA	
		   ) N_CLIENTES
	FROM CRA_PERIO PERI,
		 ZON_ZONA ZONA,
		 ZON_REGIO REG,
		 (
		 SELECT FEC_INIC
		 FROM CRA_PERIO 
		 WHERE OID_PERI = 55 				-- PARAMETRO DE PERIODO DESDE -- 
		 ) FI,
		 (
		 SELECT FEC_FINA
		 FROM CRA_PERIO 
		 WHERE OID_PERI = 67               -- PARAMETRO DE PERIDO HASTA --
		 ) FF,
		 (
		 SELECT GEN.VAL_OID, GEN.VAL_I18N
		 FROM V_GEN_I18N_SICC GEN
		 WHERE GEN.ATTR_ENTI = 'SEG_PAIS'
			   AND GEN.IDIO_OID_IDIO = 1			   -- PARAMETRO DE IDIOMA --
     	 ) GEN_PAIS
	WHERE PERI.FEC_INIC >= FI.FEC_INIC
		  AND PERI.FEC_FINA <= FF.FEC_FINA
		  AND ZONA.ZORG_OID_REGI = REG.OID_REGI
		  AND PERI.PAIS_OID_PAIS = GEN_PAIS.VAL_OID(+)
		  AND PERI.PAIS_OID_PAIS = 1		-- PARAMETRO DE PAIS --
		  AND PERI.MARC_OID_MARC = 1		-- PARAMETRO DE MARCA --
		  AND PERI.CANA_OID_CANA = 1		-- PARAMETRO DE CANAL --
		  AND ZONA.OID_ZONA = 1	   			-- PARAMETRO DE ZONA --
		  AND REG.OID_REGI = 7				-- PARAMETRO DE REGION --
		 )
GROUP BY PAIS,
	   DES_REGI,
	   DES_ZONA  
)		  