SELECT *
FROM
	(
	 	SELECT PRO.STRINGVALUE SOCIEDAD_DEFECTO
		FROM PRINCIPALS PRI,
			PROPERTYVALUES PRO			
		WHERE PRI.NAME = 'USUARIO1'			   	  	 -- PARAMETRO DE USUARIO POR DEFECTO --
			 AND PRO.IDPROPERTY = 48
			 AND PRO.IDPRINCIPAL = PRI.IDPRINCIPAL
	),
	(
	SELECT DATOS_AAAA.PAIS,
		   DATOS_AAAA.DES_REGI,
		   DATOS_AAAA.DES_ZONA,
		   DATOS_AAAA.VAL_ANIO AAAA,
		   DATOS_AAAA.VAL_NOMB_PERI,
		   TRUNC(((DATOS_AAAA.COD_PERI) - 1)/6)+1 GRUPO,
	-------------------------- NUEVAS -------------------------------------
		   DATOS_AA.PMNP_NUEVAS PMNP_NUEVAS_AA,
		   DATOS_AAAA.PMNP_NUEVAS PMNP_NUEVAS_AAAA,	   
		   CASE WHEN (DATOS_AAAA.PMNP_NUEVAS IS NOT NULL) THEN
		   	   ROUND(DECODE(DATOS_AA.PMNP_NUEVAS, 0, 0, ((DATOS_AAAA.PMNP_NUEVAS/DATOS_AA.PMNP_NUEVAS)-1)*100))
		   END PORC_PMNP_NUEVAS,
	-------------------------- NIVEL I -------------------------------------
		   DATOS_AA.PMNP_NIVELI PMNP_NIVELI_AA,
		   DATOS_AAAA.PMNP_NIVELI PMNP_NIVELI_AAAA,	   
		   CASE WHEN (DATOS_AAAA.PMNP_NIVELI IS NOT NULL) THEN
		   	   ROUND(DECODE(DATOS_AA.PMNP_NIVELI, 0, 0, ((DATOS_AAAA.PMNP_NIVELI/DATOS_AA.PMNP_NIVELI)-1)*100))
		   END PORC_PMNP_NIVELI,
	-------------------------- NIVEL II-------------------------------------
		   DATOS_AA.PMNP_NIVELII PMNP_NIVELII_AA,
		   DATOS_AAAA.PMNP_NIVELII PMNP_NIVELII_AAAA,	   
		   CASE WHEN (DATOS_AAAA.PMNP_NIVELII IS NOT NULL) THEN
		   	   ROUND(DECODE(DATOS_AA.PMNP_NIVELII, 0, 0, ((DATOS_AAAA.PMNP_NIVELII/DATOS_AA.PMNP_NIVELII)-1)*100))
		   END PORC_PMNP_NIVELII,
	-------------------------- NIVEL III -----------------------------------
		   DATOS_AA.PMNP_NIVELIII PMNP_NIVELIII_AA,
		   DATOS_AAAA.PMNP_NIVELIII PMNP_NIVELIII_AAAA,	   
		   CASE WHEN (DATOS_AAAA.PMNP_NIVELIII IS NOT NULL) THEN
		   	   ROUND(DECODE(DATOS_AA.PMNP_NIVELIII, 0, 0, ((DATOS_AAAA.PMNP_NIVELIII/DATOS_AA.PMNP_NIVELIII)-1)*100))
		   END PORC_PMNP_NIVELIII,
	-------------------------- NIVEL IV -------------------------------------
		   DATOS_AA.PMNP_NIVELIV PMNP_NIVELIV_AA,
		   DATOS_AAAA.PMNP_NIVELIV PMNP_NIVELIV_AAAA,	   
		   CASE WHEN (DATOS_AAAA.PMNP_NIVELIV IS NOT NULL) THEN
		   	   ROUND(DECODE(DATOS_AA.PMNP_NIVELIV, 0, 0, ((DATOS_AAAA.PMNP_NIVELIV/DATOS_AA.PMNP_NIVELIV)-1)*100))
		   END PORC_PMNP_NIVELIV,	
	-------------------------- TOTALES --------------------------------------
	   	   DATOS_AA.PMNP_NUEVAS + DATOS_AA.PMNP_NIVELI + DATOS_AA.PMNP_NIVELII + DATOS_AA.PMNP_NIVELIII + DATOS_AA.PMNP_NIVELIV TOTAL_AA,
	   	   DATOS_AAAA.PMNP_NUEVAS + DATOS_AAAA.PMNP_NIVELI + DATOS_AAAA.PMNP_NIVELII + DATOS_AAAA.PMNP_NIVELIII + DATOS_AAAA.PMNP_NIVELIV TOTAL_AAAA,	   	       
	   	   CASE WHEN (DATOS_AAAA.PMNP_NUEVAS IS NOT NULL) THEN
		   	   ROUND(DECODE((DATOS_AA.PMNP_NUEVAS + DATOS_AA.PMNP_NIVELI + DATOS_AA.PMNP_NIVELII + DATOS_AA.PMNP_NIVELIII + DATOS_AA.PMNP_NIVELIV), 0, 0, (((DATOS_AAAA.PMNP_NUEVAS + DATOS_AAAA.PMNP_NIVELI + DATOS_AAAA.PMNP_NIVELII + DATOS_AAAA.PMNP_NIVELIII + DATOS_AAAA.PMNP_NIVELIV)/(DATOS_AA.PMNP_NUEVAS + DATOS_AA.PMNP_NIVELI + DATOS_AA.PMNP_NIVELII + DATOS_AA.PMNP_NIVELIII + DATOS_AA.PMNP_NIVELIV))-1)*100))
		   END PORC_TOTALES,
		   CASE WHEN (DATOS_AAAA.PMNP_NUEVAS IS NOT NULL) THEN
		   		1
		   END IND_PARA_TOTAL_CAMPANIA_FIN
	---------------------------------------------------------------------------------------------------------------	   
	FROM
	(
		SELECT ROWNUM AS POS,
			   V_AAAA.PAIS,
			   V_AAAA.OID_REGI,
			   V_AAAA.DES_REGI,
			   V_AAAA.OID_ZONA,
			   V_AAAA.DES_ZONA,
			   V_AAAA.VAL_ANIO,
			   SUBSTR(V_AAAA.COD_PERI,5,2) COD_PERI,
			   V_AAAA.VAL_NOMB_PERI,
			   DATOS_AAAA.PMNP_NUEVAS,
			   DATOS_AAAA.PMNP_NIVELI,
			   DATOS_AAAA.PMNP_NIVELII,
			   DATOS_AAAA.PMNP_NIVELIII,
			   DATOS_AAAA.PMNP_NIVELIV
		FROM
		(
			SELECT OID_REGI,
				   OID_ZONA,
				   OID_PERI,
				   SUM(NVL(PMNP_NUEVAS, 0)) PMNP_NUEVAS,
				   SUM(NVL(PMNP_NIVELI, 0)) PMNP_NIVELI,
				   SUM(NVL(PMNP_NIVELII, 0)) PMNP_NIVELII,
		  		   SUM(NVL(PMNP_NIVELIII, 0)) PMNP_NIVELIII,
				   SUM(NVL(PMNP_NIVELIV, 0)) PMNP_NIVELIV		   		   		    
			FROM
				(
				SELECT REG.OID_REGI,
					   ZONA.OID_ZONA,
					   PERI.OID_PERI,
					   decode(NIVEL.OID_NIVE_SEGM,1,avg(SEG_CLI.VAL_VENT),0)as PMNP_NUEVAS,
					   decode(NIVEL.OID_NIVE_SEGM,2,avg(SEG_CLI.VAL_VENT),0)as PMNP_NIVELI,
					   decode(NIVEL.OID_NIVE_SEGM,3,avg(SEG_CLI.VAL_VENT),0)as PMNP_NIVELII,
					   decode(NIVEL.OID_NIVE_SEGM,4,avg(SEG_CLI.VAL_VENT),0)as PMNP_NIVELIII,
					   decode(NIVEL.OID_NIVE_SEGM,5,avg(SEG_CLI.VAL_VENT),0)as PMNP_NIVELIV
				FROM CRA_PERIO PERI,
					 ZON_ZONA ZONA,
					 ZON_REGIO REG,
					 DTR_SEGME_CLIEN SEG_CLI,
					 DTR_NIVEL_SEGME NIVEL,
					 (
						 SELECT FEC_INIC
						 FROM CRA_PERIO 
						 WHERE OID_PERI = 55 				-- PARAMETRO DE PERIODO DESDE -- 
					 ) FI,
					 (
						 SELECT FEC_FINA
						 FROM CRA_PERIO 
						 WHERE OID_PERI = 67               -- PARAMETRO DE PERIDO HASTA --
					 ) FF	 
				WHERE PERI.FEC_INIC >= FI.FEC_INIC
					  AND PERI.FEC_FINA <= FF.FEC_FINA
					  AND ZONA.ZORG_OID_REGI = REG.OID_REGI
					  AND SEG_CLI.PERD_OID_PERI = PERI.OID_PERI
					  AND SEG_CLI.ZZON_OID_ZONA = ZONA.OID_ZONA
					  AND SEG_CLI.ZORG_OID_REGI = REG.OID_REGI
					  AND SEG_CLI.NVSG_OID_NIVE_SEGM = NIVEL.OID_NIVE_SEGM
					  AND (NIVEL.OID_NIVE_SEGM = 1 OR NIVEL.OID_NIVE_SEGM = 2 OR NIVEL.OID_NIVE_SEGM = 3 OR NIVEL.OID_NIVE_SEGM = 4 OR NIVEL.OID_NIVE_SEGM = 5)
					  AND PERI.PAIS_OID_PAIS = 1		-- PARAMETRO DE PAIS --
					  AND PERI.MARC_OID_MARC = 1		-- PARAMETRO DE MARCA --
					  AND PERI.CANA_OID_CANA = 1		-- PARAMETRO DE CANAL --
					  AND ZONA.OID_ZONA = 1	   			-- PARAMETRO DE ZONA --
					  AND REG.OID_REGI = 7				-- PARAMETRO DE REGION --
			   GROUP BY REG.OID_REGI,
					   ZONA.OID_ZONA,
					   PERI.OID_PERI,
		  			   NIVEL.OID_NIVE_SEGM		  
			   )
		     GROUP BY OID_REGI,
			 	   OID_ZONA,
				   OID_PERI
		) DATOS_AAAA,
		(
		SELECT GEN_PAIS.VAL_I18N PAIS,
			   REG.OID_REGI,
			   REG.DES_REGI,
			   ZONA.OID_ZONA,
			   ZONA.DES_ZONA,
			   PC.VAL_ANIO,
			   PC.COD_PERI,
			   PERI.OID_PERI,
			   PERI.VAL_NOMB_PERI
		FROM CRA_PERIO PERI,
			 ZON_ZONA ZONA,
			 ZON_REGIO REG,
			 (
			 SELECT PER_COR.OID_PERI,
			 		PER_COR.COD_PERI,
					PER_COR.VAL_ANIO
			 FROM SEG_PERIO_CORPO PER_COR
			 WHERE PER_COR.VAL_ANIO = (
		   							 SELECT PER_COR.VAL_ANIO
									 FROM SEG_PERIO_CORPO PER_COR,
									 	  CRA_PERIO PERI 
									 WHERE PERI.OID_PERI = 1379	  				   			 	-- PARAMETRO DE PERIODO DESDE --
									 	   AND PERI.PERI_OID_PERI = PER_COR.OID_PERI								    	  
									 )
			) PC,
			(
			SELECT GEN.VAL_OID, GEN.VAL_I18N
			FROM V_GEN_I18N_SICC GEN
			WHERE GEN.ATTR_ENTI = 'SEG_PAIS'
				  AND GEN.IDIO_OID_IDIO = 1	   					  		  -- PARAMETRO DE PAIS  --
			) GEN_PAIS
		WHERE PERI.PERI_OID_PERI = PC.OID_PERI 
			  AND GEN_PAIS.VAL_OID(+) = PERI.PAIS_OID_PAIS
			  AND PERI.MARC_OID_MARC = 1			   					  -- PARAMETRO DE MARCA --
			  AND PERI.CANA_OID_CANA = 1								  -- PARAMETRO DE CANAL --
			  AND PERI.PAIS_OID_PAIS = 1								  -- PARAMETRO DE PAIS -- 
			  AND ZONA.ZORG_OID_REGI = REG.OID_REGI
		      AND ZONA.OID_ZONA = 1	   			-- PARAMETRO DE ZONA --
		      AND REG.OID_REGI = 7				-- PARAMETRO DE REGION --
		) V_AAAA
		WHERE DATOS_AAAA.OID_PERI(+) = V_AAAA.OID_PERI
			  AND DATOS_AAAA.OID_REGI(+) = V_AAAA.OID_REGI
			  AND DATOS_AAAA.OID_ZONA(+) = V_AAAA.OID_ZONA
	) DATOS_AAAA,
	---------------------------------------------------------------------------------------------------------------
	(
		SELECT V_AA.OID_REGI,
			   V_AA.OID_ZONA,
			   SUBSTR(V_AA.COD_PERI,5,2) COD_PERI,
			   NVL(DATOS_AA.PMNP_NUEVAS, 0) PMNP_NUEVAS,
			   NVL(DATOS_AA.PMNP_NIVELI, 0) PMNP_NIVELI,
			   NVL(DATOS_AA.PMNP_NIVELII, 0) PMNP_NIVELII,
			   NVL(DATOS_AA.PMNP_NIVELIII, 0) PMNP_NIVELIII,
			   NVL(DATOS_AA.PMNP_NIVELIV, 0) PMNP_NIVELIV
		FROM
		(
			SELECT OID_REGI,
				   OID_ZONA,
				   COD_PERI,
				   SUM(NVL(PMNP_NUEVAS, 0)) PMNP_NUEVAS,
				   SUM(NVL(PMNP_NIVELI, 0)) PMNP_NIVELI,
				   SUM(NVL(PMNP_NIVELII, 0)) PMNP_NIVELII,
		  		   SUM(NVL(PMNP_NIVELIII, 0)) PMNP_NIVELIII,
				   SUM(NVL(PMNP_NIVELIV, 0)) PMNP_NIVELIV		   		   		    
			FROM
				(
				SELECT REG.OID_REGI,
					   ZONA.OID_ZONA,
					   PC.COD_PERI,
					   decode(NIVEL.OID_NIVE_SEGM,1,avg(SEG_CLI.VAL_VENT),0)as PMNP_NUEVAS,
					   decode(NIVEL.OID_NIVE_SEGM,2,avg(SEG_CLI.VAL_VENT),0)as PMNP_NIVELI,
					   decode(NIVEL.OID_NIVE_SEGM,3,avg(SEG_CLI.VAL_VENT),0)as PMNP_NIVELII,
					   decode(NIVEL.OID_NIVE_SEGM,4,avg(SEG_CLI.VAL_VENT),0)as PMNP_NIVELIII,
					   decode(NIVEL.OID_NIVE_SEGM,5,avg(SEG_CLI.VAL_VENT),0)as PMNP_NIVELIV
				FROM CRA_PERIO PERI,
					 ZON_ZONA ZONA,
					 ZON_REGIO REG,
					 DTR_SEGME_CLIEN SEG_CLI,
					 DTR_NIVEL_SEGME NIVEL,
					 (
					 SELECT PER_COR.OID_PERI,
					 		PER_COR.COD_PERI
					 FROM SEG_PERIO_CORPO PER_COR
					 WHERE PER_COR.VAL_ANIO = (
				   							 SELECT PER_COR.VAL_ANIO
											 FROM SEG_PERIO_CORPO PER_COR,
											 	  CRA_PERIO PERI 
											 WHERE PERI.OID_PERI = 1379	  				   			 	-- PARAMETRO DE PERIODO DESDE --
											 	   AND PERI.PERI_OID_PERI = PER_COR.OID_PERI								    	  
											 ) - 1 
					) PC
				WHERE PERI.PERI_OID_PERI = PC.OID_PERI
					  AND SEG_CLI.PERD_OID_PERI = PERI.OID_PERI
					  AND SEG_CLI.ZZON_OID_ZONA = ZONA.OID_ZONA
					  AND SEG_CLI.ZORG_OID_REGI = REG.OID_REGI
					  AND SEG_CLI.NVSG_OID_NIVE_SEGM = NIVEL.OID_NIVE_SEGM
					  AND (NIVEL.OID_NIVE_SEGM = 1 OR NIVEL.OID_NIVE_SEGM = 2 OR NIVEL.OID_NIVE_SEGM = 3 OR NIVEL.OID_NIVE_SEGM = 4 OR NIVEL.OID_NIVE_SEGM = 5)
					  AND PERI.MARC_OID_MARC = 1			   					  -- PARAMETRO DE MARCA --
					  AND PERI.CANA_OID_CANA = 1								  -- PARAMETRO DE CANAL --
					  AND PERI.PAIS_OID_PAIS = 1								  -- PARAMETRO DE PAIS -- 
					  AND ZONA.ZORG_OID_REGI = REG.OID_REGI
				      AND ZONA.OID_ZONA = 1	   			-- PARAMETRO DE ZONA --
				      AND REG.OID_REGI = 7				-- PARAMETRO DE REGION --
			    GROUP BY REG.OID_REGI,
						 ZONA.OID_ZONA,
						 PC.COD_PERI,
			  			 NIVEL.OID_NIVE_SEGM		  
			   )
		     GROUP BY OID_REGI,
			 	   OID_ZONA,
				   COD_PERI
		) DATOS_AA,
		(
		SELECT REG.OID_REGI,
			   ZONA.OID_ZONA,
			   PC.COD_PERI
		FROM CRA_PERIO PERI,
			 ZON_ZONA ZONA,
			 ZON_REGIO REG,
			 (
			 SELECT PER_COR.OID_PERI,
			 		PER_COR.COD_PERI
			 FROM SEG_PERIO_CORPO PER_COR
			 WHERE PER_COR.VAL_ANIO = (
		   							 SELECT PER_COR.VAL_ANIO
									 FROM SEG_PERIO_CORPO PER_COR,
									 	  CRA_PERIO PERI 
									 WHERE PERI.OID_PERI = 1379	  				   			 	-- PARAMETRO DE PERIODO DESDE --
									 	   AND PERI.PERI_OID_PERI = PER_COR.OID_PERI								    	  
									 ) - 1 
			) PC
		WHERE PERI.PERI_OID_PERI = PC.OID_PERI 
			  AND PERI.MARC_OID_MARC = 1			   					  -- PARAMETRO DE MARCA --
			  AND PERI.CANA_OID_CANA = 1								  -- PARAMETRO DE CANAL --
			  AND PERI.PAIS_OID_PAIS = 1								  -- PARAMETRO DE PAIS -- 
			  AND ZONA.ZORG_OID_REGI = REG.OID_REGI
		      AND ZONA.OID_ZONA = 1	   			-- PARAMETRO DE ZONA --
		      AND REG.OID_REGI = 7				-- PARAMETRO DE REGION --
		) V_AA
		WHERE DATOS_AA.COD_PERI(+) = V_AA.COD_PERI
			  AND DATOS_AA.OID_REGI(+) = V_AA.OID_REGI
			  AND DATOS_AA.OID_ZONA(+) = V_AA.OID_ZONA
	) DATOS_AA
	WHERE DATOS_AAAA.COD_PERI = DATOS_AA.COD_PERI(+)
		  AND DATOS_AAAA.OID_REGI = DATOS_AA.OID_REGI(+)
		  AND DATOS_AAAA.OID_ZONA = DATOS_AA.OID_ZONA(+)
	)		  
ORDER BY DES_REGI,
	  	 DES_ZONA,
		 GRUPO,
		 VAL_NOMB_PERI
	  
		  
	  
	  
 

 