



SELECT *
FROM
	(
	 	SELECT PRO.STRINGVALUE SOCIEDAD_DEFECTO
		FROM PRINCIPALS PRI,
			PROPERTYVALUES PRO			
		WHERE PRI.NAME = 'USUARIO1'			   	  	 -- PARAMETRO DE USUARIO POR DEFECTO --
			 AND PRO.IDPROPERTY = 48
			 AND PRO.IDPRINCIPAL = PRI.IDPRINCIPAL
	),
(
SELECT REGION,
	   ZONA,
	   CASE WHEN (RANK_ZONA <= 10) THEN
	   		1
	   ELSE
	   		2			
	   END GRUPO_RANK,
	   RANK_ZONA,
	   RANK_REGION,
	   COD_CLIE,
	   NOMBRE,
	   VENTA
FROM
(
	SELECT REGION,
		   ZONA,
		   sum(1) OVER (PARTITION BY region,zona ORDER BY venta desc RANGE UNBOUNDED PRECEDING) RANK_ZONA,
	       OWN_PERU.FN_011_CALC_RANK_POR_REGION(PAIS_OID_PAIS, MARC_OID_MARC, CANA_OID_CANA, OID_REGI, 61, 61, CLIE_OID_CLIE) RANK_REGION, -- PARAMETRO DE PERIODO DESDE Y PARAMETRO DE PERIODO HASTA --	   
		   COD_CLIE,
		   NOMBRE,
		   VENTA
	FROM
	(
		SELECT PERI.PAIS_OID_PAIS,
			   PERI.MARC_OID_MARC,
			   PERI.CANA_OID_CANA,
			   REG.DES_REGI REGION,
			   REG.OID_REGI, 
			   ZONA.DES_ZONA ZONA,	
		       SEG_CLI.CLIE_OID_CLIE,
			   CLI.COD_CLIE,
			   SUBSTR(CLI.VAL_APE1||' '||CLI.VAL_APE2||' '||CLI.VAL_NOM1||' '||CLI.VAL_NOM2, 0, 40) NOMBRE,
			   SUM(SEG_CLI.VAL_VENT) VENTA
		FROM DTR_SEGME_CLIEN SEG_CLI,
			 CRA_PERIO PERI,
			 ZON_REGIO REG,
		 	 MAE_CLIEN CLI,
			 ZON_ZONA ZONA,
			 (
			 SELECT FEC_INIC
			 FROM CRA_PERIO
			 WHERE OID_PERI = 61	 				-- PARAMETRO DE PERIODO DESDE --
			 ) FI,
			 (
			 SELECT FEC_FINA
			 FROM CRA_PERIO
			 WHERE OID_PERI = 61					-- PARAMETRO DE PERIODO HASTA --
			 ) FF	
		WHERE FI.FEC_INIC <= PERI.FEC_INIC
			  AND FF.FEC_FINA >= PERI.FEC_FINA
			  AND SEG_CLI.PERD_OID_PERI = PERI.OID_PERI
		 	  AND CLI.OID_CLIE = SEG_CLI.CLIE_OID_CLIE
			  AND SEG_CLI.ZORG_OID_REGI = REG.OID_REGI
			  AND SEG_CLI.ZZON_OID_ZONA = ZONA.OID_ZONA
			  AND REG.OID_REGI = ZONA.ZORG_OID_REGI
			  AND REG.OID_REGI = 7				   	   			 -- PARAMETRO DE REGION --
			  AND ZONA.OID_ZONA = 1								 -- PARAMETRO DE ZONA --
			  AND PERI.PAIS_OID_PAIS = 1  			   			 -- PARAMETRO DE PAIS --
			  AND PERI.CANA_OID_CANA = 1						 -- PARAMETRO DE CANAL --
			  AND PERI.MARC_OID_MARC = 1						 -- PARAMETRO DE MARCA --
		GROUP BY PERI.PAIS_OID_PAIS,
			     PERI.MARC_OID_MARC,
			     PERI.CANA_OID_CANA,
			     REG.OID_REGI,
			  	 REG.DES_REGI,
			  	 ZONA.DES_ZONA,
				 SEG_CLI.CLIE_OID_CLIE,
		         CLI.COD_CLIE,
				 SUBSTR(CLI.VAL_APE1||' '||CLI.VAL_APE2||' '||CLI.VAL_NOM1||' '||CLI.VAL_NOM2, 0, 40)		  
		ORDER BY VENTA DESC
	)
)
)
