





SELECT *
FROM
(
 	SELECT PRO.STRINGVALUE SOCIEDAD_DEFECTO
	FROM PRINCIPALS PRI,
		PROPERTYVALUES PRO			
	WHERE PRI.NAME = 'USUARIO1'			   	  	 -- PARAMETRO DE USUARIO POR DEFECTO --
		 AND PRO.IDPROPERTY = 48
		 AND PRO.IDPRINCIPAL = PRI.IDPRINCIPAL
),
(
SELECT DATOS_AAAA.PAIS,
	   DATOS_AAAA.DES_REGI,
	   DATOS_AAAA.DES_ZONA,
	   DATOS_AAAA.VAL_ANIO AAAA,
	   DATOS_AAAA.VAL_NOMB_PERI,
	   TRUNC(((DATOS_AAAA.COD_PERI) - 1)/6) +1 GRUPO,
-------------------------- NUEVAS -------------------------------------
	   DATOS_AA.VTA_NUEVAS VTA_NUEVAS_AA,
	   DATOS_AAAA.VTA_NUEVAS VTA_NUEVAS_AAAA,	   
	   CASE WHEN (DATOS_AAAA.VTA_NUEVAS IS NOT NULL) THEN
	   	   ROUND(DECODE(DATOS_AA.VTA_NUEVAS, 0, 0, ((DATOS_AAAA.VTA_NUEVAS/DATOS_AA.VTA_NUEVAS)-1)*100))
	   END PORC_VTA_NUEVAS,
-------------------------- NIVEL I -------------------------------------
	   DATOS_AA.VTA_NIVELI VTA_NIVELI_AA,
	   DATOS_AAAA.VTA_NIVELI VTA_NIVELI_AAAA,	   
	   CASE WHEN (DATOS_AAAA.VTA_NIVELI IS NOT NULL) THEN
	   	   ROUND(DECODE(DATOS_AA.VTA_NIVELI, 0, 0, ((DATOS_AAAA.VTA_NIVELI/DATOS_AA.VTA_NIVELI)-1)*100))
	   END PORC_VTA_NIVELI,
-------------------------- NIVEL II-------------------------------------
	   DATOS_AA.VTA_NIVELII VTA_NIVELII_AA,
	   DATOS_AAAA.VTA_NIVELII VTA_NIVELII_AAAA,	   
	   CASE WHEN (DATOS_AAAA.VTA_NIVELII IS NOT NULL) THEN
	   	   ROUND(DECODE(DATOS_AA.VTA_NIVELII, 0, 0, ((DATOS_AAAA.VTA_NIVELII/DATOS_AA.VTA_NIVELII)-1)*100))
	   END PORC_VTA_NIVELII,
-------------------------- NIVEL III -----------------------------------
	   DATOS_AA.VTA_NIVELIII VTA_NIVELIII_AA,
	   DATOS_AAAA.VTA_NIVELIII VTA_NIVELIII_AAAA,	   
	   CASE WHEN (DATOS_AAAA.VTA_NIVELIII IS NOT NULL) THEN
	   	   ROUND(DECODE(DATOS_AA.VTA_NIVELIII, 0, 0, ((DATOS_AAAA.VTA_NIVELIII/DATOS_AA.VTA_NIVELIII)-1)*100))
	   END PORC_VTA_NIVELIII,
-------------------------- NIVEL IV -------------------------------------
	   DATOS_AA.VTA_NIVELIV VTA_NIVELIV_AA,
	   DATOS_AAAA.VTA_NIVELIV VTA_NIVELIV_AAAA,	   
	   CASE WHEN (DATOS_AAAA.VTA_NIVELIV IS NOT NULL) THEN
	   	   ROUND(DECODE(DATOS_AA.VTA_NIVELIV, 0, 0, ((DATOS_AAAA.VTA_NIVELIV/DATOS_AA.VTA_NIVELIV)-1)*100))
	   END PORC_VTA_NIVELIV,	
-------------------------- TOTALES --------------------------------------
   	   DATOS_AA.VTA_NUEVAS + DATOS_AA.VTA_NIVELI + DATOS_AA.VTA_NIVELII + DATOS_AA.VTA_NIVELIII + DATOS_AA.VTA_NIVELIV TOTAL_AA,
   	   DATOS_AAAA.VTA_NUEVAS + DATOS_AAAA.VTA_NIVELI + DATOS_AAAA.VTA_NIVELII + DATOS_AAAA.VTA_NIVELIII + DATOS_AAAA.VTA_NIVELIV TOTAL_AAAA,	   	       
   	   CASE WHEN (DATOS_AAAA.VTA_NUEVAS IS NOT NULL) THEN
	   	   ROUND(DECODE((DATOS_AA.VTA_NUEVAS + DATOS_AA.VTA_NIVELI + DATOS_AA.VTA_NIVELII + DATOS_AA.VTA_NIVELIII + DATOS_AA.VTA_NIVELIV), 0, 0, (((DATOS_AAAA.VTA_NUEVAS + DATOS_AAAA.VTA_NIVELI + DATOS_AAAA.VTA_NIVELII + DATOS_AAAA.VTA_NIVELIII + DATOS_AAAA.VTA_NIVELIV)/(DATOS_AA.VTA_NUEVAS + DATOS_AA.VTA_NIVELI + DATOS_AA.VTA_NIVELII + DATOS_AA.VTA_NIVELIII + DATOS_AA.VTA_NIVELIV))-1)*100))
	   END PORC_TOTALES,
	   CASE WHEN (DATOS_AAAA.VTA_NUEVAS IS NOT NULL) THEN
	   		1
	   END IND_PARA_TOTAL_CAMPANIA_FIN
FROM
(
	SELECT V_AAAA.PAIS,
		   V_AAAA.OID_REGI,
		   V_AAAA.DES_REGI,
		   V_AAAA.OID_ZONA,
		   V_AAAA.DES_ZONA,
		   V_AAAA.VAL_ANIO,
		   SUBSTR(V_AAAA.COD_PERI,5,2) COD_PERI,
		   V_AAAA.VAL_NOMB_PERI,
		   DATOS_AAAA.VTA_NUEVAS,
		   DATOS_AAAA.VTA_NIVELI,
		   DATOS_AAAA.VTA_NIVELII,
		   DATOS_AAAA.VTA_NIVELIII,
		   DATOS_AAAA.VTA_NIVELIV
	FROM
	(
		SELECT OID_REGI,
			   OID_ZONA,
			   OID_PERI,
			   SUM(NVL(VTA_NUEVAS, 0)) VTA_NUEVAS,
			   SUM(NVL(VTA_NIVELI, 0)) VTA_NIVELI,
			   SUM(NVL(VTA_NIVELII, 0)) VTA_NIVELII,
	  		   SUM(NVL(VTA_NIVELIII, 0)) VTA_NIVELIII,
			   SUM(NVL(VTA_NIVELIV, 0)) VTA_NIVELIV		   		   		    
		FROM
			(
			SELECT REG.OID_REGI,
				   ZONA.OID_ZONA,
				   PERI.OID_PERI,
				   CASE WHEN (NIVEL.OID_NIVE_SEGM = 1) THEN
				   		SUM(NVL(SEG_CLI.VAL_VENT, 0))
				   END VTA_NUEVAS,
				   CASE WHEN (NIVEL.OID_NIVE_SEGM = 2) THEN
				   		SUM(NVL(SEG_CLI.VAL_VENT, 0))
				   END VTA_NIVELI,
				   CASE WHEN (NIVEL.OID_NIVE_SEGM = 3) THEN
				   		SUM(NVL(SEG_CLI.VAL_VENT, 0))
				   END VTA_NIVELII,
				   CASE WHEN (NIVEL.OID_NIVE_SEGM = 4) THEN
				   		SUM(NVL(SEG_CLI.VAL_VENT, 0))
				   END VTA_NIVELIII,
				   CASE WHEN (NIVEL.OID_NIVE_SEGM = 5) THEN
				   		SUM(NVL(SEG_CLI.VAL_VENT, 0))
				   END VTA_NIVELIV
			FROM CRA_PERIO PERI,
				 ZON_ZONA ZONA,
				 ZON_REGIO REG,
				 DTR_SEGME_CLIEN SEG_CLI,
				 DTR_NIVEL_SEGME NIVEL,
				 (
				 SELECT FEC_INIC
				 FROM CRA_PERIO 
				 WHERE OID_PERI = 55 				-- PARAMETRO DE PERIODO DESDE -- 
				 ) FI,
				 (
				 SELECT FEC_FINA
				 FROM CRA_PERIO 
				 WHERE OID_PERI = 67               -- PARAMETRO DE PERIDO HASTA --
				 ) FF	 
			WHERE PERI.FEC_INIC >= FI.FEC_INIC
				  AND PERI.FEC_FINA <= FF.FEC_FINA
				  AND ZONA.ZORG_OID_REGI = REG.OID_REGI
				  AND SEG_CLI.PERD_OID_PERI = PERI.OID_PERI
				  AND SEG_CLI.ZZON_OID_ZONA = ZONA.OID_ZONA
				  AND SEG_CLI.ZORG_OID_REGI = REG.OID_REGI
				  AND SEG_CLI.NVSG_OID_NIVE_SEGM = NIVEL.OID_NIVE_SEGM
				  AND (NIVEL.OID_NIVE_SEGM = 1 OR NIVEL.OID_NIVE_SEGM = 2 OR NIVEL.OID_NIVE_SEGM = 3 OR NIVEL.OID_NIVE_SEGM = 4 OR NIVEL.OID_NIVE_SEGM = 5)
				  AND PERI.PAIS_OID_PAIS = 1		-- PARAMETRO DE PAIS --
				  AND PERI.MARC_OID_MARC = 1		-- PARAMETRO DE MARCA --
				  AND PERI.CANA_OID_CANA = 1		-- PARAMETRO DE CANAL --
				  AND ZONA.OID_ZONA = 1	   			-- PARAMETRO DE ZONA --
				  AND REG.OID_REGI = 7				-- PARAMETRO DE REGION --
		   GROUP BY REG.OID_REGI,
				   ZONA.OID_ZONA,
				   PERI.OID_PERI,
	  			   NIVEL.OID_NIVE_SEGM		  
		   )
	     GROUP BY OID_REGI,
		 	   OID_ZONA,
			   OID_PERI
	) DATOS_AAAA,
	(
	SELECT GEN_PAIS.VAL_I18N PAIS,
		   REG.OID_REGI,
		   REG.DES_REGI,
		   ZONA.OID_ZONA,
		   ZONA.DES_ZONA,
		   PC.VAL_ANIO,
		   PC.COD_PERI,
		   PERI.OID_PERI,
		   PERI.VAL_NOMB_PERI
	FROM CRA_PERIO PERI,
		 ZON_ZONA ZONA,
		 ZON_REGIO REG,
		 (
		 SELECT PER_COR.OID_PERI,
		 		PER_COR.COD_PERI,
				PER_COR.VAL_ANIO
		 FROM SEG_PERIO_CORPO PER_COR
		 WHERE PER_COR.VAL_ANIO = (
	   							 SELECT PER_COR.VAL_ANIO
								 FROM SEG_PERIO_CORPO PER_COR,
								 	  CRA_PERIO PERI 
								 WHERE PERI.OID_PERI = 1379	  				   			 	-- PARAMETRO DE PERIODO DESDE --
								 	   AND PERI.PERI_OID_PERI = PER_COR.OID_PERI								    	  
								 )
		) PC,
		(
		SELECT GEN.VAL_OID, GEN.VAL_I18N
		FROM V_GEN_I18N_SICC GEN
		WHERE GEN.ATTR_ENTI = 'SEG_PAIS'
			  AND GEN.IDIO_OID_IDIO = 1	   					  		  -- PARAMETRO DE PAIS  --
		) GEN_PAIS
	WHERE PERI.PERI_OID_PERI = PC.OID_PERI 
		  AND GEN_PAIS.VAL_OID(+) = PERI.PAIS_OID_PAIS
		  AND PERI.MARC_OID_MARC = 1			   					  -- PARAMETRO DE MARCA --
		  AND PERI.CANA_OID_CANA = 1								  -- PARAMETRO DE CANAL --
		  AND PERI.PAIS_OID_PAIS = 1								  -- PARAMETRO DE PAIS -- 
		  AND ZONA.ZORG_OID_REGI = REG.OID_REGI
	      AND ZONA.OID_ZONA = 1	   			-- PARAMETRO DE ZONA --
	      AND REG.OID_REGI = 7				-- PARAMETRO DE REGION --
	) V_AAAA
	WHERE DATOS_AAAA.OID_PERI(+) = V_AAAA.OID_PERI
		  AND DATOS_AAAA.OID_REGI(+) = V_AAAA.OID_REGI
		  AND DATOS_AAAA.OID_ZONA(+) = V_AAAA.OID_ZONA
) DATOS_AAAA,
(
	SELECT V_AA.OID_REGI,
		   V_AA.OID_ZONA,
		   SUBSTR(V_AA.COD_PERI,5,2) COD_PERI,
		   NVL(DATOS_AA.VTA_NUEVAS, 0) VTA_NUEVAS,
		   NVL(DATOS_AA.VTA_NIVELI, 0) VTA_NIVELI,
		   NVL(DATOS_AA.VTA_NIVELII, 0) VTA_NIVELII,
		   NVL(DATOS_AA.VTA_NIVELIII, 0) VTA_NIVELIII,
		   NVL(DATOS_AA.VTA_NIVELIV, 0) VTA_NIVELIV
	FROM
	(
		SELECT OID_REGI,
			   OID_ZONA,
			   COD_PERI,
			   SUM(NVL(VTA_NUEVAS, 0)) VTA_NUEVAS,
			   SUM(NVL(VTA_NIVELI, 0)) VTA_NIVELI,
			   SUM(NVL(VTA_NIVELII, 0)) VTA_NIVELII,
	  		   SUM(NVL(VTA_NIVELIII, 0)) VTA_NIVELIII,
			   SUM(NVL(VTA_NIVELIV, 0)) VTA_NIVELIV		   		   		    
		FROM
			(
			SELECT REG.OID_REGI,
				   ZONA.OID_ZONA,
				   PC.COD_PERI,
				   CASE WHEN (NIVEL.OID_NIVE_SEGM = 1) THEN
				   		SUM(NVL(SEG_CLI.VAL_VENT, 0))
				   END VTA_NUEVAS,
				   CASE WHEN (NIVEL.OID_NIVE_SEGM = 2) THEN
				   		SUM(NVL(SEG_CLI.VAL_VENT, 0))
				   END VTA_NIVELI,
				   CASE WHEN (NIVEL.OID_NIVE_SEGM = 3) THEN
				   		SUM(NVL(SEG_CLI.VAL_VENT, 0))
				   END VTA_NIVELII,
				   CASE WHEN (NIVEL.OID_NIVE_SEGM = 4) THEN
				   		SUM(NVL(SEG_CLI.VAL_VENT, 0))
				   END VTA_NIVELIII,
				   CASE WHEN (NIVEL.OID_NIVE_SEGM = 5) THEN
				   		SUM(NVL(SEG_CLI.VAL_VENT, 0))
				   END VTA_NIVELIV
			FROM CRA_PERIO PERI,
				 ZON_ZONA ZONA,
				 ZON_REGIO REG,
				 DTR_SEGME_CLIEN SEG_CLI,
				 DTR_NIVEL_SEGME NIVEL,
				 (
				 SELECT PER_COR.OID_PERI,
				 		PER_COR.COD_PERI
				 FROM SEG_PERIO_CORPO PER_COR
				 WHERE PER_COR.VAL_ANIO = (
			   							 SELECT PER_COR.VAL_ANIO
										 FROM SEG_PERIO_CORPO PER_COR,
										 	  CRA_PERIO PERI 
										 WHERE PERI.OID_PERI = 1379	  				   			 	-- PARAMETRO DE PERIODO DESDE --
										 	   AND PERI.PERI_OID_PERI = PER_COR.OID_PERI								    	  
										 ) - 1 
				) PC
			WHERE PERI.PERI_OID_PERI = PC.OID_PERI
				  AND SEG_CLI.PERD_OID_PERI = PERI.OID_PERI
				  AND SEG_CLI.ZZON_OID_ZONA = ZONA.OID_ZONA
				  AND SEG_CLI.ZORG_OID_REGI = REG.OID_REGI
				  AND SEG_CLI.NVSG_OID_NIVE_SEGM = NIVEL.OID_NIVE_SEGM
				  AND (NIVEL.OID_NIVE_SEGM = 1 OR NIVEL.OID_NIVE_SEGM = 2 OR NIVEL.OID_NIVE_SEGM = 3 OR NIVEL.OID_NIVE_SEGM = 4 OR NIVEL.OID_NIVE_SEGM = 5)
				  AND PERI.MARC_OID_MARC = 1			   					  -- PARAMETRO DE MARCA --
				  AND PERI.CANA_OID_CANA = 1								  -- PARAMETRO DE CANAL --
				  AND PERI.PAIS_OID_PAIS = 1								  -- PARAMETRO DE PAIS -- 
				  AND ZONA.ZORG_OID_REGI = REG.OID_REGI
			      AND ZONA.OID_ZONA = 1	   			-- PARAMETRO DE ZONA --
			      AND REG.OID_REGI = 7				-- PARAMETRO DE REGION --
		    GROUP BY REG.OID_REGI,
					 ZONA.OID_ZONA,
					 PC.COD_PERI,
		  			 NIVEL.OID_NIVE_SEGM		  
		   )
	     GROUP BY OID_REGI,
		 	   OID_ZONA,
			   COD_PERI
	) DATOS_AA,
	(
	SELECT REG.OID_REGI,
		   ZONA.OID_ZONA,
		   PC.COD_PERI
	FROM CRA_PERIO PERI,
		 ZON_ZONA ZONA,
		 ZON_REGIO REG,
		 (
		 SELECT PER_COR.OID_PERI,
		 		PER_COR.COD_PERI
		 FROM SEG_PERIO_CORPO PER_COR
		 WHERE PER_COR.VAL_ANIO = (
	   							 SELECT PER_COR.VAL_ANIO
								 FROM SEG_PERIO_CORPO PER_COR,
								 	  CRA_PERIO PERI 
								 WHERE PERI.OID_PERI = 1379	  				   			 	-- PARAMETRO DE PERIODO DESDE --
								 	   AND PERI.PERI_OID_PERI = PER_COR.OID_PERI								    	  
								 ) - 1 
		) PC
	WHERE PERI.PERI_OID_PERI = PC.OID_PERI 
		  AND PERI.MARC_OID_MARC = 1			   					  -- PARAMETRO DE MARCA --
		  AND PERI.CANA_OID_CANA = 1								  -- PARAMETRO DE CANAL --
		  AND PERI.PAIS_OID_PAIS = 1								  -- PARAMETRO DE PAIS -- 
		  AND ZONA.ZORG_OID_REGI = REG.OID_REGI
	      AND ZONA.OID_ZONA = 1	   			-- PARAMETRO DE ZONA --
	      AND REG.OID_REGI = 7				-- PARAMETRO DE REGION --
	ORDER BY REG.DES_REGI,
		  	 ZONA.DES_ZONA, 
		  	 PC.COD_PERI
	) V_AA
	WHERE DATOS_AA.COD_PERI(+) = V_AA.COD_PERI
		  AND DATOS_AA.OID_REGI(+) = V_AA.OID_REGI
		  AND DATOS_AA.OID_ZONA(+) = V_AA.OID_ZONA
) DATOS_AA
WHERE DATOS_AAAA.COD_PERI = DATOS_AA.COD_PERI(+)
	  AND DATOS_AAAA.OID_REGI = DATOS_AA.OID_REGI(+)
	  AND DATOS_AAAA.OID_ZONA = DATOS_AA.OID_ZONA(+)
)		  
ORDER BY DES_REGI,
	  	 DES_ZONA,
		 GRUPO,
		 VAL_NOMB_PERI
	  
	  
 

 