SELECT GEN_PAIS.VAL_I18N PAIS, USU.APELLIDOPATERNO||' '||USU.APELLIDOMATERNO||' '||USU.NOMBRE1||' '||USU.NOMBRE2 AGENTE,
	   MAE_CLI.COD_CLIE, MAE_CLI.VAL_APE1||' ' ||MAE_CLI.VAL_APE2||' '||MAE_CLI.VAL_NOM1||' '||MAE_CLI.VAL_NOM2 
	   NOMBRE_CLI, CON.VAL_HORA_INIC FEC_CREACION, TO_CHAR(CON.VAL_HORA_INIC, 'HH24:MI:SS') HORA_CREA,
	   trunc((((86400*(SYSDATE-CON.VAL_HORA_INIC))/60)/60)/24) DIAS_PEND, GEN_CONTA.VAL_I18N MOT_CONTACTO	 
FROM CAL_CONTA CON,
	 CAL_TIPO_ESTAD_CONTA TIP_EST,
	 CAL_ATRIB_ESTAD_CONTA ATR_EST,
	 MAE_CLIEN MAE_CLI,
	 CAL_MOTIV_CONTA MOT_CON,
	 OWN_MARE.V_USU_LARGO USU,
	 (
	 SELECT GEN.VAL_OID, GEN.VAL_I18N
	 FROM V_GEN_I18N_SICC GEN
	 WHERE GEN.ATTR_ENTI = 'SEG_PAIS' 
	 	   AND GEN.IDIO_OID_IDIO = 1        -- PARAMETRO DE IDIOMA --
	 ) GEN_PAIS,
	 (
	 SELECT GEN.VAL_OID, GEN.VAL_I18N
	 FROM V_GEN_I18N_SICC GEN
	 WHERE GEN.ATTR_ENTI = 'CAL_MOTIV_CONTA'
	 	   AND GEN.IDIO_OID_IDIO = 1        -- PARAMETRO DE IDIOMA --
     ) GEN_CONTA
WHERE TIP_EST.OID_TIPO_ESTA_CONT = ATR_EST.TECO_OID_TIPO_ESTA_CONT
	  AND ATR_EST.OID_ATRI_ESTA_CONT = CON.ATEC_OID_ATRI_ESTA_CONT
	  AND GEN_PAIS.VAL_OID = CON.PAIS_OID_PAIS
	  AND MAE_CLI.OID_CLIE = CON.CLIE_OID_CLIE	 
	  AND MAE_CLI.PAIS_OID_PAIS = CON.PAIS_OID_PAIS
	  AND MOT_CON.OID_MOTI_CONT = CON.MOCO_OID_MOTI_CONT
	  AND GEN_CONTA.VAL_OID = MOT_CON.OID_MOTI_CONT
	  AND USU.NOMBREUSUARIO = CON.COD_OPER
	  AND CON.FEC_CONT >= to_date('01/01/2003', 'dd/MM/yyyy')  -- PARAMETRO FECHA DE INICIO --
	  AND CON.FEC_CONT <= to_date('01/01/2009', 'dd/MM/yyyy')  --PARAMETRO FECHA DE FIN --
	  AND MAE_CLI.COD_CLIE = 1          -- PARAMETRO DE CODIGO DE CLIENTE --
	  AND TIP_EST.COD_ESTA <> '03'
	  AND CON.COD_OPER = 'USUARIO1'     -- PARAMETRO DEL AGENTE --      
	  AND CON.PAIS_OID_PAIS = 1         -- PARAMETRO DE PAIS -- 
ORDER BY PAIS,
	  	 AGENTE,
		 FEC_CREACION,
		 MOT_CONTACTO,
		 COD_CLIE