SELECT  GEN_PAIS.VAL_I18N PAIS,CLI.COD_CLIE, CLI.VAL_APE1||' '||CLI.VAL_APE2||' '||CLI.VAL_NOM1||' '||CLI.VAL_NOM2 NOMBRE_COMPLETO, CON.FEC_CONT,
                GEN_MOTIVO.VAL_I18N MOTIVO, USU.VAL_APEL_PATE||' '||USU.VAL_APE_MATE||' '||USU.VAL_NOM1||' '||USU.VAL_NOM2 AGENTE,
	1 as CANTIDAD 
FROM CAL_CONTA CON,
	 MAE_CLIEN CLI,
	 CAL_TIPO_ESTAD_CONTA TIP_EST_CON,
	 CAL_ATRIB_ESTAD_CONTA ATR_EST_CON,   
	 (SELECT GEN.VAL_OID, GEN.VAL_I18N
	  FROM V_GEN_I18N_SICC GEN
	  WHERE GEN.ATTR_ENTI = 'CAL_MOTIV_CONTA'
	  		AND GEN.IDIO_OID_IDIO = 1   --PARAMETRO--
	 ) GEN_MOTIVO,
     (SELECT GEN.VAL_OID, GEN.VAL_I18N
	  FROM V_GEN_I18N_SICC GEN
	  WHERE GEN.ATTR_ENTI = 'SEG_PAIS'
	  		AND GEN.IDIO_OID_IDIO = 1   --PARAMETRO--
	 ) GEN_PAIS,
	 V_REP_USUAR_LARGO USU	 	 	 
WHERE TIP_EST_CON.COD_ESTA <> '03'
	  AND TIP_EST_CON.OID_TIPO_ESTA_CONT = ATR_EST_CON.TECO_OID_TIPO_ESTA_CONT
	  AND ATR_EST_CON.OID_ATRI_ESTA_CONT = CON.ATEC_OID_ATRI_ESTA_CONT
--	  AND CLI.COD_CLIE = 1                       --PARAMETRO OID CLIENTE--
	  AND CLI.OID_CLIE = CON.CLIE_OID_CLIE
--	  AND CON.VAL_HORA_INIC >= to_date('1/1/2003', 'dd/MM/yyyy') --PARAMETRO VAL_FECHA_INICIO--
--	  AND CON.VAL_HORA_FIN <= to_date('31/12/2015', 'dd/MM/yyyy') --PARAMETRO VAL_FECHA_FIN--
	  AND GEN_MOTIVO.VAL_OID(+) = CON.MOCO_OID_MOTI_CONT
	  AND USU.VAL_NOMB_USUA = CON.COD_OPER
      AND CON.PAIS_OID_PAIS = 1 --PARAMETRO--
	  AND CON.PAIS_OID_PAIS = GEN_PAIS.VAL_OID(+)
ORDER BY GEN_PAIS.VAL_I18N,
	  	 CLI.COD_CLIE,
		 CON.FEC_CONT,
		 GEN_MOTIVO.VAL_I18N
		 
		 
