SELECT 
	   C.COD_CLIE, 
	   (C.VAL_APE1 || ' ' || C.VAL_APE2 || ' ' || C.VAL_NOM1 || ' ' || C.VAL_NOM2) AS NOMBRE,
	   C_COM_TEL.VAL_TEXT_COMU AS TELEFONO,
	   C_ESTAT.COD_ESTA_CLIE,  
	   C_COM_MAIL.VAL_TEXT_COMU AS E_MAIL,
	   S_CANAL.COD_CANA,
	   S_MARCA.COD_MARC,
	   PERI.VAL_NOMB_PERI,
	   DECODE(T_BLOQ.COD_TIPO_BLOQ,'02','SI','NO') AS BLOQ_ADMIN, 
	   DECODE(T_BLOQ.COD_TIPO_BLOQ,'02',C_BLOQ.VAL_MOTI_BLOQ,'') AS MOTIV_BLOQ, 
	   C.FEC_INGR,
	   DECODE(T_BLOQ.COD_TIPO_BLOQ,'01','SI','NO') AS BLOQ_FINAN, 
	   CC_M.COD_TIPO_SOLI,
	   CC_M.NUM_IDEN_CUOT,
	   CC_M.VAL_DENO,
	   CC_M.FEC_DOCU,
	   CC_M.FEC_VENC,
	   CC_M.COD_FORM_PAGO,
	   CC_M.IMP_MOVI AS MONTO,
	   (CC_M.IMP_MOVI - CC_M.IMP_PAGA) AS MONTO_SALDO,
	   pq_apl_rep.FN_CU_CALC_SALDO_CTA_CTE(C.OID_CLIE) AS SALDO_ACTUAL,
	   NVL((
		 SELECT COUNT(DISTINCT m.NUM_IDEN_CUOT) AS CANT
		 FROM   CCC_CABEC_DTO_RECAR_FINAN CAB,
		 		CCC_DETAL_DTO_RECAR_FINAN DET,
	 			CCC_MOVIM_CUENT_CORRI M,
				CCC_SUBPR S,
				CCC_PROCE P	
		 WHERE  CAB.SUBP_OID_SUBP = S.OID_SUBP
	 		AND S.CCPR_OID_PROC = P.OID_PROC
			AND S.COD_SUBP = 1 
			AND P.COD_PROC = 'CCC005'
			AND CAB.FEC_DOCU>=(ADD_MONTHS(SYSDATE,-6))
			AND CAB.PAIS_OID_PAIS = 1
			AND DET.CDRF_OID_CABE_DTO_RECA_FINA = CAB.OID_CABE_DTO_RECA_FINA
			AND DET.MVCC_OID_MOVI_CC = M.OID_MOVI_CC
			AND CAB.CLIE_OID_CLIE = C.OID_CLIE
		 GROUP BY CAB.CLIE_OID_CLIE, M.NUM_IDEN_CUOT, M.NUM_ORDE_CUOT
	   ),0) AS N_VECES_PRONTO_PAGO,	   
	   NVL((
		 SELECT COUNT(DISTINCT m.NUM_IDEN_CUOT) AS CANT
		 FROM   CCC_CABEC_DTO_RECAR_FINAN CAB,
		 		CCC_DETAL_DTO_RECAR_FINAN DET,
	 			CCC_MOVIM_CUENT_CORRI M,
				CCC_SUBPR S,
				CCC_PROCE P	
		 WHERE  CAB.SUBP_OID_SUBP = S.OID_SUBP
	 		AND S.CCPR_OID_PROC = P.OID_PROC
			AND S.COD_SUBP = 2 
			AND P.COD_PROC = 'CCC005'
			AND CAB.FEC_DOCU>=(ADD_MONTHS(SYSDATE,-6))
			AND CAB.PAIS_OID_PAIS = 1
			AND DET.CDRF_OID_CABE_DTO_RECA_FINA = CAB.OID_CABE_DTO_RECA_FINA
			AND DET.MVCC_OID_MOVI_CC = M.OID_MOVI_CC
			AND CAB.CLIE_OID_CLIE = C.OID_CLIE
		 GROUP BY CAB.CLIE_OID_CLIE, M.NUM_IDEN_CUOT, M.NUM_ORDE_CUOT
	   ),0) AS N_VECES_REC_FINANC,
	   pq_apl_rep.FN_CU_CALC_DIAS_ATRASO_CLIEN(C.PAIS_OID_PAIS, C.OID_CLIE) AS PROM_DIAS_MORA,
	   pq_apl_rep.FN_CU_CALC_DEUDA_VENC_CLIEN(C.PAIS_OID_PAIS, C.OID_CLIE) AS VAL_TOT_MORA,
	   DECODE(pq_apl_rep.FN_CU_CALC_SALDO_CTA_CTE(C.OID_CLIE),0,0,(pq_apl_rep.FN_CU_CALC_DEUDA_VENC_CLIEN(C.PAIS_OID_PAIS,C.OID_CLIE)/pq_apl_rep.FN_CU_CALC_SALDO_CTA_CTE(C.OID_CLIE))*100) AS PORC_MORA_RESP_FACT,
	   (CASE WHEN
	   		  (
	   		   SELECT NVL(SUM(ASIGN.IMP_DEUD_ASIG) - SUM(ASIGN.IMP_DEUD_CANC),0)
			   FROM COB_ASIGN_COBRA ASIGN,
	 		   		ccc_movim_cuent_corri movi
			   WHERE asign.MVCC_OID_MOVI_CC = movi.OID_MOVI_CC 
			   		 AND movi.clie_oid_clie = C.OID_CLIE 
	   		  )>0 THEN 'SI' ELSE 'NO'
		END
	   ) AS EN_COBRANZA,
	   (
		SELECT CODIGO 
		FROM		   
			(
			SELECT 
				   ROWNUM AS R, DATOS.CODIGO, DATOS.VECES 	   
			FROM
			 	   (
				   	SELECT etapa.COD_ETAP_DEUD AS CODIGO, COUNT(etapa.OID_ETAP_DEUD) AS  VECES
				   	FROM COB_ASIGN_COBRA ASIGN, ccc_movim_cuent_corri movi, COB_CRONO_COBRA crono_cobra, COB_ETAPA_DEUDA ETAPA, MAE_CLIEN MCLIE
				    WHERE ASIGN.CRCO_OID_CRON_COBR = crono_cobra.OID_CRON_COBR AND asign.MVCC_OID_MOVI_CC = movi.OID_MOVI_CC AND crono_cobra.ETDE_OID_ETAP_DEUD = etapa.OID_ETAP_DEUD AND MCLIE.OID_CLIE = movi.CLIE_OID_CLIE
					AND MCLIE.PAIS_OID_PAIS = 1 AND MCLIE.COD_CLIE = '00000000183' 
					GROUP BY etapa.COD_ETAP_DEUD ORDER BY ETAPA.COD_ETAP_DEUD
					) DATOS
			WHERE
				 	ROWNUM<=8
			)
		WHERE R=1
	   ) AS ETAPA_1,
	   ( 
		SELECT VECES 
		FROM		   
			(
			SELECT 
				   ROWNUM AS R, DATOS.CODIGO, DATOS.VECES 	   
			FROM
			 	   (
				   	SELECT etapa.COD_ETAP_DEUD AS CODIGO, COUNT(etapa.OID_ETAP_DEUD) AS  VECES
				   	FROM COB_ASIGN_COBRA ASIGN, ccc_movim_cuent_corri movi, COB_CRONO_COBRA crono_cobra, COB_ETAPA_DEUDA ETAPA, MAE_CLIEN MCLIE
				    WHERE ASIGN.CRCO_OID_CRON_COBR = crono_cobra.OID_CRON_COBR AND asign.MVCC_OID_MOVI_CC = movi.OID_MOVI_CC AND crono_cobra.ETDE_OID_ETAP_DEUD = etapa.OID_ETAP_DEUD AND MCLIE.OID_CLIE = MOVI.CLIE_OID_CLIE
					AND MCLIE.PAIS_OID_PAIS = 1 AND MCLIE.COD_CLIE = '00000000183' 
					GROUP BY etapa.COD_ETAP_DEUD ORDER BY ETAPA.COD_ETAP_DEUD
					) DATOS
			WHERE
				 	ROWNUM<=8
			)
		WHERE R=1
	   ) AS N_VECES_ETAPA_1,
	   (
		SELECT CODIGO 
		FROM		   
			(
			SELECT 
				   ROWNUM AS R, DATOS.CODIGO, DATOS.VECES 	   
			FROM
			 	   (
				   	SELECT etapa.COD_ETAP_DEUD AS CODIGO, COUNT(etapa.OID_ETAP_DEUD) AS  VECES
				   	FROM COB_ASIGN_COBRA ASIGN, ccc_movim_cuent_corri movi, COB_CRONO_COBRA crono_cobra, COB_ETAPA_DEUDA ETAPA, MAE_CLIEN MCLIE
				    WHERE ASIGN.CRCO_OID_CRON_COBR = crono_cobra.OID_CRON_COBR AND asign.MVCC_OID_MOVI_CC = movi.OID_MOVI_CC AND crono_cobra.ETDE_OID_ETAP_DEUD = etapa.OID_ETAP_DEUD AND MCLIE.OID_CLIE = MOVI.CLIE_OID_CLIE
					AND MCLIE.PAIS_OID_PAIS = 1 AND MCLIE.COD_CLIE = '00000000183' 
					GROUP BY etapa.COD_ETAP_DEUD ORDER BY ETAPA.COD_ETAP_DEUD
					) DATOS
			WHERE
				 	ROWNUM<=8
			)
		WHERE R=2
	   ) AS ETAPA_2,
	   ( 
		SELECT VECES 
		FROM		   
			(
			SELECT 
				   ROWNUM AS R, DATOS.CODIGO, DATOS.VECES 	   
			FROM
			 	   (
				   	SELECT etapa.COD_ETAP_DEUD AS CODIGO, COUNT(etapa.OID_ETAP_DEUD) AS  VECES
				   	FROM COB_ASIGN_COBRA ASIGN, ccc_movim_cuent_corri movi, COB_CRONO_COBRA crono_cobra, COB_ETAPA_DEUDA ETAPA, MAE_CLIEN MCLIE
				    WHERE ASIGN.CRCO_OID_CRON_COBR = crono_cobra.OID_CRON_COBR AND asign.MVCC_OID_MOVI_CC = movi.OID_MOVI_CC AND crono_cobra.ETDE_OID_ETAP_DEUD = etapa.OID_ETAP_DEUD AND MCLIE.OID_CLIE = MOVI.CLIE_OID_CLIE
					AND MCLIE.PAIS_OID_PAIS = 1 AND MCLIE.COD_CLIE = '00000000183' 
					GROUP BY etapa.COD_ETAP_DEUD ORDER BY ETAPA.COD_ETAP_DEUD
					) DATOS
			WHERE
				 	ROWNUM<=8
			)
		WHERE R=2
	   ) AS N_VECES_ETAPA_2,
	   (
		SELECT CODIGO 
		FROM		   
			(
			SELECT 
				   ROWNUM AS R, DATOS.CODIGO, DATOS.VECES 	   
			FROM
			 	   (
				   	SELECT etapa.COD_ETAP_DEUD AS CODIGO, COUNT(etapa.OID_ETAP_DEUD) AS  VECES
				   	FROM COB_ASIGN_COBRA ASIGN, ccc_movim_cuent_corri movi, COB_CRONO_COBRA crono_cobra, COB_ETAPA_DEUDA ETAPA, MAE_CLIEN MCLIE
				    WHERE ASIGN.CRCO_OID_CRON_COBR = crono_cobra.OID_CRON_COBR AND asign.MVCC_OID_MOVI_CC = movi.OID_MOVI_CC AND crono_cobra.ETDE_OID_ETAP_DEUD = etapa.OID_ETAP_DEUD AND MCLIE.OID_CLIE = MOVI.CLIE_OID_CLIE
					AND MCLIE.PAIS_OID_PAIS = 1 AND MCLIE.COD_CLIE = '00000000183' 
					GROUP BY etapa.COD_ETAP_DEUD ORDER BY ETAPA.COD_ETAP_DEUD
					) DATOS
			WHERE
				 	ROWNUM<=8
			)
		WHERE R=3
	   ) AS ETAPA_3,
	   ( 
		SELECT VECES 
		FROM		   
			(
			SELECT 
				   ROWNUM AS R, DATOS.CODIGO, DATOS.VECES 	   
			FROM
			 	   (
				   	SELECT etapa.COD_ETAP_DEUD AS CODIGO, COUNT(etapa.OID_ETAP_DEUD) AS  VECES
				   	FROM COB_ASIGN_COBRA ASIGN, ccc_movim_cuent_corri movi, COB_CRONO_COBRA crono_cobra, COB_ETAPA_DEUDA ETAPA, MAE_CLIEN MCLIE
				    WHERE ASIGN.CRCO_OID_CRON_COBR = crono_cobra.OID_CRON_COBR AND asign.MVCC_OID_MOVI_CC = movi.OID_MOVI_CC AND crono_cobra.ETDE_OID_ETAP_DEUD = etapa.OID_ETAP_DEUD AND MCLIE.OID_CLIE = MOVI.CLIE_OID_CLIE
					AND MCLIE.PAIS_OID_PAIS = 1 AND MCLIE.COD_CLIE = '00000000183' 
					GROUP BY etapa.COD_ETAP_DEUD ORDER BY ETAPA.COD_ETAP_DEUD
					) DATOS
			WHERE
				 	ROWNUM<=8
			)
		WHERE R=3
	   ) AS N_VECES_ETAPA_3,
	   (
		SELECT CODIGO 
		FROM		   
			(
			SELECT 
				   ROWNUM AS R, DATOS.CODIGO, DATOS.VECES 	   
			FROM
			 	   (
				   	SELECT etapa.COD_ETAP_DEUD AS CODIGO, COUNT(etapa.OID_ETAP_DEUD) AS  VECES
				   	FROM COB_ASIGN_COBRA ASIGN, ccc_movim_cuent_corri movi, COB_CRONO_COBRA crono_cobra, COB_ETAPA_DEUDA ETAPA, MAE_CLIEN MCLIE
				    WHERE ASIGN.CRCO_OID_CRON_COBR = crono_cobra.OID_CRON_COBR AND asign.MVCC_OID_MOVI_CC = movi.OID_MOVI_CC AND crono_cobra.ETDE_OID_ETAP_DEUD = etapa.OID_ETAP_DEUD AND MCLIE.OID_CLIE = MOVI.CLIE_OID_CLIE
					AND MCLIE.PAIS_OID_PAIS = 1 AND MCLIE.COD_CLIE = '00000000183' 
					GROUP BY etapa.COD_ETAP_DEUD ORDER BY ETAPA.COD_ETAP_DEUD
					) DATOS
			WHERE
				 	ROWNUM<=8
			)
		WHERE R=4
	   ) AS ETAPA_4,
	   ( 
		SELECT VECES 
		FROM		   
			(
			SELECT 
				   ROWNUM AS R, DATOS.CODIGO, DATOS.VECES 	   
			FROM
			 	   (
				   	SELECT etapa.COD_ETAP_DEUD AS CODIGO, COUNT(etapa.OID_ETAP_DEUD) AS  VECES
				   	FROM COB_ASIGN_COBRA ASIGN, ccc_movim_cuent_corri movi, COB_CRONO_COBRA crono_cobra, COB_ETAPA_DEUDA ETAPA, MAE_CLIEN MCLIE
				    WHERE ASIGN.CRCO_OID_CRON_COBR = crono_cobra.OID_CRON_COBR AND asign.MVCC_OID_MOVI_CC = movi.OID_MOVI_CC AND crono_cobra.ETDE_OID_ETAP_DEUD = etapa.OID_ETAP_DEUD AND MCLIE.OID_CLIE = MOVI.CLIE_OID_CLIE
					AND MCLIE.PAIS_OID_PAIS = 1 AND MCLIE.COD_CLIE = '00000000183' 
					GROUP BY etapa.COD_ETAP_DEUD ORDER BY ETAPA.COD_ETAP_DEUD
					) DATOS
			WHERE
				 	ROWNUM<=8
			)
		WHERE R=4
	   ) AS N_VECES_ETAPA_4,
	   (
		SELECT CODIGO 
		FROM		   
			(
			SELECT 
				   ROWNUM AS R, DATOS.CODIGO, DATOS.VECES 	   
			FROM
			 	   (
				   	SELECT etapa.COD_ETAP_DEUD AS CODIGO, COUNT(etapa.OID_ETAP_DEUD) AS  VECES
				   	FROM COB_ASIGN_COBRA ASIGN, ccc_movim_cuent_corri movi, COB_CRONO_COBRA crono_cobra, COB_ETAPA_DEUDA ETAPA, MAE_CLIEN MCLIE
				    WHERE ASIGN.CRCO_OID_CRON_COBR = crono_cobra.OID_CRON_COBR AND asign.MVCC_OID_MOVI_CC = movi.OID_MOVI_CC AND crono_cobra.ETDE_OID_ETAP_DEUD = etapa.OID_ETAP_DEUD AND MCLIE.OID_CLIE = MOVI.CLIE_OID_CLIE
					AND MCLIE.PAIS_OID_PAIS = 1 AND MCLIE.COD_CLIE = '00000000183' 
					GROUP BY etapa.COD_ETAP_DEUD ORDER BY ETAPA.COD_ETAP_DEUD
					) DATOS
			WHERE
				 	ROWNUM<=8
			)
		WHERE R=5
	   ) AS ETAPA_5,
	   ( 
		SELECT VECES 
		FROM		   
			(
			SELECT 
				   ROWNUM AS R, DATOS.CODIGO, DATOS.VECES 	   
			FROM
			 	   (
				   	SELECT etapa.COD_ETAP_DEUD AS CODIGO, COUNT(etapa.OID_ETAP_DEUD) AS  VECES
				   	FROM COB_ASIGN_COBRA ASIGN, ccc_movim_cuent_corri movi, COB_CRONO_COBRA crono_cobra, COB_ETAPA_DEUDA ETAPA, MAE_CLIEN MCLIE
				    WHERE ASIGN.CRCO_OID_CRON_COBR = crono_cobra.OID_CRON_COBR AND asign.MVCC_OID_MOVI_CC = movi.OID_MOVI_CC AND crono_cobra.ETDE_OID_ETAP_DEUD = etapa.OID_ETAP_DEUD AND MCLIE.OID_CLIE = MOVI.CLIE_OID_CLIE
					AND MCLIE.PAIS_OID_PAIS = 1 AND MCLIE.COD_CLIE = '00000000183' 
					GROUP BY etapa.COD_ETAP_DEUD ORDER BY ETAPA.COD_ETAP_DEUD
					) DATOS
			WHERE
				 	ROWNUM<=8
			)
		WHERE R=5
	   ) AS N_VECES_ETAPA_5,
	   (
		SELECT CODIGO 
		FROM		   
			(
			SELECT 
				   ROWNUM AS R, DATOS.CODIGO, DATOS.VECES 	   
			FROM
			 	   (
				   	SELECT etapa.COD_ETAP_DEUD AS CODIGO, COUNT(etapa.OID_ETAP_DEUD) AS  VECES
				   	FROM COB_ASIGN_COBRA ASIGN, ccc_movim_cuent_corri movi, COB_CRONO_COBRA crono_cobra, COB_ETAPA_DEUDA ETAPA, MAE_CLIEN MCLIE
				    WHERE ASIGN.CRCO_OID_CRON_COBR = crono_cobra.OID_CRON_COBR AND asign.MVCC_OID_MOVI_CC = movi.OID_MOVI_CC AND crono_cobra.ETDE_OID_ETAP_DEUD = etapa.OID_ETAP_DEUD AND MCLIE.OID_CLIE = MOVI.CLIE_OID_CLIE
					AND MCLIE.PAIS_OID_PAIS = 1 AND MCLIE.COD_CLIE = '00000000183' 
					GROUP BY etapa.COD_ETAP_DEUD ORDER BY ETAPA.COD_ETAP_DEUD
					) DATOS
			WHERE
				 	ROWNUM<=8
			)
		WHERE R=6
	   ) AS ETAPA_6,
	   ( 
		SELECT VECES 
		FROM		   
			(
			SELECT 
				   ROWNUM AS R, DATOS.CODIGO, DATOS.VECES 	   
			FROM
			 	   (
				   	SELECT etapa.COD_ETAP_DEUD AS CODIGO, COUNT(etapa.OID_ETAP_DEUD) AS  VECES
				   	FROM COB_ASIGN_COBRA ASIGN, ccc_movim_cuent_corri movi, COB_CRONO_COBRA crono_cobra, COB_ETAPA_DEUDA ETAPA, MAE_CLIEN MCLIE
				    WHERE ASIGN.CRCO_OID_CRON_COBR = crono_cobra.OID_CRON_COBR AND asign.MVCC_OID_MOVI_CC = movi.OID_MOVI_CC AND crono_cobra.ETDE_OID_ETAP_DEUD = etapa.OID_ETAP_DEUD AND MCLIE.OID_CLIE = MOVI.CLIE_OID_CLIE
					AND MCLIE.PAIS_OID_PAIS = 1 AND MCLIE.COD_CLIE = '00000000183' 
					GROUP BY etapa.COD_ETAP_DEUD ORDER BY ETAPA.COD_ETAP_DEUD
					) DATOS
			WHERE
				 	ROWNUM<=8
			)
		WHERE R=6
	   ) AS N_VECES_ETAPA_6,
	   (
		SELECT CODIGO 
		FROM		   
			(
			SELECT 
				   ROWNUM AS R, DATOS.CODIGO, DATOS.VECES 	   
			FROM
			 	   (
				   	SELECT etapa.COD_ETAP_DEUD AS CODIGO, COUNT(etapa.OID_ETAP_DEUD) AS  VECES
				   	FROM COB_ASIGN_COBRA ASIGN, ccc_movim_cuent_corri movi, COB_CRONO_COBRA crono_cobra, COB_ETAPA_DEUDA ETAPA, MAE_CLIEN MCLIE
				    WHERE ASIGN.CRCO_OID_CRON_COBR = crono_cobra.OID_CRON_COBR AND asign.MVCC_OID_MOVI_CC = movi.OID_MOVI_CC AND crono_cobra.ETDE_OID_ETAP_DEUD = etapa.OID_ETAP_DEUD AND MCLIE.OID_CLIE = MOVI.CLIE_OID_CLIE
					AND MCLIE.PAIS_OID_PAIS = 1 AND MCLIE.COD_CLIE = '00000000183' 
					GROUP BY etapa.COD_ETAP_DEUD ORDER BY ETAPA.COD_ETAP_DEUD
					) DATOS
			WHERE
				 	ROWNUM<=8
			)
		WHERE R=7
	   ) AS ETAPA_7,
	   ( 
		SELECT VECES 
		FROM		   
			(
			SELECT 
				   ROWNUM AS R, DATOS.CODIGO, DATOS.VECES 	   
			FROM
			 	   (
				   	SELECT etapa.COD_ETAP_DEUD AS CODIGO, COUNT(etapa.OID_ETAP_DEUD) AS  VECES
				   	FROM COB_ASIGN_COBRA ASIGN, ccc_movim_cuent_corri movi, COB_CRONO_COBRA crono_cobra, COB_ETAPA_DEUDA ETAPA, MAE_CLIEN MCLIE
				    WHERE ASIGN.CRCO_OID_CRON_COBR = crono_cobra.OID_CRON_COBR AND asign.MVCC_OID_MOVI_CC = movi.OID_MOVI_CC AND crono_cobra.ETDE_OID_ETAP_DEUD = etapa.OID_ETAP_DEUD AND MCLIE.OID_CLIE = MOVI.CLIE_OID_CLIE
					AND MCLIE.PAIS_OID_PAIS = 1 AND MCLIE.COD_CLIE = '00000000183' 
					GROUP BY etapa.COD_ETAP_DEUD ORDER BY ETAPA.COD_ETAP_DEUD
					) DATOS
			WHERE
				 	ROWNUM<=8
			)
		WHERE R=7
	   ) AS N_VECES_ETAPA_7,
	   (
		SELECT CODIGO 
		FROM		   
			(
			SELECT 
				   ROWNUM AS R, DATOS.CODIGO, DATOS.VECES 	   
			FROM
			 	   (
				   	SELECT etapa.COD_ETAP_DEUD AS CODIGO, COUNT(etapa.OID_ETAP_DEUD) AS  VECES
				   	FROM COB_ASIGN_COBRA ASIGN, ccc_movim_cuent_corri movi, COB_CRONO_COBRA crono_cobra, COB_ETAPA_DEUDA ETAPA, MAE_CLIEN MCLIE
				    WHERE ASIGN.CRCO_OID_CRON_COBR = crono_cobra.OID_CRON_COBR AND asign.MVCC_OID_MOVI_CC = movi.OID_MOVI_CC AND crono_cobra.ETDE_OID_ETAP_DEUD = etapa.OID_ETAP_DEUD AND MCLIE.OID_CLIE = MOVI.CLIE_OID_CLIE
					AND MCLIE.PAIS_OID_PAIS = 1 AND MCLIE.COD_CLIE = '00000000183' 
					GROUP BY etapa.COD_ETAP_DEUD ORDER BY ETAPA.COD_ETAP_DEUD
					) DATOS
			WHERE
				 	ROWNUM<=8
			)
		WHERE R=8
	   ) AS ETAPA_8,
	   ( 
		SELECT VECES 
		FROM		   
			(
			SELECT 
				   ROWNUM AS R, DATOS.CODIGO, DATOS.VECES 	   
			FROM
			 	   (
				   	SELECT etapa.COD_ETAP_DEUD AS CODIGO, COUNT(etapa.OID_ETAP_DEUD) AS  VECES
				   	FROM COB_ASIGN_COBRA ASIGN, ccc_movim_cuent_corri movi, COB_CRONO_COBRA crono_cobra, COB_ETAPA_DEUDA ETAPA, MAE_CLIEN MCLIE
				    WHERE ASIGN.CRCO_OID_CRON_COBR = crono_cobra.OID_CRON_COBR AND asign.MVCC_OID_MOVI_CC = movi.OID_MOVI_CC AND crono_cobra.ETDE_OID_ETAP_DEUD = etapa.OID_ETAP_DEUD AND MCLIE.OID_CLIE = MOVI.CLIE_OID_CLIE
					AND MCLIE.PAIS_OID_PAIS = 1 AND MCLIE.COD_CLIE = '00000000183' 
					GROUP BY etapa.COD_ETAP_DEUD ORDER BY ETAPA.COD_ETAP_DEUD
					) DATOS
			WHERE
				 	ROWNUM<=8
			)
		WHERE R=8
	   ) AS N_VECES_ETAPA_8,
	   (
	   	SELECT USU.VAL_APEL_PATE || ' ' || USU.VAL_APE_MATE || ' ' || USU.VAL_NOM1 || ' ' || USU.VAL_NOM2
		FROM	CAR_ASIGN_EJECU_CUENT AS_EJ,
				CAR_EJECU_CUENT EJ_CTA,
				V_REP_USUAR_LARGO USU,
				ZON_ZONA ZONA,
				ZON_REGIO REGION,
				ZON_TERRI_ADMIN TERR_ADMIN,
				ZON_SECCI SECCION
	   	WHERE	
				TERR_ADMIN.OID_TERR_ADMI = C_UN.ZTAD_OID_TERR_ADMI 
				AND TERR_ADMIN.ZSCC_OID_SECC = SECCION.OID_SECC
				AND SECCION.ZZON_OID_ZONA = ZONA.OID_ZONA
				AND ZONA.ZORG_OID_REGI = REGION.OID_REGI
				AND AS_EJ.ZZON_OID_ZONA = ZONA.OID_ZONA
				AND AS_EJ.ZORG_OID_REGI = REGION.OID_REGI
				AND AS_EJ.ZSGV_OID_SUBG_VENT = REGION.ZSGV_OID_SUBG_VENT
				AND AS_EJ.EJCU_OID_EJEC_CUEN = EJ_CTA.OID_EJEC_CUEN
				AND EJ_CTA.USER_EJEC_CUEN = USU.COD_USUA
	   ) AS RESP_CRED,
	   NVL(C_ADICI.IMP_MONT_LINE_CRED,0) AS LIN_CRED_ACTUAL,
	   NVL((C_ADICI.IMP_MONT_LINE_CRED - 
	   pq_apl_rep.FN_CU_CALC_MONTO_SOLIC_NUEVAS(C.OID_CLIE) - 
	   pq_apl_rep.FN_CU_CALC_SALDO_CTA_CTE (C.OID_CLIE) +
	   pq_apl_rep.FN_CU_CALC_CUPON_EN_TRAMITE (C.PAIS_OID_PAIS, C.OID_CLIE)
	   ),0) AS LIN_CRED_DISP,
	   (
	   	SELECT PER.VAL_NOMB_PERI
		FROM CRA_PERIO PER
		WHERE PER.OID_PERI = C_ADICI.PERD_OID_PERI_LINE_CRED
	   ) AS PERI_ULT_EVAL_CRED,
	   pq_apl_rep.FN_CU_CALC_PED_PROMEDIO_CLIEN(
	   									   c.oid_clie, 
										   CL_SOLIC.OID_CLAS_SOLI,
										   C_ADICI.PERD_OID_PERI_LINE_CRED,
										   PERI_ACTUAL.OID_PERI
										  ) AS PED_PROM_ULT_EVAL,
	   DECODE(
	   		  NVL((
	   		  C_ADICI.IMP_MONT_LINE_CRED - 
	   		  pq_apl_rep.FN_CU_CALC_MONTO_SOLIC_NUEVAS(C.OID_CLIE) - 
	   		  pq_apl_rep.FN_CU_CALC_SALDO_CTA_CTE (C.OID_CLIE) +
	   		  pq_apl_rep.FN_CU_CALC_CUPON_EN_TRAMITE (C.PAIS_OID_PAIS, C.OID_CLIE)
	   		  ),0),
			  0,
			  0,
	   		  NVL(C_ADICI.IMP_MONT_LINE_CRED,0) /
			  NVL((
	   		  C_ADICI.IMP_MONT_LINE_CRED - 
	   		  pq_apl_rep.FN_CU_CALC_MONTO_SOLIC_NUEVAS(C.OID_CLIE) - 
	   		  pq_apl_rep.FN_CU_CALC_SALDO_CTA_CTE (C.OID_CLIE) +
	   		  pq_apl_rep.FN_CU_CALC_CUPON_EN_TRAMITE (C.PAIS_OID_PAIS, C.OID_CLIE)
	   		  ),0)
	   		  ) AS PORC_LIN_CRED_ACT_CONS,	   
	   RIESGO.COD_NIVE_RIES,
	   (
	   	SELECT PER.VAL_NOMB_PERI
		FROM CRA_PERIO PER
		WHERE PER.OID_PERI = C_ADICI.PERD_OID_PERI_NIVE_RIES
			  AND PER.PAIS_OID_PAIS = PERI.PAIS_OID_PAIS
			  AND PER.MARC_OID_MARC = PERI.MARC_OID_MARC
			  AND PER.CANA_OID_CANA = PERI.CANA_OID_CANA
	   ) AS PERI_ULT_EVAL_RIES,
	   pq_apl_rep.FN_CU_CALC_PERI_CON_PEDIDOS(
	   									 c.oid_clie, 
										 CL_SOLIC.OID_CLAS_SOLI, 
										 DECODE(C_ADICI.PERD_OID_PERI_LINE_CRED,
										 		NULL,  
												(
			   									 SELECT PERI_INGR.OID_PERI
												 FROM  
			   		   								(
					   								 SELECT PERIO.OID_PERI, PERIO.PAIS_OID_PAIS, PERIO.MARC_OID_MARC, PERIO.CANA_OID_CANA,
													 		CLI.OID_CLIE, CLI.FEC_INGR 
					   								 FROM CRA_PERIO PERIO, MAE_CLIEN CLI
													 WHERE PERIO.FEC_INIC >= CLI.FEC_INGR
							  						 	   AND CLI.FEC_INGR <=PERIO.FEC_FINA
							  							   AND VAL_ESTA = 1
													 ORDER BY PERIO.FEC_INIC 
			   										) PERI_INGR
												 WHERE ROWNUM = 1
			   		  							 	   AND PERI.PAIS_OID_PAIS = PERI_INGR.PAIS_OID_PAIS
			   		  								   AND PERI.MARC_OID_MARC = PERI_INGR.MARC_OID_MARC
			   		  								   AND PERI.CANA_OID_CANA = PERI_INGR.CANA_OID_CANA
													   AND C.OID_CLIE = PERI_INGR.OID_CLIE
													   AND C.FEC_INGR = PERI_INGR.FEC_INGR   
			   									 ),
												C_ADICI.PERD_OID_PERI_LINE_CRED  
										 ),
										 (
	   									  SELECT PERI_ACT.OID_PERI
										  FROM  
	   		   							  		(
			   									 SELECT PERIO.OID_PERI, PERIO.PAIS_OID_PAIS, PERIO.MARC_OID_MARC, PERIO.CANA_OID_CANA 
			   									 FROM CRA_PERIO PERIO
												 WHERE PERIO.FEC_INIC >= SYSDATE 
					  							 	   AND SYSDATE <=PERIO.FEC_FINA
					  								   AND VAL_ESTA = 1
												ORDER BY PERIO.FEC_INIC 
	   											) PERI_ACT
										  WHERE ROWNUM = 1
	   		  							  		AND PERI.PAIS_OID_PAIS = PERI_ACT.PAIS_OID_PAIS
	   		  									AND PERI.MARC_OID_MARC = PERI_ACT.MARC_OID_MARC
	   		  									AND PERI.CANA_OID_CANA = PERI_ACT.CANA_OID_CANA   
	   									 ) 
										) AS NRO_PERI_CON_PEDIDOS, 
       SOLIC_BLOQUEADAS.COD_TIPO_SOLI AS COD_TIPO_SOLI_SOL,
       SOLIC_BLOQUEADAS.VAL_NUME_SOLI,
       SOLIC_BLOQUEADAS.VAL_NOMB_PERI AS VAL_NOMB_PERI_SOL,
       SOLIC_BLOQUEADAS.FEC_DOCU AS FEC_DOCU_SOL,
       SOLIC_BLOQUEADAS.VAL_MONT_ORDE, 
	   SOLIC_BLOQUEADAS.VAL_MONT_DEUD_VENC,
       SOLIC_BLOQUEADAS.VAL_1, 
	   SOLIC_BLOQUEADAS.VAL_2, 
	   SOLIC_BLOQUEADAS.VAL_3,
       SOLIC_BLOQUEADAS.VAL_4, 
	   SOLIC_BLOQUEADAS.USUARIO,
       SOLIC_BLOQUEADAS.FEC_HORA_LIBE, 
	   SOLIC_BLOQUEADAS.ESTADO_EVAL_AUTO,
       SOLIC_BLOQUEADAS.NOTIFICADO,
       SOLIC_BLOQUEADAS.COD_NIVE_RIES AS COD_NIVE_RIES_SOL, 
	   0 AS CANTIDAD
FROM
	   MAE_CLIEN C,
	   MAE_CLIEN_COMUN C_COM_TEL,
	   MAE_CLIEN_COMUN C_COM_MAIL,
	   MAE_CLIEN_DATOS_ADICI C_ADICI,
	   MAE_CLIEN_BLOQU C_BLOQ,
	   MAE_TIPO_BLOQU T_BLOQ,
	   MAE_ESTAT_CLIEN C_ESTAT,
	   MAE_CLIEN_UNIDA_ADMIN C_UN,
	   MAE_CLIEN_HISTO_ESTAT C_HISTO,
	   ZON_TERRI_ADMIN Z_TERR,
	   SEG_MARCA S_MARCA,
	   SEG_CANAL S_CANAL,
	   CRA_PERIO PERI,
	   CAR_NIVEL_RIESG RIESGO,
	   (
	   	SELECT * 
		FROM  
	   		   (
			   	SELECT PERIO.OID_PERI, PERIO.PAIS_OID_PAIS, PERIO.MARC_OID_MARC, PERIO.CANA_OID_CANA 
			   	FROM CRA_PERIO PERIO
				WHERE PERIO.FEC_INIC >= SYSDATE 
					  AND SYSDATE <=PERIO.FEC_FINA
					  AND VAL_ESTA = 1
				ORDER BY PERIO.FEC_INIC 
	   			) PERI_ACT
		WHERE ROWNUM = 1
	   ) PERI_ACTUAL,
	   (
	   	SELECT CL_SOL.OID_CLAS_SOLI 
		FROM PED_CLASE_SOLIC CL_SOL
		WHERE CL_SOL.IND_ORDE_COMP = 1
	   ) CL_SOLIC,
	   (
	   	SELECT * FROM
			   	 	 ( 
					 SELECT SOCI.COD_SOCI, SOCI.VAL_DENO, M.*, FPAGO.COD_FORM_PAGO, TSOLIC.COD_TIPO_SOLI
					 FROM   CCC_MOVIM_CUENT_CORRI M,
			   		 		CCC_SUBPR S,
			   				CCC_PROCE P,	
	   						SEG_SOCIE SOCI,
	   						BEL_FORMA_PAGO FPAGO, 
	   						PED_TIPO_SOLIC_PAIS TSOLIC_PA,
	   						PED_TIPO_SOLIC TSOLIC,
	   						PED_SOLIC_CABEC SOLIC_CAB,
							MAE_CLIEN CL
					 WHERE  M.SUBP_OID_SUBP_CREA = S.OID_SUBP
			   		 		AND S.CCPR_OID_PROC = P.OID_PROC
			   				AND M.SUBP_OID_SUBP_CREA = 1 
			   				AND P.COD_PROC = 'CCC001'
						   	AND M.TSPA_OID_TIPO_SOLI_PAIS(+) = TSOLIC_PA.OID_TIPO_SOLI_PAIS
						   	AND M.SOCI_OID_SOCI = SOCI.OID_SOCI(+)
	   						AND SOLIC_CAB.TSPA_OID_TIPO_SOLI_PAIS = TSOLIC_PA.OID_TIPO_SOLI_PAIS 
	   						AND SOLIC_CAB.FOPA_OID_FORM_PAGO = FPAGO.OID_FORM_PAGO(+)			 
	   						AND TSOLIC_PA.TSOL_OID_TIPO_SOLI = TSOLIC.OID_TIPO_SOLI(+)
							AND TSOLIC_PA.PAIS_OID_PAIS = FPAGO.PAIS_OID_PAIS
							AND TSOLIC_PA.PAIS_OID_PAIS = 1
							AND M.CLIE_OID_CLIE = CL.OID_CLIE
							AND CL.COD_CLIE = '00000000183'
							AND (NVL(M.IMP_MOVI,0) - NVL(M.IMP_PAGA,0)) <> 0
					 ORDER BY M.FEC_DOCU  DESC
					 )
		WHERE ROWNUM = 1
	   ) CC_M,
	   ( 
	   	SELECT CLIEN.OID_CLIE,
			   T_SOLIC.COD_TIPO_SOLI,
			   SOL_CAB.VAL_NUME_SOLI,
			   PERI.VAL_NOMB_PERI, 
	  		   SOL_ENTR.FEC_DOCU,
	  		   SOL_ENTR.VAL_MONT_ORDE,
	  		   SOL_ENTR.VAL_MONT_DEUD_VENC,
	  		   DECODE(SOL_ENTR.IND_VALI_1,1,'B1 ',' ') AS VAL_1, 
	  		   DECODE(SOL_ENTR.IND_VALI_2,1,'B2 ',' ') AS VAL_2, 
	  		   DECODE(SOL_ENTR.IND_VALI_3,1,'B3 ',' ') AS VAL_3,
	  		   DECODE(SOL_ENTR.IND_VALI_4,1,'B4 ',' ') AS VAL_4,
	  		   USUARIO_LIBERACION.VAL_NOMB_USUA AS USUARIO,
	  		   SOL_ENTR.FEC_HORA_LIBE,
	  		   GEN_ESTADO_EVAL_AUTO.ESTADO_EVAL_AUTO,
	  		   DECODE(SOL_ENTR.IND_NOTI,1,'SI','NO') AS NOTIFICADO,
	  		   RIESGO.COD_NIVE_RIES
		FROM
	  		   CAR_SOLI_ENTR_BLOQ SOL_ENTR,
	  		   PED_TIPO_SOLIC T_SOLIC,
	  		   CAR_NIVEL_RIESG RIESGO,
	  		   CRA_PERIO PERI,
	  		   MAE_CLIEN CLIEN,
	  		   MAE_CLIEN_DATOS_ADICI CLIEN_ADICI,
	  		   CAR_EJECU_CUENT EJECTA_LIBERACION,
	  		   V_REP_USUAR_LARGO USUARIO_LIBERACION,
	  		   PED_SOLIC_CABEC SOL_CAB,
	  		   CAR_CODIG_APROB COD, 
	  		   PED_ESTAD_SOLIC SOL_ESTADO,
	  		   (
	   		   	SELECT GEN.VAL_OID, GEN.VAL_I18N AS ESTADO_EVAL_AUTO
	   			FROM V_GEN_I18N_SICC GEN
	   			WHERE GEN.ATTR_ENTI = 'CAR_ESTAT_PEDID' 
			  		  AND GEN.IDIO_OID_IDIO = 1		 	 		 				  
	  		   ) GEN_ESTADO_EVAL_AUTO
		WHERE
	      	   SOL_ENTR.PERD_OID_PERI = PERI.OID_PERI
	  		   AND SOL_ENTR.TSOL_OID_TIPO_SOLI = T_SOLIC.OID_TIPO_SOLI
	  		   AND SOL_ENTR.NIRI_OID_NIVE_RIES = RIESGO.OID_NIVE_RIES
	  		   AND SOL_ENTR.CLIE_OID_CLIE = CLIEN.OID_CLIE
	  		   AND SOL_ENTR.CLIE_OID_CLIE = CLIEN_ADICI.CLIE_OID_CLIE(+)
	  		   AND SOL_ENTR.SOCA_OID_SOLI_CABE = SOL_CAB.OID_SOLI_CABE
	  		   AND SOL_ENTR.COAP_OID_CODI_APRO = COD.OID_CODI_APRO(+)
	  		   AND SOL_CAB.ESSO_OID_ESTA_SOLI = SOL_ESTADO.OID_ESTA_SOLI
	  		   AND SOL_ENTR.ESPE_OID_ESTA_PEDI= GEN_ESTADO_EVAL_AUTO.VAL_OID(+)
	  		   AND SOL_ENTR.EJCU_OID_USUA_LIBE= EJECTA_LIBERACION.OID_EJEC_CUEN
	  		   AND EJECTA_LIBERACION.USER_EJEC_CUEN  = USUARIO_LIBERACION.COD_USUA(+)
			   AND PERI.FEC_INIC >= ADD_MONTHS(SYSDATE,-6) 
			   AND PERI.FEC_FINA <= SYSDATE 
	   ) SOLIC_BLOQUEADAS
WHERE 
	   C.OID_CLIE = C_ADICI.CLIE_OID_CLIE
	   AND C.PAIS_OID_PAIS =1	
	   AND C.COD_CLIE ='00000000183'
	   AND C.OID_CLIE = C_COM_TEL.CLIE_OID_CLIE(+)
	   AND C.OID_CLIE = C_COM_MAIL.CLIE_OID_CLIE(+)
	   AND C_COM_TEL.TICM_OID_TIPO_COMU(+) = 1  
	   AND C_COM_MAIL.TICM_OID_TIPO_COMU(+) = 3	 
	   AND C_ADICI.ESTA_OID_ESTA_CLIE = C_ESTAT.OID_ESTA_CLIE
	   AND C.OID_CLIE = C_UN.CLIE_OID_CLIE
	   AND C_UN.IND_ACTI = 1
	   AND C_UN.ZTAD_OID_TERR_ADMI = Z_TERR.OID_TERR_ADMI
	   AND Z_TERR.CANA_OID_CANA = S_CANAL.OID_CANA
	   AND Z_TERR.MARC_OID_MARC = S_MARCA.OID_MARC
	   AND C.PAIS_OID_PAIS = Z_TERR.PAIS_OID_PAIS
	   AND C.OID_CLIE = CC_M.CLIE_OID_CLIE(+)
	   AND C_ADICI.NIRI_OID_NIVE_RIES = RIESGO.OID_NIVE_RIES(+)
	   AND C.OID_CLIE = SOLIC_BLOQUEADAS.OID_CLIE(+)
	   AND C.OID_CLIE = C_BLOQ.CLIE_OID_CLIE(+)
	   AND C_BLOQ.TIBQ_OID_TIPO_BLOQ = T_BLOQ.OID_TIPO_BLOQ
	   AND C_HISTO.PERD_OID_PERI = PERI.OID_PERI		 
	   AND C.OID_CLIE =  C_HISTO.CLIE_OID_CLIE(+)
--	   AND C_HISTO.ESTA_OID_ESTA_CLIE = 1

