SELECT 
	  PERI.VAL_NOMB_PERI,
	  GEN_CANA.CANAL, 
	  PERI.FEC_INIC, 
	  PERI.FEC_FINA,
	  REGI.COD_REGI, 
	  ZONA.COD_ZONA, 
	  T_SOLIC.COD_TIPO_SOLI, 
	  RIESGO.COD_NIVE_RIES,
	  (
		SELECT 
			  COD.COD_APRO
		FROM
			  CAR_CODIG_APROB COD
		WHERE COD.OID_CODI_APRO = 1
	  ) AS LIB_1_COD,
	  (
		SELECT 
			  COD.COD_APRO
		FROM
			  CAR_CODIG_APROB COD
		WHERE COD.OID_CODI_APRO = 2
	  ) AS LIB_2_COD,
	  (
		SELECT 
			  COD.COD_APRO
		FROM
			  CAR_CODIG_APROB COD
		WHERE COD.OID_CODI_APRO = 3
	  ) AS LIB_3_COD,
	  (
		SELECT 
			  COD.COD_APRO
		FROM
			  CAR_CODIG_APROB COD
		WHERE COD.OID_CODI_APRO = 4
	  ) AS LIB_4_COD,
	  COUNT(*) AS TOTAL_EVAL,
	  (
		SELECT 
			  COUNT(*) 
		FROM
			  CAR_SOLI_ENTR_BLOQ SOL_EN,
			  ZON_ZONA ZO,
			  ZON_REGIO RE
		WHERE
			      SOL_EN.ZZON_OID_ZONA = ZO.OID_ZONA
			  AND ZO.ZORG_OID_REGI = RE.OID_REGI
			  AND SOL_EN.ESPE_OID_ESTA_PEDI = 3
---------------------------------------------------------------------------
			  AND SOL_EN.PERD_OID_PERI = PERI.OID_PERI
			  AND RE.ZSGV_OID_SUBG_VENT = SUBGV.OID_SUBG_VENT 
			  AND SOL_EN.ZZON_OID_ZONA = ZONA.OID_ZONA
			  AND ZO.ZORG_OID_REGI = REGI.OID_REGI
			  AND SOL_EN.TSOL_OID_TIPO_SOLI = SOL_ENTR.TSOL_OID_TIPO_SOLI
			  AND SOL_EN.NIRI_OID_NIVE_RIES = SOL_ENTR.NIRI_OID_NIVE_RIES 
	  ) AS BLOQUEADAS,
	  (
		SELECT 
			  COUNT(*) 
		FROM
			  CAR_SOLI_ENTR_BLOQ SOL_EN,
			  ZON_ZONA ZO,
			  ZON_REGIO RE
		WHERE
			      SOL_EN.ZZON_OID_ZONA = ZO.OID_ZONA
			  AND ZO.ZORG_OID_REGI = RE.OID_REGI
			  AND SOL_EN.ESPE_OID_ESTA_PEDI = 3
			  AND SOL_EN.IND_VALI_1=1
---------------------------------------------------------------------------
			  AND SOL_EN.PERD_OID_PERI = PERI.OID_PERI
			  AND RE.ZSGV_OID_SUBG_VENT = SUBGV.OID_SUBG_VENT 
			  AND SOL_EN.ZZON_OID_ZONA = ZONA.OID_ZONA
			  AND ZO.ZORG_OID_REGI = REGI.OID_REGI
			  AND SOL_EN.TSOL_OID_TIPO_SOLI = SOL_ENTR.TSOL_OID_TIPO_SOLI
			  AND SOL_EN.NIRI_OID_NIVE_RIES = SOL_ENTR.NIRI_OID_NIVE_RIES 
	  ) AS BLOQ_EVAL_1,
	  (
		SELECT 
			  COUNT(*) 
		FROM
			  CAR_SOLI_ENTR_BLOQ SOL_EN,
			  ZON_ZONA ZO,
			  ZON_REGIO RE
		WHERE
			      SOL_EN.ZZON_OID_ZONA = ZO.OID_ZONA
			  AND ZO.ZORG_OID_REGI = RE.OID_REGI
			  AND SOL_EN.ESPE_OID_ESTA_PEDI = 3
			  AND SOL_EN.IND_VALI_2=1
---------------------------------------------------------------------------
			  AND SOL_EN.PERD_OID_PERI = PERI.OID_PERI
			  AND RE.ZSGV_OID_SUBG_VENT = SUBGV.OID_SUBG_VENT 
			  AND SOL_EN.ZZON_OID_ZONA = ZONA.OID_ZONA
			  AND ZO.ZORG_OID_REGI = REGI.OID_REGI
			  AND SOL_EN.TSOL_OID_TIPO_SOLI = SOL_ENTR.TSOL_OID_TIPO_SOLI
			  AND SOL_EN.NIRI_OID_NIVE_RIES = SOL_ENTR.NIRI_OID_NIVE_RIES 
	  ) AS BLOQ_EVAL_2,
	  (
		SELECT 
			  COUNT(*) 
		FROM
			  CAR_SOLI_ENTR_BLOQ SOL_EN,
			  ZON_ZONA ZO,
			  ZON_REGIO RE
		WHERE
			      SOL_EN.ZZON_OID_ZONA = ZO.OID_ZONA
			  AND ZO.ZORG_OID_REGI = RE.OID_REGI
			  AND SOL_EN.ESPE_OID_ESTA_PEDI = 3
			  AND SOL_EN.IND_VALI_3=1
---------------------------------------------------------------------------
			  AND SOL_EN.PERD_OID_PERI = PERI.OID_PERI
			  AND RE.ZSGV_OID_SUBG_VENT = SUBGV.OID_SUBG_VENT 
			  AND SOL_EN.ZZON_OID_ZONA = ZONA.OID_ZONA
			  AND ZO.ZORG_OID_REGI = REGI.OID_REGI
			  AND SOL_EN.TSOL_OID_TIPO_SOLI = SOL_ENTR.TSOL_OID_TIPO_SOLI
			  AND SOL_EN.NIRI_OID_NIVE_RIES = SOL_ENTR.NIRI_OID_NIVE_RIES 
	  ) AS BLOQ_EVAL_3,
	  (
		SELECT 
			  COUNT(*)
		FROM
			  CAR_SOLI_ENTR_BLOQ SOL_EN,
			  ZON_ZONA ZO,
			  ZON_REGIO RE
		WHERE
			      SOL_EN.ZZON_OID_ZONA = ZO.OID_ZONA
			  AND ZO.ZORG_OID_REGI = RE.OID_REGI
			  AND SOL_EN.ESPE_OID_ESTA_PEDI = 3
			  AND SOL_EN.IND_VALI_4=1
---------------------------------------------------------------------------
			  AND SOL_EN.PERD_OID_PERI = PERI.OID_PERI
			  AND RE.ZSGV_OID_SUBG_VENT = SUBGV.OID_SUBG_VENT 
			  AND SOL_EN.ZZON_OID_ZONA = ZONA.OID_ZONA
			  AND ZO.ZORG_OID_REGI = REGI.OID_REGI
			  AND SOL_EN.TSOL_OID_TIPO_SOLI = SOL_ENTR.TSOL_OID_TIPO_SOLI
			  AND SOL_EN.NIRI_OID_NIVE_RIES = SOL_ENTR.NIRI_OID_NIVE_RIES 
	  ) AS BLOQ_EVAL_4,
	  (
		SELECT 
			  COUNT(*) 
		FROM
			  CAR_SOLI_ENTR_BLOQ SOL_EN,
			  ZON_ZONA ZO,
			  ZON_REGIO RE
		WHERE
			      SOL_EN.ZZON_OID_ZONA = ZO.OID_ZONA
			  AND ZO.ZORG_OID_REGI = RE.OID_REGI
			  AND SOL_EN.ESPE_OID_ESTA_PEDI = 7
---------------------------------------------------------------------------
			  AND SOL_EN.PERD_OID_PERI = PERI.OID_PERI
			  AND RE.ZSGV_OID_SUBG_VENT = SUBGV.OID_SUBG_VENT 
			  AND SOL_EN.ZZON_OID_ZONA = ZONA.OID_ZONA
			  AND ZO.ZORG_OID_REGI = REGI.OID_REGI
			  AND SOL_EN.TSOL_OID_TIPO_SOLI = SOL_ENTR.TSOL_OID_TIPO_SOLI
			  AND SOL_EN.NIRI_OID_NIVE_RIES = SOL_ENTR.NIRI_OID_NIVE_RIES 
	  ) AS RECHAZADAS,
	  (
		SELECT 
			  COUNT(*)
		FROM
			  CAR_SOLI_ENTR_BLOQ SOL_EN,
			  ZON_ZONA ZO,
			  ZON_REGIO RE
		WHERE
			      SOL_EN.ZZON_OID_ZONA = ZO.OID_ZONA
			  AND ZO.ZORG_OID_REGI = RE.OID_REGI
			  AND SOL_EN.ESPE_OID_ESTA_PEDI = 7
			  AND SOL_EN.IND_VALI_1=1
---------------------------------------------------------------------------
			  AND SOL_EN.PERD_OID_PERI = PERI.OID_PERI
			  AND RE.ZSGV_OID_SUBG_VENT = SUBGV.OID_SUBG_VENT 
			  AND SOL_EN.ZZON_OID_ZONA = ZONA.OID_ZONA
			  AND ZO.ZORG_OID_REGI = REGI.OID_REGI
			  AND SOL_EN.TSOL_OID_TIPO_SOLI = SOL_ENTR.TSOL_OID_TIPO_SOLI
			  AND SOL_EN.NIRI_OID_NIVE_RIES = SOL_ENTR.NIRI_OID_NIVE_RIES 
	  ) AS B1,
	  (
		SELECT 
			  COUNT(*) 
		FROM
			  CAR_SOLI_ENTR_BLOQ SOL_EN,
			  ZON_ZONA ZO,
			  ZON_REGIO RE
		WHERE
			      SOL_EN.ZZON_OID_ZONA = ZO.OID_ZONA
			  AND ZO.ZORG_OID_REGI = RE.OID_REGI
			  AND SOL_EN.ESPE_OID_ESTA_PEDI = 7
			  AND SOL_EN.IND_VALI_2=1
---------------------------------------------------------------------------
			  AND SOL_EN.PERD_OID_PERI = PERI.OID_PERI
			  AND RE.ZSGV_OID_SUBG_VENT = SUBGV.OID_SUBG_VENT 
			  AND SOL_EN.ZZON_OID_ZONA = ZONA.OID_ZONA
			  AND ZO.ZORG_OID_REGI = REGI.OID_REGI
			  AND SOL_EN.TSOL_OID_TIPO_SOLI = SOL_ENTR.TSOL_OID_TIPO_SOLI
			  AND SOL_EN.NIRI_OID_NIVE_RIES = SOL_ENTR.NIRI_OID_NIVE_RIES 
	  ) AS B2,
	  (
		SELECT 
			  COUNT(*) 
		FROM
			  CAR_SOLI_ENTR_BLOQ SOL_EN,
			  ZON_ZONA ZO,
			  ZON_REGIO RE
		WHERE
			      SOL_EN.ZZON_OID_ZONA = ZO.OID_ZONA
			  AND ZO.ZORG_OID_REGI = RE.OID_REGI
			  AND SOL_EN.ESPE_OID_ESTA_PEDI = 7
			  AND SOL_EN.IND_VALI_3=1
---------------------------------------------------------------------------
			  AND SOL_EN.PERD_OID_PERI = PERI.OID_PERI
			  AND RE.ZSGV_OID_SUBG_VENT = SUBGV.OID_SUBG_VENT 
			  AND SOL_EN.ZZON_OID_ZONA = ZONA.OID_ZONA
			  AND ZO.ZORG_OID_REGI = REGI.OID_REGI
			  AND SOL_EN.TSOL_OID_TIPO_SOLI = SOL_ENTR.TSOL_OID_TIPO_SOLI
			  AND SOL_EN.NIRI_OID_NIVE_RIES = SOL_ENTR.NIRI_OID_NIVE_RIES 
	  ) AS B3,
	  (
		SELECT 
			  COUNT(*) 
		FROM
			  CAR_SOLI_ENTR_BLOQ SOL_EN,
			  ZON_ZONA ZO,
			  ZON_REGIO RE
		WHERE
			      SOL_EN.ZZON_OID_ZONA = ZO.OID_ZONA
			  AND ZO.ZORG_OID_REGI = RE.OID_REGI
			  AND SOL_EN.ESPE_OID_ESTA_PEDI = 7
			  AND SOL_EN.IND_VALI_4=1
---------------------------------------------------------------------------
			  AND SOL_EN.PERD_OID_PERI = PERI.OID_PERI
			  AND RE.ZSGV_OID_SUBG_VENT = SUBGV.OID_SUBG_VENT 
			  AND SOL_EN.ZZON_OID_ZONA = ZONA.OID_ZONA
			  AND ZO.ZORG_OID_REGI = REGI.OID_REGI
			  AND SOL_EN.TSOL_OID_TIPO_SOLI = SOL_ENTR.TSOL_OID_TIPO_SOLI
			  AND SOL_EN.NIRI_OID_NIVE_RIES = SOL_ENTR.NIRI_OID_NIVE_RIES 
	  ) AS B4,
	  (
		SELECT 
			  COUNT(*) 
		FROM
			  CAR_SOLI_ENTR_BLOQ SOL_EN,
			  ZON_ZONA ZO,
			  ZON_REGIO RE
		WHERE
			      SOL_EN.ZZON_OID_ZONA = ZO.OID_ZONA
			  AND ZO.ZORG_OID_REGI = RE.OID_REGI
			  AND SOL_EN.ESPE_OID_ESTA_PEDI = 4
---------------------------------------------------------------------------
			  AND SOL_EN.PERD_OID_PERI = PERI.OID_PERI
			  AND RE.ZSGV_OID_SUBG_VENT = SUBGV.OID_SUBG_VENT 
			  AND SOL_EN.ZZON_OID_ZONA = ZONA.OID_ZONA
			  AND ZO.ZORG_OID_REGI = REGI.OID_REGI
			  AND SOL_EN.TSOL_OID_TIPO_SOLI = SOL_ENTR.TSOL_OID_TIPO_SOLI
			  AND SOL_EN.NIRI_OID_NIVE_RIES = SOL_ENTR.NIRI_OID_NIVE_RIES 
	  ) AS LIBERADAS,
	  NVL((
		SELECT 
			  COUNT(*)
		FROM
			  CAR_SOLI_ENTR_BLOQ SOL_EN,
			  ZON_ZONA ZO,
			  ZON_REGIO RE,
			  CAR_CODIG_APROB COD
		WHERE
			      SOL_EN.ZZON_OID_ZONA = ZO.OID_ZONA
			  AND ZO.ZORG_OID_REGI = RE.OID_REGI
			  AND SOL_EN.COAP_OID_CODI_APRO = COD.OID_CODI_APRO
			  AND SOL_EN.ESPE_OID_ESTA_PEDI = 4
			  AND COD.OID_CODI_APRO = 1
---------------------------------------------------------------------------
			  AND SOL_EN.PERD_OID_PERI = PERI.OID_PERI
			  AND RE.ZSGV_OID_SUBG_VENT = SUBGV.OID_SUBG_VENT 
			  AND SOL_EN.ZZON_OID_ZONA = ZONA.OID_ZONA
			  AND ZO.ZORG_OID_REGI = REGI.OID_REGI
			  AND SOL_EN.TSOL_OID_TIPO_SOLI = SOL_ENTR.TSOL_OID_TIPO_SOLI
			  AND SOL_EN.NIRI_OID_NIVE_RIES = SOL_ENTR.NIRI_OID_NIVE_RIES
		GROUP BY COD.COD_APRO 
	  ),0) AS LIB_1_VAL,
	  NVL((
		SELECT 
			  COUNT(*)
		FROM
			  CAR_SOLI_ENTR_BLOQ SOL_EN,
			  ZON_ZONA ZO,
			  ZON_REGIO RE,
			  CAR_CODIG_APROB COD
		WHERE
			      SOL_EN.ZZON_OID_ZONA = ZO.OID_ZONA
			  AND ZO.ZORG_OID_REGI = RE.OID_REGI
			  AND SOL_EN.COAP_OID_CODI_APRO = COD.OID_CODI_APRO
			  AND SOL_EN.ESPE_OID_ESTA_PEDI = 4
			  AND COD.OID_CODI_APRO = 2
---------------------------------------------------------------------------
			  AND SOL_EN.PERD_OID_PERI = PERI.OID_PERI
			  AND RE.ZSGV_OID_SUBG_VENT = SUBGV.OID_SUBG_VENT 
			  AND SOL_EN.ZZON_OID_ZONA = ZONA.OID_ZONA
			  AND ZO.ZORG_OID_REGI = REGI.OID_REGI
			  AND SOL_EN.TSOL_OID_TIPO_SOLI = SOL_ENTR.TSOL_OID_TIPO_SOLI
			  AND SOL_EN.NIRI_OID_NIVE_RIES = SOL_ENTR.NIRI_OID_NIVE_RIES
		GROUP BY COD.COD_APRO 
	  ),0) AS LIB_2_VAL,
	  NVL((
		SELECT 
			  COUNT(*)
		FROM
			  CAR_SOLI_ENTR_BLOQ SOL_EN,
			  ZON_ZONA ZO,
			  ZON_REGIO RE,
			  CAR_CODIG_APROB COD
		WHERE
			      SOL_EN.ZZON_OID_ZONA = ZO.OID_ZONA
			  AND ZO.ZORG_OID_REGI = RE.OID_REGI
			  AND SOL_EN.COAP_OID_CODI_APRO = COD.OID_CODI_APRO
			  AND SOL_EN.ESPE_OID_ESTA_PEDI = 4
			  AND COD.OID_CODI_APRO = 3
---------------------------------------------------------------------------
			  AND SOL_EN.PERD_OID_PERI = PERI.OID_PERI
			  AND RE.ZSGV_OID_SUBG_VENT = SUBGV.OID_SUBG_VENT 
			  AND SOL_EN.ZZON_OID_ZONA = ZONA.OID_ZONA
			  AND ZO.ZORG_OID_REGI = REGI.OID_REGI
			  AND SOL_EN.TSOL_OID_TIPO_SOLI = SOL_ENTR.TSOL_OID_TIPO_SOLI
			  AND SOL_EN.NIRI_OID_NIVE_RIES = SOL_ENTR.NIRI_OID_NIVE_RIES
		GROUP BY COD.COD_APRO 
	  ),0) AS LIB_3_VAL,
	  NVL((
		SELECT 
			  COUNT(*)
		FROM
			  CAR_SOLI_ENTR_BLOQ SOL_EN,
			  ZON_ZONA ZO,
			  ZON_REGIO RE,
			  CAR_CODIG_APROB COD
		WHERE
			      SOL_EN.ZZON_OID_ZONA = ZO.OID_ZONA
			  AND ZO.ZORG_OID_REGI = RE.OID_REGI
			  AND SOL_EN.COAP_OID_CODI_APRO = COD.OID_CODI_APRO
			  AND SOL_EN.ESPE_OID_ESTA_PEDI = 4
			  AND COD.OID_CODI_APRO = 4
---------------------------------------------------------------------------
			  AND SOL_EN.PERD_OID_PERI = PERI.OID_PERI
			  AND RE.ZSGV_OID_SUBG_VENT = SUBGV.OID_SUBG_VENT 
			  AND SOL_EN.ZZON_OID_ZONA = ZONA.OID_ZONA
			  AND ZO.ZORG_OID_REGI = REGI.OID_REGI
			  AND SOL_EN.TSOL_OID_TIPO_SOLI = SOL_ENTR.TSOL_OID_TIPO_SOLI
			  AND SOL_EN.NIRI_OID_NIVE_RIES = SOL_ENTR.NIRI_OID_NIVE_RIES
		GROUP BY COD.COD_APRO 
	  ),0) AS LIB_4_VAL
FROM
	  CAR_SOLI_ENTR_BLOQ SOL_ENTR,
	  PED_TIPO_SOLIC T_SOLIC,
	  CAR_NIVEL_RIESG RIESGO,
	  CRA_PERIO PERI,
	  ZON_ZONA ZONA,
	  ZON_REGIO REGI,
	  ZON_SUB_GEREN_VENTA SUBGV,
	  (
	  SELECT GEN.VAL_OID, GEN.VAL_I18N CANAL
	  FROM V_GEN_I18N_SICC GEN
	  WHERE GEN.ATTR_ENTI = 'SEG_CANAL'
	  		AND GEN.IDIO_OID_IDIO = 1 --PARAMETRO--
	  )GEN_CANA
WHERE
	      SOL_ENTR.PERD_OID_PERI = PERI.OID_PERI
	  AND SOL_ENTR.ZZON_OID_ZONA = ZONA.OID_ZONA
	  AND ZONA.ZORG_OID_REGI = REGI.OID_REGI
	  AND REGI.ZSGV_OID_SUBG_VENT = SUBGV.OID_SUBG_VENT 
	  AND SOL_ENTR.TSOL_OID_TIPO_SOLI = T_SOLIC.OID_TIPO_SOLI
	  AND SOL_ENTR.NIRI_OID_NIVE_RIES = RIESGO.OID_NIVE_RIES
	  AND PERI.CANA_OID_CANA = GEN_CANA.VAL_OID(+)
------------------------------------------------------------
--	  AND PERI.PAIS_OID_PAIS = 1 --PARAMETRO--
--	  AND PERI.MARC_OID_MARC = 1 --PARAMETRO--
--	  AND PERI.CANA_OID_CANA = 1 --PARAMETRO--
--	  AND PERI.OID_PERI = 57 --54--40 --PARAMETRO--
--	  AND SOL_ENTR.TSOL_OID_TIPO_SOLI IN (72, 1433,10,67,1384,1,2,3,4,5,65) --PARAMETRO--
--	  AND SUBGV.OID_SUBG_VENT = 1  --PARAMETRO--
--	  AND REGI.OID_REGI IN (1,2,3,4,5,6,7,8,9,10) --PARAMETRO--
--	  AND ZONA.OID_ZONA IN (1,2,3,4,5,6,7,8,9,10,11,12,13,14) --PARAMETRO--
--	  AND SOL_ENTR.NIRI_OID_NIVE_RIES = 1 --PARAMETRO--
GROUP BY 	   
	  PERI.VAL_NOMB_PERI,	  
	  GEN_CANA.CANAL, 
	  PERI.FEC_INIC, 
	  PERI.FEC_FINA,
	  SUBGV.OID_SUBG_VENT,
	  REGI.COD_REGI, ZONA.COD_ZONA, 
	  T_SOLIC.COD_TIPO_SOLI, 
	  RIESGO.COD_NIVE_RIES,
	  PERI.OID_PERI,ZONA.OID_ZONA, 
	  REGI.OID_REGI,
	  SOL_ENTR.TSOL_OID_TIPO_SOLI,
	  SOL_ENTR.NIRI_OID_NIVE_RIES
ORDER BY
	  PERI.VAL_NOMB_PERI,  
	  REGI.COD_REGI, ZONA.COD_ZONA, 
	  T_SOLIC.COD_TIPO_SOLI, 
	  RIESGO.COD_NIVE_RIES
  