
SELECT COB.PAIS,
	   COB.SOCI,
	   COB.REGION,
	   COB.ZONA,
	   COB.SECCION,
	   COB.TERRITORIO,
	   COB.COD_CONSULTORA,
	   COB.CONSULTORA,
	   COB.DOCUMENTO,
	   COB.TIPO_VIA,
	   COB.NOMBRE_VIA,
	   COB.NUMERO,
	   COB.INTERIOR,
	   COB.MANZANA,
	   COB.LOTE,
	   COB.KM,
	   COB.TELEFONO,
	   COB.CAMP,
	   COB.BOLETA,
	   COB.FECHA_FACT,
	   COB.IMPORTE_FACTURADO,
	   COB.SALDO_CARTERA,
	   MOV.FEC_RANGO1,
	   MOV.FEC_RANGO2,
	   MOV.FEC_RANGO3,
	   MOV.FEC_RANGO4,
	   MOV.FEC_RANGO5,
	   MOV.FEC_RANGO6,
	   MOV.RANGO_1,
	   MOV.RANGO_2,
	   MOV.RANGO_3,
	   MOV.RANGO_4,
	   MOV.RANGO_5,
	   MOV.RANGO_6,	
	   COB.REBAJA,
	   (  NVL(COB.SALDO_CARTERA, 0) - ( NVL(MOV.RANGO_1, 0) + NVL(MOV.RANGO_2, 0) + NVL(MOV.RANGO_3, 0) + NVL(MOV.RANGO_4, 0) + NVL(MOV.RANGO_5, 0) + NVL(MOV.RANGO_6,0)   )) SALDO_PRELIMINAR,   	   	   	   	   
	   COB.SALDO_LIQUIDA  
FROM
	(
		SELECT GEN_PAIS.VAL_I18N PAIS,
			   GEN_SOCI.VAL_I18N SOCI,
			   MCC.OID_MOVI_CC,
			   SUBG.OID_SUBG_VENT,
			   REG.DES_REGI REGION,
			   ZONA.DES_ZONA ZONA,
			   SEC.DES_SECCI SECCION,
			   TER.COD_TERR TERRITORIO,
			   CLI.COD_CLIE COD_CONSULTORA,
			   CLI.VAL_NOM1||' '||CLI.VAL_NOM2||' '||CLI.VAL_APE1||' '||CLI.VAL_APE2 CONSULTORA,
			   DATOS_CLI.NUM_DOCU_IDEN DOCUMENTO,
			   GEN_TIP_VIA.VAL_I18N TIPO_VIA,
			   DATOS_CLI.VAL_NOMB_VIA NOMBRE_VIA,
			   DATOS_CLI.NUM_PPAL NUMERO,
			   DATOS_CLI.VAL_INTE INTERIOR,
			   DATOS_CLI.VAL_MANZ MANZANA,
			   DATOS_CLI.VAL_LOTE LOTE,
			   DATOS_CLI.VAL_KM KM,
			   DATOS_CLI.VAL_TEXT_COMU TELEFONO,
			   PERIO.VAL_NOMB_PERI CAMP,
			   MCC.NUM_IDEN_CUOT BOLETA,
			   ASI_COB.IMP_ORIG_DEUD IMPORTE_FACTURADO,
			   ASI_COB.IMP_DEUD_ASIG SALDO_CARTERA,
			   MCC.FEC_DOCU FECHA_FACT,
			   NVL((
			   	SELECT SUM(ASI.IMP_DEUD_ASIG)
				FROM COB_ASIGN_COBRA ASI,
					 COB_CRONO_COBRA CRO,
					 ccc_movim_cuent_corri movi, --MAE_CLIEN_TIPO_SUBTI TIP,
					 COB_ESTAD_ASIGN EST_ASG	 	 
				WHERE ASI.MVCC_OID_MOVI_CC = movi.OID_MOVI_CC
--				  	  AND TIP.IND_PPAL = 1
					  --AND ASI.CTSU_OID_CLIE_TIPO_SUBT = TIP.SBTI_OID_SUBT_CLIE
					  AND movi.CLIE_OID_CLIE = CLI.OID_CLIE 
					  AND EST_ASG.OID_ESTA_ASIG = ASI.ESAS_OID_ESTA_ASIG 
					  AND EST_ASG.OID_ESTA_ASIG = 4
					  AND CRO.ETDE_OID_ETAP_DEUD = CRO_COB.ETDE_OID_ETAP_DEUD
					  AND CRO.PERD_OID_PERI = CRO_COB.PERD_OID_PERI
				GROUP BY movi.CLIE_OID_CLIE 
			   ), 0) REBAJA,
			   PQ_APL_REP.FN_CU_CALC_SALDO_CTA_CTE(CLI.PAIS_OID_PAIS, CLI.OID_CLIE) SALDO_LIQUIDA,
			   ASI_COB.FEC_ASIG
		FROM COB_ASIGN_COBRA ASI_COB,
			 COB_CRONO_COBRA CRO_COB,
			 SEG_MARCA MARCA,
			 SEG_CANAL CANAL,
			 CRA_PERIO PERIO,
			 COB_USUAR_COBRA USU_COB,
			 COB_USUAR_GRUPO_USUAR GRU_USU,
			 ZON_SUB_GEREN_VENTA SUBG,
			 ZON_ZONA ZONA,
			 ZON_REGIO REG,
			 ZON_SECCI SEC,
			 ZON_TERRI TER,
			 ZON_TERRI_ADMIN TER_ADM,
			 CCC_MOVIM_CUENT_CORRI MCC,
			 MAE_CLIEN CLI,
			 COB_ESTAD_ASIGN EST_ASG, 
			 (
			 SELECT CLI_IDE.CLIE_OID_CLIE,
			 	    CLI_DIR.VAL_NOMB_VIA,
				   	CLI_DIR.NUM_PPAL,
					CLI_DIR.VAL_INTE,
					CLI_DIR.VAL_MANZ,
					CLI_DIR.VAL_LOTE,
					CLI_DIR.VAL_KM,
					CLI_IDE.NUM_DOCU_IDEN,
					TIP_VIA.OID_TIPO_VIA,
		            CLI_COM.VAL_TEXT_COMU
			 FROM MAE_CLIEN_IDENT CLI_IDE,
			 	  MAE_CLIEN_DIREC CLI_DIR,
				  SEG_TIPO_VIA TIP_VIA,		  
				  MAE_CLIEN_COMUN CLI_COM		  
			 WHERE CLI_IDE.VAL_IDEN_DOCU_PRIN = 1
			 	   AND CLI_DIR.IND_DIRE_PPAL = 1
				   AND CLI_DIR.CLIE_OID_CLIE(+) = CLI_IDE.CLIE_OID_CLIE
				   AND TIP_VIA.OID_TIPO_VIA = CLI_DIR.TIVI_OID_TIPO_VIA
				   AND CLI_COM.CLIE_OID_CLIE(+) = CLI_IDE.CLIE_OID_CLIE	  
			 ) DATOS_CLI,
			 (
				 SELECT GEN.VAL_OID, GEN.VAL_I18N
				 FROM V_GEN_I18N_SICC GEN
				 WHERE GEN.ATTR_ENTI = 'SEG_PAIS'
				 	   AND GEN.IDIO_OID_IDIO = 1 			-- PARAMETRO DE IDIOMA --
			 ) GEN_PAIS,
			 (
		 SELECT GEN.VAL_OID, GEN.VAL_I18N
		 FROM V_GEN_I18N_SICC GEN
		 WHERE GEN.ATTR_ENTI = 'SEG_SOCIE'
		 	   AND GEN.IDIO_OID_IDIO = 1 			-- PARAMETRO DE IDIOMA --
			 ) GEN_SOCI,
			 (
				 SELECT GEN.VAL_OID, GEN.VAL_I18N
				 FROM V_GEN_I18N_SICC GEN
				 WHERE GEN.ATTR_ENTI = 'SEG_TIPO_VIA'		   			 
				 	   AND GEN.IDIO_OID_IDIO = 1						 -- PARAMETRO DE IDIOMA --
			 ) GEN_TIP_VIA
		WHERE ASI_COB.CRCO_OID_CRON_COBR = CRO_COB.OID_CRON_COBR
			  AND PERIO.CANA_OID_CANA = CANAL.OID_CANA
			  AND PERIO.MARC_OID_MARC = MARCA.OID_MARC
			  AND PERIO.OID_PERI = CRO_COB.PERD_OID_PERI
			  AND USU_COB.OID_USUA_COBR = CRO_COB.USCO_OID_USUA_COBR
			  AND GRU_USU.USCO_OID_USUA_COBR = USU_COB.OID_USUA_COBR
			  AND SUBG.OID_SUBG_VENT = REG.ZSGV_OID_SUBG_VENT
			  AND ZONA.ZORG_OID_REGI = REG.OID_REGI
			  AND ZONA.OID_ZONA = SEC.ZZON_OID_ZONA
			  AND SEC.OID_SECC = TER_ADM.ZSCC_OID_SECC
			  AND TER_ADM.TERR_OID_TERR = TER.OID_TERR	    
			  AND SUBG.CANA_OID_CANA = CANAL.OID_CANA
			  AND SUBG.MARC_OID_MARC = MARCA.OID_MARC
			  AND DATOS_CLI.CLIE_OID_CLIE(+) = CLI.OID_CLIE	
			  AND MCC.ZORG_OID_REGI = REG.OID_REGI
			  AND MCC.ZSCC_OID_SECC = SEC.OID_SECC
			  AND MCC.ZSGV_OID_SUBG_VENT = SUBG.OID_SUBG_VENT
		--	  AND MCC.ZTAD_OID_TERR_ADMI = TER_ADM.OID_TERR_ADMI
			  AND ASI_COB.MVCC_OID_MOVI_CC = MCC.OID_MOVI_CC
		      AND CLI.OID_CLIE = MCC.CLIE_OID_CLIE
			  AND EST_ASG.OID_ESTA_ASIG = ASI_COB.ESAS_OID_ESTA_ASIG	  
			  AND (EST_ASG.OID_ESTA_ASIG = 2 OR EST_ASG.OID_ESTA_ASIG = 3 OR EST_ASG.OID_ESTA_ASIG = 6) 
			  AND DATOS_CLI.OID_TIPO_VIA = GEN_TIP_VIA.VAL_OID(+)
			  AND ZONA.PAIS_OID_PAIS = GEN_PAIS.VAL_OID(+)
			  AND ASI_COB.SOCI_OID_SOCI = GEN_SOCI.VAL_OID(+)  
		--	  AND CRO_COB.USCO_OID_USUA_COBR = 1							-- PARAMETRO DE USUARIO --
		--	  AND GRU_USU.GUCO_OID_GRUP_USUA_COBR = 1							-- PARAMETRO DE GRUPO DE USUARIO --
		--	  AND MARCA.OID_MARC = 1	   									-- PARAMETRO DE MARCA --
		--	  AND CANAL.OID_CANA = 1										-- PARAMETRO DE CANAL --
		--	  AND CRO_COB.PERD_OID_PERI = 1									-- PARAMETRO DE PERIODO --
		--	  AND REG.OID_REGI = 1									-- PARAMETRO DE REGION --
		--	  AND ZONA.OID_ZONA = 1								-- PARAMETRO DE ZONA --
		--	  AND SEC.OID_SECC = 1									-- PARAMETRO DE SECCION --
		--	  AND TER.COD_TERR = '1'									-- PARAMETRO DE TERRITORIO -- 	 
			  AND ASI_COB.PAIS_OID_PAIS = 1									-- PARAMETRO DE PAIS --
		      AND TO_DATE(ASI_COB.FEC_ASIG) > TO_DATE('01/03/2005', 'DD/MM/YYYY') --PARAMETRO DE FECHA DE ASIGNACION --
	) COB,
	(
		SELECT OID_MOVI_CC,
			   FEC_RANGO1,
			   SUM(RANGO_1) RANGO_1,
			   FEC_RANGO2,
			   SUM(RANGO_2) RANGO_2,
			   FEC_RANGO3,
		   	   SUM(RANGO_3) RANGO_3,
			   FEC_RANGO4,
			   SUM(RANGO_4) RANGO_4,
			   FEC_RANGO5,
			   SUM(RANGO_5) RANGO_5,
			   FEC_RANGO6,
			   SUM(RANGO_6) RANGO_6
		FROM	   	   	   
			(
			 SELECT OID_MOVI_CC,
			 		CASE WHEN (TO_DATE('01/03/2005', 'DD/MM/YYYY') + 15) > SYSDATE THEN  -- PARAMETRO DE FECHA DE ASIGNACION --
						 TO_DATE('01/03/2005', 'DD/MM/YYYY')||' '||SYSDATE 		   		 -- PARAMETRO DE FECHA DE ASIGNACION --
					ELSE
						TO_DATE('01/03/2005', 'DD/MM/YYYY')||' '||(TO_DATE('01/03/2005', 'DD/MM/YYYY') + 15) -- PARAMETRO DE FECHA DE ASIGNACION --
					END AS FEC_RANGO1,
			 	   CASE WHEN (TO_DATE('01/03/2005', 'DD/MM/YYYY') <= FECHA AND (TO_DATE('01/03/2005', 'DD/MM/YYYY') + 15) >= FECHA) THEN   -- PARAMETRO DE FECHA DE ASIGNACION --
				   		SUM(IMPORTE)
				   END AS RANGO_1,
				   CASE WHEN (TO_DATE('01/03/2005', 'DD/MM/YYYY') + 16) > SYSDATE THEN -- PARAMETRO DE FECHA DE ASIGNACION --
				   		NULL
				   ELSE
				   	   CASE WHEN (TO_DATE('01/03/2005', 'DD/MM/YYYY') + 30) > SYSDATE THEN  -- PARAMETRO DE FECHA DE ASIGNACION --
					   		(TO_DATE('01/03/2005', 'DD/MM/YYYY') + 16)||' '||SYSDATE -- PARAMETRO DE FECHA DE ASIGNACION --
						ELSE
							(TO_DATE('01/03/2005', 'DD/MM/YYYY') + 16)||' '||(TO_DATE('01/03/2005', 'DD/MM/YYYY') + 30) -- PARAMETRO DE FECHA DE ASIGNACION --
						END 
				  END AS FEC_RANGO2,		    
				   CASE WHEN ((TO_DATE('01/03/2005', 'DD/MM/YYYY') + 16) <= FECHA AND (TO_DATE('01/03/2005', 'DD/MM/YYYY') + 30) >= FECHA) THEN  -- PARAMETRO DE FECHA DE ASIGNACION --
				   		SUM(IMPORTE)
				   END AS RANGO_2,
				   CASE WHEN (TO_DATE('01/03/2005', 'DD/MM/YYYY') + 31) > SYSDATE THEN -- PARAMETRO DE FECHA DE ASIGNACION --
				   		NULL
				   ELSE
				   	   CASE WHEN (TO_DATE('01/03/2005', 'DD/MM/YYYY') + 45) > SYSDATE THEN  -- PARAMETRO DE FECHA DE ASIGNACION --
					   		(TO_DATE('01/03/2005', 'DD/MM/YYYY') + 31)||' '||SYSDATE -- PARAMETRO DE FECHA DE ASIGNACION --
						ELSE
							(TO_DATE('01/03/2005', 'DD/MM/YYYY') + 31)||' '||(TO_DATE('01/03/2005', 'DD/MM/YYYY') + 45) -- PARAMETRO DE FECHA DE ASIGNACION --
						END 
				  END AS FEC_RANGO3,		    
				   CASE WHEN ((TO_DATE('01/03/2005', 'DD/MM/YYYY') + 31) <= FECHA AND (TO_DATE('01/03/2005', 'DD/MM/YYYY') + 45) >= FECHA) THEN  -- PARAMETRO DE FECHA DE ASIGNACION --
				   		SUM(IMPORTE)
				   END AS RANGO_3,
				   CASE WHEN (TO_DATE('01/03/2005', 'DD/MM/YYYY') + 46) > SYSDATE THEN -- PARAMETRO DE FECHA DE ASIGNACION --
				   		NULL
				   ELSE
				   	   CASE WHEN (TO_DATE('01/03/2005', 'DD/MM/YYYY') + 60) > SYSDATE THEN  -- PARAMETRO DE FECHA DE ASIGNACION --
					   		(TO_DATE('01/03/2005', 'DD/MM/YYYY') + 46)||' '||SYSDATE -- PARAMETRO DE FECHA DE ASIGNACION --
						ELSE
							(TO_DATE('01/03/2005', 'DD/MM/YYYY') + 46)||' '||(TO_DATE('01/03/2005', 'DD/MM/YYYY') + 60) -- PARAMETRO DE FECHA DE ASIGNACION --
						END 
				  END AS FEC_RANGO4,		    
				   CASE WHEN ((TO_DATE('01/03/2005', 'DD/MM/YYYY') + 46) <= FECHA AND (TO_DATE('01/03/2005', 'DD/MM/YYYY') + 60) >= FECHA) THEN  -- PARAMETRO DE FECHA DE ASIGNACION --
				   		SUM(IMPORTE)
				   END AS RANGO_4,
				   CASE WHEN (TO_DATE('01/03/2005', 'DD/MM/YYYY') + 61) > SYSDATE THEN -- PARAMETRO DE FECHA DE ASIGNACION --
				   		NULL
				   ELSE
				   	   CASE WHEN (TO_DATE('01/03/2005', 'DD/MM/YYYY') + 75) > SYSDATE THEN  -- PARAMETRO DE FECHA DE ASIGNACION --
					   		(TO_DATE('01/03/2005', 'DD/MM/YYYY') + 61)||' '||SYSDATE -- PARAMETRO DE FECHA DE ASIGNACION --
						ELSE
							(TO_DATE('01/03/2005', 'DD/MM/YYYY') + 61)||' '||(TO_DATE('01/03/2005', 'DD/MM/YYYY') + 75) -- PARAMETRO DE FECHA DE ASIGNACION --
						END 
				  END AS FEC_RANGO5,		    
				   CASE WHEN ((TO_DATE('01/03/2005', 'DD/MM/YYYY') + 61) <= FECHA AND (TO_DATE('01/03/2005', 'DD/MM/YYYY') + 75) >= FECHA) THEN  -- PARAMETRO DE FECHA DE ASIGNACION --
				   		SUM(IMPORTE)
				   END AS RANGO_5,
				   CASE WHEN (TO_DATE('01/03/2005', 'DD/MM/YYYY') + 76) > SYSDATE THEN -- PARAMETRO DE FECHA DE ASIGNACION --
				   		NULL
				   ELSE
				   	   CASE WHEN (TO_DATE('01/03/2005', 'DD/MM/YYYY') + 90) > SYSDATE THEN  -- PARAMETRO DE FECHA DE ASIGNACION --
					   		(TO_DATE('01/03/2005', 'DD/MM/YYYY') + 76)||' '||SYSDATE -- PARAMETRO DE FECHA DE ASIGNACION --
						ELSE
							(TO_DATE('01/03/2005', 'DD/MM/YYYY') + 76)||' '||(TO_DATE('01/03/2005', 'DD/MM/YYYY') + 90) -- PARAMETRO DE FECHA DE ASIGNACION --
						END 
				  END AS FEC_RANGO6,		    
				   CASE WHEN ((TO_DATE('01/03/2005', 'DD/MM/YYYY') + 76) <= FECHA AND (TO_DATE('01/03/2005', 'DD/MM/YYYY') + 90) >= FECHA) THEN  -- PARAMETRO DE FECHA DE ASIGNACION --
				   		SUM(IMPORTE)
				   END AS RANGO_6
			 FROM
				 (
					SELECT OID_MOVI_CC,
						   FECHA,
						   IMPORTE				
					FROM
					(
						(
					------------------------- MOVIMIENTOS DE CUENTA CORRIENTE --------------------------------------			
							SELECT MOV_CCC.OID_MOVI_CC,
								   MOV_CCC.FEC_ULTI_MOVI FECHA,
								   MOV_CCC.IMP_PAGO IMPORTE
							FROM COB_ASIGN_COBRA ASI_COB,
								 COB_ESTAD_ASIGN EST_ASG,
					 			 CCC_MOVIM_CUENT_CORRI MOV_CCC
							WHERE TO_DATE('01/03/2005', 'DD/MM/YYYY') <= MOV_CCC.FEC_ULTI_MOVI -- PARAMETRO DE FECHA DE ASIGNACION --
					  			  AND MOV_CCC.FEC_ULTI_MOVI <= (CASE WHEN (TO_DATE('01/03/2005', 'DD/MM/YYYY') + 90) > SYSDATE THEN -- PARAMETRO DE FECHA DE ASIGNACION --
								  	  						   		SYSDATE
																ELSE
																	(TO_DATE('01/03/2005', 'DD/MM/YYYY') + 90)  --PARAMETRO DE FECHA DE ASIGNACION --  
																END)					  
								  AND EST_ASG.OID_ESTA_ASIG = ASI_COB.ESAS_OID_ESTA_ASIG	  
								  AND (EST_ASG.OID_ESTA_ASIG = 2 OR EST_ASG.OID_ESTA_ASIG = 3 OR EST_ASG.OID_ESTA_ASIG = 6)
								  AND ASI_COB.PAIS_OID_PAIS = 1	 						  	-- PARAMETRO DE PAIS ---
							      AND TO_DATE(ASI_COB.FEC_ASIG) > TO_DATE('01/03/2005', 'DD/MM/YYYY') --PARAMETRO DE FECHA DE ASIGNACION --					  
						)
						UNION
						(
					-------------------- MOVIMIENTOS EN HISTORICO DE CUENTAS CORRIENTES ------------------------------------------
							SELECT HTO.MVCC_OID_MOVI_CC,
								   HTO.FEC_MOVI FECHA, 
								   HTO.IMP_PAGO IMPORTE
							FROM COB_ASIGN_COBRA ASI_COB,
								 COB_ESTAD_ASIGN EST_ASG,
					 			 CCC_HISTO_MOVIM_CC HTO,
								 CCC_MOVIM_CUENT_CORRI MOV_CCC
							WHERE MOV_CCC.OID_MOVI_CC = HTO.MVCC_OID_MOVI_CC
								  AND TO_DATE('01/03/2005', 'DD/MM/YYYY') <= HTO.FEC_MOVI -- PARAMETRO DE FECHA DE ASIGNACION --
					  			  AND HTO.FEC_MOVI <= (CASE WHEN (TO_DATE('01/03/2005', 'DD/MM/YYYY') + 90) > SYSDATE THEN -- PARAMETRO DE FECHA DE ASIGNACION --
			 	  					  	  	 			   SYSDATE
													  ELSE
														   (TO_DATE('01/03/2005', 'DD/MM/YYYY') + 90)  -- PARAMETRO DE FECHA DE ASIGNACION -- 
				       								  END)																	  	  
			    				  AND EST_ASG.OID_ESTA_ASIG = ASI_COB.ESAS_OID_ESTA_ASIG	  
								  AND (EST_ASG.OID_ESTA_ASIG = 2 OR EST_ASG.OID_ESTA_ASIG = 3 OR EST_ASG.OID_ESTA_ASIG = 6)
								  AND ASI_COB.PAIS_OID_PAIS = 1	 						  	-- PARAMETRO DE PAIS ---
								 AND TO_DATE(ASI_COB.FEC_ASIG) > TO_DATE('01/03/2005', 'DD/MM/YYYY') --PARAMETRO DE FECHA DE ASIGNACION --					  
						) 
					)
				 ) 
			GROUP BY OID_MOVI_CC,
				  FECHA
			)
		GROUP BY OID_MOVI_CC,
			  FEC_RANGO1,
			  FEC_RANGO2,
			  FEC_RANGO3,
			  FEC_RANGO4,
			  FEC_RANGO5,
			  FEC_RANGO6	  
	) MOV	
WHERE COB.OID_MOVI_CC = MOV.OID_MOVI_CC  