SELECT CLI.COD_CLIE COD_CONS,
	   CLI.VAL_NOM1||' '||CLI.VAL_NOM2||' '||CLI.VAL_APE1||' '||CLI.VAL_APE2 NOMBRE_CONS,
	   (
		   SELECT DES_REGI||' / '||DES_ZONA||' / '||COD_TERR
		   FROM
		   (
			   SELECT REG.DES_REGI,
			   		  ZONA.DES_ZONA,
					  TER.COD_TERR
			   FROM MAE_CLIEN_UNIDA_ADMIN UND_ADM,	   
		            ZON_REGIO REG,
				    ZON_ZONA ZONA,
				    ZON_SECCI SEC,
				    ZON_TERRI TER,
				    ZON_TERRI_ADMIN TER_ADM,
					CRA_PERIO PERI,
					MAE_CLIEN CLIE			
			   WHERE CLIE.OID_CLIE = UND_ADM.CLIE_OID_CLIE
			   		 AND CLIE.COD_CLIE = '00000000001'									-- PARAMETRO DE CLIENTE --
			         AND REG.OID_REGI = ZONA.ZORG_OID_REGI
			  		 AND ZONA.OID_ZONA = SEC.ZZON_OID_ZONA
			  		 AND SEC.OID_SECC = TER_ADM.ZSCC_OID_SECC
			  		 AND TER.OID_TERR = TER_ADM.TERR_OID_TERR
			  		 AND UND_ADM.ZTAD_OID_TERR_ADMI = TER_ADM.OID_TERR_ADMI
					 AND PERI.OID_PERI = UND_ADM.PERD_OID_PERI_INI
					 AND UND_ADM.IND_ACTI = 1
			   ORDER BY PERI.FEC_FINA DESC
		   )
		   WHERE ROWNUM = 1		   
	   ) UND_ADMIN,	  
	   GEN_EST.VAL_I18N ESTADO_CONS,
	   CLI.FEC_INGR FECHA_INGRESO,
	   NIV.COD_NIVE_RIES NIVEL_RIESGO,
	   CRO_COB.COD_CART CARTERA,
	   ETA_DEU.VAL_DESC GESTION,
	   USU.VAL_NOM1||' '||USU.VAL_APEL_PATE GESTORE,
	   PER.VAL_NOMB_PERI CAMP,
	   GEN_TIP_SOL.VAL_I18N DOCUMENTO,
	   MCC.VAL_EJER_CUOT||'-'||LPAD(MCC.NUM_IDEN_CUOT, 8, '0') NUM_DOCUM,
	   DECODE(MCC.FEC_VALO, NULL, MCC.FEC_DOCU, MCC.FEC_VALO) F_VALOR,
	   ASI_COB.IMP_ORIG_DEUD IMPORTE,	   
	   ASI_COB.IMP_DEUD_ASIG IMPORTE_CARTERA,
	   ASI_COB.FEC_ASIG FECHA_ASIG,
	   (
	   	  SELECT VAL_DESC
		  FROM
		  (
	   		SELECT CAC.VAL_DESC
			FROM COB_GESTI_COBRA CGC,
				 COB_ACCIO_COBRA CAC,
				 MAE_CLIEN C
			WHERE CGC.CLIE_OID_CLIE = C.OID_CLIE
				  AND C.COD_CLIE = '00000000001'
				  AND CGC.ACCO_OID_ACCI_COBR = CAC.OID_ACCI_COBR
		    ORDER BY CGC.FEC_GEST DESC
		 )
		 WHERE ROWNUM = 1
	   ) GESTION_EFEC,
	   ASI_COB.IMP_DEUD_CANC DEUDA_CAN,
	   MCC.FEC_ULTI_MOVI FECHA_PAGO
FROM MAE_CLIEN CLI,
	 MAE_CLIEN_DATOS_ADICI CLI_DAT,
	 COB_ASIGN_COBRA ASI_COB,
	 COB_CRONO_COBRA CRO_COB,
     COB_ESTAD_ASIGN EST_ASG,
	 CCC_MOVIM_CUENT_CORRI MCC,
	 MAE_ESTAT_CLIEN EST_CLI,
	 CAR_NIVEL_RIESG NIV,
	 COB_ETAPA_DEUDA ETA_DEU,
	 CRA_PERIO PER,
	 PED_TIPO_SOLIC TIP_SOL,
	 PED_TIPO_SOLIC_PAIS TIP_PAIS,
	 V_REP_USUAR_LARGO USU,
	 (
		 SELECT GEN.VAL_I18N, GEN.VAL_OID
		 FROM V_GEN_I18N_SICC GEN
		 WHERE GEN.ATTR_ENTI = 'MAE_ESTAT_CLIEN'
		 	   AND GEN.IDIO_OID_IDIO = 1					   			-- PARAMETRO DE IDIOMA--
	 ) GEN_EST,
 	 (
		 SELECT GEN.VAL_I18N, GEN.VAL_OID
		 FROM V_GEN_I18N_SICC GEN
		 WHERE GEN.ATTR_ENTI = 'PED_TIPO_SOLIC'
		 	   AND GEN.IDIO_OID_IDIO = 1					   			-- PARAMETRO DE IDIOMA--
	 ) GEN_TIP_SOL
WHERE CLI_DAT.CLIE_OID_CLIE = CLI.OID_CLIE
	  AND ASI_COB.CRCO_OID_CRON_COBR = CRO_COB.OID_CRON_COBR
	  AND EST_ASG.OID_ESTA_ASIG = ASI_COB.ESAS_OID_ESTA_ASIG
	--  AND (EST_ASG.OID_ESTA_ASIG = 2 OR EST_ASG.OID_ESTA_ASIG = 3) 
	  AND MCC.OID_MOVI_CC = ASI_COB.MVCC_OID_MOVI_CC 
	  AND MCC.CLIE_OID_CLIE = CLI.OID_CLIE
	  AND MCC.COD_USUA = USU.VAL_NOMB_USUA
	  AND EST_CLI.OID_ESTA_CLIE = CLI_DAT.ESTA_OID_ESTA_CLIE
	  AND EST_CLI.OID_ESTA_CLIE = GEN_EST.VAL_OID(+)
	  AND TIP_SOL.OID_TIPO_SOLI = GEN_TIP_SOL.VAL_OID(+)
	  AND MCC.TSPA_OID_TIPO_SOLI_PAIS = TIP_PAIS.OID_TIPO_SOLI_PAIS(+)
	  AND TIP_PAIS.TSOL_OID_TIPO_SOLI = TIP_SOL.OID_TIPO_SOLI(+)
	  AND NIV.OID_NIVE_RIES = CLI_DAT.NIRI_OID_NIVE_RIES
	  AND ETA_DEU.OID_ETAP_DEUD = CRO_COB.ETDE_OID_ETAP_DEUD
	  AND MCC.PERD_OID_PERI = PER.OID_PERI
	  AND CLI.PAIS_OID_PAIS = 1										  	-- PARAMETRO DE pais --
	  AND CLI.COD_CLIE = '00000000001'									-- PARAMETRO DE CLIENTE --