



SELECT *
FROM
(
	(
	SELECT VIRTUAL.ETAPA,
		   VIRTUAL.ETAPA_FIN,
		   VIRTUAL.COD_PERI,
		   VIRTUAL.VAL_ANIO,
		   DATOS_ASIG.IMP_DEUD_ASIG VENTA_COB,
		   DATOS_PED.IMP_TOT_VEN TOTAL_VENTA,
		   DECODE(DATOS_PED.IMP_TOT_VEN, 0, 0, (DATOS_ASIG.IMP_DEUD_ASIG/DATOS_PED.IMP_TOT_VEN)*100) VENTA_COB_PORC,
		   DATOS_ASIG.IMP_DEUD_CANC COBRANZA,
		   DECODE(DATOS_ASIG.IMP_DEUD_ASIG, 0, 0, (DATOS_ASIG.IMP_DEUD_CANC / DATOS_ASIG.IMP_DEUD_ASIG)*100) REC_PORC
	FROM	
	( 
	SELECT PER_COR.OID_PERI,
		   NVL(SUM(ASI_COB.IMP_DEUD_ASIG), 0) IMP_DEUD_ASIG,
		   NVL(SUM(ASI_COB.IMP_DEUD_CANC), 0) IMP_DEUD_CANC
	FROM SEG_PERIO_CORPO PER_COR,
		 COB_ASIGN_COBRA ASI_COB,
		 COB_CRONO_COBRA CRO_COB,
		 CRA_PERIO PER,
		 ZON_SECCI SEC,
		 ZON_TERRI_ADMIN TER_ADM,
		 ZON_TERRI TER,
		 COB_ETAPA_DEUDA ETAPA,
		 CCC_MOVIM_CUENT_CORRI MCC
	WHERE PER_COR.VAL_ANIO = (CASE WHEN -1 = 57 THEN 							-- PARAMETRO DE PERIODO --
		  				     	TO_NUMBER(TO_CHAR(SYSDATE, 'YYYY'))
					     	ELSE
								(
								SELECT PC.VAL_ANIO
								FROM CRA_PERIO PER,
									 SEG_PERIO_CORPO PC
								WHERE PER.OID_PERI = 57                        -- PARAMETRO DE PERIODO --
									  AND PC.OID_PERI = PER.PERI_OID_PERI
									  AND PER.MARC_OID_MARC = 1			 	   -- PARAMETRO DE MARCA --
									  AND PER.CANA_OID_CANA = 1				   -- PERAMETRO DE CANAL --
								)
							END)
			AND CRO_COB.OID_CRON_COBR = ASI_COB.CRCO_OID_CRON_COBR
			AND CRO_COB.ETDE_OID_ETAP_DEUD = ETAPA.OID_ETAP_DEUD 
			AND CRO_COB.PERD_OID_PERI = PER.OID_PERI 
			AND PER_COR.OID_PERI = PER.PERI_OID_PERI
			AND SEC.OID_SECC = TER_ADM.ZSCC_OID_SECC
			AND TER.OID_TERR = TER_ADM.TERR_OID_TERR
			AND MCC.OID_MOVI_CC = ASI_COB.MVCC_OID_MOVI_CC
			AND MCC.ZSCC_OID_SECC = SEC.OID_SECC
	--		AND MCC.ZTAD_OID_TERR_ADMI = TER_ADM.OID_TERR_ADMI
	--		AND TER.COD_TERR >= 1						   	  	  		 	   -- PARAMETRO DE TERRITORIO DESDE--
	--		AND TER.COD_TERR <= 1						   	  	  		 	   -- PARAMETRO DE TERRITORIO HASTA--		
	--		AND SEC.OID_SECC = 1  				 	 			  		 	   -- PARAMETRO DE SECCION --
	--		AND SEC.ZZON_OID_ZONA= 1 				 	 			  		 	   -- PARAMETRO DE ZONA --
	--		AND MCC.ZORG_OID_REGI= 1  				 	 			  		 	   -- PARAMETRO DE REGION --
			AND ETAPA.OID_ETAP_DEUD = 1				 			  		 	   -- PARAMETRO DE ETAPA DE DEUDA --
			AND PER.PAIS_OID_PAIS = 1				 			  		 	   -- PARAMETRO DE PAIS --
	GROUP BY PER_COR.OID_PERI
	) DATOS_ASIG,
	(
	   SELECT PER_COR.OID_PERI,
	   		  NVL(SUM(SOL.VAL_TOTA_PAGA_LOCA), 0) IMP_TOT_VEN
	   FROM PED_SOLIC_CABEC SOL,
	   		ZON_SUB_GEREN_VENTA SUBG,
			ZON_ZONA ZONA,
			ZON_REGIO REG,
			ZON_SECCI SEC,
			ZON_TERRI_ADMIN TER_ADM,
			ZON_TERRI TER,
			CRA_PERIO PER,
			SEG_PERIO_CORPO PER_COR
		WHERE PER_COR.VAL_ANIO = (CASE WHEN -1 = 57 THEN 							-- PARAMETRO DE PERIODO --
	 				     	TO_NUMBER(TO_CHAR(SYSDATE, 'YYYY'))
			     	ELSE
						(
						SELECT PC.VAL_ANIO
						FROM CRA_PERIO PER,
							 SEG_PERIO_CORPO PC
						WHERE PER.OID_PERI = 57                        -- PARAMETRO DE PERIODO --
							  AND PC.OID_PERI = PER.PERI_OID_PERI
							  AND PER.MARC_OID_MARC = 1			 	   -- PARAMETRO DE MARCA --
							  AND PER.CANA_OID_CANA = 1				   -- PERAMETRO DE CANAL --
						)
					END)
			AND SOL.PERD_OID_PERI = PER.OID_PERI
			AND PER_COR.OID_PERI = PER.PERI_OID_PERI
			AND SOL.ZZON_OID_ZONA = ZONA.OID_ZONA
			AND SOL.ZTAD_OID_TERR_ADMI = TER_ADM.OID_TERR_ADMI
			AND SOL.TERR_OID_TERR = TER.OID_TERR
			AND SUBG.OID_SUBG_VENT = REG.ZSGV_OID_SUBG_VENT
			AND REG.OID_REGI = ZONA.ZORG_OID_REGI
			AND ZONA.OID_ZONA = SEC.ZZON_OID_ZONA
			AND SEC.OID_SECC = TER_ADM.ZSCC_OID_SECC
			AND TER.OID_TERR = TER_ADM.TERR_OID_TERR
			AND PER.PERI_OID_PERI = PER_COR.OID_PERI
	--		AND SOL.IND_TS_NO_CONSO <> 1
			AND SOL.IND_GENE_CC = 1
			AND SOL.IND_PEDI_PRUE <> 1
			AND SOL.FEC_FACT IS NOT NULL
	--		AND TER.COD_TERR >= 1						   	  	  		 	   -- PARAMETRO DE TERRITORIO DESDE--
	--		AND TER.COD_TERR <= 1						   	  	  		 	   -- PARAMETRO DE TERRITORIO HASTA--		
	--		AND SEC.OID_SECC = 1  				 	 			  		 	   -- PARAMETRO DE SECCION --
	--		AND ZONA.OID_ZONA = 1 				 	 			  		 	   -- PARAMETRO DE ZONA --
	--		AND REG.OID_REGI = 1  				 	 			  		 	   -- PARAMETRO DE REGION --
	--		AND SUBG.MARC_OID_MARC = 1			 	 			  		 	   -- PARAMETRO DE MARCA --
	--		AND SUBG.CANA_OID_CANA = 1			 	 			  		 	   -- PARAMETRO DE CANAL --						
			AND SOL.PAIS_OID_PAIS = 1				 			  		 	   -- PARAMETRO DE PAIS --
		GROUP BY PER_COR.OID_PERI
	) DATOS_PED,
	(
	SELECT (
		   SELECT ET.VAL_DESC||': '||ET.VAL_EDAD_INIC
		   FROM COB_ETAPA_DEUDA ET
		   WHERE ET.OID_ETAP_DEUD = 1   									   	-- PARAMETRO DE ETAPA DE DEUDA --
		   ) ETAPA,
		   (
		   SELECT ET.VAL_EDAD_FINA
		   FROM COB_ETAPA_DEUDA ET
		   WHERE ET.OID_ETAP_DEUD = 1   									   	-- PARAMETRO DE ETAPA DE DEUDA --
		   ) ETAPA_FIN,
		   OID_PERI, 
		   COD_PERI,
		   VAL_ANIO 			
	FROM SEG_PERIO_CORPO PER_COR
	WHERE PER_COR.VAL_ANIO = (CASE WHEN -1 = 57 THEN								-- PARAMETRO DE PERIODO --
		  				     	TO_NUMBER(TO_CHAR(SYSDATE, 'YYYY'))
					     	ELSE
								(
								SELECT PC.VAL_ANIO
								FROM CRA_PERIO PER,
									 SEG_PERIO_CORPO PC
								WHERE PER.OID_PERI = 57                        -- PARAMETRO DE PERIODO --
									  AND PC.OID_PERI = PER.PERI_OID_PERI
									  AND PER.MARC_OID_MARC = 1			 	   -- PARAMETRO DE MARCA --
									  AND PER.CANA_OID_CANA = 1				   -- PERAMETRO DE CANAL --
								)
							END)
	) VIRTUAL			
	WHERE DATOS_ASIG.OID_PERI(+) = VIRTUAL.OID_PERI
		AND DATOS_PED.OID_PERI(+) = VIRTUAL.OID_PERI	
	) 						
	UNION ALL
	(
	SELECT VIRTUAL.ETAPA,
		   VIRTUAL.ETAPA_FIN,
		   VIRTUAL.COD_PERI,
		   VIRTUAL.VAL_ANIO,
		   DATOS_ASIG.IMP_DEUD_ASIG VENTA_COB,
		   DATOS_PED.IMP_TOT_VEN TOTAL_VENTA,
		   DECODE(DATOS_PED.IMP_TOT_VEN, 0, 0, (DATOS_ASIG.IMP_DEUD_ASIG/DATOS_PED.IMP_TOT_VEN)*100) VENTA_COB_PORC,
		   DATOS_ASIG.IMP_DEUD_CANC COBRANZA,
		   DECODE(DATOS_ASIG.IMP_DEUD_ASIG, 0, 0, (DATOS_ASIG.IMP_DEUD_CANC / DATOS_ASIG.IMP_DEUD_ASIG)*100) REC_PORC
	FROM	
	( 
		SELECT PER_COR.OID_PERI,
			   NVL(SUM(ASI_COB.IMP_DEUD_ASIG), 0) IMP_DEUD_ASIG,
			   NVL(SUM(ASI_COB.IMP_DEUD_CANC), 0) IMP_DEUD_CANC
		FROM SEG_PERIO_CORPO PER_COR,
			 COB_ASIGN_COBRA ASI_COB,
			 COB_CRONO_COBRA CRO_COB,
			 CRA_PERIO PER,
			 ZON_SECCI SEC,
			 ZON_TERRI_ADMIN TER_ADM,
			 ZON_TERRI TER,
			 COB_ETAPA_DEUDA ETAPA,
			 CCC_MOVIM_CUENT_CORRI MCC
		WHERE PER_COR.VAL_ANIO = ((CASE WHEN -1 = 57 THEN 							-- PARAMETRO DE PERIODO --
			  				     	TO_NUMBER(TO_CHAR(SYSDATE, 'YYYY'))
						     	ELSE
									(
									SELECT PC.VAL_ANIO
									FROM CRA_PERIO PER,
										 SEG_PERIO_CORPO PC
									WHERE PER.OID_PERI = 57                        -- PARAMETRO DE PERIODO --
										  AND PC.OID_PERI = PER.PERI_OID_PERI
										  AND PER.MARC_OID_MARC = 1			 	   -- PARAMETRO DE MARCA --
										  AND PER.CANA_OID_CANA = 1				   -- PERAMETRO DE CANAL --
									)
								END)-1)
				AND CRO_COB.OID_CRON_COBR = ASI_COB.CRCO_OID_CRON_COBR
				AND CRO_COB.ETDE_OID_ETAP_DEUD = ETAPA.OID_ETAP_DEUD 
				AND CRO_COB.PERD_OID_PERI = PER.OID_PERI 
				AND PER_COR.OID_PERI = PER.PERI_OID_PERI
				AND SEC.OID_SECC = TER_ADM.ZSCC_OID_SECC
				AND TER.OID_TERR = TER_ADM.TERR_OID_TERR
				AND MCC.OID_MOVI_CC = ASI_COB.MVCC_OID_MOVI_CC
				AND MCC.ZSCC_OID_SECC = SEC.OID_SECC
		--		AND MCC.ZTAD_OID_TERR_ADMI = TER_ADM.OID_TERR_ADMI
		--		AND TER.COD_TERR >= 1						   	  	  		 	   -- PARAMETRO DE TERRITORIO DESDE--
		--		AND TER.COD_TERR <= 1						   	  	  		 	   -- PARAMETRO DE TERRITORIO HASTA--		
		--		AND SEC.OID_SECC = 1  				 	 			  		 	   -- PARAMETRO DE SECCION --
		--		AND SEC.ZZON_OID_ZONA= 1 				 	 			  		 	   -- PARAMETRO DE ZONA --
		--		AND MCC.ZORG_OID_REGI= 1  				 	 			  		 	   -- PARAMETRO DE REGION --
				AND ETAPA.OID_ETAP_DEUD = 1				 			  		 	   -- PARAMETRO DE ETAPA DE DEUDA --
				AND PER.PAIS_OID_PAIS = 1				 			  		 	   -- PARAMETRO DE PAIS --
		GROUP BY PER_COR.OID_PERI
	) DATOS_ASIG,
	(
	   SELECT PER_COR.OID_PERI,
	   		  NVL(SUM(SOL.VAL_TOTA_PAGA_LOCA), 0) IMP_TOT_VEN
	   FROM PED_SOLIC_CABEC SOL,
	   		ZON_SUB_GEREN_VENTA SUBG,
			ZON_ZONA ZONA,
			ZON_REGIO REG,
			ZON_SECCI SEC,
			ZON_TERRI_ADMIN TER_ADM,
			ZON_TERRI TER,
			CRA_PERIO PER,
			SEG_PERIO_CORPO PER_COR
		WHERE PER_COR.VAL_ANIO = ((CASE WHEN -1 = 57 THEN 							-- PARAMETRO DE PERIODO --
	 				     	TO_NUMBER(TO_CHAR(SYSDATE, 'YYYY'))
			     	ELSE
						(
						SELECT PC.VAL_ANIO
						FROM CRA_PERIO PER,
							 SEG_PERIO_CORPO PC
						WHERE PER.OID_PERI = 57                        -- PARAMETRO DE PERIODO --
							  AND PC.OID_PERI = PER.PERI_OID_PERI
							  AND PER.MARC_OID_MARC = 1			 	   -- PARAMETRO DE MARCA --
							  AND PER.CANA_OID_CANA = 1				   -- PERAMETRO DE CANAL --
						)
					END)-1)
			AND SOL.PERD_OID_PERI = PER.OID_PERI
			AND PER_COR.OID_PERI = PER.PERI_OID_PERI
			AND SOL.ZZON_OID_ZONA = ZONA.OID_ZONA
			AND SOL.ZTAD_OID_TERR_ADMI = TER_ADM.OID_TERR_ADMI
			AND SOL.TERR_OID_TERR = TER.OID_TERR
			AND SUBG.OID_SUBG_VENT = REG.ZSGV_OID_SUBG_VENT
			AND REG.OID_REGI = ZONA.ZORG_OID_REGI
			AND ZONA.OID_ZONA = SEC.ZZON_OID_ZONA
			AND SEC.OID_SECC = TER_ADM.ZSCC_OID_SECC
			AND TER.OID_TERR = TER_ADM.TERR_OID_TERR
			AND PER.PERI_OID_PERI = PER_COR.OID_PERI
	--		AND SOL.IND_TS_NO_CONSO <> 1
			AND SOL.IND_GENE_CC = 1
			AND SOL.IND_PEDI_PRUE <> 1
			AND SOL.FEC_FACT IS NOT NULL
	--		AND TER.COD_TERR >= 1						   	  	  		 	   -- PARAMETRO DE TERRITORIO DESDE--
	--		AND TER.COD_TERR <= 1						   	  	  		 	   -- PARAMETRO DE TERRITORIO HASTA--		
	--		AND SEC.OID_SECC = 1  				 	 			  		 	   -- PARAMETRO DE SECCION --
	--		AND ZONA.OID_ZONA = 1 				 	 			  		 	   -- PARAMETRO DE ZONA --
	--		AND REG.OID_REGI = 1  				 	 			  		 	   -- PARAMETRO DE REGION --
	--		AND SUBG.MARC_OID_MARC = 1			 	 			  		 	   -- PARAMETRO DE MARCA --
	--		AND SUBG.CANA_OID_CANA = 1			 	 			  		 	   -- PARAMETRO DE CANAL --						
			AND SOL.PAIS_OID_PAIS = 1				 			  		 	   -- PARAMETRO DE PAIS --
		GROUP BY PER_COR.OID_PERI
	) DATOS_PED,
	(
		SELECT (
			   SELECT ET.VAL_DESC||': '||ET.VAL_EDAD_INIC
			   FROM COB_ETAPA_DEUDA ET
			   WHERE ET.OID_ETAP_DEUD = 1   									   	-- PARAMETRO DE ETAPA DE DEUDA --
			   ) ETAPA,
			   (
			   SELECT ET.VAL_EDAD_FINA
			   FROM COB_ETAPA_DEUDA ET
			   WHERE ET.OID_ETAP_DEUD = 1   									   	-- PARAMETRO DE ETAPA DE DEUDA --
			   ) ETAPA_FIN,
			   OID_PERI, 
			   COD_PERI,
			   VAL_ANIO 			
		FROM SEG_PERIO_CORPO PER_COR
		WHERE PER_COR.VAL_ANIO = ((CASE WHEN -1 = 57 THEN								-- PARAMETRO DE PERIODO --
			  				     	TO_NUMBER(TO_CHAR(SYSDATE, 'YYYY'))
						     	ELSE
									(
									SELECT PC.VAL_ANIO
									FROM CRA_PERIO PER,
										 SEG_PERIO_CORPO PC
									WHERE PER.OID_PERI = 57                        -- PARAMETRO DE PERIODO --
										  AND PC.OID_PERI = PER.PERI_OID_PERI
										  AND PER.MARC_OID_MARC = 1			 	   -- PARAMETRO DE MARCA --
										  AND PER.CANA_OID_CANA = 1				   -- PERAMETRO DE CANAL --
									)
								END)-1)
	) VIRTUAL			
	WHERE DATOS_ASIG.OID_PERI(+) = VIRTUAL.OID_PERI
		AND DATOS_PED.OID_PERI(+) = VIRTUAL.OID_PERI	
	) 						
) 
ORDER BY VAL_ANIO DESC,
	  COD_PERI ASC