SELECT 
	   I18PAIS.VAL_I18N AS PAIS,
	   MARCA.DES_MARC AS MARCA, 
	   I18CANAL.VAL_I18N AS CANAL, 
	   PERI.VAL_NOMB_PERI,
   	   I18ACTIV.VAL_I18N AS ACTIV,
	   OFDET.VAL_CODI_VENT,
	   PRODU.COD_SAP,
	   I18PRODU.VAL_I18N AS DESC_PROD,
	   OFDET.IMP_PREC_CATA,
	   OFDET.IMP_PREC_POSI,
	   CIVI.COD_CICL_VIDA, 
	   TOFE.COD_TIPO_OFER,
	   I18TCLIEN.VAL_I18N AS DESC_TIPO_CLIEN,
	   SUM(ENVIO_FORMU_VARVTA.NUM_UNID) AS CANTIDAD_ESTIMADA,
	   SUBT_CLIEN.COD_SUBT_CLIE AS SUB_TIPO_CLIEN,	     
	   T_CLASI_CLIEN.COD_TIPO_CLAS AS TIPO_CLASI_CLIEN, 
	   CLASI_CLIEN.CLAS_OID_CLAS AS CLASI_CLIEN,	
	   REGION.COD_REGI, 
	   ZONA.COD_ZONA, 
	   T_DESPA.DES_TIPO_DESP, 
	   SCRIT.DES_SUBC,
	   (
	   	CASE WHEN (DETAL_MAV.SCAS_OID_SUBC = 15) THEN 
				 TO_CHAR(CURSO.COD_CURS)
			 ELSE ''
	   END
	   ) AS VALOR_CRITERIO, 
	   SUM(ENVIO.NUM_UNID) AS TOTAL_A_ENVIAR,
	   NVL((DETAL_MAV.VAL_BASE_ESTI_DEST * DETAL_MAV.VAL_FACT_CORR * DETAL_MAV.NUM_UNID_ESTI), 0) AS UN_ESTIM,
	   SUM(DECODE(ENVIO.IND_ENVI,'P',ENVIO.NUM_UNID,0)) AS UN_PEND_ENVIO,
   	   SUM(DECODE(ENVIO.IND_ENVI,'E',ENVIO.NUM_UNID,0)) AS UN_DISTRIBUIDAS 
FROM
	CRA_PERIO PERI,
	SEG_MARCA MARCA,
	MAV_DETAL_MAV DETAL_MAV,
	PRE_MATRI_FACTU MAFA,
	PRE_OFERT_DETAL OFDET,
	MAV_ENVIO ENVIO,
	MAV_ACTIV_TIPO_DESPA ACTIV_T_DESPA,
	MAV_TIPO_DESPA T_DESPA,
----------------------------------------------------------------------------
	MAE_CLIEN_TIPO_SUBTI T_SUBTI_CLIEN,
	MAE_SUBTI_CLIEN SUBT_CLIEN,
	MAE_TIPO_CLIEN T_CLIEN,
	MAE_TIPO_CLASI_CLIEN T_CLASI_CLIEN,
	MAE_CLIEN_CLASI CLASI_CLIEN,
------------------------------------------------------------------------------
	MAE_CLIEN_UNIDA_ADMIN UNADMIN,
	ZON_TERRI_ADMIN TERR_ADMI,
	ZON_SECCI SECCI,
	ZON_ZONA ZONA,
	ZON_REGIO REGION,
----------------------------------------------------------------------------
	PRE_CICLO_VIDA CIVI,
	PRE_TIPO_OFERT TOFE,
	MAE_PRODU PRODU,
   	MAV_SUBCR_ASIGN SCRIT,
	EDU_MATRI_CURSO CURSO,
	(
	 SELECT 
	 	   ENV.DENV_OID_DETA_MAV, ENV.ACTI_OID_ACTI, ENV.NUM_UNID, ENV.CLIE_OID_CLIE, PERI.PAIS_OID_PAIS
	 FROM
		   MAV_DETAL_MAV DET,
	 	   MAV_ENVIO ENV,
		   MAV_SUBCR_ASIGN SCRI,
		   MAV_CRITE_ASIGN CRI,		   
		   CRA_PERIO PERI		   
	 WHERE
		       DET.SCAS_OID_SUBC = SCRI.OID_SUBC
		   AND SCRI.CRAS_OID_CRIT_ASIG = CRI.OID_CRIT_ASIG
	 	   AND ENV.DENV_OID_DETA_MAV = DET.OID_DETA_MAV
	 	   AND ENV.ACTI_OID_ACTI = DET.ACTI_OID_ACTI
	 	   AND CRI.OID_CRIT_ASIG IN (2,3)
		   AND PERI.OID_PERI = DET.PERD_OID_PERI
	) ENVIO_FORMU_VARVTA,
	(
	 SELECT V.VAL_OID, V.VAL_I18N 
	  FROM V_GEN_I18N_SICC V 
	   WHERE V.ATTR_ENTI = 'SEG_PAIS' 
	    AND V.IDIO_OID_IDIO = 1		 	 		 -- PARAMETRO --
	) I18PAIS,
	(
	 SELECT V.VAL_OID, V.VAL_I18N 
	  FROM V_GEN_I18N_SICC V 
	   WHERE V.ATTR_ENTI = 'SEG_CANAL' 
	    AND V.IDIO_OID_IDIO = 1		 	 		 -- PARAMETRO --
	) I18CANAL,
	(
	 SELECT V.VAL_OID, V.VAL_I18N 
	  FROM V_GEN_I18N_SICC V 
	   WHERE V.ATTR_ENTI = 'MAE_PRODU' 
	    AND V.IDIO_OID_IDIO = 1		 	 		 -- PARAMETRO --
	) I18PRODU,
	(
	 SELECT V.VAL_OID, V.VAL_I18N 
	  FROM V_GEN_I18N_SICC V 
	   WHERE V.ATTR_ENTI = 'MAV_ACTIV' 
	    AND V.IDIO_OID_IDIO = 1		 	 		 -- PARAMETRO --
	) I18ACTIV,
	(
	 SELECT V.VAL_OID, V.VAL_I18N 
	  FROM V_GEN_I18N_SICC V 
	   WHERE V.ATTR_ENTI = 'MAE_TIPO_CLIEN' 
	    AND V.IDIO_OID_IDIO = 1		 	 		 -- PARAMETRO --
	) I18TCLIEN
WHERE
	 	DETAL_MAV.PERD_OID_PERI = PERI.OID_PERI
	AND	DETAL_MAV.CIVI_OID_CICL_VIDA = CIVI.OID_CICL_VIDA
	AND DETAL_MAV.TOFE_OID_TIPO_OFER = TOFE.OID_TIPO_OFER
	AND PERI.MARC_OID_MARC = MARCA.OID_MARC
	AND DETAL_MAV.MAFA_OID_MATR_FACT = MAFA.OID_MATR_FACT
	AND MAFA.OFDE_OID_DETA_OFER = OFDET.OID_DETA_OFER
	AND DETAL_MAV.PROD_OID_PROD = PRODU.OID_PROD
	AND DETAL_MAV.SCAS_OID_SUBC = SCRIT.OID_SUBC
	AND DETAL_MAV.MCUR_OID_CURS = CURSO.OID_CURS(+)
-----------------------------------------------------------------------------------
	AND DETAL_MAV.ATDE_OID_ACTI_TIPO_DESP = ACTIV_T_DESPA.OID_ACTI_TIPO_DESP
	AND ACTIV_T_DESPA.TDCH_OID_TIPO_DESP = T_DESPA.OID_TIPO_DESP
-----------------------------------------------------------------------------------
	AND ENVIO.ACTI_OID_ACTI = DETAL_MAV.ACTI_OID_ACTI
	AND ENVIO.DENV_OID_DETA_MAV = DETAL_MAV.OID_DETA_MAV
	AND ENVIO_FORMU_VARVTA.ACTI_OID_ACTI(+) = DETAL_MAV.ACTI_OID_ACTI
	AND ENVIO_FORMU_VARVTA.DENV_OID_DETA_MAV(+) = DETAL_MAV.OID_DETA_MAV
	AND ENVIO_FORMU_VARVTA.CLIE_OID_CLIE = ENVIO.CLIE_OID_CLIE
	AND ENVIO_FORMU_VARVTA.PAIS_OID_PAIS = PERI.PAIS_OID_PAIS
-----------------------------------------------------------------------------------
	AND I18PAIS.VAL_OID (+)= PERI.PAIS_OID_PAIS
	AND I18CANAL.VAL_OID (+)= PERI.CANA_OID_CANA
	AND I18PRODU.VAL_OID (+)= DETAL_MAV.PROD_OID_PROD
	AND I18TCLIEN.VAL_OID (+)= DETAL_MAV.TICL_OID_TIPO_CLIE
	AND I18ACTIV.VAL_OID (+)= DETAL_MAV.ACTI_OID_ACTI
-----------------------------------------------------------------------------------
	AND ENVIO.CLIE_OID_CLIE(+) = UNADMIN.CLIE_OID_CLIE
	AND UNADMIN.IND_ACTI = 1
	AND UNADMIN.ZTAD_OID_TERR_ADMI = TERR_ADMI.OID_TERR_ADMI
	AND TERR_ADMI.ZSCC_OID_SECC = SECCI.OID_SECC
	AND SECCI.ZZON_OID_ZONA = ZONA.OID_ZONA
	AND ZONA.ZORG_OID_REGI = REGION.OID_REGI	
	AND ZONA.PAIS_OID_PAIS = PERI.PAIS_OID_PAIS
	AND ZONA.MARC_OID_MARC = PERI.MARC_OID_MARC
	AND ZONA.CANA_OID_CANA = PERI.CANA_OID_CANA
-----------------------------------------------------------------------------------
	AND ENVIO.CLIE_OID_CLIE = T_SUBTI_CLIEN.CLIE_OID_CLIE
	AND T_SUBTI_CLIEN.SBTI_OID_SUBT_CLIE = SUBT_CLIEN.OID_SUBT_CLIE
	AND SUBT_CLIEN.TICL_OID_TIPO_CLIE = T_CLIEN.OID_TIPO_CLIE
	AND SUBT_CLIEN.OID_SUBT_CLIE = T_CLASI_CLIEN.SBTI_OID_SUBT_CLIE
	AND T_CLASI_CLIEN.OID_TIPO_CLAS = CLASI_CLIEN.TCCL_OID_TIPO_CLASI			 
	AND CLASI_CLIEN.CTSU_OID_CLIE_TIPO_SUBT = T_SUBTI_CLIEN.OID_CLIE_TIPO_SUBT 	 
-----------------------------------------------------------------------------------
	AND PERI.PAIS_OID_PAIS = 1	   			   									   	  -- PARAMETRO --
	AND PERI.MARC_OID_MARC = 1	   			   										  -- PARAMETRO --
	AND PERI.CANA_OID_CANA = 1	   			   										  -- PARAMETRO --
	AND PERI.OID_PERI = 41 	 	   			   										  -- PARAMETRO --
	AND DETAL_MAV.ACTI_OID_ACTI IN (1024)											  -- PARAMETRO --
	AND PRODU.COD_SAP >= '200007725-P019' 	  										  -- PARAMETRO --
	AND PRODU.COD_SAP <= '200007726-P019'											  -- PARAMETRO --
	AND OFDET.VAL_CODI_VENT >=1								   						  -- PARAMETRO --
	AND OFDET.VAL_CODI_VENT <=9999999						   						  -- PARAMETRO --
	AND OFDET.IMP_PREC_CATA >= 1.50 		--(El Operador Viene Por Parametro)   	  -- PARAMETRO --
	AND OFDET.IMP_PREC_POSI >= 1.80 		--(El Operador Viene Por Parametro)   	  -- PARAMETRO --
	AND NVL((DETAL_MAV.VAL_BASE_ESTI_DEST * DETAL_MAV.VAL_FACT_CORR * DETAL_MAV.NUM_UNID_ESTI), 0) >= 0   -- PARAMETRO --
	AND DETAL_MAV.TICL_OID_TIPO_CLIE IN (1,2,3,4,5)									  -- PARAMETRO --
	AND DETAL_MAV.CIVI_OID_CICL_VIDA IN (2)  			   							  -- PARAMETRO --		
	AND DETAL_MAV.TOFE_OID_TIPO_OFER IN (25)  			   							  -- PARAMETRO --
GROUP BY    
	I18PAIS.VAL_I18N,
	   MARCA.DES_MARC, 
	   I18CANAL.VAL_I18N, 
	   PERI.VAL_NOMB_PERI,
   	   I18ACTIV.VAL_I18N,
	   OFDET.VAL_CODI_VENT,
	   PRODU.COD_SAP,
	   I18PRODU.VAL_I18N,
	   OFDET.IMP_PREC_CATA,
	   OFDET.IMP_PREC_POSI,
	   CIVI.COD_CICL_VIDA, 
	   TOFE.COD_TIPO_OFER,
	   I18TCLIEN.VAL_I18N,
	   SUBT_CLIEN.COD_SUBT_CLIE,	     
	   T_CLASI_CLIEN.COD_TIPO_CLAS, 
	   CLASI_CLIEN.CLAS_OID_CLAS,	
	   REGION.COD_REGI, 
	   ZONA.COD_ZONA, 
	   T_DESPA.DES_TIPO_DESP, 
	   SCRIT.DES_SUBC,
	   NVL((DETAL_MAV.VAL_BASE_ESTI_DEST * DETAL_MAV.VAL_FACT_CORR * DETAL_MAV.NUM_UNID_ESTI), 0),
	   DETAL_MAV.SCAS_OID_SUBC, CURSO.COD_CURS
ORDER BY
	I18ACTIV.VAL_I18N,
	OFDET.VAL_CODI_VENT, 
	PRODU.COD_SAP	