--ESTE LAYOUT TIENE DOS CRITERIOS DE ORDENAMIENTO QUE SE DETALLAN ABAJO
SELECT  
	   GEN_PAIS.VAL_I18N PAIS,
	   GEN_SOCIE.VAL_I18N SOCI,
	   CLI.COD_CLIE CODIGO,
	   CLI.VAL_APE1||' '||CLI.VAL_APE2||' '||CLI.VAL_NOM1||' '||CLI.VAL_NOM2 CONSULTORA,
	   MOV_CCC.VAL_DOCU_NUME CARGO,
	   MOV_CCC.VAL_REFE_NUME_DOCU_EXTE REFERENCIA,
	   ZONA.COD_ZONA ZONA,
	   MOV_CCC.FEC_DOCU FECHA,
	   PERIO.VAL_NOMB_PERI CAMP,
	   MOV_CCC.IMP_MOVI IMPORTE,
	   MOV_CCC.IMP_PEND SALDO
FROM CCC_MOVIM_CUENT_CORRI MOV_CCC,
	 CCC_PROCE PRO,
	 CCC_SUBPR SUBP,
	 CCC_TIPO_ABONO_SUBPR TIP_ABO_SUB,
	 CCC_TIPO_CARGO_ABONO TIP_CAR,
	 CRA_PERIO PERIO,
	 ZON_SUB_GEREN_VENTA SUBG,
	 ZON_REGIO REG,
	 ZON_ZONA ZONA,
	 ZON_SECCI SEC,
	 ZON_TERRI_ADMIN TER_ADM,
	 ZON_TERRI TER,
	 MAE_CLIEN CLI,
	 (
	 SELECT GEN.VAL_OID, GEN.VAL_I18N
	 FROM V_GEN_I18N_SICC GEN
	 WHERE GEN.ATTR_ENTI = 'SEG_PAIS'
	 	   AND GEN.IDIO_OID_IDIO = 1  										-- PARAMETRO DE IDIOMA --
	 ) GEN_PAIS,
 	 (
	 SELECT GEN.VAL_OID, GEN.VAL_I18N
	 FROM V_GEN_I18N_SICC GEN
	 WHERE GEN.ATTR_ENTI = 'SEG_SOCIE'
	 	   AND GEN.IDIO_OID_IDIO = 1  										-- PARAMETRO DE IDIOMA --
	 ) GEN_SOCIE
WHERE MOV_CCC.SUBP_OID_SUBP_CREA = SUBP.OID_SUBP
	  AND PERIO.CANA_OID_CANA = SUBG.CANA_OID_CANA
	  AND PERIO.MARC_OID_MARC = SUBG.MARC_OID_MARC
	  AND PERIO.PAIS_OID_PAIS = PRO.PAIS_OID_PAIS
	  AND MOV_CCC.PERD_OID_PERI = PERIO.OID_PERI
	  AND SUBP.CCPR_OID_proc= PRO.OID_PROC
--	  AND SUBP.OID_SUBP = 4
--	  AND PRO.COD_proc= 'CCC004'
	  AND TIP_ABO_SUB.SUBP_OID_SUBP = SUBP.OID_SUBP
	  AND TIP_CAR.OID_TIPO_CARG_ABON = TIP_ABO_SUB.TCAB_OID_TCAB
	  AND SUBG.PAIS_OID_PAIS = PRO.PAIS_OID_PAIS
	  AND MOV_CCC.ZORG_OID_REGI = REG.OID_REGI
	  AND REG.OID_REGI = ZONA.ZORG_OID_REGI
	  AND MOV_CCC.ZSGV_OID_SUBG_VENT = SUBG.OID_SUBG_VENT
	  AND MOV_CCC.ZTAD_OID_TERR_ADMI = TER_ADM.OID_TERR_ADMI
	  AND TER.OID_TERR = TER_ADM.TERR_OID_TERR
	  AND MOV_CCC.CLIE_OID_CLIE = CLI.OID_CLIE
	  AND SEC.OID_SECC = MOV_CCC.ZSCC_OID_SECC
	  AND SEC.ZZON_OID_ZONA = ZONA.OID_ZONA
	  AND MOV_CCC.IMP_PEND <> 0
	  AND PRO.PAIS_OID_PAIS = GEN_PAIS.VAL_OID(+)	
	  AND MOV_CCC.SOCI_OID_SOCI = GEN_SOCIE.VAL_OID(+)  
	  AND TIP_CAR.OID_TIPO_CARG_ABON = 16								  -- PARAMETRO DE TIPO DE CARGO ABONO --
	  AND TO_DATE(MOV_CCC.FEC_DOCU) >= TO_DATE('01/01/2000','DD/MM/YYYY') -- PARAMETRO DE FECHA VALOR DESDE --
	  AND TO_DATE(MOV_CCC.FEC_DOCU) <= TO_DATE('01/01/2050','DD/MM/YYYY') -- PARAMETRO DE FECHA VALOR HASTA-- 
	  AND PRO.PAIS_OID_PAIS = 1		   									  -- PARAMETRO DE PAIS --	  
	  AND SUBG.MARC_OID_MARC = 1  				  							  -- PARAMETRO DE MARCA --
	  AND SUBG.CANA_OID_CANA = 1											  -- PARAMETRO DE CANAL --
	  AND PERIO.OID_PERI IN (57)											  -- PARAMETRO DE PERIODO --  		   							
	  AND SUBG.OID_SUBG_VENT IN (1)										  -- PARAMETRO DE SUBGERENCIA --
	  AND MOV_CCC.ZORG_OID_REGI IN (1)									  -- PARAMETRO DE REGION --	
	  AND ZONA.OID_ZONA IN (1)											  -- PARAMETRO DE ZONA --
	  AND TER.COD_TERR > 1 												  -- PARAMETRO DE TERRITORIO DESDE -- 
 	  AND TER.COD_TERR < 10000											  -- PARAMETRO DE TERRITORIO HASTA --
	  AND REG.OID_REGI IN (1) --PARAMETRO REGION--
ORDER BY PAIS,
	  	 SOCI,
		 CODIGO,
		 FECHA 