SELECT *
FROM	
(
	(
	SELECT GEN_PAIS.VAL_I18N PAIS,
		   GEN_SOC.VAL_I18N SOC,
		   CLI.COD_CLIE CODIGO,
		   CLI.VAL_APE1||' '||CLI.VAL_APE2||' '||CLI.VAL_NOM1||' '||CLI.VAL_NOM2 CONSUL,
		   MOV_CCC.VAL_DOCU_NUME CARGO,
		   MOV_CCC.VAL_REFE_NUME_DOCU_EXTE REFE,
		   ZONA.COD_ZONA ZONA,
		   MOV_CCC.FEC_ULTI_MOVI FECHA,
		   PERI.VAL_NOMB_PERI CAMPANIA,
		   MOV_CCC.IMP_MOVI IMPORTE,
		   MOV_CCC.IMP_PAGO PAGO, 
		   1 AS CANTIDAD
	FROM CCC_MOVIM_CUENT_CORRI MOV_CCC,
		 CCC_PROCE PROC,
		 CCC_SUBPR SUBP,
		 SEG_SOCIE SOC,
		 MAE_CLIEN CLI,
		 CRA_PERIO PERI,
		 MAE_CLIEN_UNIDA_ADMIN UND_AMD,
		 ZON_TERRI_ADMIN TER_ADM,
		 ZON_SECCI SEC,
		 ZON_ZONA ZONA,
		 (
		 SELECT GEN.VAL_OID, GEN.VAL_I18N
		 FROM V_GEN_I18N_SICC GEN
		 WHERE GEN.ATTR_ENTI = 'SEG_PAIS'
		 	    AND GEN.IDIO_OID_IDIO = 1						-- PARAMETRO DE IDIOMA --
		 ) GEN_PAIS,
		 (
		 SELECT GEN.VAL_OID, GEN.VAL_I18N
		 FROM V_GEN_I18N_SICC GEN
		 WHERE GEN.ATTR_ENTI = 'SEG_SOCIE'
		 	    AND GEN.IDIO_OID_IDIO = 1						-- PARAMETRO DE IDIOMA --
		 ) GEN_SOC
	WHERE SUBP.COD_SUBP = 4
		  AND MOV_CCC.IMP_PAGO <> 0
		  AND MOV_CCC.IMP_PEND = 0	  	
	--	  AND PROC.COD_proc = 'CCC004'
		  AND SOC.PAIS_OID_PAIS = GEN_PAIS.VAL_OID(+)
		  AND SOC.OID_SOCI = GEN_SOC.VAL_OID(+)
		  AND MOV_CCC.SUBP_OID_SUBP_CREA = SUBP.OID_SUBP
		  AND SOC.OID_SOCI = MOV_CCC.SOCI_OID_SOCI 
		  AND MOV_CCC.CLIE_OID_CLIE = CLI.OID_CLIE
		  AND UND_AMD.CLIE_OID_CLIE = CLI.OID_CLIE
		  AND UND_AMD.IND_ACTI = 1
		  AND UND_AMD.ZTAD_OID_TERR_ADMI = TER_ADM.OID_TERR_ADMI
		  AND TER_ADM.ZSCC_OID_SECC = SEC.OID_SECC
		  AND SEC.ZZON_OID_ZONA = ZONA.OID_ZONA
		  AND PERI.OID_PERI = MOV_CCC.PERD_OID_PERI
		  AND SUBP.CCPR_OID_proc= PROC.OID_proc
		  AND SOC.PAIS_OID_PAIS = 1			   			 						   -- PARAMETRO DE PAIS --
		  AND TO_DATE(MOV_CCC.FEC_ULTI_MOVI) >= TO_DATE('01/01/2000','DD/MM/YYYY') -- PARAMETRO DE FECHA DE CANCELACION DESDE --
		  AND TO_DATE(MOV_CCC.FEC_ULTI_MOVI) <= TO_DATE('01/01/2050','DD/MM/YYYY') -- PARAMETRO DE FECHA DE CANCELACION HASTA-- 
	)
	UNION
	(
	SELECT GEN_PAIS.VAL_I18N PAIS,
		   GEN_SOC.VAL_I18N SOC,
		   CLI.COD_CLIE CODIGO,
		   USU.VAL_APEL_PATE||''||USU.VAL_APE_MATE||''||USU.VAL_NOM1||''||USU.VAL_NOM2 CONSUL,
		   HTO.VAL_ULTI_DOCU_NUME CARGO,
		   HTO.VAL_REFE_NUME_DOCU_EXTE REFE,
		   ZONA.COD_ZONA ZONA,
		   HTO.FEC_MOVI FECHA,
		   PERI.VAL_NOMB_PERI CAMPANIA,
		   HTO.IMP_MOVI IMPORTE,
		   HTO.IMP_PAGO PAGO,
		   1 AS CANTIDAD
	FROM CCC_MOVIM_CUENT_CORRI MOV_CCC,
		 CCC_PROCE PROC,
		 CCC_SUBPR SUBP,
		 SEG_SOCIE SOC,
	 	 CCC_HISTO_MOVIM_CC HTO,
		 V_REP_USUAR_LARGO USU,
		 MAE_CLIEN CLI,
		 CRA_PERIO PERI,
		 MAE_CLIEN_UNIDA_ADMIN UND_AMD,
		 ZON_TERRI_ADMIN TER_ADM,
		 ZON_SECCI SEC,
		 ZON_ZONA ZONA,
		 (
		 SELECT GEN.VAL_OID, GEN.VAL_I18N
		 FROM V_GEN_I18N_SICC GEN
		 WHERE GEN.ATTR_ENTI = 'SEG_PAIS'
		 	    AND GEN.IDIO_OID_IDIO = 1						-- PARAMETRO DE IDIOMA --
		 ) GEN_PAIS,
		 (
		 SELECT GEN.VAL_OID, GEN.VAL_I18N
		 FROM V_GEN_I18N_SICC GEN
		 WHERE GEN.ATTR_ENTI = 'SEG_SOCIE'
		 	    AND GEN.IDIO_OID_IDIO = 1						-- PARAMETRO DE IDIOMA --
		 ) GEN_SOC
	WHERE SUBP.COD_SUBP = 4
		  AND MOV_CCC.IMP_PAGO <> 0
		  AND PROC.COD_proc = 'CCC004'
		  AND SOC.PAIS_OID_PAIS = GEN_PAIS.VAL_OID(+)
		  AND SOC.OID_SOCI = GEN_SOC.VAL_OID(+)
		  AND MOV_CCC.SUBP_OID_SUBP_CREA = SUBP.OID_SUBP
		  AND SOC.OID_SOCI = MOV_CCC.SOCI_OID_SOCI 
		  AND MOV_CCC.OID_MOVI_CC = HTO.MVCC_OID_MOVI_CC
		  AND MOV_CCC.CLIE_OID_CLIE = CLI.OID_CLIE
		  AND UND_AMD.CLIE_OID_CLIE = CLI.OID_CLIE
		  AND UND_AMD.IND_ACTI = 1
		  AND UND_AMD.ZTAD_OID_TERR_ADMI = TER_ADM.OID_TERR_ADMI
		  AND TER_ADM.ZSCC_OID_SECC = SEC.OID_SECC
		  AND SEC.ZZON_OID_ZONA = ZONA.OID_ZONA
		  AND PERI.OID_PERI = MOV_CCC.PERD_OID_PERI
		  AND USU.VAL_NOMB_USUA = MOV_CCC.COD_USUA
		  AND SUBP.CCPR_OID_proc= PROC.OID_proc
		  AND HTO.IMP_PAGO <> 0
		  AND HTO.SUBP_OID_SUBP = SUBP.OID_SUBP
	  	  AND SOC.PAIS_OID_PAIS = 1			   			 						   -- PARAMETRO DE PAIS --
		  AND TO_DATE(HTO.FEC_MOVI) >= TO_DATE('01/01/2000','DD/MM/YYYY') -- PARAMETRO DE FECHA DE CANCELACION DESDE --
		  AND TO_DATE(HTO.FEC_MOVI) <= TO_DATE('01/01/2050','DD/MM/YYYY') -- PARAMETRO DE FECHA DE CANCELACION HASTA-- 
		  AND TO_DATE(MOV_CCC.FEC_ULTI_MOVI) >= TO_DATE('01/01/2000','DD/MM/YYYY') -- PARAMETRO DE FECHA DE CANCELACION DESDE --
		  AND TO_DATE(MOV_CCC.FEC_ULTI_MOVI) <= TO_DATE('01/01/2050','DD/MM/YYYY') -- PARAMETRO DE FECHA DE CANCELACION HASTA-- 
	)
)
ORDER BY CONSUL
--ORDER BY FECHA --FLUJO ALTERNATIVO	
	
