
SELECT DETALLE.PAIS,
	   DETALLE.SOCIEDAD,
	   DETALLE.PROCESO,
	   DETALLE.FEC_DOCU,
	   DETALLE.COMPROBANTE,
	   DETALLE.OBSERVACIONES,
	   RESUMEN.IMPORTE_CAB,
	   RESUMEN.REGISTROS,
	   DETALLE.SUBPROCESO,
	   DETALLE.CONSULTORA,
	   DETALLE.VAL_APE1,
	   DETALLE.VAL_APE2,
	   DETALLE.NOMBRE,
	   DETALLE.NUM_ABONO,
	   DETALLE.IMPORTE   
FROM
(
	SELECT SUBP.OID_PAIS,
		   GEN_PAIS.VAL_I18N PAIS,
		   SUBP.SOCI,
		   GEN_SOCI.VAL_I18N SOCIEDAD,
		   SUBP.PROCESO,
		   SUBP.FEC_DOCU,
		   SUBP.COMPROBANTE,
		   SUBP.OBSERVACIONES,
		   SUBP.ORDENSUB,
		   SUBP.SUBPROCESO,
		   SUBP.CONSULTORA,
		   SUBP.VAL_APE1,
		   SUBP.VAL_APE2,
		   SUBP.NOMBRE,
		   SUBP.NUM_ABONO,
		   SUBP.IMPORTE
	FROM
	(
		(
		--------------------------------------SUBPROCESO 1 = CANCELACION DE DEUDA Y GENERACION DE DEUDA -----------------
			SELECT *
			FROM
			(
				SELECT CAB_CAR.PAIS_OID_PAIS OID_PAIS,
					   CAB_CAR.SOCI_OID_SOCI SOCI,
					   PRO.DES_proc PROCESO ,
					   CAB_CAR.FEC_DOCU,
					   CAB_CAR.VAL_NUME_LOTE_CONT COMPROBANTE,
					   CAB_CAR.VAL_OBSE OBSERVACIONES,
					   'A' ORDENSUB,
					   'CANCELACION DE DEUDA' SUBPROCESO,
					   TO_CHAR(CLI.COD_CLIE) CONSULTORA,
					   CLI.VAL_APE1,
					   CLI.VAL_APE2,
					   CLI.VAL_NOM1||' '||CLI.VAL_NOM2 NOMBRE,
					   MOV_CCC.VAL_EJER_CUOT||'/'||MOV_CCC.NUM_IDEN_CUOT||'/'||MOV_CCC.NUM_ORDE_CUOT NUM_ABONO,
					   DET_CAR.IMP IMPORTE	   	     	   	   
				FROM CCC_CABEC_CARGA_ABONO_DIREC CAB_CAR,
					 CCC_PROCE PRO,
					 CCC_DETAL_CARGO_ABONO_DIREC DET_CAR,
					 CCC_TIPO_ABONO_SUBPR TIP_ABO,
					 CCC_SUBPR SUBP,
					 MAE_CLIEN CLI,
					 CCC_MOVIM_CUENT_CORRI MOV_CCC
				WHERE CAB_CAR.CCPR_OID_proc= PRO.OID_PROC 
				--	  AND PRO.IND_CV_DIRE = 1
					  AND DET_CAR.CCAD_OID_CABE_CARG = CAB_CAR.OID_CABE_CARG
					  AND TIP_ABO.OID_TIPO_ABON_SUBP = DET_CAR.TASP_OID_TIPO_ABON_SUBP
					  AND TIP_ABO.SUBP_OID_SUBP = SUBP.OID_SUBP
					  AND CLI.OID_CLIE = CAB_CAR.CLIE_OID_CLIE
					  AND DET_CAR.MVCC_OID_MOVI_CC = MOV_CCC.OID_MOVI_CC
					  AND SUBP.COD_SUBP = 1
				--	  AND TIP_ABO.OID_TIPO_ABON_SUBP IN (1)							  	  -- PARAMETRO DE TIPO DE ABONO --
				--	  AND CAB_CAR.VAL_NUME_LOTE_CONT = 1  								  -- PARAMETRO DE NUMERO DE COMPROBANTE --
					  AND TO_DATE(CAB_CAR.FEC_DOCU) >= TO_DATE('01/01/2000','DD/MM/YYYY') -- PARAMETRO DE FECHA DE PROCESO DESDE --
				 	  AND TO_DATE(CAB_CAR.FEC_DOCU) <= TO_DATE('01/01/2006','DD/MM/YYYY') -- PARAMETRO DE FECHA DE PROCESO HASTA -- 	 	
				--	  AND PRO.OID_proc IN (1)		  						-- PARAMETRO DE PROCESO --
				--	  AND CAB_CAR.PAIS_OID_PAIS = 1	 							-- PARAMETRO DE PAIS --
				ORDER BY CONSULTORA,
					 	 NUM_ABONO
			)
		)
		UNION 
		(
			SELECT *
			FROM
			(
			--------------------------------------SUBPROCESO 2 = APLICACION DE TESORERIA -----------------
				SELECT CAB_CAR.PAIS_OID_PAIS OID_PAIS,
					   CAB_CAR.SOCI_OID_SOCI SOCI,
					   PRO.DES_proc PROCESO,
					   CAB_CAR.FEC_DOCU,
					   CAB_CAR.VAL_NUME_LOTE_CONT COMPROBANTE,
	   				   CAB_CAR.VAL_OBSE OBSERVACIONES,
					   'C' ORDENSUB,
					   'APLICACION DE TESORERIA' SUBPROCESO,
					   TO_CHAR(DET_CAR.CCBA_OID_CUEN_CORR_BANC) CUENTA,
					   CCC_BAN.DES_CC,
					   '' AS VAL_APE2,
					   '' AS NOMBRE,
					   MOV_BAN.NUM_LOTE||'/'||MOV_BAN.NUM_CONS_TRAN MOVIMIENTO,
					   DET_CAR.IMP IMPORTE	   	   
				FROM CCC_CABEC_CARGA_ABONO_DIREC CAB_CAR,
					 CCC_PROCE PRO,
					 CCC_DETAL_CARGO_ABONO_DIREC DET_CAR,
					 CCC_TIPO_ABONO_SUBPR TIP_ABO,
					 CCC_SUBPR SUBP,
					 CCC_MOVIM_BANCA MOV_BAN,
					 CCC_CUENT_CORRI_BANCA CCC_BAN
				WHERE CAB_CAR.CCPR_OID_proc= PRO.OID_PROC 
				--	  AND PRO.IND_CV_DIRE = 1
					  AND DET_CAR.CCAD_OID_CABE_CARG = CAB_CAR.OID_CABE_CARG
					  AND TIP_ABO.OID_TIPO_ABON_SUBP = DET_CAR.TASP_OID_TIPO_ABON_SUBP
					  AND TIP_ABO.SUBP_OID_SUBP = SUBP.OID_SUBP
					  AND CCC_BAN.OID_CUEN_CORR_BANC = CAB_CAR.CCBA_OID_CUEN_CORR_BANC
					  AND MOV_BAN.CCBA_OID_CC_BANC = CCC_BAN.OID_CUEN_CORR_BANC
					  AND SUBP.COD_SUBP = 2
				--	  AND TIP_ABO.OID_TIPO_ABON_SUBP IN (1)							  	  -- PARAMETRO DE TIPO DE ABONO --
				--	  AND CAB_CAR.VAL_NUME_LOTE_CONT = 1  								  -- PARAMETRO DE NUMERO DE COMPROBANTE --
					  AND TO_DATE(CAB_CAR.FEC_DOCU) >= TO_DATE('01/01/2000','DD/MM/YYYY') -- PARAMETRO DE FECHA DE PROCESO DESDE --
				 	  AND TO_DATE(CAB_CAR.FEC_DOCU) <= TO_DATE('01/01/2006','DD/MM/YYYY') -- PARAMETRO DE FECHA DE PROCESO HASTA -- 	 	
				--	  AND PRO.OID_proc IN (1)		  						-- PARAMETRO DE PROCESO --
				--	  AND CAB_CAR.PAIS_OID_PAIS = 1	 							-- PARAMETRO DE PAIS --
				ORDER BY CUENTA,
					     MOVIMIENTO	   	   	   
			)
		)
		UNION 
		(
			SELECT *
			FROM
			(
				--------------------------------------SUBPROCESO 3 = CARGOS DE ABONO DIRECTOS -----------------
				SELECT CAB_CAR.PAIS_OID_PAIS OID_PAIS,
					   CAB_CAR.SOCI_OID_SOCI SOCI,
					   PRO.DES_proc PROCESO ,
					   CAB_CAR.FEC_DOCU,
					   CAB_CAR.VAL_NUME_LOTE_CONT COMPROBANTE,
	   				   CAB_CAR.VAL_OBSE OBSERVACIONES,
   					   'B' ORDENSUB,
					   'CARGOS/ABONOS DIRECTOS' SUBPROCESO,
					   TO_CHAR(TIP_CAR.COD_TIPO_CARG_ABON) TIP_ABONO,
					   DET_CAR.VAL_GLOS_CONT GLOSA,
					   '' AS VAL_APE2,
					   '' AS NOMBRE,
					   CCC_CON.COD_CUEN_CONT CUENTA_CONTABLE,
					   DET_CAR.IMP IMPORTE 	   	   	   
				FROM CCC_CABEC_CARGA_ABONO_DIREC CAB_CAR,
					 CCC_PROCE PRO,
					 CCC_DETAL_CARGO_ABONO_DIREC DET_CAR,
					 CCC_TIPO_ABONO_SUBPR TIP_ABO,
					 CCC_SUBPR SUBP,
					 CCC_TIPO_CARGO_ABONO TIP_CAR,
					 CCC_CUENT_CONTA CCC_CON
				WHERE CAB_CAR.CCPR_OID_proc= PRO.OID_PROC 
				--	  AND PRO.IND_CV_DIRE = 1
					  AND DET_CAR.CCAD_OID_CABE_CARG = CAB_CAR.OID_CABE_CARG
					  AND TIP_ABO.OID_TIPO_ABON_SUBP = DET_CAR.TASP_OID_TIPO_ABON_SUBP
					  AND TIP_ABO.SUBP_OID_SUBP = SUBP.OID_SUBP
					  AND TIP_CAR.OID_TIPO_CARG_ABON = TIP_ABO.TCAB_OID_TCAB
					  AND CCC_CON.OID_CUEN_CONT = TIP_ABO.CUCO_OID_CUEN_CONT
					  AND SUBP.COD_SUBP = 3
				--	  AND TIP_ABO.OID_TIPO_ABON_SUBP IN (1)							  	  -- PARAMETRO DE TIPO DE ABONO --
				--	  AND CAB_CAR.VAL_NUME_LOTE_CONT = 1  								  -- PARAMETRO DE NUMERO DE COMPROBANTE --
					  AND TO_DATE(CAB_CAR.FEC_DOCU) >= TO_DATE('01/01/2000','DD/MM/YYYY') -- PARAMETRO DE FECHA DE PROCESO DESDE --
				 	  AND TO_DATE(CAB_CAR.FEC_DOCU) <= TO_DATE('01/01/2006','DD/MM/YYYY') -- PARAMETRO DE FECHA DE PROCESO HASTA -- 	 	
				--	  AND PRO.OID_proc IN (1)		  						-- PARAMETRO DE PROCESO --
				--	  AND CAB_CAR.PAIS_OID_PAIS = 1	 							-- PARAMETRO DE PAIS --
				ORDER BY TIP_ABONO,
					     IMPORTE 	   	   	   
			)
		)
		UNION 
		(
			SELECT *
			FROM
			(
				SELECT CAB_CAR.PAIS_OID_PAIS OID_PAIS,
					   CAB_CAR.SOCI_OID_SOCI SOCI,
					   PRO.DES_proc PROCESO ,
					   CAB_CAR.FEC_DOCU,
					   CAB_CAR.VAL_NUME_LOTE_CONT COMPROBANTE,
					   CAB_CAR.VAL_OBSE OBSERVACIONES,
   					   'D' ORDENSUB,
					   'GENERACION DE DEUDA' SUBPROCESO,
					   TO_CHAR(CLI.COD_CLIE) CONSULTORA,
					   CLI.VAL_APE1,
					   CLI.VAL_APE2,
					   CLI.VAL_NOM1||' '||CLI.VAL_NOM2 NOMBRE,
					   MOV_CCC.VAL_EJER_CUOT||'/'||MOV_CCC.NUM_IDEN_CUOT||'/'||MOV_CCC.NUM_ORDE_CUOT NUM_ABONO,
					   DET_CAR.IMP IMPORTE	   	  	   	   
				FROM CCC_CABEC_CARGA_ABONO_DIREC CAB_CAR,
					 CCC_PROCE PRO,
					 CCC_DETAL_CARGO_ABONO_DIREC DET_CAR,
					 CCC_TIPO_ABONO_SUBPR TIP_ABO,
					 CCC_SUBPR SUBP,
				 	 MAE_CLIEN CLI,
				 	 CCC_MOVIM_CUENT_CORRI MOV_CCC
				WHERE CAB_CAR.CCPR_OID_proc= PRO.OID_PROC 
				--	  AND PRO.IND_CV_DIRE = 1
					  AND DET_CAR.CCAD_OID_CABE_CARG = CAB_CAR.OID_CABE_CARG
					  AND TIP_ABO.OID_TIPO_ABON_SUBP = DET_CAR.TASP_OID_TIPO_ABON_SUBP
					  AND TIP_ABO.SUBP_OID_SUBP = SUBP.OID_SUBP
				 	  AND CLI.OID_CLIE = CAB_CAR.CLIE_OID_CLIE
				 	  AND DET_CAR.MVCC_OID_MOVI_CC = MOV_CCC.OID_MOVI_CC
					  AND SUBP.COD_SUBP = 4
				--	  AND TIP_ABO.OID_TIPO_ABON_SUBP IN (1)							  	  -- PARAMETRO DE TIPO DE ABONO --
				--	  AND CAB_CAR.VAL_NUME_LOTE_CONT = 1  								  -- PARAMETRO DE NUMERO DE COMPROBANTE --
					  AND TO_DATE(CAB_CAR.FEC_DOCU) >= TO_DATE('01/01/2000','DD/MM/YYYY') -- PARAMETRO DE FECHA DE PROCESO DESDE --
				 	  AND TO_DATE(CAB_CAR.FEC_DOCU) <= TO_DATE('01/01/2006','DD/MM/YYYY') -- PARAMETRO DE FECHA DE PROCESO HASTA -- 	 	
				--	  AND PRO.OID_proc IN (1)		  						-- PARAMETRO DE PROCESO --
				--	  AND CAB_CAR.PAIS_OID_PAIS = 1	 							-- PARAMETRO DE PAIS --
				ORDER BY CONSULTORA,
						 NUM_ABONO	   	   	  	   	   
			)
		)
	) SUBP,
	(
		SELECT GEN.VAL_OID, GEN.VAL_I18N 
		FROM V_GEN_I18N_SICC GEN
		WHERE GEN.ATTR_ENTI = 'SEG_PAIS'
			  AND GEN.IDIO_OID_IDIO = 1					   							-- PARAMETRO DE IDIOMA --
	) GEN_PAIS,
	(
	    SELECT GEN.VAL_OID, GEN.VAL_I18N
		FROM V_GEN_I18N_SICC GEN
		WHERE GEN.ATTR_ENTI = 'SEG_SOCIE'
		AND GEN.IDIO_OID_IDIO = 1 	 								-- PARAMETRO DE IDIOMA --
	) GEN_SOCI
	WHERE SUBP.OID_PAIS = GEN_PAIS.VAL_OID(+)
		  AND SUBP.SOCI = GEN_SOCI.VAL_OID(+)
) DETALLE,
(				   
	SELECT CAB_CAR.SOCI_OID_SOCI SOCI,
		   PRO.DES_proc PROCESO,
		   CAB_CAR.FEC_DOCU,
  		   CAB_CAR.VAL_NUME_LOTE_CONT COMPROBANTE,
		   NVL((COUNT(*)), 0) REGISTROS,
		   NVL((SUM(DET_CAR.IMP)), 0) IMPORTE_CAB
	FROM CCC_CABEC_CARGA_ABONO_DIREC CAB_CAR,
		 CCC_PROCE PRO,
		 CCC_DETAL_CARGO_ABONO_DIREC DET_CAR,
		 CCC_TIPO_ABONO_SUBPR TIP_ABO,
		 CCC_SUBPR SUBP,
		 MAE_CLIEN CLI,
		 CCC_MOVIM_CUENT_CORRI MOV_CCC
	WHERE CAB_CAR.CCPR_OID_proc= PRO.OID_PROC 
	--	  AND PRO.IND_CV_DIRE = 1
		  AND DET_CAR.CCAD_OID_CABE_CARG = CAB_CAR.OID_CABE_CARG
		  AND TIP_ABO.OID_TIPO_ABON_SUBP = DET_CAR.TASP_OID_TIPO_ABON_SUBP
		  AND TIP_ABO.SUBP_OID_SUBP = SUBP.OID_SUBP
		  AND CLI.OID_CLIE = CAB_CAR.CLIE_OID_CLIE
		  AND DET_CAR.MVCC_OID_MOVI_CC = MOV_CCC.OID_MOVI_CC
		  AND SUBP.COD_SUBP = 1
	--	  AND TIP_ABO.OID_TIPO_ABON_SUBP IN (1)							  	  -- PARAMETRO DE TIPO DE ABONO --
	--	  AND CAB_CAR.VAL_NUME_LOTE_CONT = 1  								  -- PARAMETRO DE NUMERO DE COMPROBANTE --
		  AND TO_DATE(CAB_CAR.FEC_DOCU) >= TO_DATE('01/01/2000','DD/MM/YYYY') -- PARAMETRO DE FECHA DE PROCESO DESDE --
	 	  AND TO_DATE(CAB_CAR.FEC_DOCU) <= TO_DATE('01/01/2006','DD/MM/YYYY') -- PARAMETRO DE FECHA DE PROCESO HASTA -- 	 	
	--	  AND PRO.OID_proc IN (1)		  						-- PARAMETRO DE PROCESO --
	--	  AND CAB_CAR.PAIS_OID_PAIS = 1	 							-- PARAMETRO DE PAIS --
	GROUP BY CAB_CAR.PAIS_OID_PAIS,
		   CAB_CAR.SOCI_OID_SOCI,
		   PRO.DES_proc,
		   CAB_CAR.FEC_DOCU,
		   CAB_CAR.VAL_NUME_LOTE_CONT,
		   CAB_CAR.VAL_OBSE
) RESUMEN
WHERE DETALLE.FEC_DOCU = RESUMEN.FEC_DOCU(+)
	  AND DETALLE.SOCI = RESUMEN.SOCI(+)
	  AND DETALLE.PROCESO = RESUMEN.PROCESO(+)
	  AND DETALLE.COMPROBANTE = RESUMEN.COMPROBANTE(+)  
ORDER BY DETALLE.SOCIEDAD,
	     DETALLE.PROCESO,
	     DETALLE.FEC_DOCU,
	     DETALLE.COMPROBANTE,
	     DETALLE.ORDENSUB 
	  	