------------------- POR CUENTA CORRIENTE -----------

SELECT BANCO.PAIS_OID_PAIS, 
	   GEN_PAIS.VAL_I18N PAIS,
	   MOV_BAN.SOCI_OID_SOCI,
	   GEN_SOC.VAL_I18N SOC,
	   MOV_BAN.FEC_PAGO,
	   CCC_BAN.DES_CC,
	   SUM(MOV_BAN.IMP_PAGO) IMPORTE, 
	   COUNT(*) REG
FROM CCC_MOVIM_BANCA MOV_BAN,
	 CCC_SUCUR SUC,
	 CCC_CUENT_CORRI_BANCA CCC_BAN,
	 CCC_BANCO BANCO,
	 (
	 SELECT GEN.VAL_OID, GEN.VAL_I18N
	 FROM V_GEN_I18N_SICC GEN
	 WHERE GEN.ATTR_ENTI = 'SEG_SOCIE'
	 	   AND GEN.IDIO_OID_IDIO = 1  	 							-- PARAMETRO DE IDIOMA --
	 ) GEN_SOC,
	 (
	 SELECT GEN.VAL_OID, GEN.VAL_I18N
	 FROM V_GEN_I18N_SICC GEN
	 WHERE GEN.ATTR_ENTI = 'SEG_PAIS'
	 	   AND GEN.IDIO_OID_IDIO = 1  	 							-- PARAMETRO DE IDIOMA --
	 ) GEN_PAIS
WHERE 
	  BANCO.OID_BANC = SUC.CBAN_OID_BANC
	  AND SUC.OID_SUCU = CCC_BAN.SUCU_OID_SUCU
	  AND MOV_BAN.COD_IDEN_proc<> 'T'
	  AND CCC_BAN.OID_CUEN_CORR_BANC = MOV_BAN.CCBA_OID_CC_BANC
	  AND MOV_BAN.SOCI_OID_SOCI = GEN_SOC.VAL_OID(+)
	  AND BANCO.PAIS_OID_PAIS = GEN_PAIS.VAL_OID(+)
	  AND TO_DATE(MOV_BAN.FEC_PAGO) <= TO_DATE('01/01/2006','DD/MM/YYYY') -- PARAMETRO DE FECHA HASTA --
  	  AND TO_DATE(MOV_BAN.FEC_PAGO) >= TO_DATE('01/01/2004','DD/MM/YYYY') -- PARAMETRO DE FECHA DESDE -- 
	  AND BANCO.PAIS_OID_PAIS = 1	   									  -- PARAMETRO DE PAIS --
--	  AND CCC_BAN.OID_CUEN_CORR_BANC IN (5)								  -- PARAMETRO DE CUENTA CORRIENTE BANCARIA --
--	  AND BANCO.OID_BANC IN (5) 										  -- PARAMETRO DE BANCO --
GROUP BY BANCO.PAIS_OID_PAIS, 
         GEN_PAIS.VAL_I18N,
         MOV_BAN.SOCI_OID_SOCI,
         GEN_SOC.VAL_I18N,
	     MOV_BAN.FEC_PAGO,
		 CCC_BAN.DES_CC
ORDER BY GEN_PAIS.VAL_I18N,
         GEN_SOC.VAL_I18N
