/* cOMENTARIO PARA HACER EL LAYOUT: EN LA COLUMNA REG_CORRECTOS LOS QUE TIENE UN UNO SON LOS CORRECTOS,
EL TOTAL DE REGISTROS - LOS CORRECTOS DARA LOS A REGULARIZAR, LO MISMO DEBE HACERSE PARA LA COLUMNA DE IMPORTES
(IMP_CORRECTOS))
*/

SELECT 
	   GEN_PAIS.VAL_I18N PAIS,
	   GEN_SOCI.VAL_I18N SOCI,
	   BANCO.DES_BANC BANCO,
	   CCC_BAN.DES_CC CUENTA_CC,
	   MOV_BAN.FEC_PAGO FEC_LIQUIDA,
	   MOV_BAN.NUM_LOTE COMPROBANTE,
	   MOV_BAN.COD_CONS,
	   CLI.VAL_APE1 APE_PAT,
	   CLI.VAL_APE2 APE_MAT,
	   CLI.VAL_NOM1||' '||CLI.VAL_NOM2 NOMBRE,
	   MOV_BAN.FEC_PAGO,
	   DECODE(DECODE(MOV_BAN.NUM_FACT_BOLE, NULL, MOV_BAN.NUM_CUPO, MOV_BAN.NUM_FACT_BOLE), NULL, MOV_BAN.NUM_CONS_TRAN,DECODE(MOV_BAN.NUM_FACT_BOLE, NULL, MOV_BAN.NUM_CUPO, MOV_BAN.NUM_FACT_BOLE)) NUM_ABONO,
	   MOV_BAN.IMP_PAGO,
	   DECODE(MOV_BAN.COD_CONS, NULL, 0, 1) REG_CORRECTOS,
       DECODE(MOV_BAN.COD_CONS, NULL, 0, MOV_BAN.IMP_PAGO) IMP_CORRECTOS
FROM CCC_MOVIM_BANCA MOV_BAN,
     CCC_CUENT_CORRI_BANCA CCC_BAN,
	 CCC_SUCUR SUC,
	 CCC_BANCO BANCO,
	 MAE_CLIEN CLI,
	 (
	 SELECT GEN.VAL_OID, GEN.VAL_I18N
	 FROM V_GEN_I18N_SICC GEN
	 WHERE GEN.ATTR_ENTI = 'SEG_SOCIE'
	 	   AND GEN.IDIO_OID_IDIO = 1 										-- PARAMETRO DE IDIOMA --
	 ) GEN_SOCI,
	 (
	 SELECT GEN.VAL_OID, GEN.VAL_I18N
	 FROM V_GEN_I18N_SICC GEN
	 WHERE GEN.ATTR_ENTI = 'SEG_PAIS'
	 	   AND GEN.IDIO_OID_IDIO = 1 										-- PARAMETRO DE IDIOMA --
	 ) GEN_PAIS
WHERE CCC_BAN.OID_CUEN_CORR_BANC = MOV_BAN.CCBA_OID_CC_BANC
	  AND SUC.OID_SUCU = CCC_BAN.SUCU_OID_SUCU
	  AND BANCO.OID_BANC = SUC.CBAN_OID_BANC
	  AND MOV_BAN.COD_CONS = CLI.COD_CLIE(+)
	  AND CLI.PAIS_OID_PAIS = MOV_BAN.PAIS_OID_PAIS
	  AND MOV_BAN.SOCI_OID_SOCI = GEN_SOCI.VAL_OID(+)
	  AND MOV_BAN.PAIS_OID_PAIS = GEN_PAIS.VAL_OID(+)
	  AND MOV_BAN.COD_IDEN_proc<> 'T'
	  AND MOV_BAN.PAIS_OID_PAIS = 1 										-- PARAMETRO DE PAIS--
 	  AND BANCO.OID_BANC IN (1,2,3,4,5,6,7,8)								-- PARAMETRO DE BANCO --
	  AND CCC_BAN.OID_CUEN_CORR_BANC IN (1,2,3,4,5,6,7,8)									-- PARAMETRO CCC BANCARIA--
	  AND TO_DATE(MOV_BAN.FEC_PAGO) = TO_DATE('25/04/2005','DD/MM/YYYY')    -- PARAMETRO DE FECHA DE LIQUIDACION--	
	  AND MOV_BAN.NUM_LOTE = 111401262507									-- PARAMETRO DE COMPROBANTE --
ORDER BY PAIS,
	  	 SOCI,
		 BANCO,
		 CUENTA_CC,
		 FEC_LIQUIDA,
		 COMPROBANTE,
		 COD_CONS,
		 IMP_PAGO

