SELECT SUBG,
	   REGION,
	   ZONA,
	   MARCA,
	   NRO_CONCURSO,
	   DESC_CONCURSO,
	   CAM_INI_CONCU,
	   CAM_FIN_CONCU,
	   PUESTO,
	   PUNTAJE,
	   COD_CLIE,
	   NOMBRE,
	   PROMEDIO_PUNTOS,
	   PERIODO,
	   PUNTOS    	   
FROM
(
	SELECT SUBG,
		   REGION,
		   ZONA,
		   NRO_CONCURSO,
		   DESC_CONCURSO,
		   MARCA,
		   CAM_INI_CONCU,
		   CAM_FIN_CONCU,
		   COD_CLIE,
		   NOMBRE,
		   PERIODO,
		   PUNTOS,
		   PUNTAJE,
		   PUNTAJE/COUNT(*) OVER (PARTITION BY REGION, ZONA, NRO_CONCURSO, COD_CLIE ORDER BY 1) PROMEDIO_PUNTOS, 
		   DENSE_RANK() OVER (PARTITION BY REGION, ZONA, NRO_CONCURSO ORDER BY PUNTAJE DESC, COD_CLIE) PUESTO
	FROM
	(	
		SELECT SUBG.DES_SUBG_VENT SUBG,
			   REG.DES_REGI REGION,
			   ZONA.DES_ZONA ZONA,
			   CPG.NUM_CONC NRO_CONCURSO,
			   CPG.VAL_NOMB DESC_CONCURSO,
			   MARCA.DES_MARC MARCA,
			   PERI2.VAL_NOMB_PERI CAM_INI_CONCU,
			   PERI3.VAL_NOMB_PERI CAM_FIN_CONCU,
			   CLI.COD_CLIE,
			   CLI.VAL_NOM1||' '||CLI.VAL_APE1||' '||CLI.VAL_APE2 NOMBRE,
			   PERI.VAL_NOMB_PERI PERIODO,
		       SUM(CCP.NUM_PUNT) PUNTOS,
			   SUM(SUM(CCP.NUM_PUNT)) OVER (PARTITION BY REG.DES_REGI,ZONA.DES_ZONA, CPG.NUM_CONC,CLI.COD_CLIE ORDER BY 1) PUNTAJE
		FROM INC_CONCU_PARAM_GENER CPG,
			 INC_CLIEN_RECDO RECDO,
			 INC_PARAM_GENER_PREMI PGP,
			 INC_PARAM_NIVEL_PREMI PNP,
			 MAE_CLIEN CLI,
			 MAE_CLIEN_TIPO_SUBTI CLI_SUB,
			 MAE_CLIEN_CLASI CLA,
			 INC_CUENT_CORRI_PUNTO CCP,
			 ZON_SUB_GEREN_VENTA SUBG,
			 ZON_REGIO REG,
			 ZON_ZONA ZONA,
			 ZON_SECCI SEC,
			 ZON_TERRI_ADMIN TA,
			 ZON_TERRI TER,
			 MAE_CLIEN_UNIDA_ADMIN CUA,
			 (
			 SELECT P.FEC_INIC
			 FROM CRA_PERIO P
			 WHERE P.OID_PERI = 74 	   	  			-- PARAMETRO DE PERIODO DESDE --
			 ) FI,
			 (
			 SELECT P.FEC_FINA
			 FROM CRA_PERIO P
			 WHERE P.OID_PERI = 76					-- PARAMETRO DE PERIODO HASTA --
			 ) FF,
			 CRA_PERIO PERI,
			 CRA_PERIO PERI2,
			 CRA_PERIO PERI3,
			 SEG_MARCA MARCA 
		WHERE CPG.IND_ACTI = 1
			  AND CPG.OID_PARA_GRAL = PGP.COPA_OID_PARA_GRAL
			  AND PGP.OID_PARA_GENE_PREM = PNP.PAGP_OID_PARA_GENE_PREM
			  AND PNP.OID_PARA_NIVE_PREM = RECDO.PANP_OID_PARA_NIVE_PREM
			  AND CLI.OID_CLIE = RECDO.CLIE_OID_CLIE
			  AND CLI.OID_CLIE = CLI_SUB.CLIE_OID_CLIE
			  AND CLA.CTSU_OID_CLIE_TIPO_SUBT = CLI_SUB.OID_CLIE_TIPO_SUBT
		      AND CCP.CLIE_OID_CLIE = CLI.OID_CLIE 
			  AND CCP.COPA_OID_PARA_GRAL = CPG.OID_PARA_GRAL 
			  AND ((CCP.TMOV_OID_TIPO_MOVI = 1) OR (CCP.TMOV_OID_TIPO_MOVI = 2 AND (CPG.IND_ANUL = 1 OR CPG.IND_DEVO = 1)) OR (CCP.TMOV_OID_TIPO_MOVI = 3))
		   	  AND PERI.FEC_INIC >= FI.FEC_INIC
			  AND PERI.FEC_FINA <= FF.FEC_FINA
			  AND PERI.OID_PERI = CCP.PERD_OID_PERI
			  AND PERI2.OID_PERI = CPG.PERD_OID_PERI_DESD
			  AND PERI3.OID_PERI = CPG.PERD_OID_PERI_HAST
			  AND MARCA.OID_MARC = PERI.MARC_OID_MARC
			  AND SUBG.OID_SUBG_VENT = REG.ZSGV_OID_SUBG_VENT
			  AND REG.OID_REGI = ZONA.ZORG_OID_REGI
			  AND ZONA.OID_ZONA = SEC.ZZON_OID_ZONA
			  AND SEC.OID_SECC = TA.ZSCC_OID_SECC
			  AND TER.OID_TERR = TA.TERR_OID_TERR
			  AND CUA.ZTAD_OID_TERR_ADMI = TA.OID_TERR_ADMI
			  AND CUA.CLIE_OID_CLIE = CCP.CLIE_OID_CLIE
			  AND CLA.IND_PPAL = 1
			  AND CLI_SUB.IND_PPAL = 1
--			  AND CUA.IND_ACTI = 1
			  AND TER.OID_TERR IN (1,2,3,4,5,6,7,8,9)	 	-- PARAMETRO DE TERRITORIO --
			  AND SUBG.OID_SUBG_VENT IN (1,2,3,4,5,6,7,8,9) -- PARAMETRO DE SUBGERENCIA DE VENTAS --
			  AND REG.OID_REGI IN (1,2,3,4,5,6,7,8,9)	    -- PARAMETRO DE REGION --
			  AND ZONA.OID_ZONA IN (1,2,3,4,5,6,7,8,9)	    -- PARAMETRO DE ZONA --
			  AND PERI.PAIS_OID_PAIS = 1		   				-- PARAMETRO DE PAIS --
			  AND PERI.MARC_OID_MARC = 1						-- PARAMETRO DE MARCA --
			  AND PERI.CANA_OID_CANA = 1						-- PARAMETRO DE CANAL --
		      AND CLI_SUB.SBTI_OID_SUBT_CLIE = 1				-- PARAMETRO DE SUBTIPO DE CLIENTE --
			  AND CLI_SUB.TICL_OID_TIPO_CLIE = 2				-- PARAMETRO DE TIPO DE CLIENTE --
			  AND CLA.CLAS_OID_CLAS = 1		   					-- PARAMETRO DE CLASIFICACION --
			  AND CLA.TCCL_OID_TIPO_CLASI = 1					-- PARAMETRO DE TIPO DE CLASIFICACION --
			  AND CPG.NUM_CONC IN ('1', '2') 					-- PARAMETRO DE NUMERO DE CONCURSO --
		GROUP BY SUBG.DES_SUBG_VENT,
			   REG.DES_REGI,
			   ZONA.DES_ZONA,
			   CPG.NUM_CONC,
			   CPG.VAL_NOMB,
			   MARCA.DES_MARC,
			   PERI2.VAL_NOMB_PERI,
			   PERI3.VAL_NOMB_PERI,
			   CLI.COD_CLIE,
			   CLI.VAL_NOM1||' '||CLI.VAL_APE1||' '||CLI.VAL_APE2,
			   PERI.VAL_NOMB_PERI 
		ORDER BY REGION,
			     ZONA,
				 NRO_CONCURSO,
				 PUNTAJE DESC	  	  
	)	  
)	  
--WHERE PUESTO <= 1    -- PARAMETRO DE NUMERO DE PUESTOS --	  
   




















