






SELECT DATOS.MARCA,
	   DATOS.SUBG,
	   DATOS.REGION,
	   DATOS.ZONA,
	   DATOS.NUM_CONCURSO,
	   DATOS.DES_CONCURSO,
	   (
	   SELECT GEN.VAL_I18N
	   FROM V_GEN_I18N_SICC GEN
	   WHERE GEN.ATTR_ENTI = 'SEG_MONED'
	   		 AND GEN.IDIO_OID_IDIO = 1 					-- PARAMETRO DE IDIOMA --
			 AND GEN.VAL_OID = 2   	 					-- PARAMETRO DE MONEDA DE ANALISIS --
	   ) TIPO_MONEDA,
	   DATOS.NRO_RECOMENDADAS_EF,
	   COUNT(*) NRO_RECOMTES,
	   SUM(DATOS.NRO_RECOMENDADAS_EF) TOTAL_NRO_RECDOS,
	   SUM(DATOS.GANA) NRO_GANADORES,
	   SUM(DATOS.MONTO_PEDIDO) VENTA_RECOMTES,
	   DECODE(SUM(DATOS.CANT_PEDIDOS), 0, 0, SUM(DATOS.MONTO_PEDIDO)/SUM(DATOS.CANT_PEDIDOS)) PROM_RECTE,
	   SUM(DATOS.MONTO_PEDIDO_RECDO) VENTA_RECDADAS,
	   DECODE(SUM(DATOS.CANT_PEDIDOS_RECDO), 0, 0, SUM(DATOS.MONTO_PEDIDO_RECDO)/SUM(DATOS.CANT_PEDIDOS_RECDO)) PROM_RECDO	   	  
FROM
(
	SELECT RECTE.MARCA,
		   RECTE.SUBG,
		   RECTE.REGION,
		   RECTE.ZONA,
		   RECTE.NUM_CONCURSO,
		   RECTE.DES_CONCURSO,
		   RECTE.NRO_RECOMENDADAS_EF,
		   RECTE.MONTO_PEDIDO,
		   RECTE.CANT_PEDIDOS,
	   	   (
		   SELECT CASE WHEN (PAIS.MONE_OID_MONE = 2) THEN	-- PARAMETRO DE MONEDA DE ANALISIS -- 
		   		  	   SUM(PCR.IMP_MONT_PEDI)
				  ELSE
				  	   SUM(PCR.IMP_MONT_PEDI)*(SELECT TC.VAL_TIPO_CAMB 
					   						   FROM SEG_TIPO_CAMBI TC
											   WHERE TC.MONE_OID_MON1 = PAIS.MONE_OID_MONE
											   		 AND TC.MONE_OID_MON2 = 2			  	   -- PARAMETRO DE MONEDA DE ANALISIS --
													 AND TC.FEC_DESD <= SYSDATE
													 AND TC.FEC_HAST >= SYSDATE
					   						  )
				  END					   
		   FROM INC_PEDID_CONCU_RECOM PCR,
		   		INC_CLIEN_RECDO RECDO,
				INC_CONCU_PARAM_GENER CON_PAR, 
		   		INC_PARAM_GENER_PREMI PAR_GEN,
				INC_PARAM_NIVEL_PREMI NIV_PRE,
				SEG_PAIS PAIS
		   WHERE PCR.COPA_OID_PARA_GRAL = RECTE.OID_PARA_GRAL
	   		     AND PCR.CLR3_OID_CLIE_RETE = RECTE.CLIE_OID_CLIE
			     AND PCR.CLRE_OID_CLIE_REDO = RECDO.CLIE_OID_CLIE
				 AND RECDO.CLR3_OID_CLIE_RETE = RECTE.CLIE_OID_CLIE
		   		 AND NIV_PRE.PAGP_OID_PARA_GENE_PREM = PAR_GEN.OID_PARA_GENE_PREM
				 AND PAR_GEN.COPA_OID_PARA_GRAL = RECTE.OID_PARA_GRAL
		   		 AND RECDO.PANP_OID_PARA_NIVE_PREM = NIV_PRE.OID_PARA_NIVE_PREM
				 AND RECDO.IND_EFEC = 1			 
				 AND CON_PAR.OID_PARA_GRAL = PAR_GEN.COPA_OID_PARA_GRAL
				 AND PAIS.OID_PAIS = CON_PAR.PAIS_OID_PAIS
		   GROUP BY PAIS.MONE_OID_MONE
		   ) MONTO_PEDIDO_RECDO,
		   (
		   SELECT COUNT(*)
		   FROM INC_PEDID_CONCU_RECOM PCR,
		   		INC_CLIEN_RECDO RECDO, 
		   		INC_PARAM_GENER_PREMI PAR_GEN,
				INC_PARAM_NIVEL_PREMI NIV_PRE
		   WHERE PCR.COPA_OID_PARA_GRAL = RECTE.OID_PARA_GRAL
	   		     AND PCR.CLR3_OID_CLIE_RETE = RECTE.CLIE_OID_CLIE
			     AND PCR.CLRE_OID_CLIE_REDO = RECDO.CLIE_OID_CLIE
				 AND RECDO.CLR3_OID_CLIE_RETE = RECTE.CLIE_OID_CLIE
		   		 AND NIV_PRE.PAGP_OID_PARA_GENE_PREM = PAR_GEN.OID_PARA_GENE_PREM
				 AND PAR_GEN.COPA_OID_PARA_GRAL = RECTE.OID_PARA_GRAL
		   		 AND RECDO.PANP_OID_PARA_NIVE_PREM = NIV_PRE.OID_PARA_NIVE_PREM
				 AND RECDO.IND_EFEC = 1			 
		   ) CANT_PEDIDOS_RECDO,
		   (
		   SELECT COUNT(DISTINCT RECTE.CLIE_OID_CLIE)
		   FROM INC_GANAD GANA,
		   		INC_PARAM_GENER_PREMI PAR_GEN,
				INC_PARAM_NIVEL_PREMI NIV_PRE
		   WHERE GANA.PANP_OID_PARA_NIVE_PREM = NIV_PRE.OID_PARA_NIVE_PREM
		   		 AND NIV_PRE.PAGP_OID_PARA_GENE_PREM = PAR_GEN.OID_PARA_GENE_PREM
				 AND PAR_GEN.COPA_OID_PARA_GRAL = RECTE.OID_PARA_GRAL
				 AND GANA.CLIE_OID_CLIE = RECTE.CLIE_OID_CLIE
		   ) GANA
	FROM
	(
		SELECT MARCA.DES_MARC MARCA,
			   SUBG.DES_SUBG_VENT SUBG,
			   REG.DES_REGI REGION,
			   ZONA.DES_ZONA ZONA,
			   CON_PAR.NUM_CONC NUM_CONCURSO,
			   CON_PAR.VAL_NOMB DES_CONCURSO,
			   CON_PAR.OID_PARA_GRAL,
			   (
			   SELECT COUNT(*)
			   FROM INC_CLIEN_RECDO CLI_RECDO,
			   		INC_PARAM_GENER_PREMI PAR_GEN,
					INC_PARAM_NIVEL_PREMI NIV_PRE
			   WHERE CLI_RECDO.CLR3_OID_CLIE_RETE = CLI_RECTE.CLIE_OID_CLIE
			   		 AND NIV_PRE.PAGP_OID_PARA_GENE_PREM = PAR_GEN.OID_PARA_GENE_PREM
					 AND PAR_GEN.COPA_OID_PARA_GRAL = CON_PAR.OID_PARA_GRAL
			   		 AND CLI_RECDO.PANP_OID_PARA_NIVE_PREM = NIV_PRE.OID_PARA_NIVE_PREM
					 AND CLI_RECDO.IND_EFEC = 1
			   ) NRO_RECOMENDADAS_EF,
			   CLI_RECTE.CLIE_OID_CLIE,
		   	   (
			   SELECT SUM(PCR.IMP_MONT_PEDI)
			   FROM INC_PEDID_CONCU_RECOM PCR 
			   WHERE PCR.COPA_OID_PARA_GRAL = CON_PAR.OID_PARA_GRAL
		   		     AND PCR.CLR3_OID_CLIE_RETE = CLI_RECTE.CLIE_OID_CLIE
				     AND PCR.CLRE_OID_CLIE_REDO IS NULL
			   ) MONTO_PEDIDO,
			   (
			   SELECT COUNT(*)
			   FROM INC_PEDID_CONCU_RECOM PCR
			   WHERE PCR.COPA_OID_PARA_GRAL = CON_PAR.OID_PARA_GRAL
		   		     AND PCR.CLR3_OID_CLIE_RETE = CLI_RECTE.CLIE_OID_CLIE
				     AND PCR.CLRE_OID_CLIE_REDO IS NULL
			   ) CANT_PEDIDOS
		FROM ZON_SUB_GEREN_VENTA SUBG,
			 ZON_REGIO REG,
			 ZON_ZONA ZONA,
			 ZON_SECCI SEC,
			 ZON_TERRI_ADMIN TER_ADM,
			 MAE_CLIEN_UNIDA_ADMIN CLI_UA,
			 INC_CLIEN_RECTE CLI_RECTE,
			 INC_CONCU_PARAM_GENER CON_PAR,
			 INC_PLANT_CONCU PLA_CON,
			 SEG_MARCA MARCA	 
		WHERE REG.OID_REGI = ZONA.ZORG_OID_REGI
			  AND CON_PAR.PLC2_OID_PLAN_CONC = PLA_CON.OID_PLAN_CONC
			  AND SUBG.OID_SUBG_VENT = REG.ZSGV_OID_SUBG_VENT
			  AND ZONA.OID_ZONA = SEC.ZZON_OID_ZONA
			  AND SEC.OID_SECC = TER_ADM.ZSCC_OID_SECC
			  AND TER_ADM.OID_TERR_ADMI = CLI_UA.ZTAD_OID_TERR_ADMI
			  AND MARCA.OID_MARC = SUBG.MARC_OID_MARC
			  AND CLI_RECTE.CLIE_OID_CLIE = CLI_UA.CLIE_OID_CLIE
			  AND CON_PAR.OID_PARA_GRAL = CLI_RECTE.COPA_OID_PARA_GRAL	  
			  AND CLI_UA.IND_ACTI = 1
			  AND CON_PAR.IND_ACTI = 1
			  AND PLA_CON.TVEN_OID_TIPO_VENT =1 						  -- PARAMETRO DE TIPO DE VENTA --
			  AND CON_PAR.PAIS_OID_PAIS = 1								  -- PARAMETRO DE PAIS --
			  AND CON_PAR.NUM_CONC IN ('1','2','05/002','05/005')  		  -- PARAMETRO DE NUMERO DE CONCURSO --
			  AND SUBG.MARC_OID_MARC = 1 								  -- PARAMETRO DE MARCA --
			  AND SUBG.CANA_OID_CANA = 1								  -- PARAMETRO DE CANAL --
			  AND SUBG.OID_SUBG_VENT IN (1,2,3,4,5,6,7,8)   			  -- PARAMETRO DE SUBGERENCIA DE VENTA --
			  AND REG.OID_REGI IN (1,2,3,4,5,6,7,8) 					  -- PARAMETRO DE REGION --
			  AND ZONA.OID_ZONA IN (1,2,3,4,5,6,7,8)					  -- PARAMETRO DE ZONA --
	) RECTE
	WHERE NRO_RECOMENDADAS_EF IN (1,2,3,4)								  -- PARAMETRO DE NUMERO DE RECOMENDADAS -- 
) DATOS
GROUP BY DATOS.MARCA,
	  	 DATOS.SUBG,
	   DATOS.REGION,
	   DATOS.ZONA,
	   DATOS.NUM_CONCURSO,
	   DATOS.DES_CONCURSO,
	   DATOS.NRO_RECOMENDADAS_EF
