
SELECT SUBG,
	   REGION,
	   ZONA,
	   NUM_CONC,
	   RANGO,
	   METAS_ASIG,
	   PUNTOS_LOGRADOS,
	   PORC_VAR,
	   VENTA_NETA
FROM
(
	SELECT SUBG,
		   REGION,
		   ZONA,
		   NUM_CONC,
		   RANGO,
		   CASE WHEN (1 = 2) THEN					-- PARAMETRO DE TIPO DE VARIACION --
		      	   SUM(META_GANA)
		   ELSE
		   	   	   SUM(META_NO_GANA)
		   END  METAS_ASIG,
		   CASE WHEN (1 = 2) THEN 					-- PARAMETRO DE TIPO DE VARIACION --
	               SUM(PUNTOS_GANA)
		   ELSE
		   	       SUM(PUNTOS_NO_GANA)
		   END PUNTOS_LOGRADOS,
		   CASE WHEN (1 = 2) THEN 	  				-- PARAMETRO DE TIPO DE VARIACION --
		   		DECODE(SUM(META_GANA), 0, 0,((SUM(PUNTOS_GANA)-SUM(META_GANA))/SUM(META_GANA))*100)
		   ELSE
		   	    DECODE(SUM(META_NO_GANA), 0, 0,(((SUM(PUNTOS_NO_GANA)-SUM(META_NO_GANA))/SUM(META_NO_GANA))*100)+100)
		   END PORC_VAR,	   
		   CASE WHEN (1 = 2) THEN	  				-- PARAMETRO DE TIPO DE VARIACION --
		   		   SUM(VENTA_GANA)
		   ELSE
		   	   	   SUM(VENTA_NO_GANA)
		   END VENTA_NETA				   
	FROM
	(
		SELECT SUBG,
			   REGION,
			   ZONA,
			   NUM_CONC,
			   FN_072_RANGO(VENTA) RANGO,
			   CASE WHEN (GANA = 1) THEN
			   	   SUM(PUNTOS)
			   ELSE 		  
			   	   0			   
			   END PUNTOS_GANA,
			   CASE WHEN (GANA = 0) THEN
			   	   SUM(PUNTOS)
			   ELSE
			   	   0
			   END PUNTOS_NO_GANA,
			   CASE WHEN (GANA = 1) THEN
			   	   SUM(VENTA)
			   ELSE 
			   	   0
			   END VENTA_GANA,
			   CASE WHEN (GANA = 0) THEN
			   	   SUM(VENTA)
			   ELSE
			   	   0
			   END VENTA_NO_GANA,
			   CASE WHEN (GANA = 1) THEN
			   	   SUM(META)
			   ELSE
			       0
			   END META_GANA,
			   CASE WHEN (GANA = 0) THEN
			   	   SUM(META)
			   ELSE
			   	   0
			   END META_NO_GANA
		FROM
		(
			SELECT SUBG.DES_SUBG_VENT SUBG,
				   REG.DES_REGI REGION,
				   ZONA.DES_ZONA ZONA,
				   CPG.NUM_CONC,	
				   CLI_UA.CLIE_OID_CLIE,   
				   SUM(CCP.NUM_PUNT) PUNTOS,
			   	   FN_083_CU_OBT_VENTA(CPG.OID_PARA_GRAL, CLI_UA.CLIE_OID_CLIE, PLC.TVEN_OID_TIPO_VENT)*MONEDA.TIP_CAM VENTA,
				   NVL((
				   SELECT 1
				   FROM INC_GANAD G
				   WHERE G.PANP_OID_PARA_NIVE_PREM = PNP.OID_PARA_NIVE_PREM
				   		 AND G.CLIE_OID_CLIE = CLI_UA.CLIE_OID_CLIE
				  		 AND ROWNUM = 1
				   ), 0) GANA,
				   (
				   SELECT MET.VAL_META
				   FROM INC_METAS_TIPO_VENTA MET
				   WHERE MET.COPA_OID_PARA_GRAL = CPG.OID_PARA_GRAL
				   		 AND MET.CLIE_OID_CLIE = CLI_UA.CLIE_OID_CLIE
				   ) META
			FROM ZON_SUB_GEREN_VENTA SUBG,
				 ZON_REGIO REG,
				 ZON_ZONA ZONA,
				 ZON_SECCI SEC,
				 ZON_TERRI_ADMIN TA,
				 MAE_CLIEN_UNIDA_ADMIN CLI_UA,
				 MAE_CLIEN_TIPO_SUBTI CLI_SUB,
				 MAE_CLIEN_CLASI CLA,
				 INC_METAS_TIPO_VENTA MET,
				 INC_CONCU_PARAM_GENER CPG,
				 INC_CUENT_CORRI_PUNTO CCP,
				 INC_PLANT_CONCU PLC,
				 INC_PARAM_GENER_PREMI PGP,
				 INC_PARAM_NIVEL_PREMI PNP,
				 (
				 SELECT CASE WHEN (PAIS.MONE_OID_MONE = 1) THEN			 -- PARAMETRO DE MONEDA DE REFENCIA --
				 			 1
						ELSE
							 (SELECT TC.VAL_TIPO_CAMB
							 FROM SEG_TIPO_CAMBI TC
							 WHERE TC.MONE_OID_MON1 = PAIS.MONE_OID_MONE 
							 	   AND TC.MONE_OID_MON2 = 1				 -- PARAMETRO DE MONEDA REFENCIA --
								   AND TC.FEC_DESD <= SYSDATE
								   AND TC.FEC_HAST >= SYSDATE
							 )
						END TIP_CAM
				 FROM SEG_PAIS PAIS
				 WHERE PAIS.OID_PAIS = 1	  		 	   	   			 -- PARAMETRO DE PAIS --
				 ) MONEDA
			WHERE SUBG.OID_SUBG_VENT = REG.ZSGV_OID_SUBG_VENT
				  AND PGP.COPA_OID_PARA_GRAL = CPG.OID_PARA_GRAL
				  AND PNP.PAGP_OID_PARA_GENE_PREM = PGP.OID_PARA_GENE_PREM
				  AND REG.OID_REGI = ZONA.ZORG_OID_REGI
				  AND ZONA.OID_ZONA = SEC.ZZON_OID_ZONA
				  AND SEC.OID_SECC = TA.ZSCC_OID_SECC
				  AND TA.OID_TERR_ADMI = CLI_UA.ZTAD_OID_TERR_ADMI
			      AND CLI_SUB.CLIE_OID_CLIE = CLI_UA.CLIE_OID_CLIE
				  AND CLI_SUB.SBTI_OID_SUBT_CLIE = CLA.CTSU_OID_CLIE_TIPO_SUBT
				  AND CPG.IND_ACTI = 1
				  AND CLA.IND_PPAL = 1
				  AND CLI_UA.IND_ACTI = 1
				  AND PLC.OID_PLAN_CONC = CPG.PLC2_OID_PLAN_CONC
				  AND PLC.TVEN_OID_TIPO_VENT = 1					-- PARAMETRO DE TIPO DE VENTA -- 
				  AND MET.CLIE_OID_CLIE = CLI_UA.CLIE_OID_CLIE
				  AND CPG.OID_PARA_GRAL = MET.COPA_OID_PARA_GRAL
				  AND CCP.COPA_OID_PARA_GRAL = CPG.OID_PARA_GRAL
				  AND CCP.CLIE_OID_CLIE = CLI_UA.CLIE_OID_CLIE
				  AND CLI_SUB.IND_PPAL = 1
				  AND MET.COPA_OID_PARA_GRAL = 1					-- PARAMETRO DE NUMERO DE CONCURSO --
				  AND SUBG.PAIS_OID_PAIS = 1	 					-- PARAMETRO DE PAIS --
				  AND SUBG.MARC_OID_MARC = 1					-- PARAMETRO DE MARCA --
				  AND SUBG.CANA_OID_CANA = 1					-- PARAMETRO DE CANAL --
				  AND SUBG.OID_SUBG_VENT IN (1,2,3,4,5,6,7,8,9)    -- PARAMETRO DE SUBGERENCIA DE VENTAS --
				  AND REG.OID_REGI IN (1,2,3,4,5,6,7,8,9)		   -- PARAMETRO DE REGION --
				  AND ZONA.OID_ZONA IN (1,2,3,4,5,6,7,8,9) 		   -- PARAMETRO DE ZONA -- 
				  AND CLA.TCCL_OID_TIPO_CLASI = 6  			   -- PARAMETRO DE TIPO DE CLASIFICACION --
				  AND CLA.CLAS_OID_CLAS = 9				  			   -- PARAMETRO DE CLASIFICION -- 
				  AND CLI_SUB.TICL_OID_TIPO_CLIE = 2	   		   -- PARAMETRO DE TIPO DE CLIENTE --
				  AND CLI_SUB.SBTI_OID_SUBT_CLIE = 1			   -- PARAMETRO DE SUBTIPO DE CLIENTE --
			GROUP BY SUBG.DES_SUBG_VENT,
				   	 REG.DES_REGI,
				   	 ZONA.DES_ZONA,
					 CPG.OID_PARA_GRAL,
					 PLC.TVEN_OID_TIPO_VENT,
				   	 CPG.NUM_CONC,
					 PNP.OID_PARA_NIVE_PREM,
					 MONEDA.TIP_CAM,
					 CLI_UA.CLIE_OID_CLIE		  
		)	  
		GROUP BY SUBG,
			   REGION,
			   ZONA,
			   NUM_CONC,
			   FN_072_RANGO(VENTA),
			   GANA
	)    
	GROUP BY SUBG,
		   REGION,
		   ZONA,
		   NUM_CONC,
		   RANGO
)
WHERE PORC_VAR >= 0			       -- PARAMETRO DE VARIACION DESDE --
	  AND PORC_VAR <= 100 		   -- PARAMETRO DE VARIACION HASTA --	  
	  AND RANGO IN (0) 	  		   -- PARAMETRO DE MONTO DE VENTA --
