




SELECT REGION,
	   ZONA,
	   TERRITORIO,
	   NUM_CONCURSO,
	   DESC_CONCURSO,
	   CAMP_INI_CONCU,
	   CAMP_FIN_CONCU,
	   TIPO_VENTA,
	   NIVEL,
	   COD_CLIENTE,
	   NOMBRE,
	   DESC_PREMIO,
	   CANTIDAD,
	   CAMP_DESPACHO,
	   CASE WHEN (CONTROL = 1)  THEN
	   		VENTA_CONCURSO
	   END VENTA_CONCURSO,
	   CUENTA	   
FROM
(
SELECT REG.DES_REGI REGION,
	   ZONA.DES_ZONA ZONA,
	   TER.COD_TERR TERRITORIO,
	   CON_GEN.NUM_CONC NUM_CONCURSO,
	   CON_GEN.VAL_NOMB DESC_CONCURSO,
	   PERI1.VAL_NOMB_PERI CAMP_INI_CONCU,
	   PERI2.VAL_NOMB_PERI CAMP_FIN_CONCU,
	   GEN_TV.VAL_I18N TIPO_VENTA,
	   PAR_NIV.NUM_NIVE NIVEL,
	   CLI.COD_CLIE COD_CLIENTE,
	   CLI.VAL_NOM1||' '||CLI.VAL_NOM2||' '||CLI.VAL_APE1||' '||CLI.VAL_APE2 NOMBRE,
	   VISTA.TIPO_PREMIO||' '||VISTA.DESCRIPCION||' '||VISTA.CANTIDAD DESC_PREMIO,
	   GAN.NUM_UNID CANTIDAD,
	   PERI3.VAL_NOMB_PERI CAMP_DESPACHO,
	   FN_083_CU_OBT_VENTA(CON_GEN.OID_PARA_GRAL,CLI_UA.CLIE_OID_CLIE,PLA_CON.TVEN_OID_TIPO_VENT) VENTA_CONCURSO,
	   SUM(1) OVER (PARTITION BY REG.DES_REGI, ZONA.DES_ZONA, TER.COD_TERR, CON_GEN.NUM_CONC, PAR_NIV.NUM_NIVE, CLI.COD_CLIE ORDER BY ROWNUM) CONTROL,
       COUNT(DISTINCT COD_CLIE) OVER (PARTITION BY PAR_NIV.NUM_NIVE, ZONA.DES_ZONA, TER.COD_TERR, CON_GEN.NUM_CONC, PERI1.VAL_NOMB_PERI, PERI2.VAL_NOMB_PERI, PAR_NIV.NUM_NIVE ) AS CUENTA
FROM INC_CONCU_PARAM_GENER CON_GEN,
	 INC_PARAM_GENER_PREMI PAR_GEN,
	 INC_PARAM_NIVEL_PREMI PAR_NIV,
	 INC_PLANT_CONCU PLA_CON,
	 INC_GANAD GAN,
	 ZON_SUB_GEREN_VENTA SUBG,
	 ZON_REGIO REG,
	 ZON_ZONA ZONA,
	 ZON_SECCI SEC,
	 ZON_TERRI_ADMIN TER_ADM,
	 ZON_TERRI TER,
	 MAE_CLIEN_UNIDA_ADMIN CLI_UA,
	 MAE_CLIEN CLI,
	 V_REP_PREMIOS VISTA,
	 CRA_PERIO PERI1,
	 CRA_PERIO PERI2,
	 CRA_PERIO PERI3,
	 (
	 SELECT GEN.VAL_OID, GEN.VAL_I18N
	 FROM V_GEN_I18N_SICC GEN
	 WHERE GEN.ATTR_ENTI = 'INC_TIPO_VENTA'
	 	   AND GEN.IDIO_OID_IDIO = 1	   									-- PARAMETRO DE IDIOMA --
	 ) GEN_TV	 
WHERE CON_GEN.PLC2_OID_PLAN_CONC = PLA_CON.OID_PLAN_CONC
	  AND PAR_GEN.COPA_OID_PARA_GRAL = CON_GEN.OID_PARA_GRAL
	  AND PAR_GEN.OID_PARA_GENE_PREM = PAR_NIV.PAGP_OID_PARA_GENE_PREM 
	  AND GAN.PANP_OID_PARA_NIVE_PREM = PAR_NIV.OID_PARA_NIVE_PREM
	  AND GAN.PERD_OID_PERI = PERI3.OID_PERI
	  AND SUBG.OID_SUBG_VENT = REG.ZSGV_OID_SUBG_VENT
	  AND REG.OID_REGI = ZONA.ZORG_OID_REGI
	  AND ZONA.OID_ZONA = SEC.ZZON_OID_ZONA
	  AND SEC.OID_SECC = TER_ADM.ZSCC_OID_SECC
	  AND TER.OID_TERR = TER_ADM.TERR_OID_TERR
	  AND CLI_UA.ZTAD_OID_TERR_ADMI = TER_ADM.OID_TERR_ADMI
	  AND CLI_UA.CLIE_OID_CLIE = GAN.CLIE_OID_CLIE
	  AND PAR_NIV.OID_PARA_NIVE_PREM = VISTA.OID_PARA_NIVE_PREM
	  AND CON_GEN.PERD_OID_PERI_DESD = PERI1.OID_PERI
	  AND CON_GEN.PERD_OID_PERI_HAST = PERI2.OID_PERI
	  AND PLA_CON.TVEN_OID_TIPO_VENT = GEN_TV.VAL_OID(+)
	  AND CLI_UA.CLIE_OID_CLIE = CLI.OID_CLIE
	  AND VISTA.OID_PARA_NIVE_PREM(+) = PAR_NIV.OID_PARA_NIVE_PREM
--	  AND VISTA.IDIO_TIPO_PREMIO = 1 		 				   -- PARAMETRO DE IDIOMA --
	  AND CLI_UA.IND_ACTI = 1
	  AND CON_GEN.IND_ACTI = 1
	  AND PLA_CON.TVEN_OID_TIPO_VENT = 1						-- PARAMETRO DE TIPO DE VENTA --
--	  AND CON_GEN.NUM_CONC IN ('1','2','3','4','5','6','7','8','9')	-- PARAMETRO DE NUMERO DE CONCURSO--
--	  AND PAR_NIV.NUM_NIVE IN (1,2,3,4,5,6,7,8,9)					-- PARAMETRO DE NUMERO DE NIVEL --
	  AND CON_GEN.PAIS_OID_PAIS = 1								-- PARAMETRO DE PAIS --
	  AND SUBG.OID_SUBG_VENT IN (1,2,3,4,5,6,7,8,9)				-- PARAMETRO DE SUBGERENCIA DE VENTAS --
	  AND REG.OID_REGI IN (1,2,3,4,5,6,7,8,9)					-- PARAMETRO DE REGION --
	  AND ZONA.OID_ZONA IN (1,2,3,4,5,6,7,8,9)					-- PARAMETRO DE ZONA --
	  AND TER.OID_TERR IN (1,2,3,4,5,6,7,8,9)					-- PARAMETRO DE TERRITORIO --	  	  
ORDER BY REGION,
	  	 ZONA,
		 TERRITORIO,
		 NUM_CONCURSO
) 	
