SELECT CONCURSO,
	   'GERENTES DE ZONA' DIRIGIDO,
	   PREMI.DESC_PRE,
	   FN_070_CONCAT_PERI(CONCU.OID_PARA_GRAL) PERIODOS,
	   TOTAL_CON,
	   N_GANA,
	   PORC,
	   ' ' REQUISITOS
FROM
(
	SELECT OID_PARA_GRAL,
		   CONCURSO,
		   COUNT(*) TOTAL_CON, 	   
		   SUM(GANA) N_GANA,
		   (SUM(GANA)*100)/COUNT(*) PORC
	FROM 
	(
		SELECT CPG.OID_PARA_GRAL,
			   CPG.VAL_NOMB||' '||CPG.NUM_CONC||' '||CPG.NUM_VERS CONCURSO,
			   NVL((
			   SELECT 1
			   FROM INC_GANAD GANA,
			   		INC_PARAM_GENER_PREMI PGP,
					INC_PARAM_NIVEL_PREMI PNP			
			   WHERE GANA.CLIE_OID_CLIE = ZONA.CLIE_OID_CLIE
			   		 AND GANA.PANP_OID_PARA_NIVE_PREM = PNP.OID_PARA_NIVE_PREM
					 AND PNP.PAGP_OID_PARA_GENE_PREM = PGP.OID_PARA_GENE_PREM 
					 AND PGP.COPA_OID_PARA_GRAL = CPG.OID_PARA_GRAL
					 AND ROWNUM = 1
			   ), 0) GANA	   
		FROM INC_PARTI_CONCU_CABEC PCC,
			 INC_PARTI_CONCU_DETAL PCD, 
			 INC_CLASI_PARTI_CONCU CPC,
			 INC_CONCU_PARAM_GENER CPG,
			 (
				SELECT DISTINCT 
					   AG.COPA_OID_PARA_GRAL,
					   CASE WHEN ZON.OID_ZONA IS NULL THEN
					   		CASE WHEN ZON3.OID_ZONA IS NULL THEN
								  ZON2.OID_ZONA
						    ELSE
								 ZON3.OID_ZONA
						    END 
					   ELSE
					   	    ZON.OID_ZONA 
					   END ZONA   
				FROM INC_AMBIT_GEOGR AG,
					 ZON_SUB_GEREN_VENTA SUBG,
					 ZON_REGIO REG,
					 ZON_REGIO REG2,
					 ZON_ZONA ZON,
					 ZON_ZONA ZON2,
					 ZON_ZONA ZON3
				WHERE AG.ZSGV_OID_SUBG_VENT = SUBG.OID_SUBG_VENT
					  AND SUBG.OID_SUBG_VENT = REG2.ZSGV_OID_SUBG_VENT
					  AND REG2.OID_REGI = ZON2.ZORG_OID_REGI
					  AND AG.ZORG_OID_REGI = REG.OID_REGI(+)
					  AND REG.OID_REGI = ZON3.ZORG_OID_REGI(+)
					  AND AG.ZZON_OID_ZONA = ZON.OID_ZONA(+)
					  AND AG.COPA_OID_PARA_GRAL IN (1,1408)  		  				 -- PARAMETRO DE CONCURSO --
				ORDER BY AG.COPA_OID_PARA_GRAL, 
					  	ZONA
			 ) AMB,
			 ZON_ZONA ZONA
		WHERE PCC.OID_PART_CONC_CABE = CPC.PACI_OID_PART_CONC_CABE
			  AND CPG.OID_PARA_GRAL = CPC.COPA_OID_PARA_GRAL
			  AND PCD.PACI_OID_PART_CONC_CABE = PCC.OID_PART_CONC_CABE
			  AND AMB.COPA_OID_PARA_GRAL = CPG.OID_PARA_GRAL
			  AND ZONA.OID_ZONA = AMB.ZONA
		--	  AND PCD.TICL_OID_TIPO_CLIE = 4
		--	  AND PCD.SBTI_OID_SUBT_CLIE = 4
			  AND CPG.IND_ACTI = 1	  
			  AND CPG.OID_PARA_GRAL IN (1,1408) 						 -- PARAMETRO DE CONCURSO --
	)
	GROUP BY OID_PARA_GRAL, CONCURSO
) CONCU,
(
	 SELECT CPG.OID_PARA_GRAL, 			 		
	 		VIS.TIPO_PREMIO||' '||VIS.DESCRIPCION||' '||VIS.CANTIDAD DESC_PRE
	 FROM INC_CONCU_PARAM_GENER CPG,
	 	  INC_PARAM_NIVEL_PREMI PNP,
		  INC_PARAM_GENER_PREMI PGP,
		  V_REP_PREMIOS VIS				  
	 WHERE CPG.OID_PARA_GRAL = PGP.COPA_OID_PARA_GRAL
	 	   AND PGP.OID_PARA_GENE_PREM = PNP.PAGP_OID_PARA_GENE_PREM
		   AND VIS.OID_PARA_NIVE_PREM = PNP.OID_PARA_NIVE_PREM		
		   AND VIS.IDIO_TIPO_PREMIO = 1									-- PARAMETRO DE IDIOMA --
		   AND CPG.OID_PARA_GRAL IN (1, 1408)						-- PARAMETRO DE CONCURSO --
) PREMI
WHERE CONCU.OID_PARA_GRAL = PREMI.OID_PARA_GRAL(+)

	  
	  
	  
	  
	  
	
	  

